import { QuizBank } from '../types';

/** CFA Level I — five questions per topic area, in the Institute's house style. */
export const CFA_L1_QUESTIONS: QuizBank = {
  'cfa-l1-ethics': [
    {
      text: 'A member works in a jurisdiction whose regulation permits front-running client orders. The Code and Standards prohibit it. The member must:',
      given: null,
      opts: ['Follow local law', 'Follow the stricter Code and Standards', 'Disclose the practice and proceed', 'Seek written employer approval'],
      a: 1,
      why: 'Members follow the most strict of applicable law, the Code and the Standards. Less strict local law never lowers the bar.',
      ref: 'Standard I(A) — Knowledge of the Law',
    },
    {
      text: 'An analyst accepts a paid consulting role outside her firm without informing her employer. She has most likely violated:',
      given: null,
      opts: ['Standard III(A) Loyalty, Prudence and Care', 'Standard IV(B) Additional Compensation Arrangements', 'Standard V(A) Diligence and Reasonable Basis', 'No standard, because the work is outside the firm'],
      a: 1,
      why: 'Additional compensation arrangements that could conflict with the employer\'s interest require written consent from all parties involved.',
      ref: 'Standard IV(B) — Additional Compensation Arrangements',
    },
    {
      text: 'A member publishes a research summary that omits the fact that his firm holds an 8% beneficial ownership stake in the issuer. This most likely violates:',
      given: null,
      opts: ['Standard VI(A) Disclosure of Conflicts', 'Standard II(B) Market Manipulation', 'Standard III(D) Performance Presentation', 'Standard VII(A) Conduct as Participants'],
      a: 0,
      why: 'Beneficial ownership that could reasonably impair independence must be disclosed prominently. Omitting it breaches Standard VI(A).',
      ref: 'Standard VI(A) — Disclosure of Conflicts',
    },
    {
      text: 'Which action best satisfies Standard V(B), Communication with Clients and Prospective Clients?',
      given: null,
      opts: ['Presenting projections as assured outcomes', 'Distinguishing between fact and opinion', 'Omitting the process used to reach the conclusion', 'Reporting only the recommendations that performed well'],
      a: 1,
      why: 'Members must distinguish fact from opinion and describe the basic process by which conclusions were reached, including its limitations.',
      ref: 'Standard V(B) — Communication with Clients',
    },
    {
      text: 'A portfolio manager recommends a security after reading a single sell-side note and performing no further work. The security subsequently performs well. The manager has:',
      given: null,
      opts: ['Not violated the Standards, because the result was favourable', 'Violated Standard V(A) regardless of the outcome', 'Violated Standard III(A) only if a client lost money', 'Violated Standard I(C) Misrepresentation'],
      a: 1,
      why: 'Standard V(A) requires a reasonable and adequate basis supported by appropriate research. The outcome is irrelevant — the process is what is judged.',
      ref: 'Standard V(A) — Diligence and Reasonable Basis',
    },
  ],

  'cfa-l1-quant': [
    {
      text: 'An investment offers a stated annual rate of 8% compounded quarterly. The effective annual rate is closest to:',
      given: 'r = 8% · m = 4',
      opts: ['8.00%', '8.24%', '8.30%', '8.33%'],
      a: 1,
      why: 'EAR = (1 + 0.08/4)⁴ − 1 = 1.02⁴ − 1 = 8.243%. More frequent compounding always raises the effective rate above the stated rate.',
      ref: 'Quantitative Methods — Rates and Returns, LOS 1.b',
    },
    {
      text: 'A researcher rejects the null hypothesis at the 5% significance level when the null is in fact true. This is best described as:',
      given: null,
      opts: ['A Type I error', 'A Type II error', 'A power failure', 'A specification error'],
      a: 0,
      why: 'Rejecting a true null is a Type I error, and its probability equals the significance level chosen. Failing to reject a false null is Type II.',
      ref: 'Quantitative Methods — Hypothesis Testing, LOS 8.a',
    },
    {
      text: 'A sample of 25 monthly returns has a mean of 1.2% and a standard deviation of 3.0%. The standard error of the sample mean is closest to:',
      given: 'x̄ = 1.2% · s = 3.0% · n = 25',
      opts: ['0.12%', '0.60%', '3.00%', '1.20%'],
      a: 1,
      why: 'The standard error is s/√n = 3.0%/5 = 0.60%. It falls with the square root of sample size, not with sample size itself.',
      ref: 'Quantitative Methods — Estimation and Inference, LOS 7.c',
    },
    {
      text: 'In a simple linear regression the coefficient of determination is 0.64. The correlation between the dependent and independent variable is:',
      given: 'R² = 0.64',
      opts: ['0.41', '0.64', '0.80 in absolute value', '1.28'],
      a: 2,
      why: 'In simple linear regression R² is the squared correlation, so |r| = √0.64 = 0.80. The sign follows the sign of the slope coefficient.',
      ref: 'Quantitative Methods — Simple Linear Regression, LOS 10.d',
    },
    {
      text: 'Which measure of central tendency is most appropriate for describing a compound annual growth rate over multiple periods?',
      given: null,
      opts: ['Arithmetic mean', 'Geometric mean', 'Harmonic mean', 'Mode'],
      a: 1,
      why: 'The geometric mean accounts for compounding and gives the constant rate that reproduces the ending value. It is always ≤ the arithmetic mean.',
      ref: 'Quantitative Methods — Rates and Returns, LOS 1.d',
    },
  ],

  'cfa-l1-econ': [
    {
      text: 'A firm faces a downward-sloping demand curve and sells a differentiated product with many close substitutes and low barriers to entry. This market is best characterised as:',
      given: null,
      opts: ['Perfect competition', 'Monopolistic competition', 'Oligopoly', 'Monopoly'],
      a: 1,
      why: 'Product differentiation with many sellers and easy entry defines monopolistic competition. Long-run economic profit is competed away to zero.',
      ref: 'Economics — The Firm and Market Structures, LOS 1.b',
    },
    {
      text: 'The inventory–sales ratio rises sharply. This most likely indicates the economy is:',
      given: null,
      opts: ['Entering an expansion', 'Entering a contraction', 'At a cyclical trough', 'Unaffected — the ratio is not cyclical'],
      a: 1,
      why: 'Sales fall before firms cut production, so unsold inventory builds up. A rising inventory–sales ratio is a classic early-contraction signal.',
      ref: 'Economics — Understanding Business Cycles, LOS 2.b',
    },
    {
      text: 'The spot USD/EUR rate is 1.1000. The one-year US interest rate is 5% and the euro rate is 3%. The one-year forward USD/EUR rate implied by covered interest rate parity is closest to:',
      given: 'S = 1.1000 · i_USD = 5% · i_EUR = 3%',
      opts: ['1.0787', '1.1000', '1.1214', '1.1550'],
      a: 2,
      why: 'F = S × (1 + i_USD)/(1 + i_EUR) = 1.1000 × 1.05/1.03 = 1.1214. The higher-rate currency trades at a forward discount.',
      ref: 'Economics — Capital Flows and the FX Market, LOS 7.c',
    },
    {
      text: 'Which of the following is most accurately described as a lagging economic indicator?',
      given: null,
      opts: ['The slope of the yield curve', 'New orders for capital goods', 'The average duration of unemployment', 'Building permits issued'],
      a: 2,
      why: 'The average duration of unemployment continues rising after a recovery begins, making it a lagging indicator. The other three are leading.',
      ref: 'Economics — Understanding Business Cycles, LOS 2.d',
    },
    {
      text: 'A central bank raises its policy rate to combat inflation. Compared with fiscal policy, monetary policy most likely has:',
      given: null,
      opts: ['A longer enactment lag but a shorter impact lag', 'A shorter enactment lag but a longer impact lag', 'Shorter lags on both dimensions', 'Longer lags on both dimensions'],
      a: 1,
      why: 'Monetary policy can be enacted quickly by committee decision, but works indirectly through rates, credit and expectations, so its impact lag is long and variable.',
      ref: 'Economics — Monetary Policy, LOS 4.f',
    },
  ],

  'cfa-l1-fsa': [
    {
      text: 'A company reports net income of $480,000, depreciation of $95,000, a $40,000 increase in accounts receivable and a $25,000 increase in accounts payable. Cash flow from operations is closest to:',
      given: 'NI 480,000 · Dep 95,000 · ΔAR +40,000 · ΔAP +25,000',
      opts: ['$510,000', '$560,000', '$600,000', '$640,000'],
      a: 1,
      why: '480,000 + 95,000 − 40,000 + 25,000 = $560,000. An increase in a receivable uses cash; an increase in a payable provides it.',
      ref: 'FSA — Analyzing Statements of Cash Flows I, LOS 4.c',
    },
    {
      text: 'During a period of rising prices with stable inventory quantities, a firm using LIFO rather than FIFO will report:',
      given: null,
      opts: ['Higher ending inventory and higher net income', 'Lower ending inventory and lower net income', 'Higher ending inventory and lower net income', 'Lower ending inventory and higher net income'],
      a: 1,
      why: 'LIFO charges the most recent, highest costs to COGS, lowering net income, and leaves older, cheaper costs in ending inventory.',
      ref: 'FSA — Analysis of Inventories, LOS 6.b',
    },
    {
      text: 'Under IFRS, which classification of interest paid on the statement of cash flows is permitted?',
      given: null,
      opts: ['Operating only', 'Financing only', 'Either operating or financing', 'Investing only'],
      a: 2,
      why: 'IFRS allows interest paid to be classified as either operating or financing. US GAAP requires it to be classified as operating.',
      ref: 'FSA — Analyzing Statements of Cash Flows I, LOS 4.a',
    },
    {
      text: 'A firm consistently reports net income well above cash flow from operations over several years. This is best interpreted as a signal of:',
      given: null,
      opts: ['Strong earnings quality', 'A high accruals component and potentially lower earnings quality', 'Aggressive but permissible tax planning', 'Nothing — the two measures are unrelated'],
      a: 1,
      why: 'A persistent gap between net income and operating cash flow indicates a large accruals component, which historically predicts lower earnings persistence.',
      ref: 'FSA — Financial Reporting Quality, LOS 10.d',
    },
    {
      text: 'A company capitalises rather than expenses a cost in the current year. In that year, the firm will report:',
      given: null,
      opts: ['Lower net income and lower assets', 'Higher net income and higher assets', 'Higher net income and lower assets', 'Lower net income and higher assets'],
      a: 1,
      why: 'Capitalising moves the cost to the balance sheet, raising assets and deferring the expense, which raises current-year net income. Later years bear the amortisation.',
      ref: 'FSA — Analysis of Long-Term Assets, LOS 7.a',
    },
  ],

  'cfa-l1-corp': [
    {
      text: 'A project requires an initial outlay of $1,000,000 and generates $300,000 per year for five years. At a cost of capital of 10%, the NPV is closest to:',
      given: 'Outlay 1,000,000 · CF 300,000 × 5 yrs · r = 10%',
      opts: ['−$62,000', '+$137,000', '+$500,000', '+$1,137,000'],
      a: 1,
      why: 'The five-year annuity factor at 10% is 3.7908, so PV = 300,000 × 3.7908 = $1,137,236. NPV = 1,137,236 − 1,000,000 ≈ +$137,000.',
      ref: 'Corporate Issuers — Capital Investments and Capital Allocation, LOS 5.c',
    },
    {
      text: 'When NPV and IRR give conflicting rankings for two mutually exclusive projects, an analyst should most appropriately:',
      given: null,
      opts: ['Choose the project with the higher IRR', 'Choose the project with the higher NPV', 'Choose the project with the shorter payback', 'Reject both projects'],
      a: 1,
      why: 'NPV measures the value added in currency terms and assumes reinvestment at the cost of capital, which is the economically defensible assumption.',
      ref: 'Corporate Issuers — Capital Investments and Capital Allocation, LOS 5.d',
    },
    {
      text: 'A firm has a target capital structure of 40% debt and 60% equity, a pre-tax cost of debt of 6%, a cost of equity of 11% and a tax rate of 25%. Its WACC is closest to:',
      given: 'w_d 40% · r_d 6% · w_e 60% · r_e 11% · t 25%',
      opts: ['8.40%', '8.40% before tax only', '7.80%', '9.20%'],
      a: 0,
      why: 'WACC = 0.40 × 6% × (1 − 0.25) + 0.60 × 11% = 1.80% + 6.60% = 8.40%. Only the debt component is tax-affected.',
      ref: 'Corporate Issuers — Capital Structure, LOS 6.b',
    },
    {
      text: 'A firm reports days of inventory on hand of 60, days sales outstanding of 45 and days of payables of 30. Its cash conversion cycle is:',
      given: 'DOH 60 · DSO 45 · DPO 30',
      opts: ['45 days', '75 days', '105 days', '135 days'],
      a: 1,
      why: 'CCC = DOH + DSO − DPO = 60 + 45 − 30 = 75 days. This is the length of time cash is tied up in the operating cycle.',
      ref: 'Corporate Issuers — Working Capital and Liquidity, LOS 4.c',
    },
    {
      text: 'The conflict of interest between controlling and minority shareholders is best described as:',
      given: null,
      opts: ['A principal–agent problem', 'A principal–principal problem', 'A stakeholder externality', 'A regulatory arbitrage'],
      a: 1,
      why: 'Both parties are owners, so it is a principal–principal conflict. The principal–agent problem sits between shareholders and managers.',
      ref: 'Corporate Issuers — Corporate Governance, LOS 3.a',
    },
  ],

  'cfa-l1-equity': [
    {
      text: 'A stock just paid an annual dividend of $2.00. Dividends are expected to grow at 4% indefinitely and the required return is 9%. The value of the stock is closest to:',
      given: 'D₀ = $2.00 · g = 4% · r = 9%',
      opts: ['$40.00', '$41.60', '$50.00', '$52.00'],
      a: 1,
      why: 'D₁ = 2.00 × 1.04 = $2.08. V₀ = 2.08 / (0.09 − 0.04) = $41.60. Using D₀ directly gives $40.00, the planted distractor.',
      ref: 'Equity Investments — Discounted Cash Flow and Growth Models, LOS 6.b',
    },
    {
      text: 'A two-for-one stock split of a constituent affects a price-weighted index by:',
      given: null,
      opts: ['Reducing the index level permanently', 'Requiring an adjustment to the divisor', 'Increasing the constituent\'s weight', 'Having no effect on any index type'],
      a: 1,
      why: 'The divisor is adjusted so the index level is unchanged by the split. In a market-cap weighted index no adjustment is required at all.',
      ref: 'Equity Investments — Sources of Equity Returns, LOS 4.c',
    },
    {
      text: 'A firm has a retention ratio of 40% and a return on equity of 15%. Its sustainable growth rate is:',
      given: 'b = 40% · ROE = 15%',
      opts: ['4.0%', '6.0%', '9.0%', '15.0%'],
      a: 1,
      why: 'g = b × ROE = 0.40 × 0.15 = 6.0%. This is the rate at which the firm can grow without issuing new equity.',
      ref: 'Equity Investments — Discounted Cash Flow and Growth Models, LOS 6.d',
    },
    {
      text: 'The justified leading P/E for a firm with a payout ratio of 60%, a required return of 10% and a growth rate of 5% is closest to:',
      given: '(1 − b) = 0.60 · r = 10% · g = 5%',
      opts: ['6.0×', '10.0×', '12.0×', '20.0×'],
      a: 2,
      why: 'P/E = (1 − b)/(r − g) = 0.60/(0.10 − 0.05) = 12.0×. The same inputs that drive a dividend model drive the justified multiple.',
      ref: 'Equity Investments — Relative Value Equity Valuation Approaches, LOS 7.b',
    },
    {
      text: 'Which characteristic most strongly indicates that an industry has high pricing power?',
      given: null,
      opts: ['Low industry concentration', 'Minimal barriers to entry', 'High switching costs for customers', 'Rapid technological change'],
      a: 2,
      why: 'High switching costs lock customers in and reduce buyer power, which supports pricing power. The other three erode it.',
      ref: 'Equity Investments — Industry and Competitive Analysis, LOS 9.c',
    },
  ],

  'cfa-l1-fixed': [
    {
      text: 'A bond with a modified duration of 7.2 is held when yields rise by 40 basis points. Using duration alone, the estimated percentage price change is closest to:',
      given: 'ModDur = 7.2 · Δy = +0.40%',
      opts: ['−2.88%', '−0.29%', '+2.88%', '−7.20%'],
      a: 0,
      why: '−ModDur × Δy = −7.2 × 0.0040 = −2.88%. The sign is negative because yields rose; convexity would make the true loss slightly smaller.',
      ref: 'Fixed Income — Yield-Based Bond Duration Measures, LOS 11.c',
    },
    {
      text: 'A bond pays a 6% annual coupon while the market yield on comparable bonds is 4.5%. The bond most likely trades at:',
      given: null,
      opts: ['A discount to par', 'Par value', 'A premium to par', 'A price that cannot be determined'],
      a: 2,
      why: 'When the coupon rate exceeds the required yield, the cash flows are richer than the market demands, so the price is bid above par.',
      ref: 'Fixed Income — Bond Valuation: Prices and Yields, LOS 6.b',
    },
    {
      text: 'Compared with a duration-only estimate, adding a positive convexity adjustment for a large yield increase will:',
      given: null,
      opts: ['Lower the estimated price', 'Raise the estimated price', 'Leave the estimate unchanged', 'Reverse the sign of the estimate'],
      a: 1,
      why: 'Positive convexity means the true price–yield curve lies above the tangent line, so the convexity term is additive for moves in either direction.',
      ref: 'Fixed Income — Yield-Based Bond Convexity, LOS 12.b',
    },
    {
      text: 'Spread duration measures the sensitivity of a corporate bond’s price to a change in:',
      given: null,
      opts: ['The benchmark government yield', 'The credit spread only', 'Both the benchmark and the spread', 'The realised default frequency'],
      a: 1,
      why: 'Spread duration isolates the credit spread component, holding the benchmark curve fixed. Effective duration captures the benchmark move.',
      ref: 'Fixed Income — Credit Risk, LOS 14.b',
    },
    {
      text: 'Which statement about Macaulay and modified duration is correct?',
      given: null,
      opts: ['Modified duration always exceeds Macaulay duration', 'They are always equal', 'Macaulay duration divided by (1 + periodic yield) gives modified duration', 'Macaulay duration is measured in percent'],
      a: 2,
      why: 'ModDur = MacDur / (1 + periodic yield), so modified duration is always slightly smaller. Macaulay duration is expressed in years.',
      ref: 'Fixed Income — Yield-Based Bond Duration Measures, LOS 11.a',
    },
  ],

  'cfa-l1-deriv': [
    {
      text: 'A non-dividend-paying stock trades at $50. The one-year risk-free rate is 4%. The no-arbitrage one-year forward price is closest to:',
      given: 'S₀ = $50 · r = 4% · T = 1',
      opts: ['$48.08', '$50.00', '$52.00', '$54.00'],
      a: 2,
      why: 'F₀ = S₀(1 + r)ᵀ = 50 × 1.04 = $52.00. The expected future price of the stock is irrelevant to the forward price.',
      ref: 'Derivatives — Arbitrage, Replication and the Cost of Carry, LOS 4.b',
    },
    {
      text: 'According to put–call parity, a synthetic long call can be constructed from:',
      given: 'c + X/(1+r)ᵀ = p + S₀',
      opts: ['Long put, long stock, short bond', 'Short put, long stock, long bond', 'Long put, short stock, long bond', 'Short put, short stock, short bond'],
      a: 0,
      why: 'Rearranging gives c = p + S₀ − X/(1+r)ᵀ: long put, long the underlying, and short a bond with face value equal to the strike.',
      ref: 'Derivatives — Option Replication Using Put–Call Parity, LOS 9.a',
    },
    {
      text: 'In a one-period binomial model with u = 1.25, d = 0.80 and a risk-free rate of 5%, the risk-neutral probability of an up move is closest to:',
      given: 'u = 1.25 · d = 0.80 · r = 5%',
      opts: ['0.44', '0.50', '0.56', '0.62'],
      a: 2,
      why: 'π = (1 + r − d)/(u − d) = (1.05 − 0.80)/(1.25 − 0.80) = 0.25/0.45 = 0.556. The actual probability of an up move is not used.',
      ref: 'Derivatives — Valuing a Derivative Using a One-Period Binomial Model, LOS 10.b',
    },
    {
      text: 'At initiation, the value of a plain vanilla interest rate swap to the fixed-rate payer is:',
      given: null,
      opts: ['Positive', 'Negative', 'Zero', 'Equal to the notional principal'],
      a: 2,
      why: 'The fixed rate is set precisely so the present values of the two legs are equal, making the swap worth zero to both parties at inception.',
      ref: 'Derivatives — Pricing and Valuation of Interest Rate Swaps, LOS 7.a',
    },
    {
      text: 'Which of the following best describes the credit risk of an exchange-traded futures contract relative to an otherwise identical forward?',
      given: null,
      opts: ['Higher, because of daily settlement', 'Lower, because of daily settlement and the clearinghouse', 'Identical, because the payoffs are identical', 'Undefined, because futures carry no credit risk at all'],
      a: 1,
      why: 'Daily mark-to-market settlement and the clearinghouse acting as counterparty substantially reduce credit risk relative to a bilateral forward.',
      ref: 'Derivatives — Derivative Instrument and Market Features, LOS 1.c',
    },
  ],

  'cfa-l1-alt': [
    {
      text: 'A hedge fund charges a 2% management fee on beginning assets and a 20% incentive fee on returns net of the management fee. Beginning assets are $100m and the gross return is 15%. The total fee is closest to:',
      given: 'AUM $100m · gross return 15% · 2% mgmt · 20% incentive, net of mgmt',
      opts: ['$4.60m', '$4.80m', '$5.00m', '$5.60m'],
      a: 0,
      why: 'Management fee = $2m. Gross gain = $15m; net of management fee = $13m. Incentive = 20% × 13 = $2.6m. Total = $4.6m.',
      ref: 'Alternative Investments — Performance and Returns, LOS 2.c',
    },
    {
      text: 'A property generates net operating income of $450,000 and comparable properties transact at a capitalisation rate of 6%. The estimated value is:',
      given: 'NOI $450,000 · cap rate 6%',
      opts: ['$2,700,000', '$7,500,000', '$4,500,000', '$27,000'],
      a: 1,
      why: 'Value = NOI / cap rate = 450,000 / 0.06 = $7,500,000. Direct capitalisation assumes NOI is constant in perpetuity.',
      ref: 'Alternative Investments — Real Estate and Infrastructure, LOS 4.c',
    },
    {
      text: 'The J-curve effect in private equity refers to:',
      given: null,
      opts: ['Rising fees over a fund\'s life', 'Early negative returns followed by later positive returns', 'The shape of the capital call schedule', 'Persistent underperformance versus public markets'],
      a: 1,
      why: 'Fees and early write-downs are recognised before exits generate gains, so reported returns are negative early and recover later.',
      ref: 'Alternative Investments — Investments in Private Capital, LOS 3.b',
    },
    {
      text: 'An illiquid strategy reports a Sharpe ratio far above comparable liquid strategies. The most likely explanation is:',
      given: null,
      opts: ['Genuinely superior risk-adjusted skill', 'Return smoothing from appraisal-based valuation', 'A higher risk-free rate assumption', 'Survivorship bias in the risk-free rate'],
      a: 1,
      why: 'Stale and appraisal-based marks smooth reported returns, understating volatility and inflating the Sharpe ratio. It is a measurement artefact.',
      ref: 'Alternative Investments — Performance and Returns, LOS 2.d',
    },
    {
      text: 'Compared with a direct investment in a hedge fund, a fund-of-funds most likely offers:',
      given: null,
      opts: ['Lower total fees and higher manager concentration', 'Higher total fees and greater diversification', 'Identical fees and identical diversification', 'Lower fees and greater diversification'],
      a: 1,
      why: 'A fund-of-funds adds a second layer of fees but provides diversification across managers and access to closed funds.',
      ref: 'Alternative Investments — Hedge Funds, LOS 6.b',
    },
  ],

  'cfa-l1-pm': [
    {
      text: 'Two assets have a correlation of exactly +1.0. Combining them in a portfolio will produce:',
      given: 'ρ₁,₂ = +1.0',
      opts: ['A reduction in portfolio standard deviation', 'No diversification benefit', 'A risk-free portfolio at some weight', 'A portfolio with zero expected return'],
      a: 1,
      why: 'With perfect positive correlation the portfolio standard deviation is the weighted average of the individual standard deviations — no benefit at all.',
      ref: 'Portfolio Management — Portfolio Risk and Return: Part I, LOS 1.d',
    },
    {
      text: 'A stock has a beta of 1.4. The risk-free rate is 3% and the expected market return is 9%. Its required return under the CAPM is:',
      given: 'β = 1.4 · R_f = 3% · E(R_m) = 9%',
      opts: ['9.0%', '11.4%', '12.6%', '15.6%'],
      a: 1,
      why: 'E(R) = 3% + 1.4 × (9% − 3%) = 3% + 8.4% = 11.4%. Note the market risk premium is 6%, not 9%.',
      ref: 'Portfolio Management — Portfolio Risk and Return: Part II, LOS 2.e',
    },
    {
      text: 'A security plots above the security market line. It is best described as:',
      given: null,
      opts: ['Overvalued, with a negative alpha', 'Undervalued, with a positive alpha', 'Correctly valued', 'Undervalued, but only if beta exceeds 1'],
      a: 1,
      why: 'Plotting above the SML means the expected return exceeds what the CAPM requires for its beta — a positive alpha, so it is undervalued.',
      ref: 'Portfolio Management — Portfolio Risk and Return: Part II, LOS 2.f',
    },
    {
      text: 'A client has substantial wealth and a long horizon but becomes visibly anxious during drawdowns. The adviser should most appropriately:',
      given: null,
      opts: ['Follow the higher ability to take risk', 'Follow the lower willingness to take risk and educate the client', 'Average the two assessments', 'Decline the engagement'],
      a: 1,
      why: 'When willingness and ability conflict, the lower governs. The adviser should adopt the more conservative position while educating the client.',
      ref: 'Portfolio Management — Basics of Portfolio Planning and Construction, LOS 4.b',
    },
    {
      text: 'An investor holds a losing position because selling would confirm the loss. This bias is best classified and remedied as:',
      given: null,
      opts: ['A cognitive error, to be corrected with information', 'An emotional bias, to be moderated', 'A cognitive error, to be moderated', 'An emotional bias, to be corrected with information'],
      a: 1,
      why: 'Loss aversion is an emotional bias arising from feeling rather than faulty reasoning, so it is generally moderated and accommodated rather than corrected.',
      ref: 'Portfolio Management — The Behavioral Biases of Individuals, LOS 5.b',
    },
  ],
};
