import { QuizBank } from '../types';

/** CFA Level II — five questions per topic area, vignette-flavoured. */
export const CFA_L2_QUESTIONS: QuizBank = {
  'cfa-l2-ethics': [
    {
      text: 'An analyst assembles several individually immaterial non-public details from suppliers and customers and, combined with public filings, concludes the issuer will miss guidance. Acting on that conclusion is:',
      given: null,
      opts: [
        'A violation of Standard II(A)',
        'Permitted under the mosaic theory',
        'Permitted only after disclosure to the issuer',
        'A violation of Standard V(A)',
      ],
      a: 1,
      why: 'The mosaic theory expressly permits combining non-material non-public information with public information. No single piece was material on its own.',
      ref: 'Standard II(A) — Material Nonpublic Information',
    },
    {
      text: 'A firm offers premium clients earlier access to research than standard clients, and discloses the tiering to all clients. Under Standard III(B) this is:',
      given: null,
      opts: [
        'A violation, because all clients must receive research simultaneously',
        'Permitted, because the differential service is disclosed',
        'A violation, unless the premium fee is waived',
        'Permitted only for institutional clients',
      ],
      a: 1,
      why: 'Fair dealing does not require identical treatment. Different service levels are permissible provided they are disclosed and do not disadvantage other clients.',
      ref: 'Standard III(B) — Fair Dealing',
    },
    {
      text: 'A manager presents a composite that excludes two terminated accounts that underperformed. This most likely violates:',
      given: null,
      opts: [
        'Standard III(D) Performance Presentation',
        'Standard VI(B) Priority of Transactions',
        'Standard IV(A) Loyalty to Employer',
        'Standard I(B) Independence and Objectivity',
      ],
      a: 0,
      why: 'Excluding terminated accounts creates survivorship bias and makes the presentation neither fair nor complete, breaching Standard III(D).',
      ref: 'Standard III(D) — Performance Presentation',
    },
    {
      text: 'A member takes a research report prepared at her previous employer and reuses its analysis, with attribution removed, at her new firm. She has violated:',
      given: null,
      opts: [
        'Standard IV(A) only',
        'Standard I(C) Misrepresentation and Standard IV(A) Loyalty',
        'Standard V(B) only',
        'No standard, because she wrote the original analysis',
      ],
      a: 1,
      why: 'The work product belongs to the former employer, and presenting it as new work without attribution is plagiarism under Standard I(C).',
      ref: 'Standard I(C) — Misrepresentation; Standard IV(A) — Loyalty',
    },
    {
      text: 'An investment firm allocates a hot IPO pro rata across all suitable client accounts, including accounts in which employees are beneficial owners. Under Standard VI(B), this is:',
      given: null,
      opts: [
        'Acceptable if client accounts are filled before employee-owned accounts',
        'Acceptable in all circumstances',
        'A violation regardless of the allocation order',
        'Acceptable only if the employees are not portfolio managers',
      ],
      a: 0,
      why: 'Priority of transactions requires client interests to come before those of employees. Employee-beneficial accounts may participate only after clients are satisfied.',
      ref: 'Standard VI(B) — Priority of Transactions',
    },
  ],

  'cfa-l2-quant': [
    {
      text: 'A multiple regression reports a significant F-statistic but no individually significant t-statistics. This most likely indicates:',
      given: null,
      opts: ['Heteroskedasticity', 'Serial correlation', 'Multicollinearity', 'A unit root'],
      a: 2,
      why: 'Multicollinearity inflates the standard errors of individual coefficients while leaving the joint explanatory power intact — exactly this signature.',
      ref: 'Quantitative Methods — Model Misspecification, LOS 3.b',
    },
    {
      text: 'Adding a variable to a regression raises R² from 0.42 to 0.44 but lowers adjusted R² from 0.39 to 0.38. The analyst should conclude the variable:',
      given: 'R²: 0.42 → 0.44 · R̄²: 0.39 → 0.38',
      opts: [
        'Improves the model and should be retained',
        'Does not justify its loss of degrees of freedom',
        'Introduces heteroskedasticity',
        'Makes the model non-stationary',
      ],
      a: 1,
      why: 'R² always rises with an added regressor. A falling adjusted R² means the explanatory gain does not compensate for the lost degree of freedom.',
      ref: 'Quantitative Methods — Evaluating Regression Model Fit, LOS 2.c',
    },
    {
      text: 'An AR(1) model is estimated on a series with a unit root. The most appropriate remedy is to:',
      given: null,
      opts: [
        'Add a lag to the model',
        'First-difference the series',
        'Use White-corrected standard errors',
        'Apply a log transformation to the dependent variable',
      ],
      a: 1,
      why: 'A unit root violates covariance stationarity and produces spurious results. First differencing typically restores stationarity.',
      ref: 'Quantitative Methods — Time-Series Analysis, LOS 5.f',
    },
    {
      text: 'Conditional heteroskedasticity in a regression most directly causes:',
      given: null,
      opts: [
        'Biased coefficient estimates',
        'Unreliable standard errors and invalid t-tests',
        'A spurious unit root',
        'Perfect multicollinearity',
      ],
      a: 1,
      why: 'Coefficients remain unbiased and consistent, but the standard errors are wrong, so hypothesis tests based on them are invalid.',
      ref: 'Quantitative Methods — Model Misspecification, LOS 3.a',
    },
    {
      text: 'A machine learning model shows very low training error and substantially higher validation error. This is best described as:',
      given: null,
      opts: ['Underfitting', 'Overfitting', 'Data leakage', 'Correct generalisation'],
      a: 1,
      why: 'A large gap between training and validation performance means the model has fitted noise in the training sample rather than signal.',
      ref: 'Quantitative Methods — Machine Learning, LOS 6.c',
    },
  ],

  'cfa-l2-econ': [
    {
      text: 'An investor borrows in a low-interest-rate currency and invests in a high-interest-rate currency. This carry trade is profitable only if:',
      given: null,
      opts: [
        'Uncovered interest rate parity holds',
        'Uncovered interest rate parity fails',
        'Covered interest rate parity fails',
        'Purchasing power parity holds in the short run',
      ],
      a: 1,
      why: 'If uncovered parity held, the high-rate currency would depreciate by exactly the interest differential and the trade would earn nothing. Its empirical failure is the source of carry returns.',
      ref: 'Economics — Currency Exchange Rates, LOS 1.d',
    },
    {
      text: 'Under the neoclassical growth model, a permanent increase in the savings rate will:',
      given: null,
      opts: [
        'Raise the long-run growth rate of output per capita',
        'Raise the level of output per capita but not its long-run growth rate',
        'Have no effect on either the level or the growth rate',
        'Lower the steady-state capital-to-labour ratio',
      ],
      a: 1,
      why: 'Diminishing returns to capital mean higher saving raises the steady-state level of output per worker but leaves the long-run growth rate set by technology.',
      ref: 'Economics — Economic Growth, LOS 2.d',
    },
    {
      text: 'Relative purchasing power parity predicts that a country with persistently higher inflation than its trading partners will experience:',
      given: null,
      opts: [
        'Currency appreciation',
        'Currency depreciation',
        'No change in the nominal exchange rate',
        'A widening real interest differential only',
      ],
      a: 1,
      why: 'Higher relative inflation erodes purchasing power, so relative PPP predicts nominal depreciation roughly equal to the inflation differential.',
      ref: 'Economics — Currency Exchange Rates, LOS 1.b',
    },
    {
      text: 'A country converges toward the steady state of countries with similar institutions and savings rates, but not toward all countries. This is best described as:',
      given: null,
      opts: ['Absolute convergence', 'Conditional convergence', 'Club convergence', 'Divergence'],
      a: 2,
      why: 'Club convergence describes convergence only within groups sharing institutional characteristics — the word "institutions" is the tell.',
      ref: 'Economics — Economic Growth, LOS 2.f',
    },
    {
      text: 'Under the FX portfolio balance approach, a country running persistent fiscal deficits will most likely see its currency:',
      given: null,
      opts: [
        'Appreciate indefinitely as capital flows in',
        'Appreciate in the short run and depreciate in the long run',
        'Depreciate immediately and permanently',
        'Remain unchanged in both horizons',
      ],
      a: 1,
      why: 'Higher rates attract capital and support the currency initially, but investors eventually demand compensation for the growing debt burden, causing depreciation.',
      ref: 'Economics — Currency Exchange Rates, LOS 1.g',
    },
  ],

  'cfa-l2-fsa': [
    {
      text: 'An investor holds 30% of an investee and exercises significant influence. Compared with proportionate consolidation, the equity method will report:',
      given: null,
      opts: [
        'Higher revenue and higher total assets',
        'The same net income but lower revenue and lower total assets',
        'Lower net income and higher total assets',
        'The same revenue but different net income',
      ],
      a: 1,
      why: 'The equity method reports a single line for both the investment and the share of income. Net income is identical; revenue and assets are not grossed up.',
      ref: 'FSA — Intercorporate Investments, LOS 1.c',
    },
    {
      text: 'A sponsor lowers the discount rate used to value its defined benefit obligation. All else equal, this will:',
      given: null,
      opts: [
        'Decrease the PBO and improve funded status',
        'Increase the PBO and worsen funded status',
        'Leave the PBO unchanged',
        'Increase plan assets',
      ],
      a: 1,
      why: 'A lower discount rate raises the present value of future benefits, increasing the PBO and reducing the funded status.',
      ref: 'FSA — Employee Compensation: Post-Employment, LOS 2.c',
    },
    {
      text: 'A subsidiary’s functional currency is its local currency. The appropriate translation method and the treatment of the resulting adjustment are:',
      given: null,
      opts: [
        'Temporal method; gain or loss in net income',
        'Current rate method; adjustment in other comprehensive income',
        'Temporal method; adjustment in OCI',
        'Current rate method; gain or loss in net income',
      ],
      a: 1,
      why: 'When the functional currency is the local currency, the current rate method applies and the cumulative translation adjustment goes to OCI, not income.',
      ref: 'FSA — Multinational Operations, LOS 3.b',
    },
    {
      text: 'Which of the following is the strongest indicator of low reporting quality rather than merely low results quality?',
      given: null,
      opts: [
        'Declining margins across several periods',
        'A large one-off restructuring charge',
        'Frequent, unexplained changes in accounting estimates that raise reported income',
        'A cyclical downturn in revenue',
      ],
      a: 2,
      why: 'Reporting quality concerns the faithfulness of the numbers. Repeated income-increasing estimate changes point to biased reporting, not just poor performance.',
      ref: 'FSA — Evaluating Quality of Financial Reports, LOS 5.b',
    },
    {
      text: 'In analysing a bank, which ratio most directly addresses the adequacy of loss absorption capacity?',
      given: null,
      opts: [
        'Common equity tier 1 ratio',
        'Net interest margin',
        'Cost-to-income ratio',
        'Loan-to-deposit ratio',
      ],
      a: 0,
      why: 'CET1 measures the highest-quality capital against risk-weighted assets, which is precisely the loss-absorption question. The others address profitability or funding.',
      ref: 'FSA — Analysis of Financial Institutions, LOS 4.b',
    },
  ],

  'cfa-l2-corp': [
    {
      text: 'A firm repurchases shares at a market price above book value per share. The effect on book value per share is:',
      given: null,
      opts: ['An increase', 'A decrease', 'No change', 'An increase only if funded with cash'],
      a: 1,
      why: 'Repurchasing above book value removes more equity per share than the shares carried, so book value per share falls. Below book value it rises.',
      ref: 'Corporate Issuers — Analysis of Dividends and Share Repurchases, LOS 1.d',
    },
    {
      text: 'A firm earns EPS of $4.00, targets a 40% payout ratio and currently pays $1.00. With an adjustment factor of 0.25, the target payout adjustment model predicts a dividend increase of:',
      given: 'EPS $4.00 · target payout 40% · D₀ $1.00 · adj 0.25',
      opts: ['$0.15', '$0.25', '$0.60', '$1.60'],
      a: 0,
      why: 'Expected increase = (4.00 × 0.40 − 1.00) × 0.25 = (1.60 − 1.00) × 0.25 = $0.15. The full gap is closed only gradually.',
      ref: 'Corporate Issuers — Analysis of Dividends and Share Repurchases, LOS 1.f',
    },
    {
      text: 'When estimating the beta of a private firm using the pure-play method, the analyst should relever the unlevered beta using:',
      given: null,
      opts: [
        "The comparable company's debt-to-equity ratio",
        "The subject company's target debt-to-equity ratio",
        'The industry average debt-to-equity ratio',
        'A zero debt-to-equity ratio',
      ],
      a: 1,
      why: "Unlever with the comparable's capital structure to strip it out, then relever with the subject firm's target structure. Using the comparable's in both steps is the planted error.",
      ref: 'Corporate Issuers — Cost of Capital: Advanced Topics, LOS 3.c',
    },
    {
      text: 'In a share-exchange acquisition rather than a cash acquisition, the risk that expected synergies fail to materialise is:',
      given: null,
      opts: [
        'Borne entirely by the acquirer',
        'Shared between acquirer and target shareholders',
        'Borne entirely by the target',
        'Eliminated by the exchange ratio',
      ],
      a: 1,
      why: 'Target shareholders become owners of the combined entity, so they share in any shortfall. In a cash deal the acquirer bears the full risk.',
      ref: 'Corporate Issuers — Corporate Restructuring, LOS 4.d',
    },
    {
      text: 'Which ESG integration approach explicitly excludes entire industries from the investable universe?',
      given: null,
      opts: [
        'Best-in-class',
        'Negative screening',
        'Thematic investing',
        'Engagement and active ownership',
      ],
      a: 1,
      why: 'Negative screening removes sectors or activities outright. Best-in-class instead selects leaders within every sector.',
      ref: 'Corporate Issuers — ESG Considerations in Investment Analysis, LOS 2.b',
    },
  ],

  'cfa-l2-equity': [
    {
      text: 'A firm has negative free cash flow to equity, pays no dividend, and applies clean surplus accounting. The most appropriate valuation model is:',
      given: null,
      opts: [
        'Gordon growth dividend discount model',
        'FCFE discount model',
        'Residual income model',
        'Two-stage dividend discount model',
      ],
      a: 2,
      why: 'Residual income recognises much of the value in current book value, making it workable where dividends and near-term free cash flow are absent.',
      ref: 'Equity Valuation — Residual Income Valuation, LOS 5.a',
    },
    {
      text: 'An analyst forecasts FCFF and discounts it at the cost of equity. This produces:',
      given: null,
      opts: [
        'A correct estimate of equity value',
        'A correct estimate of firm value',
        'An overstated value, because the discount rate is too high for the cash flow',
        'An understated value, because the discount rate is too high for the cash flow',
      ],
      a: 3,
      why: 'FCFF belongs to all capital providers and must be discounted at WACC. The cost of equity exceeds WACC, so discounting FCFF at it understates value.',
      ref: 'Equity Valuation — Free Cash Flow Valuation, LOS 3.b',
    },
    {
      text: 'A firm has book value per share of $20, expected EPS of $3.00 and a required return on equity of 11%. The residual income for the coming year is:',
      given: 'B₀ = $20 · EPS $3.00 · r = 11%',
      opts: ['$0.80', '$2.20', '$3.00', '$5.20'],
      a: 0,
      why: 'RI = EPS − r × B₀ = 3.00 − 0.11 × 20 = 3.00 − 2.20 = $0.80. The equity charge is what distinguishes RI from accounting earnings.',
      ref: 'Equity Valuation — Residual Income Valuation, LOS 5.c',
    },
    {
      text: 'A controlling-interest value is $100 per share. A discount for lack of control of 20% and a discount for lack of marketability of 15% apply. The minority, non-marketable value is closest to:',
      given: 'Control value $100 · DLOC 20% · DLOM 15%',
      opts: ['$65.00', '$68.00', '$70.00', '$80.00'],
      a: 1,
      why: '100 × (1 − 0.20) × (1 − 0.15) = 100 × 0.80 × 0.85 = $68.00. The discounts compound; adding them to 35% is the planted shortcut.',
      ref: 'Equity Valuation — Private Company Valuation, LOS 6.e',
    },
    {
      text: 'Compared with a trailing P/E, a justified leading P/E is preferable when:',
      given: null,
      opts: [
        'Earnings are volatile and the most recent year was unrepresentative',
        'The firm has no analyst coverage',
        'Book value is negative',
        'The firm pays no dividend',
      ],
      a: 0,
      why: 'Leading P/E uses forecast normalised earnings, which avoids anchoring on an unrepresentative trailing figure.',
      ref: 'Equity Valuation — Market-Based Valuation, LOS 4.c',
    },
  ],

  'cfa-l2-fixed': [
    {
      text: 'A manager expects rates to evolve exactly as implied by the current forward curve. Riding the yield curve will most likely produce:',
      given: null,
      opts: [
        'Excess return over a buy-and-hold strategy',
        'The same return as any other maturity strategy',
        'A loss relative to the benchmark',
        'A gain only if the curve is inverted',
      ],
      a: 1,
      why: 'If rates evolve as the forwards imply, all maturity strategies earn the same return by no-arbitrage. A view only pays if it differs from the forwards.',
      ref: 'Fixed Income — The Term Structure and Interest Rate Dynamics, LOS 1.d',
    },
    {
      text: 'The one-year spot rate is 3% and the two-year spot rate is 4%. The one-year forward rate one year from now is closest to:',
      given: 'z₁ = 3% · z₂ = 4%',
      opts: ['3.50%', '4.00%', '5.01%', '7.00%'],
      a: 2,
      why: '(1.04)² = (1.03)(1 + f), so 1 + f = 1.0816/1.03 = 1.0501 and f = 5.01%. Forward rates exceed spot rates on an upward-sloping curve.',
      ref: 'Fixed Income — The Term Structure and Interest Rate Dynamics, LOS 1.b',
    },
    {
      text: 'Relative to an otherwise identical option-free bond, a callable bond has:',
      given: null,
      opts: [
        'A higher value and higher effective duration',
        'A lower value and lower effective duration when rates fall',
        'A higher value and lower effective duration',
        'The same value but different convexity',
      ],
      a: 1,
      why: 'The call belongs to the issuer, so the bond is worth less. As rates fall, the call compresses price appreciation, shortening effective duration.',
      ref: 'Fixed Income — Valuation and Analysis of Bonds with Embedded Options, LOS 3.c',
    },
    {
      text: 'Which criticism applies most directly to structural credit models such as Merton?',
      given: null,
      opts: [
        'They require an estimation sample of historical defaults',
        'They rely on unobservable asset values and volatilities',
        'They cannot incorporate the capital structure',
        'They assume default is a surprise jump process',
      ],
      a: 1,
      why: "Structural models require the firm's asset value and asset volatility, neither of which is directly observable. Reduced-form models face the estimation-sample criticism.",
      ref: 'Fixed Income — Credit Analysis Models, LOS 4.d',
    },
    {
      text: 'A credit protection buyer on a CDS is economically equivalent to:',
      given: null,
      opts: [
        'Being long the reference bond',
        'Being short credit risk of the reference entity',
        'Selling a put on the reference entity',
        'Being long the benchmark government bond only',
      ],
      a: 1,
      why: 'Buying protection pays off when credit deteriorates, so it is a short credit position — the mirror image of owning the bond.',
      ref: 'Fixed Income — Credit Default Swaps, LOS 5.b',
    },
  ],

  'cfa-l2-deriv': [
    {
      text: 'Three months after inception, the forward price on a contract has risen from $50 to $53. With six months remaining and a risk-free rate of 4%, the value to the long is closest to:',
      given: 'F₀ = $50 · Fₜ = $53 · T − t = 0.5 · r = 4%',
      opts: ['$2.94', '$3.00', '$3.06', '$0.00'],
      a: 0,
      why: 'V = (Fₜ − F₀)/(1 + r)^(T−t) = 3/(1.04)^0.5 = 3/1.0198 = $2.94. The value is the discounted difference between forward prices.',
      ref: 'Derivatives — Pricing and Valuation of Forward Commitments, LOS 1.c',
    },
    {
      text: 'In the Black–Scholes–Merton model, N(d₂) is best interpreted as:',
      given: null,
      opts: [
        'The delta of the call',
        'The risk-neutral probability the option finishes in the money',
        'The actual probability the option finishes in the money',
        'The present value factor applied to the strike',
      ],
      a: 1,
      why: "N(d₂) is the risk-neutral probability of exercise. N(d₁) is the option's delta, and the actual probability is not used in the model at all.",
      ref: 'Derivatives — Valuation of Contingent Claims, LOS 2.d',
    },
    {
      text: 'A dealer is short gamma and rebalances a delta hedge only weekly. A large move in the underlying in either direction will most likely produce:',
      given: null,
      opts: [
        'A hedging gain',
        'A hedging loss',
        'No effect, because the book is delta neutral',
        'A gain only if the move is upward',
      ],
      a: 1,
      why: 'A short gamma position loses on large moves in either direction because the delta hedge is systematically wrong between rebalancing dates.',
      ref: 'Derivatives — Valuation of Contingent Claims, LOS 2.h',
    },
    {
      text: 'An increase in the volatility of the underlying will, all else equal:',
      given: null,
      opts: [
        'Increase call values and decrease put values',
        'Decrease call values and increase put values',
        'Increase both call and put values',
        'Leave both unchanged',
      ],
      a: 2,
      why: 'Higher volatility raises the value of optionality on both sides, because the downside is truncated by the option structure while the upside is not.',
      ref: 'Derivatives — Valuation of Contingent Claims, LOS 2.f',
    },
    {
      text: 'Two months after inception of a plain vanilla interest rate swap, market rates have fallen. The value of the swap to the fixed-rate payer is:',
      given: null,
      opts: ['Positive', 'Negative', 'Zero', 'Positive only if the swap is collateralised'],
      a: 1,
      why: 'The fixed payer is locked into paying an above-market rate while receiving less floating. The swap has negative value to that side.',
      ref: 'Derivatives — Pricing and Valuation of Forward Commitments, LOS 1.f',
    },
  ],

  'cfa-l2-alt': [
    {
      text: 'A commodity futures curve is in contango. An investor holding a long-only rolling futures position will most likely earn:',
      given: null,
      opts: [
        'A positive roll return',
        'A negative roll return',
        'A roll return of exactly zero',
        'A roll return independent of the curve shape',
      ],
      a: 1,
      why: 'In contango the investor sells a cheaper expiring contract and buys a more expensive deferred one, producing a negative roll return.',
      ref: 'Alternative Investments — Introduction to Commodities, LOS 1.d',
    },
    {
      text: 'A REIT reports net income of $40m, depreciation of $22m and gains on property sales of $6m. Funds from operations is:',
      given: 'NI $40m · Dep $22m · Gains $6m',
      opts: ['$50m', '$56m', '$62m', '$68m'],
      a: 1,
      why: 'FFO = NI + depreciation − gains on sales = 40 + 22 − 6 = $56m. Gains are excluded because they are not recurring operating income.',
      ref: 'Alternative Investments — Investments in Real Estate through Publicly Traded Securities, LOS 3.c',
    },
    {
      text: 'A merger arbitrage strategy has a return profile most similar to:',
      given: null,
      opts: [
        'A long call on the target',
        'A short put on deal completion',
        'A long straddle',
        'A long position in the acquirer',
      ],
      a: 1,
      why: 'The strategy earns a small steady spread when deals close and suffers large losses when they break — the payoff shape of a short put.',
      ref: 'Alternative Investments — Hedge Fund Strategies, LOS 4.c',
    },
    {
      text: 'Compared with direct real estate ownership, publicly traded REITs most likely exhibit:',
      given: null,
      opts: [
        'Lower liquidity and lower short-run equity correlation',
        'Higher liquidity and higher short-run equity correlation',
        'Higher liquidity and lower short-run equity correlation',
        'Identical liquidity and correlation',
      ],
      a: 1,
      why: 'Listed vehicles trade continuously, which gives liquidity but also imports short-run equity market beta that direct property does not display.',
      ref: 'Alternative Investments — Investments in Real Estate through Publicly Traded Securities, LOS 3.a',
    },
    {
      text: 'Under the theory of storage, a market in contango is best explained by:',
      given: null,
      opts: [
        'A high convenience yield',
        'High storage costs relative to the convenience yield',
        'Producer hedging pressure',
        'Backwardated inventory levels',
      ],
      a: 1,
      why: 'Contango arises when the cost of carrying inventory exceeds the convenience yield of holding the physical commodity.',
      ref: 'Alternative Investments — Introduction to Commodities, LOS 1.e',
    },
  ],

  'cfa-l2-pm': [
    {
      text: 'A manager has an information coefficient of 0.05, 100 independent bets per year and a transfer coefficient of 0.8. The expected information ratio is closest to:',
      given: 'IC 0.05 · BR 100 · TC 0.8',
      opts: ['0.04', '0.40', '0.50', '4.00'],
      a: 1,
      why: 'IR ≈ IC × √BR × TC = 0.05 × 10 × 0.8 = 0.40. Breadth enters as a square root, so doubling bets does not double the ratio.',
      ref: 'Portfolio Management — Analysis of Active Portfolio Management, LOS 2.d',
    },
    {
      text: 'A portfolio holds 400 stocks but all positions reflect a single macroeconomic view. Under the fundamental law of active management, breadth is closest to:',
      given: null,
      opts: ['400', '20', '1', '400 divided by the transfer coefficient'],
      a: 2,
      why: 'Breadth counts independent decisions, not holdings. One macro view driving every position is a breadth of one.',
      ref: 'Portfolio Management — Analysis of Active Portfolio Management, LOS 2.e',
    },
    {
      text: 'A portfolio has a one-day 95% VaR of $1.2m. The most accurate interpretation is:',
      given: 'VaR₉₅,₁d = $1.2m',
      opts: [
        'The maximum loss on any single day is $1.2m',
        'On 5% of days the loss is expected to exceed $1.2m',
        'The average daily loss is $1.2m',
        'Losses will never exceed $1.2m in a month',
      ],
      a: 1,
      why: 'VaR is a quantile of the loss distribution. It states the frequency with which the threshold is breached, never the size of the breach.',
      ref: 'Portfolio Management — Measuring and Managing Market Risk, LOS 5.b',
    },
    {
      text: 'A backtest uses financial statement data as later restated rather than as originally reported. This introduces:',
      given: null,
      opts: ['Survivorship bias', 'Look-ahead bias', 'Data snooping bias', 'Selection bias'],
      a: 1,
      why: 'Restated data was not available at the decision date, so the backtest uses information the manager could not have had — look-ahead bias.',
      ref: 'Portfolio Management — Backtesting and Simulation, LOS 6.c',
    },
    {
      text: 'An ETF trades persistently at a premium to net asset value. The most likely cause is:',
      given: null,
      opts: [
        'A failure of the creation/redemption mechanism',
        'High portfolio turnover within the fund',
        'A high expense ratio',
        'A large number of authorised participants',
      ],
      a: 0,
      why: 'Arbitrage by authorised participants normally closes premiums and discounts. A persistent premium implies the mechanism is impaired.',
      ref: 'Portfolio Management — Exchange-Traded Funds, LOS 3.c',
    },
  ],
};
