import { QuizBank } from '../types';

/** FRM Part I and Part II — five questions per topic area, in GARP's house style. */
export const FRM_QUESTIONS: QuizBank = {
  // -------------------------------------------------------------------------
  // Part I
  // -------------------------------------------------------------------------
  'frm-p1-foundations': [
    {
      text: 'A portfolio has a return of 12%, a standard deviation of 18% and a beta of 1.2. The risk-free rate is 3%. Its Treynor ratio is closest to:',
      given: 'R_p 12% · σ 18% · β 1.2 · R_f 3%',
      opts: ['0.050', '0.075', '0.090', '0.500'],
      a: 1,
      why: 'Treynor = (R_p − R_f)/β = (12% − 3%)/1.2 = 0.075. The Sharpe ratio, using σ, would be 0.50.',
      ref: 'Foundations of Risk Management — Risk-Adjusted Performance',
    },
    {
      text: 'The collapse of Barings Bank is most directly attributed to:',
      given: null,
      opts: ['An unhedged commodity basis exposure', 'A single trader controlling both trading and settlement functions', 'A liquidity mismatch in the repo book', 'A model error in option pricing'],
      a: 1,
      why: 'The failure was one of governance: Nick Leeson controlled both the front and back office, so losses could be concealed. The trade itself was secondary.',
      ref: 'Foundations of Risk Management — Financial Disasters',
    },
    {
      text: 'Two portfolios show identical Sharpe ratios but different Treynor ratios. This most likely indicates that:',
      given: null,
      opts: ['One portfolio holds significant undiversified specific risk', 'One portfolio is leveraged', 'The risk-free rate was measured differently', 'Both portfolios are fully diversified'],
      a: 0,
      why: 'For fully diversified portfolios the two measures rank identically. Divergence implies specific risk in one portfolio that beta does not capture.',
      ref: 'Foundations of Risk Management — Risk-Adjusted Performance',
    },
    {
      text: 'Under an enterprise risk management framework, the primary responsibility for setting risk appetite lies with:',
      given: null,
      opts: ['The chief risk officer', 'The board of directors', 'Internal audit', 'The trading desk heads'],
      a: 1,
      why: 'The board sets risk appetite; management translates it into limits and the risk function monitors adherence. Audit provides independent assurance.',
      ref: 'Foundations of Risk Management — Risk Governance',
    },
    {
      text: 'A risk that can be transferred at a known cost, such as a hedgeable currency exposure, is best managed by:',
      given: null,
      opts: ['Holding economic capital against it', 'Hedging it', 'Scenario analysis only', 'Accepting it as an unknown unknown'],
      a: 1,
      why: 'Known and hedgeable risks are hedged. Capital covers quantifiable but unhedged risk; scenario analysis addresses the unknown unknowns.',
      ref: 'Foundations of Risk Management — Risk Taxonomy',
    },
  ],

  'frm-p1-quant': [
    {
      text: 'A test for a rare condition has 95% sensitivity and 95% specificity. The condition affects 1% of the population. Given a positive result, the probability the condition is present is closest to:',
      given: 'P(D) = 1% · sensitivity 95% · specificity 95%',
      opts: ['16%', '48%', '85%', '95%'],
      a: 0,
      why: 'P(D|+) = (0.95 × 0.01)/[(0.95 × 0.01) + (0.05 × 0.99)] = 0.0095/0.0590 = 16.1%. Base rates dominate when the event is rare.',
      ref: "Quantitative Analysis — Bayes' Rule",
    },
    {
      text: 'A GARCH(1,1) model is estimated with α = 0.08 and β = 0.90. Persistence and the implication for volatility are:',
      given: 'α = 0.08 · β = 0.90',
      opts: ['0.98 — volatility mean-reverts slowly', '0.98 — volatility mean-reverts quickly', '0.82 — the model is non-stationary', '1.00 — the model reduces to EWMA'],
      a: 0,
      why: 'Persistence is α + β = 0.98, close to one, so shocks decay slowly and volatility mean-reverts only gradually. At exactly 1.00 it becomes EWMA.',
      ref: 'Quantitative Analysis — Measuring Volatility',
    },
    {
      text: 'An analyst regresses one random walk on an unrelated random walk and obtains an R² of 0.78 with a significant t-statistic. The correct conclusion is that:',
      given: null,
      opts: ['A genuine economic relationship exists', 'The regression is spurious because both series are non-stationary', 'The sample size is too small', 'Heteroskedasticity is present'],
      a: 1,
      why: 'Regressing non-stationary series produces spuriously high R² and significant t-statistics with no underlying relationship. Difference the series first.',
      ref: 'Quantitative Analysis — Stationary and Non-Stationary Time Series',
    },
    {
      text: 'Lowering the significance level of a hypothesis test from 5% to 1% will:',
      given: null,
      opts: ['Reduce Type I error and reduce Type II error', 'Reduce Type I error and increase Type II error', 'Increase Type I error and reduce Type II error', 'Leave both error rates unchanged'],
      a: 1,
      why: 'A stricter threshold makes rejection harder, cutting false rejections (Type I) but raising failures to reject a false null (Type II).',
      ref: 'Quantitative Analysis — Hypothesis Testing',
    },
    {
      text: 'Compared with GARCH(1,1), the EWMA model:',
      given: null,
      opts: ['Includes a long-run variance term and mean-reverts', 'Omits the long-run variance term and does not mean-revert', 'Requires a normality assumption GARCH does not', 'Cannot be estimated from historical returns'],
      a: 1,
      why: 'EWMA is GARCH(1,1) with ω = 0 and α + β = 1, so there is no long-run variance to revert to.',
      ref: 'Quantitative Analysis — Measuring Volatility and Correlation',
    },
  ],

  'frm-p1-markets': [
    {
      text: 'The standard deviation of spot price changes is 0.65, the standard deviation of futures price changes is 0.81, and their correlation is 0.80. The minimum variance hedge ratio is closest to:',
      given: 'σ_S 0.65 · σ_F 0.81 · ρ 0.80',
      opts: ['0.64', '0.80', '0.99', '1.25'],
      a: 0,
      why: 'h* = ρ × (σ_S/σ_F) = 0.80 × (0.65/0.81) = 0.80 × 0.8025 = 0.642.',
      ref: 'Financial Markets and Products — Hedging with Futures',
    },
    {
      text: 'Initial margin posted to a central counterparty is intended to cover:',
      given: null,
      opts: ['Current mark-to-market exposure', 'Potential future exposure over the close-out period', 'The clearing member\'s default fund contribution', 'Accrued interest on the position'],
      a: 1,
      why: 'Initial margin covers potential future exposure between default and close-out. Variation margin settles current mark-to-market.',
      ref: 'Financial Markets and Products — Central Counterparties',
    },
    {
      text: 'An investor buys a call with a strike of $40 for a premium of $3. The breakeven price at expiry is:',
      given: 'X = $40 · premium $3',
      opts: ['$37', '$40', '$43', '$46'],
      a: 2,
      why: 'Breakeven = strike + premium = 40 + 3 = $43. Below that the option either expires worthless or recovers less than the premium paid.',
      ref: 'Financial Markets and Products — Options Mechanics and Payoffs',
    },
    {
      text: 'A hedger uses a futures contract on a related but different asset. The residual exposure is best described as:',
      given: null,
      opts: ['Counterparty risk', 'Basis risk', 'Liquidity risk', 'Operational risk'],
      a: 1,
      why: 'Cross-hedging leaves basis risk — the risk that the spot and futures prices do not move together.',
      ref: 'Financial Markets and Products — Forwards and Futures',
    },
    {
      text: 'On a reset date, the value of the floating leg of a plain vanilla interest rate swap is:',
      given: null,
      opts: ['Zero', 'Par', 'The notional plus accrued interest for the full remaining term', 'Indeterminate without the forward curve'],
      a: 1,
      why: 'A floating-rate note reprices to par on each reset date. That single fact collapses most swap valuation questions.',
      ref: 'Financial Markets and Products — Swaps',
    },
  ],

  'frm-p1-valuation': [
    {
      text: 'A portfolio worth $200m has a daily volatility of 1.2% and a mean daily return of zero. The 1-day 99% VaR is closest to:',
      given: 'V $200m · σ 1.2% · z₉₉ = 2.326',
      opts: ['$2.4m', '$3.9m', '$5.6m', '$8.5m'],
      a: 2,
      why: 'VaR = 2.326 × 0.012 × 200m = $5.58m. Using the 95% z-score of 1.645 gives $3.9m, the planted distractor.',
      ref: 'Valuation and Risk Models — Value-at-Risk',
    },
    {
      text: 'A loan has a probability of default of 3%, loss given default of 45% and exposure at default of $10m. Expected loss is:',
      given: 'PD 3% · LGD 45% · EAD $10m',
      opts: ['$135,000', '$300,000', '$450,000', '$1,350,000'],
      a: 0,
      why: 'EL = PD × LGD × EAD = 0.03 × 0.45 × 10,000,000 = $135,000. Provisions cover this; capital covers the unexpected loss around it.',
      ref: 'Valuation and Risk Models — Credit Risk',
    },
    {
      text: 'Which statement about expected shortfall is correct?',
      given: null,
      opts: ['ES is never greater than VaR at the same confidence level', 'ES is sub-additive; VaR need not be', 'ES ignores the shape of the tail', 'ES requires an assumption of normality'],
      a: 1,
      why: 'ES is a coherent risk measure and therefore sub-additive, while VaR can violate sub-additivity. ES also always equals or exceeds VaR at the same confidence.',
      ref: 'Valuation and Risk Models — Coherent Risk Measures',
    },
    {
      text: 'Historical simulation VaR differs from delta-normal VaR chiefly because it:',
      given: null,
      opts: ['Assumes returns are normally distributed', 'Requires no distributional assumption', 'Cannot handle option positions', 'Always produces a lower VaR estimate'],
      a: 1,
      why: 'Historical simulation reorders actual past returns, so no distribution is assumed — at the cost of needing a long, representative sample.',
      ref: 'Valuation and Risk Models — Non-parametric Approaches',
    },
    {
      text: 'A delta-neutral options book is long gamma. A large move in the underlying in either direction will produce:',
      given: null,
      opts: ['A loss', 'A gain', 'No profit or loss, since the book is delta neutral', 'A gain only if the move is upward'],
      a: 1,
      why: 'Long gamma means the position\'s delta moves favourably as the underlying moves, producing gains on large moves in either direction.',
      ref: 'Valuation and Risk Models — Option Sensitivities',
    },
  ],

  // -------------------------------------------------------------------------
  // Part II
  // -------------------------------------------------------------------------
  'frm-p2-market': [
    {
      text: 'A portfolio has a 1-day 99% VaR of $2.5m. Assuming i.i.d. returns, the 10-day 99% VaR is closest to:',
      given: 'VaR(1) = $2.5m · T = 10',
      opts: ['$7.9m', '$25.0m', '$2.5m', '$5.0m'],
      a: 0,
      why: '√10 ≈ 3.162, so 2.5 × 3.162 ≈ $7.9m. Square-root-of-time scaling requires independent, identically distributed returns.',
      ref: 'Market Risk — VaR Measurement',
    },
    {
      text: 'A bank’s 99% 1-day VaR model produced 9 exceptions in 250 trading days. This most likely indicates:',
      given: 'Expected exceptions = 0.01 × 250 = 2.5',
      opts: ['The model overstates risk', 'The model is well calibrated', 'The model understates risk', 'Nothing without expected shortfall data'],
      a: 2,
      why: 'Nine breaches against 2.5 expected is far more than chance would suggest — the model understates risk and falls into the Basel red zone.',
      ref: 'Market Risk — Backtesting VaR',
    },
    {
      text: 'Breaches of a VaR model cluster in a single stressed week rather than occurring evenly. The most appropriate test is:',
      given: null,
      opts: ["Kupiec's unconditional coverage test", "Christoffersen's conditional coverage test", 'A Jarque–Bera normality test', 'A Dickey–Fuller unit root test'],
      a: 1,
      why: 'Kupiec tests only the number of exceptions. Christoffersen adds an independence test, which is what detects clustering.',
      ref: 'Market Risk — Backtesting VaR',
    },
    {
      text: 'In extreme value theory using the peaks-over-threshold approach, a positive shape parameter ξ indicates:',
      given: null,
      opts: ['Tails thinner than the normal distribution', 'Tails fatter than the normal distribution', 'A bounded loss distribution', 'That the threshold was set too low'],
      a: 1,
      why: 'A positive ξ corresponds to the Fréchet domain — heavy tails, decaying more slowly than the normal distribution.',
      ref: 'Market Risk — Extreme Value Theory',
    },
    {
      text: 'The Gaussian copula was widely criticised after 2008 primarily because it:',
      given: null,
      opts: ['Cannot join different marginal distributions', 'Exhibits zero tail dependence', 'Requires equal marginals for all variables', 'Cannot be calibrated to market data'],
      a: 1,
      why: 'The Gaussian copula implies assets become independent in the extreme tail, exactly the opposite of observed crisis behaviour. Student t copulas admit tail dependence.',
      ref: 'Market Risk — Correlation and Copulas',
    },
  ],

  'frm-p2-credit': [
    {
      text: 'Under the Merton model, an increase in the volatility of the firm’s assets will:',
      given: null,
      opts: ['Increase equity value and decrease default probability', 'Increase equity value and increase default probability', 'Decrease equity value and increase default probability', 'Leave equity value unchanged'],
      a: 1,
      why: 'Equity is a call on the firm\'s assets, so higher asset volatility raises its value. It simultaneously raises the probability the assets fall below the debt.',
      ref: 'Credit Risk — Structural Default Models',
    },
    {
      text: 'Holding individual default probabilities constant, an increase in default correlation across a credit portfolio will:',
      given: null,
      opts: ['Increase expected loss and increase credit VaR', 'Leave expected loss unchanged and increase credit VaR', 'Increase expected loss and leave credit VaR unchanged', 'Reduce both measures'],
      a: 1,
      why: 'Expected loss depends only on individual PDs. Correlation fattens the tail of the loss distribution, which is what credit VaR measures.',
      ref: 'Credit Risk — Portfolio Credit Risk',
    },
    {
      text: 'A bank buys credit protection on a sovereign from a bank domiciled in that same sovereign. This is a clear example of:',
      given: null,
      opts: ['Right-way risk', 'Wrong-way risk', 'Basis risk', 'Settlement risk'],
      a: 1,
      why: 'The protection seller is most likely to default precisely when the protection is needed, so exposure and counterparty credit quality move adversely together.',
      ref: 'Credit Risk — Counterparty Risk and CVA',
    },
    {
      text: 'In a CDO structure, an increase in default correlation across the collateral pool will most likely:',
      given: null,
      opts: ['Benefit the equity tranche and harm the senior tranche', 'Harm the equity tranche and benefit the senior tranche', 'Benefit both tranches', 'Have no effect on either tranche'],
      a: 0,
      why: 'Higher correlation raises the probability of zero losses (helping equity) and of very large losses (harming senior). Senior tranches are effectively short correlation.',
      ref: 'Credit Risk — Structured Credit and CDOs',
    },
    {
      text: 'Which mechanism most directly reduces counterparty credit exposure without changing the underlying trades?',
      given: null,
      opts: ['Increasing the notional', 'Close-out netting and collateral agreements', 'Extending the maturity', 'Widening the credit spread charged'],
      a: 1,
      why: 'Netting offsets positive and negative exposures to the same counterparty, and collateral covers the residual. Neither alters the trades themselves.',
      ref: 'Credit Risk — Netting, Collateral and Margining',
    },
  ],

  'frm-p2-operational': [
    {
      text: 'In a loss distribution approach, operational loss frequency is most commonly modelled with:',
      given: null,
      opts: ['A lognormal distribution', 'A Poisson distribution', 'A generalised Pareto distribution', 'A Student t distribution'],
      a: 1,
      why: 'Frequency is a count over a fixed period, which the Poisson distribution describes. Severity is typically lognormal, with a Pareto tail.',
      ref: 'Operational Risk — Modelling Loss Distributions',
    },
    {
      text: 'A firm’s risk management function both designs the control framework and performs the independent assurance review of it. This most directly compromises:',
      given: null,
      opts: ['The first line of defence', 'The separation of the second and third lines of defence', 'The board\'s risk appetite statement', 'The RCSA process only'],
      a: 1,
      why: 'Independent assurance belongs to internal audit, the third line. A function cannot independently assure the controls it designed.',
      ref: 'Operational Risk — Three Lines of Defence',
    },
    {
      text: 'A model validated successfully on historical data fails badly in a new market regime. This is best classified as a failure of:',
      given: null,
      opts: ['Implementation accuracy', 'Conceptual soundness', 'Data quality controls', 'Change management'],
      a: 1,
      why: 'The model was built and coded correctly but rests on assumptions that do not hold in the new regime — a conceptual soundness failure.',
      ref: 'Operational Risk — Model Risk Management',
    },
    {
      text: 'A firm outsources a critical process to a third party that suffers an outage. Regulatory accountability for the disruption rests with:',
      given: null,
      opts: ['The third party alone', 'The firm, which cannot outsource accountability', 'Both parties equally by default', 'Neither, if the contract contains a force majeure clause'],
      a: 1,
      why: 'Outsourcing an activity never outsources the accountability. The firm remains responsible for the resilience of its critical services.',
      ref: 'Operational Risk — Third-Party and Outsourcing Risk',
    },
    {
      text: 'Internal loss data alone is generally insufficient for operational risk capital because it:',
      given: null,
      opts: ['Is not audited', 'Is too sparse in the tail to estimate extreme severity', 'Overstates high-frequency low-severity events', 'Cannot be used under Basel rules'],
      a: 1,
      why: 'A single firm rarely experiences enough extreme events to estimate the tail, so external data and scenario analysis supplement internal data.',
      ref: 'Operational Risk — Loss Data Collection',
    },
  ],

  'frm-p2-liquidity': [
    {
      text: 'A position worth $50m has a VaR of $2m and a bid–ask spread of 0.40%. Liquidity-adjusted VaR using the exogenous spread approach is closest to:',
      given: 'V $50m · VaR $2m · spread 0.40%',
      opts: ['$2.00m', '$2.10m', '$2.20m', '$4.00m'],
      a: 1,
      why: 'LVaR = VaR + ½ × spread × V = 2m + 0.5 × 0.004 × 50m = 2m + 0.1m = $2.10m.',
      ref: 'Liquidity Risk — Liquidity-Adjusted VaR',
    },
    {
      text: 'The liquidity coverage ratio requires a bank to hold high-quality liquid assets sufficient to cover net cash outflows over:',
      given: null,
      opts: ['5 days', '30 days', '90 days', 'One year'],
      a: 1,
      why: 'The LCR is a 30-day stressed horizon. The NSFR is the one-year structural measure.',
      ref: 'Liquidity Risk — Basel Liquidity Framework',
    },
    {
      text: 'A fund forced to sell assets to meet redemptions depresses prices, triggering further redemptions and further sales. This is best described as:',
      given: null,
      opts: ['Basis risk', 'A liquidity spiral', 'Wrong-way risk', 'Regulatory arbitrage'],
      a: 1,
      why: 'Funding pressure forces sales, which worsens market liquidity, which worsens funding pressure — the self-reinforcing liquidity spiral.',
      ref: 'Liquidity Risk — Funding versus Market Liquidity',
    },
    {
      text: 'Without funds transfer pricing, a bank’s long-dated lending business will most likely appear:',
      given: null,
      opts: ['Less profitable than it is, because liquidity cost is over-allocated', 'More profitable than it is, because liquidity cost is not charged to it', 'Correctly priced, since liquidity cost is a central function', 'Unaffected, since FTP is an accounting convention only'],
      a: 1,
      why: 'FTP charges business lines for the liquidity they consume. Without it, long-dated lending appears artificially profitable at the centre\'s expense.',
      ref: 'Liquidity Risk — Transfer Pricing',
    },
    {
      text: 'Which asset receives no haircut in the LCR high-quality liquid asset calculation?',
      given: null,
      opts: ['Level 1 assets', 'Level 2A assets', 'Level 2B assets', 'All HQLA receive the same haircut'],
      a: 0,
      why: 'Level 1 assets — cash, central bank reserves and qualifying sovereign debt — are counted at full value. Level 2A and 2B take haircuts and are capped.',
      ref: 'Liquidity Risk — Basel Liquidity Framework',
    },
  ],

  'frm-p2-investment': [
    {
      text: 'A small allocation to an asset with high volatility and high correlation to the rest of the portfolio can dominate the risk budget. The measure that reveals this is:',
      given: null,
      opts: ['The position weight', 'Marginal contribution to risk', 'The Sharpe ratio of the position', 'The position\'s standalone volatility'],
      a: 1,
      why: 'Marginal contribution to risk accounts for both the volatility and the correlation with the existing portfolio, which a weight or standalone volatility cannot.',
      ref: 'Risk and Investment Management — Risk Budgeting',
    },
    {
      text: 'When a hedge fund joins an index, the index provider adds the fund’s prior track record. The resulting distortion is:',
      given: null,
      opts: ['Survivorship bias', 'Backfill bias', 'Selection bias in the risk-free rate', 'Smoothing bias'],
      a: 1,
      why: 'Backfill bias arises because funds tend to join after a strong period, so the added history inflates reported index performance.',
      ref: 'Risk and Investment Management — Hedge Fund Indices',
    },
    {
      text: 'Reported returns on an illiquid private portfolio display strong positive autocorrelation. Unsmoothing the series will:',
      given: null,
      opts: ['Lower the estimated volatility and raise the Sharpe ratio', 'Raise the estimated volatility and lower the Sharpe ratio', 'Leave volatility unchanged but raise correlation', 'Lower both volatility and correlation'],
      a: 1,
      why: 'Smoothing understates true volatility and correlation. Correcting for it raises volatility, which reduces the Sharpe ratio.',
      ref: 'Risk and Investment Management — Illiquid Assets',
    },
    {
      text: 'Factor theory holds that assets earn a risk premium because they:',
      given: null,
      opts: ['Belong to a particular asset class', 'Perform poorly in bad times', 'Have high historical volatility', 'Are held by institutional investors'],
      a: 1,
      why: 'Premia compensate exposure to bad times, not asset labels. Two differently labelled assets with the same factor exposure should earn similar returns.',
      ref: 'Risk and Investment Management — Factor Theory',
    },
    {
      text: 'A manager reports strong alpha, but a factor regression shows most of the excess return is explained by a persistent value tilt. The appropriate conclusion is that the return reflects:',
      given: null,
      opts: ['Genuine manager skill', 'Systematic factor exposure available more cheaply', 'A backtesting error', 'Survivorship bias in the benchmark'],
      a: 1,
      why: 'Return attributable to a known factor is beta, not alpha, and can be obtained through cheaper systematic implementations.',
      ref: 'Risk and Investment Management — Factor Theory',
    },
  ],

  'frm-p2-current': [
    {
      text: 'The Current Issues topic differs from every other FRM topic area because it:',
      given: null,
      opts: ['Is not examined', 'Is replaced substantially each exam cycle', 'Contains only quantitative material', 'Carries the largest weight in Part II'],
      a: 1,
      why: 'The reading list rotates each year, so prior-year materials are unreliable. GARP publishes the current list directly.',
      ref: 'Current Issues in Financial Markets — Scope',
    },
    {
      text: 'The principal supervisory concern with machine learning models used in credit decisions is:',
      given: null,
      opts: ['Their computational cost', 'Limited explainability and the resulting model governance gap', 'Their inability to handle large datasets', 'That they cannot be backtested'],
      a: 1,
      why: 'Supervisors expect firms to explain credit decisions. Opaque models create a governance problem: who validates a model nobody fully understands.',
      ref: 'Current Issues — AI and Machine Learning in Finance',
    },
    {
      text: 'A scenario describing rapid, well-signalled decarbonisation policy is best characterised as:',
      given: null,
      opts: ['High physical risk and low transition risk', 'Low physical risk and high transition risk', 'High physical and high transition risk', 'Low physical and low transition risk'],
      a: 1,
      why: 'Fast policy action raises transition risk for exposed sectors while limiting the warming that drives physical risk. The scenarios deliberately trade the two off.',
      ref: 'Current Issues — Climate and Transition Risk',
    },
    {
      text: 'The 2023 US regional banking stress is best explained by the interaction of:',
      given: null,
      opts: ['Credit losses on commercial loans and inadequate provisions', 'Unrealised duration losses and concentrated, digitally mobile uninsured deposits', 'Operational failures in payment systems', 'Counterparty defaults in the derivatives market'],
      a: 1,
      why: 'Held-to-maturity portfolios carried large unrealised losses while a concentrated uninsured deposit base withdrew faster than liquidity rules assumed.',
      ref: 'Current Issues — Post-2023 Banking Stress',
    },
    {
      text: 'A key financial stability concern with fiat-referenced stablecoins is that they:',
      given: null,
      opts: ['Cannot be transferred across borders', 'Are subject to run dynamics if reserve quality or redemption is doubted', 'Pay a variable interest rate to holders', 'Are always fully insured by deposit schemes'],
      a: 1,
      why: 'A stablecoin is a redeemable claim on a reserve pool. Doubt about reserve quality or redemption capacity produces classic run dynamics.',
      ref: 'Current Issues — Digital Assets and Stablecoins',
    },
  ],
};
