/** Financial statement analysis, and the corporate-issuer terms that lean on it. */
import { GlossaryTerm } from './types';

export const FSA_TERMS: GlossaryTerm[] = [
  {
    key: 'accrual-accounting',
    term: 'Accrual accounting',
    definition:
      'Recognising revenue when it is earned and expenses when they are incurred, regardless of when cash moves.',
    note: 'The gap between accrual earnings and cash flow is where most accounting-quality questions live. Persistently high accruals are a warning sign.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'balance-sheet',
    term: 'Balance sheet',
    aka: ['statement of financial position'],
    definition: 'A statement of what a company owns and owes at a single point in time.',
    formula: 'Assets = Liabilities + Equity',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'income-statement',
    term: 'Income statement',
    aka: ['profit and loss', 'P&L'],
    definition: 'A statement of revenue, expenses and profit over a period.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'cash-flow-statement',
    term: 'Statement of cash flows',
    definition:
      'A statement reconciling opening and closing cash, split into operating, investing and financing activities.',
    note: 'Cash flow is much harder to manipulate than earnings, which is why analysts start here when something looks wrong.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'cfo',
    term: 'Cash flow from operations',
    aka: ['CFO', 'operating cash flow'],
    definition: 'Cash generated by the core business, before investment and financing.',
    note: 'The indirect method starts at net income and adds back non-cash charges and working capital movements. Classification of interest paid differs between IFRS and US GAAP.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'free-cash-flow',
    term: 'Free cash flow',
    aka: ['FCF', 'FCFF', 'FCFE'],
    definition:
      'Cash available after the investment needed to maintain the business. FCFF is available to all capital providers; FCFE is what remains for equity holders after debt service.',
    formula: 'FCFF = CFO + Interest × (1 − tax rate) − CapEx',
    note: 'Discount FCFF at WACC, FCFE at the cost of equity. Mixing the two is the most common valuation error in the exam.',
    topics: ['cfa-l1-fsa', 'cfa-l1-equity', 'cfa-l2-equity'],
  },
  {
    key: 'ebitda',
    term: 'EBITDA',
    definition:
      'Earnings before interest, tax, depreciation and amortisation — a rough proxy for operating cash generation.',
    note: 'Ignores capital intensity and working capital entirely. Two firms with identical EBITDA and very different capex are not comparable.',
    topics: ['cfa-l1-fsa', 'cfa-l1-equity'],
  },
  {
    key: 'working-capital',
    term: 'Working capital',
    definition:
      'Current assets less current liabilities — the short-term capital tied up in operations.',
    note: 'Growing revenue with faster-growing receivables means the growth is being funded by the balance sheet, not the customer.',
    topics: ['cfa-l1-fsa', 'cfa-l1-corp'],
  },
  {
    key: 'lifo-fifo',
    term: 'LIFO and FIFO',
    definition:
      'Inventory cost-flow assumptions. FIFO expenses the oldest costs first; LIFO expenses the newest.',
    note: 'LIFO is permitted under US GAAP and prohibited under IFRS. When prices rise, LIFO gives lower income and lower inventory — the LIFO reserve converts between the two.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'depreciation',
    term: 'Depreciation',
    definition: 'The systematic allocation of a tangible asset’s cost over its useful life.',
    note: 'Accelerated methods shift expense forward, lowering early income and raising later income. Useful life and salvage value are management estimates and are a standard quality-of-earnings lever.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'goodwill',
    term: 'Goodwill',
    definition:
      'The excess of a purchase price over the fair value of the identifiable net assets acquired.',
    note: 'Not amortised; tested for impairment. A large impairment is an admission that the acquisition was overpriced.',
    topics: ['cfa-l1-fsa', 'cfa-l2-fsa'],
  },
  {
    key: 'deferred-tax',
    term: 'Deferred tax',
    definition:
      'Tax arising from timing differences between accounting profit and taxable profit, recognised as an asset or a liability.',
    note: 'A deferred tax liability that never reverses behaves like equity. Analysts often reclassify it for that reason.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'operating-leverage',
    term: 'Operating leverage',
    definition:
      'The sensitivity of operating income to a change in sales, driven by the proportion of fixed costs.',
    note: 'High fixed costs amplify both directions. Pair it with financial leverage and small revenue moves produce very large earnings moves.',
    topics: ['cfa-l1-fsa', 'cfa-l1-corp'],
  },
  {
    key: 'financial-leverage',
    term: 'Financial leverage',
    aka: ['gearing'],
    definition:
      'The use of debt to finance assets, magnifying returns to equity in both directions.',
    topics: ['cfa-l1-fsa', 'cfa-l1-corp'],
  },
  {
    key: 'roe',
    term: 'Return on equity',
    aka: ['ROE'],
    definition: 'Net income as a percentage of average shareholders’ equity.',
    formula: 'ROE = Net margin × Asset turnover × Financial leverage',
    note: 'That three-part split is the DuPont decomposition. A rising ROE driven only by leverage is a different story from one driven by margin.',
    topics: ['cfa-l1-fsa', 'cfa-l1-equity'],
  },
  {
    key: 'dupont-analysis',
    term: 'DuPont analysis',
    definition:
      'Decomposing ROE into its drivers — profitability, efficiency and leverage — to identify what is actually moving it.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'current-ratio',
    term: 'Current ratio',
    definition:
      'Current assets divided by current liabilities, a rough test of short-term solvency.',
    note: 'The quick ratio strips out inventory, which is the least liquid current asset and the one most likely to be stale.',
    topics: ['cfa-l1-fsa'],
  },
  {
    key: 'interest-coverage',
    term: 'Interest coverage ratio',
    definition:
      'EBIT divided by interest expense — how many times earnings cover the interest bill.',
    note: 'A primary input to credit ratings and to covenant tests.',
    topics: ['cfa-l1-fsa', 'cfa-l1-fixed', 'frm-p2-credit'],
  },
  {
    key: 'earnings-quality',
    term: 'Earnings quality',
    definition:
      'The degree to which reported earnings are sustainable and backed by cash rather than by estimates and one-offs.',
    note: 'Standard flags: earnings persistently above cash flow, rising days sales outstanding, and repeated "non-recurring" charges.',
    topics: ['cfa-l1-fsa', 'cfa-l2-fsa'],
  },
  {
    key: 'off-balance-sheet',
    term: 'Off-balance-sheet financing',
    definition:
      'Arrangements that give a company the use of an asset or the benefit of borrowing without showing the liability on its balance sheet.',
    note: 'Largely curtailed for leases by IFRS 16 and ASC 842, which brought most operating leases on balance sheet.',
    topics: ['cfa-l1-fsa', 'cfa-l2-fsa'],
  },
];
