import { PremiumSegmentBank } from '../types';

/**
 * CFA Level I — premium segments, tranche II.
 *
 * A third segment per topic area, drawn from the learning modules the first two
 * did not reach. Level I Fixed Income alone is nineteen modules; two segments
 * could not cover it and pretending otherwise would have left the most-weighted
 * areas the thinnest.
 *
 * Appended after tranche I in `segments/index.ts`, never inserted — see the note
 * there on why the order is load-bearing.
 */
export const CFA_L1_SEGMENTS_II: PremiumSegmentBank = {
  'cfa-l1-ethics': [
    {
      slug: 'professionalism-and-diligence',
      name: 'Professionalism & Diligence',
      blurb: 'Standard I and Standard V — competence, misrepresentation, and the basis for a call.',
      modules: [
        'Code of Ethics and Standards of Professional Conduct',
        'Guidance for Standard I: Professionalism',
        'Guidance for Standard V: Investment Analysis, Recommendations, and Actions',
        'Guidance for Standard VII: Responsibilities as a CFA Institute Member or Candidate',
      ],
      cards: [
        {
          kicker: 'BASIS',
          title: 'Standard V(A) is about what you did, not what happened',
          body: 'A recommendation needs a reasonable and adequate basis supported by appropriate research and investigation. Relying on a third party is permitted only after making reasonable efforts to establish that the third party is itself sound.',
          formula: null,
          exam: 'Judge the process. A recommendation that made money on no basis is still a violation; one that lost money on a defensible basis is not.',
        },
        {
          kicker: 'MISREPRESENTATION',
          title: 'Plagiarism is the form of I(C) the exam tests most',
          body: 'Using another’s work without attribution breaches Standard I(C), including reusing charts, phrasing or model output. Recognised statistical bodies and factual data need no attribution; analysis and opinion always do.',
          formula: null,
          exam: 'Citing a source you have not read is also misrepresentation — you are claiming a diligence you did not perform.',
        },
        {
          kicker: 'COMPETENCE',
          title: 'Standard I(A) also covers not knowingly helping somebody else break it',
          body: 'Members must understand and comply with applicable law, must not knowingly participate in a violation, and must dissociate when one comes to light. Dissociation means stepping away from the activity, not merely disagreeing with it.',
          formula: null,
          exam: 'Resignation is rarely the required first step. Escalation, then documented dissociation, is.',
        },
      ],
      questions: [
        {
          text: 'An analyst forwards a third-party research note to clients as the firm’s own recommendation, having read the summary but not the underlying work. This most likely violates:',
          given: null,
          opts: [
            'Standard III(B) Fair Dealing',
            'Standard V(A) Diligence and Reasonable Basis, and Standard I(C) Misrepresentation',
            'Standard VI(A) Disclosure of Conflicts only',
            'No standard, because the third party is reputable',
          ],
          a: 1,
          why: 'Relying on third-party work requires reasonable efforts to verify its soundness. Presenting it as the firm’s own compounds the failure with misrepresentation.',
          ref: 'Standard V(A) — Diligence and Reasonable Basis',
        },
        {
          text: 'Which use of another party’s material requires attribution under Standard I(C)?',
          given: null,
          opts: [
            'Unemployment figures published by a national statistical agency',
            'A competitor analyst’s written interpretation of those figures',
            'A widely used option pricing formula',
            'The closing price of a listed security',
          ],
          a: 1,
          why: 'Factual data from recognised sources and standard formulae need no citation. Another party’s analysis and opinion always do.',
          ref: 'Standard I(C) — Misrepresentation',
        },
        {
          text: 'A member discovers that a colleague is preparing marketing material containing a claim the member knows to be false. The member’s minimum obligation is to:',
          given: null,
          opts: [
            'Say nothing, since the material is not the member’s responsibility',
            'Decline to participate and report the matter through appropriate channels',
            'Correct the material without telling anyone',
            'Resign from the firm',
          ],
          a: 1,
          why: 'Standard I(A) prohibits knowingly participating in a violation and requires dissociation. Escalation comes before resignation, which is a last resort.',
          ref: 'Standard I(A) — Knowledge of the Law',
        },
        {
          text: 'A quantitative analyst builds a model whose output drives client recommendations. Under Standard V(A) she must most appropriately:',
          given: null,
          opts: [
            'Rely on the model output alone, since it is objective',
            'Understand the model’s assumptions and limitations, and test it before relying on it',
            'Disclose the model’s source code to clients',
            'Have the model audited by a regulator',
          ],
          a: 1,
          why: 'Diligence extends to the tools used. A member who cannot state a model’s assumptions has no reasonable basis for what it produces.',
          ref: 'Standard V(A) — Diligence and Reasonable Basis',
        },
        {
          text: 'A charterholder describes herself as "a CFA" on her firm biography. This is:',
          given: null,
          opts: [
            'Acceptable, because she holds the charter',
            'Improper — the marks are adjectives, so the correct form is "CFA charterholder"',
            'Acceptable only in written materials',
            'Improper only if she is not a member in good standing',
          ],
          a: 1,
          why: 'Standard VII(B) requires the marks be used as adjectives, never as nouns or in the plural. "A CFA" treats the mark as a noun.',
          ref: 'Standard VII(B) — Reference to CFA Institute and the CFA Designation',
        },
        {
          text: 'A member is asked by a prospective employer to describe the strategies used at her current firm, including a proprietary screening method. She should most appropriately:',
          given: null,
          opts: [
            'Describe the method fully, since she developed part of it',
            'Describe her general expertise without disclosing proprietary methods belonging to her employer',
            'Refuse to discuss her experience at all',
            'Describe the method only if the prospective employer signs an agreement',
          ],
          a: 1,
          why: 'General skill and knowledge travel with a member; employer property, including proprietary methods, does not. Standards I(C) and IV(A) both bear on it.',
          ref: 'Standard IV(A) — Loyalty',
        },
      ],
    },
  ],

  'cfa-l1-quant': [
    {
      slug: 'rates-and-time-value',
      name: 'Rates & Time Value',
      blurb: 'Moving between rate conventions, and valuing a stream of cash flows correctly.',
      modules: ['Rates and Returns', 'Time Value of Money in Finance'],
      cards: [
        {
          kicker: 'CONVERT',
          title: 'Never compare two rates on different compounding conventions',
          body: 'The effective annual rate is the common currency. Convert a stated annual rate at m compoundings per year before comparing it with anything, and remember that continuous compounding is the limiting case.',
          formula: 'EAR = (1 + r/m)^m − 1;  continuous: EAR = e^r − 1',
          exam: 'A higher stated rate with less frequent compounding can be the worse deal. That is the entire point of most of these items.',
        },
        {
          kicker: 'AVERAGES',
          title: 'Arithmetic for the next period, geometric for the realised past',
          body: 'The arithmetic mean is the unbiased estimate of a single future period’s return. The geometric mean is what the investor actually earned over the whole period, and it is always lower whenever returns vary at all.',
          formula: 'geometric = [Π(1 + Ri)]^(1/n) − 1',
          exam: 'The gap between the two widens with volatility. A large gap in a stem is a hint about the dispersion, not an error.',
        },
        {
          kicker: 'ANNUITIES',
          title: 'An annuity due is an ordinary annuity times (1 + r)',
          body: 'Ordinary annuities pay at period end, annuities due at the start. Converting between them is one multiplication. Perpetuities are the limit as n grows, and a growing perpetuity divides by (r − g).',
          formula: 'PV_due = PV_ordinary × (1 + r);  PV_perpetuity = C/r',
          exam: 'Draw the timeline. Almost every time-value error is an off-by-one in when the first payment lands.',
        },
      ],
      questions: [
        {
          text: 'A bank quotes 6.0% compounded quarterly. The effective annual rate is closest to:',
          given: 'stated rate 6.0%, m = 4',
          opts: ['6.00%', '6.14%', '6.18%', '6.09%'],
          a: 1,
          why: '(1 + 0.06/4)^4 − 1 = 1.015^4 − 1 = 6.136%.',
          ref: 'Rates and Returns',
        },
        {
          text: 'Which of these offers the highest effective annual rate?',
          given: null,
          opts: [
            '6.10% compounded annually',
            '6.05% compounded semi-annually',
            '6.00% compounded continuously',
            '5.98% compounded monthly',
          ],
          a: 2,
          why: 'Converted to effective annual rates: 6.100%, 6.142%, 6.184% and 6.147%. The lowest stated rate wins, because continuous compounding is the limiting case — which is why each has to be converted rather than ranked by the quoted number.',
          ref: 'Rates and Returns',
        },
        {
          text: 'Annual returns are +30%, −20% and +15%. The geometric mean return is closest to:',
          given: 'returns +30%, −20%, +15%',
          opts: ['4.10%', '5.31%', '6.15%', '8.33%'],
          a: 2,
          why: '(1.30 × 0.80 × 1.15)^(1/3) − 1 = 1.196^(1/3) − 1 = 6.15%. The arithmetic mean is 8.33%, and it overstates what was actually earned whenever returns vary.',
          ref: 'Rates and Returns',
        },
        {
          text: 'An investor will receive 5,000 at the start of each year for 10 years, with the first payment today. At 7% the present value is closest to:',
          given: 'payment 5,000; n = 10; r = 7%; annuity due',
          opts: ['35,118', '37,576', '32,822', '50,000'],
          a: 1,
          why: 'Ordinary annuity PV = 5,000 × 7.0236 = 35,118. An annuity due multiplies by 1.07: 35,118 × 1.07 = 37,576.',
          ref: 'Time Value of Money in Finance',
        },
        {
          text: 'A perpetuity pays 400 a year starting one year from now and grows at 2%. At a required return of 7% its value is:',
          given: 'C₁ 400; g 2%; r 7%',
          opts: ['5,714', '8,000', '5,600', '20,000'],
          a: 1,
          why: 'V = C₁/(r − g) = 400/0.05 = 8,000.',
          ref: 'Time Value of Money in Finance',
        },
        {
          text: 'A holding period return of 21% is earned over 18 months. The equivalent effective annual return is closest to:',
          given: 'HPR 21% over 18 months',
          opts: ['14.0%', '13.6%', '21.0%', '31.5%'],
          a: 1,
          why: '(1.21)^(12/18) − 1 = (1.21)^(2/3) − 1 = 13.7%. Dividing 21% by 1.5 gives 14%, which is the distractor.',
          ref: 'Rates and Returns',
        },
      ],
    },
  ],

  'cfa-l1-econ': [
    {
      slug: 'market-structures',
      name: 'Firms & Market Structures',
      blurb: 'Where pricing power comes from, and how concentration is actually measured.',
      modules: ['The Firm and Market Structures'],
      cards: [
        {
          kicker: 'FOUR',
          title: 'The structures differ in one thing: the demand curve the firm faces',
          body: 'Perfect competition faces a horizontal demand curve and is a price taker. Monopolistic competition and oligopoly face downward-sloping curves through differentiation or few rivals. Monopoly faces the whole market curve.',
          formula: 'profit maximised where MR = MC',
          exam: 'Long-run economic profit is zero under perfect competition *and* monopolistic competition, because entry is free in both.',
        },
        {
          kicker: 'ELASTICITY',
          title: 'Marginal revenue and elasticity are the same fact twice',
          body: 'A firm with pricing power maximises profit only where demand is elastic: in the inelastic region raising price raises revenue and cuts cost at once, so it cannot be optimal. Marginal revenue is negative there.',
          formula: 'MR = P[1 + 1/E_d]',
          exam: 'If a stem puts the profit-maximising point in the inelastic region, something is wrong with the stem or with your reading of it.',
        },
        {
          kicker: 'CONCENTRATION',
          title: 'HHI is the measure that notices the shape, not just the count',
          body: 'The N-firm concentration ratio adds the top N shares and is blind to how they are distributed. The Herfindahl–Hirschman Index squares each share, so a market with one dominant firm scores far higher than an evenly split one with the same ratio.',
          formula: 'HHI = Σ (market share in %)²',
          exam: 'Neither measure captures entry barriers or the threat of imports, which is the standard criticism of both.',
        },
      ],
      questions: [
        {
          text: 'A market has four firms with shares of 40%, 25%, 20% and 15%. The Herfindahl–Hirschman Index is:',
          given: 'shares 40%, 25%, 20%, 15%',
          opts: ['2,850', '3,050', '1,000', '2,250'],
          a: 0,
          why: '40² + 25² + 20² + 15² = 1,600 + 625 + 400 + 225 = 2,850.',
          ref: 'The Firm and Market Structures',
        },
        {
          text: 'In long-run equilibrium, a firm in monopolistic competition earns:',
          given: null,
          opts: [
            'Positive economic profit, because its product is differentiated',
            'Zero economic profit, because entry continues until profit is competed away',
            'Negative economic profit',
            'Profit equal to that of a monopolist',
          ],
          a: 1,
          why: 'Differentiation gives short-run pricing power, but free entry erodes it. The firm ends at zero economic profit producing below minimum average cost.',
          ref: 'The Firm and Market Structures',
        },
        {
          text: 'A profit-maximising firm with pricing power will always operate where demand is:',
          given: null,
          opts: ['Inelastic', 'Elastic', 'Unit elastic', 'Perfectly inelastic'],
          a: 1,
          why: 'Marginal revenue is negative in the inelastic region, so marginal cost — which is positive — cannot equal it. The optimum is always in the elastic region.',
          ref: 'The Firm and Market Structures',
        },
        {
          text: 'Two markets both have a four-firm concentration ratio of 80%. Market A is split 65/5/5/5 and market B 20/20/20/20. Relative to the concentration ratio, the HHI will:',
          given: null,
          opts: [
            'Be identical for both, since the ratio is the same',
            'Be far higher for A, because squaring shares penalises dominance',
            'Be higher for B',
            'Be undefined without the remaining firms',
          ],
          a: 1,
          why: 'A scores 4,300 from the top four against B’s 1,600. Squaring is precisely what makes the index notice a dominant firm the ratio hides.',
          ref: 'The Firm and Market Structures',
        },
        {
          text: 'Under the Cournot model of oligopoly, firms compete by choosing:',
          given: null,
          opts: [
            'Price',
            'Quantity, taking rivals’ quantities as given',
            'Advertising spend',
            'Product quality',
          ],
          a: 1,
          why: 'Cournot is quantity competition; Bertrand is price competition, which drives price to marginal cost with homogeneous goods.',
          ref: 'The Firm and Market Structures',
        },
        {
          text: 'A perfectly competitive firm faces a market price of 24 and has marginal cost of 24 at an output of 900 units, with average total cost of 26 at that output. In the short run it should:',
          given: 'P 24; MC 24 at Q 900; ATC 26; AVC below 24',
          opts: [
            'Shut down immediately',
            'Continue producing 900 units, since price covers variable cost and part of fixed cost',
            'Raise price to 26',
            'Increase output until ATC equals price',
          ],
          a: 1,
          why: 'A price above average variable cost but below average total cost means losses, but shutting down would forgo the contribution to fixed costs. Production continues in the short run.',
          ref: 'The Firm and Market Structures',
        },
      ],
    },
  ],

  'cfa-l1-fsa': [
    {
      slug: 'statements-and-modelling',
      name: 'The Statements & Forecasting',
      blurb: 'Revenue recognition, the balance sheet, and building a forecast that holds together.',
      modules: [
        'Introduction to Financial Statement Analysis',
        'Analyzing Income Statements',
        'Analyzing Balance Sheets',
        'Topics in Long-Term Liabilities and Equity',
        'Introduction to Financial Statement Modeling',
      ],
      cards: [
        {
          kicker: 'REVENUE',
          title: 'Five steps, and step four is where judgement enters',
          body: 'Identify the contract, identify the performance obligations, determine the transaction price, allocate it to the obligations, recognise revenue as each is satisfied. Allocation across bundled obligations is where two firms with identical contracts report differently.',
          formula: null,
          exam: 'Principal versus agent decides gross versus net revenue, and it turns on who controls the good before transfer.',
        },
        {
          kicker: 'DILUTION',
          title: 'Diluted EPS uses the treasury stock method for options',
          body: 'Assume options are exercised and the proceeds buy back shares at the average market price. The incremental shares are the difference. Convertible debt instead adds back after-tax interest to the numerator and the conversion shares to the denominator.',
          formula: 'incremental shares = n × (P_market − P_exercise) / P_market',
          exam: 'An antidilutive security is excluded. Test each one separately — a convertible can be dilutive while an option is not.',
        },
        {
          kicker: 'FORECAST',
          title: 'A model is a set of drivers, not a set of growth rates',
          body: 'Forecast revenue from volume and price, costs from their own drivers, and let the balance sheet follow through working capital ratios and a capital expenditure schedule. Growth rates applied line by line produce a model that cannot be argued with because it says nothing.',
          formula: null,
          exam: 'The plug that balances the model — usually debt or cash — is where an unexamined assumption hides.',
        },
      ],
      questions: [
        {
          text: 'A software firm sells a licence with three years of support for a single upfront fee. Under the revenue standard it should most appropriately:',
          given: null,
          opts: [
            'Recognise the whole fee on delivery of the licence',
            'Allocate the transaction price across the licence and the support, recognising each as it is satisfied',
            'Recognise the whole fee evenly over three years',
            'Defer all revenue until the support period ends',
          ],
          a: 1,
          why: 'Two distinct performance obligations means the price is allocated between them and each is recognised on its own pattern of satisfaction.',
          ref: 'Analyzing Income Statements',
        },
        {
          text: 'A company has 10 million shares, options over 600,000 shares at an exercise price of 20, and an average market price of 25. Incremental shares under the treasury stock method are:',
          given: 'options 600,000; exercise 20; average market price 25',
          opts: ['120,000', '480,000', '600,000', '150,000'],
          a: 0,
          why: 'Proceeds of 600,000 × 20 = 12,000,000 buy back 480,000 shares at 25. Incremental shares are 600,000 − 480,000 = 120,000.',
          ref: 'Analyzing Income Statements',
        },
        {
          text: 'A marketplace takes orders, never holds inventory, and cannot set the price. It should most appropriately report revenue:',
          given: null,
          opts: [
            'Gross, as the full transaction value',
            'Net, as its commission, because it acts as an agent',
            'Gross, with the supplier cost in operating expenses',
            'Only on cash receipt',
          ],
          a: 1,
          why: 'Control of the good before transfer is the test for principal status. Without it the firm is an agent and reports the commission.',
          ref: 'Analyzing Income Statements',
        },
        {
          text: 'Which item would appear in other comprehensive income rather than in net income under IFRS?',
          given: null,
          opts: [
            'A realised gain on the sale of equipment',
            'Remeasurement of a defined benefit pension obligation',
            'Interest expense on a bond',
            'An inventory write-down',
          ],
          a: 1,
          why: 'IFRS routes pension remeasurements through OCI without recycling. The other three run through profit or loss.',
          ref: 'Analyzing Balance Sheets',
        },
        {
          text: 'A firm issues a bond at a discount and uses the effective interest method. Over the bond’s life, reported interest expense will:',
          given: null,
          opts: [
            'Equal the coupon each period',
            'Exceed the coupon and rise each period as the carrying amount accretes',
            'Fall each period',
            'Be recognised entirely at issuance',
          ],
          a: 1,
          why: 'Expense is the carrying amount times the market yield at issue. With a discount the carrying amount rises toward par, so expense rises and always exceeds the coupon.',
          ref: 'Topics in Long-Term Liabilities and Equity',
        },
        {
          text: 'In a three-statement model, the item that balances the balance sheet after all operating assumptions are set is best described as:',
          given: null,
          opts: [
            'The revenue growth rate',
            'The financing plug — usually revolver debt or surplus cash',
            'The tax rate',
            'Depreciation',
          ],
          a: 1,
          why: 'Once operations and investment are forecast, financing absorbs the residual. That plug is where an unexamined funding assumption lives, which is why it is the first thing to interrogate.',
          ref: 'Introduction to Financial Statement Modeling',
        },
      ],
    },
  ],

  'cfa-l1-corp': [
    {
      slug: 'governance-and-stakeholders',
      name: 'Governance & Stakeholders',
      blurb: 'Ownership forms, the conflicts they create, and the mechanisms that contain them.',
      modules: [
        'Organizational Forms, Corporate Issuer Features, and Ownership',
        'Investors and Other Stakeholders',
        'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
      ],
      cards: [
        {
          kicker: 'CONFLICTS',
          title: 'Two conflicts, and the second is the one that concentrates ownership',
          body: 'The principal–agent conflict is managers against shareholders. The controlling–minority conflict is a dominant shareholder against everyone else, and it is the dominant governance problem wherever ownership is concentrated or dual-class shares exist.',
          formula: null,
          exam: 'Dual-class structures separate cash flow rights from control rights, which is exactly what enables the second conflict.',
        },
        {
          kicker: 'MECHANISMS',
          title: 'Internal and external, and neither alone is sufficient',
          body: 'Internal: an independent board, audit and remuneration committees, shareholder voting rights. External: the market for corporate control, auditors, regulators, creditors and the analyst community. Weak internal governance is survivable only where external discipline is strong.',
          formula: null,
          exam: 'Staggered boards and poison pills weaken the market for corporate control. Name the mechanism the stem is disabling.',
        },
        {
          kicker: 'STAKEHOLDERS',
          title: 'Creditors and shareholders disagree about risk, by construction',
          body: 'Shareholders hold a residual claim that behaves like a call option, so volatility can benefit them. Creditors hold a capped claim and prefer safety. Covenants exist to stop shareholders transferring value by raising risk after the debt is issued.',
          formula: null,
          exam: 'Asset substitution — swapping safe projects for risky ones after borrowing — is the specific behaviour covenants target.',
        },
      ],
      questions: [
        {
          text: 'A founder holds 12% of the cash flow rights but 58% of the votes through a dual-class structure. The dominant governance concern is:',
          given: null,
          opts: [
            'The principal–agent conflict between managers and shareholders',
            'The conflict between the controlling shareholder and minority shareholders',
            'A conflict between shareholders and creditors',
            'Regulatory capture',
          ],
          a: 1,
          why: 'Separating control from economic exposure lets a controlling holder make decisions whose costs fall mostly on others. That is the controlling–minority conflict.',
          ref: 'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
        },
        {
          text: 'A board adopts a staggered structure in which one third of directors stand for election each year. This most directly:',
          given: null,
          opts: [
            'Strengthens the market for corporate control',
            'Weakens it, by making a change of control take at least two annual meetings',
            'Improves audit independence',
            'Increases minority shareholder voting power',
          ],
          a: 1,
          why: 'A classified board cannot be replaced in a single cycle, which blunts the takeover threat that external governance relies on.',
          ref: 'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
        },
        {
          text: 'After issuing long-dated unsecured debt, a firm sells its stable utility division and invests the proceeds in an early-stage venture. Creditors object. The behaviour is best described as:',
          given: null,
          opts: [
            'Dividend recapitalisation',
            'Asset substitution',
            'Debt overhang',
            'A poison pill',
          ],
          a: 1,
          why: 'Raising asset risk after borrowing transfers value from the capped creditor claim to the option-like equity claim. Covenants exist to prevent it.',
          ref: 'Investors and Other Stakeholders',
        },
        {
          text: 'Cumulative voting, compared with statutory voting, most directly benefits:',
          given: null,
          opts: [
            'The controlling shareholder',
            'Minority shareholders, by allowing votes to be concentrated on a single candidate',
            'Management',
            'Creditors',
          ],
          a: 1,
          why: 'Cumulative voting lets a minority holder pool all of its votes behind one director, which can secure board representation that statutory voting would deny.',
          ref: 'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
        },
        {
          text: 'The principal advantage of a limited company over a general partnership, from an investor’s point of view, is:',
          given: null,
          opts: [
            'Lower tax on distributed profits',
            'Limited liability and transferable ownership interests',
            'Fewer disclosure obligations',
            'Guaranteed dividends',
          ],
          a: 1,
          why: 'Liability capped at the amount invested, plus the ability to transfer the interest, is what makes outside equity financing possible at scale.',
          ref: 'Organizational Forms, Corporate Issuer Features, and Ownership',
        },
        {
          text: 'Which is best classified as an *external* corporate governance mechanism?',
          given: null,
          opts: [
            'An independent audit committee',
            'The threat of a hostile takeover',
            'A remuneration committee',
            'A board with a majority of independent directors',
          ],
          a: 1,
          why: 'The market for corporate control disciplines management from outside the firm. The other three are internal board structures.',
          ref: 'Corporate Governance: Conflicts, Mechanisms, Risks, and Benefits',
        },
      ],
    },
  ],

  'cfa-l1-equity': [
    {
      slug: 'industry-and-company-analysis',
      name: 'Industry & Company Analysis',
      blurb:
        'Competitive structure, forecasting a business, and reading a research report critically.',
      modules: [
        'Industry and Competitive Analysis',
        'Company Analysis: Past, Present, and Future',
        'Financial Statement Forecasting in Equity Valuation',
        'Equity Analyst Research Reports',
        'The CAPM, Market Model, and Other Factor-Based Equity Models',
      ],
      cards: [
        {
          kicker: 'STRUCTURE',
          title: 'Five forces, and industry structure explains more than management does',
          body: 'Rivalry, new entrants, substitutes, supplier power and buyer power set the profit pool an industry can sustain. A well-run firm in a terrible structure loses to an average firm in a good one, which is why structure is analysed first.',
          formula: null,
          exam: 'Barriers to entry protect incumbents’ returns; barriers to *exit* worsen rivalry by keeping capacity in a declining industry.',
        },
        {
          kicker: 'LIFECYCLE',
          title: 'Where an industry sits changes which number matters',
          body: 'Embryonic and growth industries are judged on volume and market share; mature ones on margin and cash conversion; declining ones on capital return and consolidation. Applying a growth framework to a mature business is the standard analytical error.',
          formula: null,
          exam: 'Fragmentation plus overcapacity in a mature industry predicts price competition, whatever the demand outlook.',
        },
        {
          kicker: 'REPORTS',
          title: 'Read a research report for what it assumes, not what it concludes',
          body: 'A report must state its valuation approach, the key assumptions behind it and the risks to the thesis. A target price without a stated method, or a thesis with no identified way to be wrong, tells you nothing about the company and something about the analyst.',
          formula: null,
          exam: 'Standard V(B) requires fact and opinion to be distinguished, and the basic process to be described.',
        },
      ],
      questions: [
        {
          text: 'An industry has high fixed costs, undifferentiated products, slow demand growth and expensive-to-redeploy assets. Its profitability is most likely:',
          given: null,
          opts: [
            'High and stable, because assets are hard to replicate',
            'Low, because high exit barriers keep capacity in place and intensify price competition',
            'High, because fixed costs deter entry',
            'Unrelated to industry structure',
          ],
          a: 1,
          why: 'High exit barriers trap capacity in a slow-growing commodity industry, which sustains price competition well past the point at which capacity would otherwise leave.',
          ref: 'Industry and Competitive Analysis',
        },
        {
          text: 'Which is most likely to represent a durable barrier to entry?',
          given: null,
          opts: [
            'A large current advertising budget',
            'A regulated licence with a limited number of holders',
            'A temporary cost advantage from a favourable input contract',
            'A first-mover advantage in a market with low switching costs',
          ],
          a: 1,
          why: 'A regulatory limit on participants is not competed away. The other three erode as rivals spend, contracts expire or customers switch.',
          ref: 'Industry and Competitive Analysis',
        },
        {
          text: 'A firm has an equity beta of 1.3, the risk-free rate is 3.5% and the equity risk premium is 4.5%. Under the CAPM its cost of equity is:',
          given: 'β 1.3; Rf 3.5%; ERP 4.5%',
          opts: ['8.0%', '9.35%', '5.85%', '10.4%'],
          a: 1,
          why: '3.5% + 1.3 × 4.5% = 3.5% + 5.85% = 9.35%.',
          ref: 'The CAPM, Market Model, and Other Factor-Based Equity Models',
        },
        {
          text: 'When forecasting the income statement for a retailer, the most defensible approach to revenue is to:',
          given: null,
          opts: [
            'Apply last year’s growth rate',
            'Build it from store count, sales per store and like-for-like growth',
            'Set it equal to the industry growth rate',
            'Derive it from the target price',
          ],
          a: 1,
          why: 'Driver-based forecasting exposes the assumptions to challenge. A single growth rate hides them, which is why it cannot be argued with or defended.',
          ref: 'Financial Statement Forecasting in Equity Valuation',
        },
        {
          text: 'A research report states a target price and a recommendation but does not describe the valuation method or the risks to the thesis. The most significant deficiency is that:',
          given: null,
          opts: [
            'The target price is probably wrong',
            'A reader cannot assess the basis for the conclusion or the ways it could fail',
            'The report is too short',
            'The recommendation is not quantified',
          ],
          a: 1,
          why: 'A report exists to let the reader evaluate the reasoning. Without a stated method and identified risks there is nothing to evaluate.',
          ref: 'Equity Analyst Research Reports',
        },
        {
          text: 'A mature industry is highly fragmented with persistent overcapacity. The most likely consequence for incumbents is:',
          given: null,
          opts: [
            'Pricing power and expanding margins',
            'Price competition and margin pressure until capacity leaves',
            'Rising barriers to entry',
            'Increasing product differentiation',
          ],
          a: 1,
          why: 'Many small players and more capacity than demand is the classic setup for price competition, and it persists until capacity exits or the industry consolidates.',
          ref: 'Industry and Competitive Analysis',
        },
      ],
    },
  ],

  'cfa-l1-fixed': [
    {
      slug: 'instruments-and-securitisation',
      name: 'Instruments & Securitisation',
      blurb: 'What a bond actually promises, and what happens when the promises are pooled.',
      modules: [
        'Fixed-Income Instrument Features',
        'Fixed-Income Cash Flows and Types',
        'Fixed-Income Bond Valuation: Prices and Yields',
        'Fixed-Income Securitization',
        'Asset-Backed Security (ABS) Instrument and Market Features',
        'Mortgage-Backed Security (MBS) Instrument and Market Features',
      ],
      cards: [
        {
          kicker: 'FEATURES',
          title: 'Indenture, seniority, security, covenants — in that order of consequence',
          body: 'The indenture is the contract. Seniority and security decide the recovery; covenants decide what the issuer may do before default. A high coupon on a deeply subordinated, covenant-light bond is compensation, not a bargain.',
          formula: null,
          exam: 'Affirmative covenants require action; negative covenants forbid it. Negative covenants are the ones that bind.',
        },
        {
          kicker: 'STRUCTURE',
          title: 'Securitisation moves risk by tranching, not by removing it',
          body: 'Assets go into a bankruptcy-remote special purpose entity that issues tranches with a defined loss order. Credit enhancement comes from subordination, overcollateralisation, excess spread and reserve accounts. The pool’s losses are unchanged; who bears them is not.',
          formula: null,
          exam: 'Bankruptcy remoteness is the whole point: the tranches must be insulated from the originator failing.',
        },
        {
          kicker: 'PREPAYMENT',
          title: 'An MBS investor is short an option the borrower did not pay for',
          body: 'Homeowners prepay when rates fall, returning capital exactly when it can only be reinvested at lower yields, and extend when rates rise. That is contraction and extension risk, and it is why an MBS shows negative convexity.',
          formula: null,
          exam: 'Sequential-pay tranches redistribute prepayment risk; a planned amortisation class buys stability from the support tranche.',
        },
      ],
      questions: [
        {
          text: 'A covenant preventing an issuer from pledging assets to new lenders ahead of existing ones is best described as:',
          given: null,
          opts: [
            'An affirmative covenant',
            'A negative pledge, which is a negative covenant',
            'A sinking fund provision',
            'A make-whole call',
          ],
          a: 1,
          why: 'A negative pledge forbids an action. Affirmative covenants require actions such as filing statements or maintaining insurance.',
          ref: 'Fixed-Income Instrument Features',
        },
        {
          text: 'The principal purpose of the special purpose entity in a securitisation is to:',
          given: null,
          opts: [
            'Reduce the credit risk of the underlying assets',
            'Isolate the assets from the originator’s bankruptcy',
            'Guarantee the senior tranche',
            'Avoid registration requirements',
          ],
          a: 1,
          why: 'Bankruptcy remoteness means tranche holders depend on the pool rather than on the originator surviving. Pool credit risk is unchanged by the structure.',
          ref: 'Fixed-Income Securitization',
        },
        {
          text: 'In a structure with senior, mezzanine and equity tranches, losses on the pool are absorbed:',
          given: null,
          opts: [
            'Pro rata across all three',
            'By the equity tranche first, then mezzanine, then senior',
            'By the senior tranche first, since it is largest',
            'Only after the servicer defaults',
          ],
          a: 1,
          why: 'Subordination defines the loss waterfall from the bottom up. That ordering is the credit enhancement the senior tranche is paying nothing extra for.',
          ref: 'Asset-Backed Security (ABS) Instrument and Market Features',
        },
        {
          text: 'Interest rates fall sharply. A holder of a pass-through mortgage-backed security most directly faces:',
          given: null,
          opts: [
            'Extension risk',
            'Contraction risk, as borrowers refinance and return principal early',
            'Higher credit risk',
            'A longer average life',
          ],
          a: 1,
          why: 'Falling rates trigger refinancing, shortening the average life and returning capital to be reinvested at the new lower rates.',
          ref: 'Mortgage-Backed Security (MBS) Instrument and Market Features',
        },
        {
          text: 'A planned amortisation class tranche achieves a more predictable schedule because:',
          given: null,
          opts: [
            'It is guaranteed by a government agency',
            'A support tranche absorbs prepayment variation within a defined band',
            'Its borrowers cannot prepay',
            'It pays a floating coupon',
          ],
          a: 1,
          why: 'The companion, or support, tranche takes the prepayment variability so the PAC keeps its schedule while prepayments stay inside the collar.',
          ref: 'Mortgage-Backed Security (MBS) Instrument and Market Features',
        },
        {
          text: 'A 4% annual-pay bond with three years remaining is priced to yield 5.2%. Its price per 100 of par is closest to:',
          given: 'coupon 4; n = 3; YTM 5.2%',
          opts: ['96.75', '100.00', '103.40', '98.60'],
          a: 0,
          why: '4/1.052 + 4/1.052² + 104/1.052³ = 3.802 + 3.615 + 89.33 = 96.75. A coupon below the yield means a discount.',
          ref: 'Fixed-Income Bond Valuation: Prices and Yields',
        },
      ],
    },
  ],

  'cfa-l1-deriv': [
    {
      slug: 'instruments-and-uses',
      name: 'Instruments & Their Uses',
      blurb: 'What each contract is, who uses it and why, and what it does to risk.',
      modules: [
        'Derivative Instrument and Derivative Market Features',
        'Forward Commitment and Contingent Claim Features and Instruments',
        'Derivative Benefits, Risks, and Issuer and Investor Uses',
      ],
      cards: [
        {
          kicker: 'TAXONOMY',
          title: 'Commitments oblige; contingent claims permit',
          body: 'Forwards, futures and swaps are forward commitments — both sides must perform. Options are contingent claims — the holder chooses, which is why only the holder pays a premium and why the payoff is asymmetric.',
          formula: null,
          exam: 'A payoff diagram with a kink is a contingent claim. A straight line through zero is a forward commitment.',
        },
        {
          kicker: 'USES',
          title: 'Derivatives change the shape of exposure, not the amount of risk in the world',
          body: 'They allow risk transfer, price discovery, lower transaction costs and access to exposures otherwise unavailable. The costs are counterparty risk, the leverage embedded in a small initial outlay, and a complexity that hides basis risk.',
          formula: null,
          exam: '"Derivatives create risk" is not the examined view. Mispricing, leverage and poor control create risk; the instrument transfers it.',
        },
        {
          kicker: 'MARKETS',
          title: 'Exchange-traded buys standardisation; OTC buys fit',
          body: 'Exchange contracts are standardised, cleared and margined, which removes bilateral counterparty risk at the cost of an imperfect hedge. OTC contracts match the exposure exactly and carry counterparty risk, now mitigated by mandatory clearing for many standardised swaps.',
          formula: null,
          exam: 'A hedge that cannot be matched exactly leaves basis risk. That is the price of standardisation, stated plainly.',
        },
      ],
      questions: [
        {
          text: 'Which instrument obliges both parties to perform at expiry?',
          given: null,
          opts: ['A purchased call', 'A forward contract', 'A written put', 'A purchased put'],
          a: 1,
          why: 'A forward is a forward commitment binding both sides. Options bind only the writer, and only if the holder exercises.',
          ref: 'Forward Commitment and Contingent Claim Features and Instruments',
        },
        {
          text: 'A wheat farmer sells wheat futures against an expected harvest. The position most directly:',
          given: null,
          opts: [
            'Eliminates all risk associated with the harvest',
            'Replaces price risk with basis and quantity risk',
            'Increases exposure to the wheat price',
            'Creates an obligation to buy wheat at expiry',
          ],
          a: 1,
          why: 'A short hedge fixes a price for a standardised contract, leaving the difference between the local cash price and the futures price, and the risk that the harvest differs from the hedged quantity.',
          ref: 'Derivative Benefits, Risks, and Issuer and Investor Uses',
        },
        {
          text: 'Relative to an exchange-traded contract, an over-the-counter derivative most directly offers:',
          given: null,
          opts: [
            'Lower counterparty risk',
            'Terms tailored to the exposure, at the cost of counterparty risk',
            'Daily settlement',
            'Greater price transparency',
          ],
          a: 1,
          why: 'Customisation is the reason OTC contracts exist. Standardisation, clearing and transparency are what an exchange provides instead.',
          ref: 'Derivative Instrument and Derivative Market Features',
        },
        {
          text: 'An investor pays 3.20 for a call struck at 45 and holds it to expiry with the underlying at 51. The profit per share is:',
          given: 'premium 3.20; strike 45; underlying at expiry 51',
          opts: ['2.80', '6.00', '3.20', '9.20'],
          a: 0,
          why: 'Exercise value is 51 − 45 = 6.00; profit is 6.00 − 3.20 = 2.80.',
          ref: 'Forward Commitment and Contingent Claim Features and Instruments',
        },
        {
          text: 'The leverage inherent in a futures position arises because:',
          given: null,
          opts: [
            'Futures always use borrowed money',
            'A small margin deposit controls a much larger notional exposure',
            'Futures have no expiry',
            'Exchanges guarantee profits',
          ],
          a: 1,
          why: 'Margin is a performance bond, not a purchase price, so a given cash outlay carries far more exposure than the equivalent cash position.',
          ref: 'Derivative Benefits, Risks, and Issuer and Investor Uses',
        },
        {
          text: 'Which is best described as a benefit derivatives markets provide to the wider economy?',
          given: null,
          opts: [
            'Guaranteed returns for hedgers',
            'Price discovery and lower-cost risk transfer',
            'Elimination of systemic risk',
            'Removal of counterparty risk',
          ],
          a: 1,
          why: 'Derivatives aggregate views into forward prices and let risk move to those willing to hold it, more cheaply than transacting in the underlying.',
          ref: 'Derivative Benefits, Risks, and Issuer and Investor Uses',
        },
      ],
    },
  ],

  'cfa-l1-alt': [
    {
      slug: 'structures-and-fees',
      name: 'Structures, Fees & Returns',
      blurb:
        'How alternative vehicles are put together, and what the fee schedule does to the return.',
      modules: [
        'Alternative Investment Features, Methods, and Structures',
        'Alternative Investment Performance and Returns',
      ],
      cards: [
        {
          kicker: 'ROUTES',
          title: 'Three ways in, with different control and different cost',
          body: 'A fund gives diversification and professional management at the price of fees and lock-ups. Co-investment gives exposure to a named deal at lower fees. Direct investment gives full control and requires the capability to exercise it.',
          formula: null,
          exam: 'Co-investment is the middle route the exam likes: lower fees than the fund, more concentration than the fund.',
        },
        {
          kicker: 'LOCK-UPS',
          title: 'Liquidity terms are part of the risk, not a footnote',
          body: 'Lock-up periods, notice periods, gates and side pockets exist because the underlying assets cannot be sold on demand. They protect remaining investors from forced sales — and they mean a stated redemption right may not be exercisable when it is most wanted.',
          formula: null,
          exam: 'A side pocket segregates an illiquid holding so that redeeming investors cannot take the liquid assets and leave it behind.',
        },
        {
          kicker: 'FEES',
          title: 'Compute the fee in the order the documents specify',
          body: 'Management fee on committed or invested capital; incentive fee on gains above a hurdle, subject to a high-water mark; and a fund-of-funds layers a second fee on top of the first. The order changes the answer materially.',
          formula: 'net = gross − mgmt fee − incentive rate × max(0, gain above hurdle)',
          exam: 'A soft hurdle pays carry on the whole gain once the hurdle is cleared; a hard hurdle pays only on the excess.',
        },
      ],
      questions: [
        {
          text: 'A fund charges 2% on beginning assets and 20% of gains above a 6% soft hurdle. Beginning assets are 200 and the gross return is 16%. The incentive fee is:',
          given: 'beginning 200; gross 16%; soft hurdle 6%; incentive 20%',
          opts: ['4.0', '6.4', '3.2', '2.0'],
          a: 1,
          why: 'A soft hurdle pays on the entire gain once cleared. Gain is 32; incentive is 20% × 32 = 6.4. A hard hurdle would pay 20% × (32 − 12) = 4.0, the first distractor.',
          ref: 'Alternative Investment Performance and Returns',
        },
        {
          text: 'A side pocket in a hedge fund is used to:',
          given: null,
          opts: [
            'Hold the manager’s own capital',
            'Segregate an illiquid holding so redeeming investors cannot leave it behind',
            'Defer the management fee',
            'Hold cash for margin calls',
          ],
          a: 1,
          why: 'Without a side pocket, redemptions are met from liquid assets and the illiquid residue concentrates on whoever stays. Segregating it shares the exposure fairly.',
          ref: 'Alternative Investment Features, Methods, and Structures',
        },
        {
          text: 'Relative to investing through the fund, a co-investment alongside the general partner typically offers:',
          given: null,
          opts: [
            'Greater diversification and higher fees',
            'Lower fees and greater concentration in a single deal',
            'Daily liquidity',
            'Priority over the fund in the waterfall',
          ],
          a: 1,
          why: 'Co-investments usually carry reduced or no fees and expose the investor to one asset rather than the portfolio.',
          ref: 'Alternative Investment Features, Methods, and Structures',
        },
        {
          text: 'A fund of funds charging 1% and 10% invests in underlying funds charging 2% and 20%. The principal implication for the investor is:',
          given: null,
          opts: [
            'Fees are netted against each other',
            'Two layers of fees apply, so a substantial gross return is needed to deliver an attractive net one',
            'The fund of funds fee replaces the underlying fees',
            'Incentive fees cannot be charged at both levels',
          ],
          a: 1,
          why: 'Both layers are charged. The diversification and manager selection have to be worth the second layer, which is the whole argument about the structure.',
          ref: 'Alternative Investment Performance and Returns',
        },
        {
          text: 'A lock-up period in a hedge fund exists primarily to:',
          given: null,
          opts: [
            'Guarantee the manager’s fee income',
            'Let the manager hold less liquid positions without facing forced sales',
            'Comply with securities registration rules',
            'Reduce the incentive fee',
          ],
          a: 1,
          why: 'Matching the redemption terms to the liquidity of the underlying positions is what stops redemptions forcing sales at distressed prices.',
          ref: 'Alternative Investment Features, Methods, and Structures',
        },
        {
          text: 'A fund’s net asset value falls 20% in year one and rises 25% in year two, returning to its starting value. Under a high-water mark, the incentive fee for year two is:',
          given: 'year 1 −20%; year 2 +25%; high-water mark in force',
          opts: [
            'Charged on the full 25% gain',
            'Zero, because the prior peak has only just been recovered',
            'Charged on half the gain',
            'Charged on the gain above the hurdle only',
          ],
          a: 1,
          why: 'The high-water mark requires the previous peak to be exceeded before new incentive fees accrue. Recovering to it exactly produces no fee.',
          ref: 'Alternative Investment Performance and Returns',
        },
      ],
    },
  ],

  'cfa-l1-pm': [
    {
      slug: 'process-and-execution',
      name: 'The Portfolio Process',
      blurb: 'Who the investors are, what the steps are, and where each one can go wrong.',
      modules: ['Portfolio Management: An Overview', 'Introduction to Risk Management'],
      cards: [
        {
          kicker: 'STEPS',
          title: 'Planning, execution, feedback — and feedback is the one that gets skipped',
          body: 'Planning produces the IPS and the strategic allocation. Execution is portfolio construction and trading. Feedback is monitoring, rebalancing and performance evaluation, and it is where a drifting portfolio is caught before it becomes a different portfolio.',
          formula: null,
          exam: 'Rebalancing belongs to feedback, not execution. The distinction is examined.',
        },
        {
          kicker: 'INVESTORS',
          title: 'Institutional types differ by horizon and liability, not by sophistication',
          body: 'Defined benefit plans have a liability; endowments and foundations have a spending rule and a perpetual horizon; insurers have regulation and duration matching; banks have a balance sheet. The type sets the constraint before any preference is expressed.',
          formula: null,
          exam: 'Individual investors differ from institutions chiefly in taxation and in a finite, uncertain horizon.',
        },
        {
          kicker: 'VEHICLES',
          title: 'The wrapper changes cost, liquidity and tax, not the exposure',
          body: 'Mutual funds, ETFs, separately managed accounts and pooled vehicles can hold identical assets and deliver materially different net outcomes through fees, trading costs, tax treatment and the ability to redeem.',
          formula: null,
          exam: 'An ETF’s in-kind creation and redemption is what makes it more tax-efficient than an equivalent open-ended fund in many jurisdictions.',
        },
      ],
      questions: [
        {
          text: 'Rebalancing a portfolio back to its strategic allocation belongs to which step of the portfolio management process?',
          given: null,
          opts: ['Planning', 'Execution', 'Feedback', 'It is not part of the process'],
          a: 2,
          why: 'Feedback covers monitoring, rebalancing and evaluation. Planning sets the target; execution builds to it; feedback keeps it there.',
          ref: 'Portfolio Management: An Overview',
        },
        {
          text: 'Which investor type is most directly characterised by a perpetual horizon and a spending rule?',
          given: null,
          opts: [
            'A life insurer',
            'An endowment',
            'A defined benefit pension plan',
            'A commercial bank',
          ],
          a: 1,
          why: 'Endowments exist in perpetuity and distribute under a spending policy, which supports high risk tolerance and modest liquidity needs.',
          ref: 'Portfolio Management: An Overview',
        },
        {
          text: 'An exchange-traded fund is often more tax-efficient than an equivalent open-ended mutual fund because:',
          given: null,
          opts: [
            'It pays no dividends',
            'In-kind creation and redemption avoids realising gains to meet redemptions',
            'It is not required to distribute income',
            'It has lower management fees',
          ],
          a: 1,
          why: 'Redemptions settled in securities rather than cash avoid the sales that would otherwise realise capital gains for remaining holders.',
          ref: 'Portfolio Management: An Overview',
        },
        {
          text: 'A firm identifies a risk, quantifies it, finds it outside tolerance, and buys insurance against it. This response is best described as:',
          given: null,
          opts: ['Risk avoidance', 'Risk transfer', 'Risk acceptance', 'Risk mitigation'],
          a: 1,
          why: 'Insurance moves the financial consequence to a third party. Avoidance would mean not taking the exposure; mitigation would mean reducing it; acceptance would mean retaining it.',
          ref: 'Introduction to Risk Management',
        },
        {
          text: 'Relative to an institutional investor, an individual investor’s investment policy is most distinctively shaped by:',
          given: null,
          opts: [
            'Regulatory capital requirements',
            'Taxation and a finite, uncertain time horizon',
            'A spending rule set by trustees',
            'Duration matching against policy liabilities',
          ],
          a: 1,
          why: 'Individuals are taxed on returns and have a lifespan. The other three constraints belong to specific institutional types.',
          ref: 'Portfolio Management: An Overview',
        },
        {
          text: 'A risk management framework’s first step, before any exposure is measured, is to:',
          given: null,
          opts: [
            'Purchase hedging instruments',
            'Establish risk governance and define risk tolerance',
            'Compute value at risk',
            'Set a rebalancing corridor',
          ],
          a: 1,
          why: 'Measurement without a stated tolerance produces numbers nobody can act on. Governance and tolerance come first by design.',
          ref: 'Introduction to Risk Management',
        },
      ],
    },
  ],
};
