import { PremiumSegmentBank } from '../types';

/**
 * CFA Level III — premium segments, including the three specialised pathways.
 *
 * Level III is examined in essays as well as item sets, so these items lean on
 * judgement — which strategy fits the mandate, which measure answers the question
 * asked — rather than on arithmetic alone. Where a number is needed the `given`
 * block carries it.
 */
export const CFA_L3_SEGMENTS: PremiumSegmentBank = {
  'cfa-l3-allocation': [
    {
      slug: 'capital-market-expectations',
      name: 'Capital Market Expectations',
      blurb: 'Forecasting returns without fooling yourself, and the biases that make it hard.',
      modules: [
        'Capital Market Expectations, Part 1: Framework and Macro Considerations',
        'Capital Market Expectations, Part 2: Forecasting Asset Class Returns',
      ],
      cards: [
        {
          kicker: 'BUILDING BLOCKS',
          title: 'Grinold–Kroner decomposes an equity return into things you can forecast',
          body: 'Expected equity return is the dividend yield, less the percentage change in shares outstanding, plus nominal earnings growth, plus the repricing term. Each piece is separately arguable, which is the point — a single number is not.',
          formula: 'E(R) ≈ D/P − ΔS + i + g + Δ(P/E)',
          exam: 'Net buybacks make −ΔS positive. A stem giving a buyback yield is handing you that term directly.',
        },
        {
          kicker: 'BIASES',
          title: 'Five ways a forecast goes wrong before the data does',
          body: 'Survivorship in the sample, appraisal smoothing understating risk, non-stationarity across regimes, data mining from repeated testing, and the analyst biases — anchoring, status quo, confirmation, overconfidence.',
          formula: null,
          exam: 'Smoothed private-asset returns understate both volatility and correlation. Unsmoothing is the correction the exam wants named.',
        },
        {
          kicker: 'ESTIMATION',
          title: 'A shrinkage estimator beats a sample covariance matrix',
          body: 'Sample covariances estimated from short histories are noisy and produce corner solutions in an optimiser. Shrinking toward a structured target — a factor model, or a constant-correlation matrix — trades a little bias for a large reduction in variance.',
          formula: null,
          exam: 'Mean-variance optimisation is famously input-sensitive. Any answer that improves the inputs beats one that constrains the output.',
        },
      ],
      questions: [
        {
          text: 'Dividend yield is 2.2%, net share repurchases are 0.8% of market capitalisation, expected nominal earnings growth is 4.5% and the price-earnings multiple is expected to contract by 0.5% a year. The Grinold–Kroner expected return is closest to:',
          given: 'D/P 2.2%; net buyback 0.8%; nominal earnings growth 4.5%; Δ(P/E) −0.5%',
          opts: ['6.0%', '7.0%', '7.5%', '5.4%'],
          a: 1,
          why: '2.2 + 0.8 + 4.5 − 0.5 = 7.0%. Net repurchases reduce shares outstanding, so −ΔS enters positively.',
          ref: 'Capital Market Expectations, Part 2',
        },
        {
          text: 'An analyst estimates the volatility of a private real estate index from quarterly appraisal-based returns. The estimate is most likely:',
          given: null,
          opts: [
            'Unbiased',
            'Understated, because smoothing induces positive serial correlation',
            'Overstated, because appraisals lag',
            'Understated only if leverage is ignored',
          ],
          a: 1,
          why: 'Appraisal smoothing dampens period-to-period variation and induces serial correlation, which understates both volatility and correlation with public markets.',
          ref: 'Capital Market Expectations, Part 1',
        },
        {
          text: 'An analyst tests forty variables against historical equity returns and reports the three that are significant at the 5% level. The most likely problem is:',
          given: null,
          opts: ['Survivorship bias', 'Data mining', 'Non-stationarity', 'Anchoring'],
          a: 1,
          why: 'At a 5% threshold, two significant results are expected from forty tests by chance alone. Reporting the winners from a large search is data mining.',
          ref: 'Capital Market Expectations, Part 1',
        },
        {
          text: 'Using a single sample period spanning both a managed-exchange-rate regime and a floating one to estimate currency volatility most directly risks:',
          given: null,
          opts: [
            'Survivorship bias',
            'Non-stationarity in the data series',
            'Appraisal smoothing',
            'Confirmation bias',
          ],
          a: 1,
          why: 'A regime change means the data-generating process is not constant, so a single estimate describes neither regime.',
          ref: 'Capital Market Expectations, Part 1',
        },
        {
          text: 'A central bank tightening into a slowing economy is most consistent with expectations of:',
          given: null,
          opts: [
            'A steepening yield curve and widening credit spreads',
            'A flattening or inverting yield curve and widening credit spreads',
            'A flattening curve and narrowing credit spreads',
            'A steepening curve and narrowing credit spreads',
          ],
          a: 1,
          why: 'Short rates rise with policy while long rates reflect weaker growth, flattening or inverting the curve; slowing growth widens credit spreads.',
          ref: 'Capital Market Expectations, Part 1',
        },
        {
          text: 'Shrinkage estimation applied to a covariance matrix most directly addresses:',
          given: null,
          opts: [
            'Non-normality of returns',
            'Estimation error in a noisy sample matrix, which an optimiser would otherwise magnify',
            'Serial correlation in appraisal-based returns',
            'Survivorship bias in the index constituents',
          ],
          a: 1,
          why: 'Shrinking the sample matrix toward a structured target reduces estimation error, which is what mean-variance optimisers amplify into corner solutions.',
          ref: 'Capital Market Expectations, Part 2',
        },
      ],
    },
    {
      slug: 'allocation-with-constraints',
      name: 'Allocation with Real Constraints',
      blurb:
        'Liability-relative and goals-based approaches, rebalancing, and what taxes do to all of it.',
      modules: [
        'Overview of Asset Allocation',
        'Principles of Asset Allocation',
        'Asset Allocation with Real-World Constraints',
      ],
      cards: [
        {
          kicker: 'FRAME',
          title: 'Three frames, and the mandate chooses between them',
          body: 'Asset-only optimises the portfolio in isolation. Liability-relative optimises surplus against a liability stream. Goals-based builds sub-portfolios matched to separate objectives with their own horizons and required success probabilities.',
          formula: null,
          exam: 'A defined benefit plan is liability-relative. A wealthy family with named goals is goals-based. Read the objective, not the asset list.',
        },
        {
          kicker: 'REBALANCING',
          title: 'The corridor widens with transaction costs and narrows with risk',
          body: 'An optimal corridor is wider for illiquid or expensive-to-trade assets, wider where correlation with the rest of the portfolio is high, and narrower where the asset is volatile relative to the portfolio. Higher risk tolerance also widens it.',
          formula: null,
          exam: 'Rebalancing is a short-volatility strategy: it sells what has risen. It underperforms in a trend and earns in a range.',
        },
        {
          kicker: 'TAX',
          title: 'Tax changes both the expected return and the risk borne',
          body: 'A taxable investor bears only (1 − t) of the return and, where losses are deductible, only (1 − t) of the risk. Asset location — placing heavily taxed assets in sheltered accounts — is usually worth more than any allocation tweak.',
          formula: 'after-tax return ≈ r(1 − t);  after-tax σ ≈ σ(1 − t)',
          exam: 'A tax-exempt and a taxable investor with the same risk tolerance hold different pre-tax allocations. That is the point of the adjustment.',
        },
      ],
      questions: [
        {
          text: 'A corporate defined benefit plan is 96% funded with a closed, ageing membership. The most appropriate allocation frame is:',
          given: null,
          opts: [
            'Asset-only mean-variance',
            'Liability-relative',
            'Goals-based',
            'Equal risk contribution',
          ],
          a: 1,
          why: 'The objective is surplus stability against a defined liability stream, which is precisely what liability-relative allocation optimises.',
          ref: 'Principles of Asset Allocation',
        },
        {
          text: 'Which characteristic most justifies a *wider* rebalancing corridor for an asset class?',
          given: null,
          opts: [
            'High volatility relative to the portfolio',
            'High transaction costs',
            'Low correlation with the rest of the portfolio',
            'A short investment horizon',
          ],
          a: 1,
          why: 'High trading costs make frequent rebalancing expensive, so the corridor widens. High volatility and low correlation both argue for a narrower one.',
          ref: 'Asset Allocation with Real-World Constraints',
        },
        {
          text: 'An investor faces a 30% tax on returns with losses fully deductible. A pre-tax portfolio volatility of 14% corresponds to an after-tax volatility closest to:',
          given: 'pre-tax σ 14%; t = 30%, losses deductible',
          opts: ['14.0%', '9.8%', '4.2%', '20.0%'],
          a: 1,
          why: 'When the tax authority shares both gains and losses, it bears part of the risk: 14% × (1 − 0.30) = 9.8%.',
          ref: 'Asset Allocation with Real-World Constraints',
        },
        {
          text: 'A goals-based allocation assigns a higher required probability of success to a near-term essential goal than to a distant aspirational one. The near-term sub-portfolio should most appropriately hold:',
          given: null,
          opts: [
            'A higher equity weight, to maximise expected return',
            'A lower-risk, shorter-duration mix',
            'The same allocation as the aspirational goal',
            'The largest share of illiquid alternatives',
          ],
          a: 1,
          why: 'A high required success probability over a short horizon leaves little room for shortfall, which forces a conservative sub-portfolio.',
          ref: 'Principles of Asset Allocation',
        },
        {
          text: 'A calendar rebalancing policy compared with a percentage-of-portfolio corridor policy is most likely to:',
          given: null,
          opts: [
            'Control risk more tightly between review dates',
            'Be simpler to administer but allow larger drift between dates',
            'Produce lower turnover in all market conditions',
            'Eliminate the need to specify a strategic allocation',
          ],
          a: 1,
          why: 'Calendar rebalancing is simple and predictable, but the allocation is unmonitored between dates, so drift can be large.',
          ref: 'Asset Allocation with Real-World Constraints',
        },
        {
          text: 'Asset location, as distinct from asset allocation, is the decision about:',
          given: null,
          opts: [
            'Which countries to invest in',
            'Which account type holds each asset class, given differing tax treatment',
            'Which custodian holds the assets',
            'Whether to use pooled or segregated vehicles',
          ],
          a: 1,
          why: 'Asset location places heavily taxed assets in tax-sheltered accounts and tax-efficient ones in taxable accounts, without changing the overall allocation.',
          ref: 'Asset Allocation with Real-World Constraints',
        },
      ],
    },
  ],

  'cfa-l3-construction': [
    {
      slug: 'equity-and-fixed-income-portfolios',
      name: 'Equity & Fixed-Income Portfolios',
      blurb: 'Building blocks, benchmark risk, and matching a bond portfolio to a liability.',
      modules: [
        'Overview of Equity Portfolio Management',
        'Overview of Fixed-Income Portfolio Management',
      ],
      cards: [
        {
          kicker: 'EQUITY',
          title: 'Three building blocks explain every active equity portfolio',
          body: 'Rewarded factor exposures, alpha skills, and position sizing. The first is cheap and replicable, the second is scarce, and the third is where concentration and constraints decide how much of either reaches the portfolio.',
          formula: null,
          exam: 'Active share measures how different the holdings are; active risk measures how differently they behave. A high active share with low active risk is many small factor-neutral bets.',
        },
        {
          kicker: 'LIABILITIES',
          title: 'Immunisation needs duration, dispersion and convexity handled together',
          body: 'Matching money duration is necessary but not sufficient: to immunise a single liability the portfolio needs minimum convexity dispersion, and for multiple liabilities the asset cash flows must bracket each liability date.',
          formula: 'money duration = D_mod × market value',
          exam: 'A barbell immunises a single liability worse than a bullet — higher convexity means higher structural risk against non-parallel shifts.',
        },
        {
          kicker: 'COSTS',
          title: 'A bond portfolio is priced by liquidity before it is priced by credit',
          body: 'Fixed-income trading is dealer-intermediated and thin outside the on-the-run issues. Turnover budgets, laddered maturities and the choice between cash bonds and derivatives are all liquidity decisions first.',
          formula: null,
          exam: 'Where a stem asks how to take credit exposure quickly and cheaply, the answer is usually a CDS index rather than cash bonds.',
        },
      ],
      questions: [
        {
          text: 'A portfolio holds 120 stocks against a 500-stock benchmark, with sector weights matched to the benchmark and an active risk of 1.8%. This is best described as:',
          given: null,
          opts: [
            'High active share, high active risk',
            'High active share, low active risk — many small, factor-neutral stock bets',
            'Low active share, high active risk',
            'Closet indexing',
          ],
          a: 1,
          why: 'Holding a quarter of the names creates a large active share, while matching sector weights suppresses systematic deviation and keeps active risk low.',
          ref: 'Overview of Equity Portfolio Management',
        },
        {
          text: 'To immunise a single future liability, a portfolio should most appropriately have:',
          given: null,
          opts: [
            'Money duration matching the liability and the maximum available convexity',
            'Money duration matching the liability and the minimum convexity consistent with that match',
            'Market value equal to the liability, regardless of duration',
            'A barbell structure spanning the liability date',
          ],
          a: 1,
          why: 'Higher convexity means greater cash-flow dispersion, which raises exposure to non-parallel shifts. The immunising portfolio minimises convexity subject to the duration match.',
          ref: 'Overview of Fixed-Income Portfolio Management',
        },
        {
          text: 'A manager wants rapid, low-cost exposure to investment grade credit spreads for a tactical view lasting weeks. The most appropriate instrument is:',
          given: null,
          opts: [
            'A diversified portfolio of cash corporate bonds',
            'A credit default swap index',
            'A single-name CDS on the largest index constituent',
            'A portfolio of government bonds',
          ],
          a: 1,
          why: 'CDS indices are liquid, standardised and cheap to enter and exit, which suits a short-horizon, broad credit view far better than assembling cash bonds.',
          ref: 'Overview of Fixed-Income Portfolio Management',
        },
        {
          text: 'A pension plan must meet five annual liabilities. Cash flow matching, relative to duration matching, most directly reduces:',
          given: null,
          opts: [
            'Credit risk',
            'Reinvestment and rebalancing risk, because each liability is met by a maturing cash flow',
            'Liquidity risk in the underlying bonds',
            'The cost of the portfolio',
          ],
          a: 1,
          why: 'Cash flow matching retires each liability with a dedicated maturing bond, removing the need to rebalance and the reliance on reinvestment assumptions.',
          ref: 'Overview of Fixed-Income Portfolio Management',
        },
        {
          text: 'A fund with an active share of 0.12 and an active risk of 0.4% against its benchmark, charging an active management fee, is best described as:',
          given: null,
          opts: [
            'A concentrated stock picker',
            'A closet indexer',
            'A factor-tilted portfolio',
            'A market-neutral strategy',
          ],
          a: 1,
          why: 'Very low active share and active risk with an active fee is the definition of closet indexing: the client pays for a tracker.',
          ref: 'Overview of Equity Portfolio Management',
        },
        {
          text: 'A long-only equity manager is given a constraint against holding more than 2% in any single name. Relative to an unconstrained mandate, this most directly reduces:',
          given: null,
          opts: [
            'The information coefficient',
            'The transfer coefficient',
            'The benchmark return',
            'Breadth',
          ],
          a: 1,
          why: 'A position limit stops the strongest views being expressed at full size, which is exactly what the transfer coefficient measures.',
          ref: 'Overview of Equity Portfolio Management',
        },
      ],
    },
    {
      slug: 'institutions-and-trading',
      name: 'Institutions, Alternatives & Trading',
      blurb: 'What each institution is really solving for, and what execution actually costs.',
      modules: [
        'Asset Allocation to Alternative Investments',
        'An Overview of Private Wealth Management',
        'Portfolio Management for Institutional Investors',
        'Trading Costs and Electronic Markets',
        'Case Study in Portfolio Management: Institutional (SWF)',
      ],
      cards: [
        {
          kicker: 'MANDATES',
          title: 'Each institution has one binding constraint',
          body: 'A defined benefit plan is bound by its liabilities, an endowment by its spending rule and perpetual horizon, an insurer by regulation and duration matching, a sovereign wealth fund by its stated purpose — stabilisation, savings or development.',
          formula: null,
          exam: 'Endowments have high risk tolerance and low liquidity needs *because* the horizon is perpetual. A stabilisation fund has the opposite of both.',
        },
        {
          kicker: 'COSTS',
          title: 'Implementation shortfall counts what the decision cost, not what the ticket cost',
          body: 'The shortfall is the gap between the paper return of a decision executed instantly at the decision price and the actual return achieved — delay, market impact, commissions and the opportunity cost of what went unfilled.',
          formula: 'IS = delay + execution cost + fees + missed trade opportunity cost',
          exam: 'The unfilled portion is the piece candidates forget, and it is often the largest term in an urgent trade.',
        },
        {
          kicker: 'ALTERNATIVES',
          title: 'Liquidity is the constraint that sizes an alternatives programme',
          body: 'Commitments are drawn over years and distributions are unpredictable, so the programme has to be sized against cash needs and against the denominator effect — falling public markets raise the private allocation without a single transaction.',
          formula: null,
          exam: 'A stem describing an over-allocation to private assets after an equity drawdown is describing the denominator effect.',
        },
      ],
      questions: [
        {
          text: 'A university endowment with a perpetual horizon and a 4.5% spending rule is most appropriately characterised as having:',
          given: null,
          opts: [
            'Low risk tolerance and high liquidity needs',
            'High risk tolerance and relatively low liquidity needs',
            'High risk tolerance and high liquidity needs',
            'Low risk tolerance and low liquidity needs',
          ],
          a: 1,
          why: 'A perpetual horizon supports substantial risk, and the only regular outflow is the spending rule, so liquidity needs are modest and predictable.',
          ref: 'Portfolio Management for Institutional Investors',
        },
        {
          text: 'A decision to buy 100,000 shares is made at 40.00. 60,000 execute at an average of 40.25 with commissions of 0.02 per share; the remainder goes unfilled and the price closes at 41.00. The missed trade opportunity cost component is closest to:',
          given: 'decision price 40.00; 40,000 shares unfilled; closing price 41.00',
          opts: ['15,000', '40,000', '25,000', '0'],
          a: 1,
          why: 'The unfilled 40,000 shares forgo (41.00 − 40.00) = 1.00 each, so 40,000. Ignoring the unfilled portion is the standard omission.',
          ref: 'Trading Costs and Electronic Markets',
        },
        {
          text: 'Equity markets fall 30% while a plan’s private equity holdings are marked with a lag. The plan’s private allocation rises above its policy range. This is best described as:',
          given: null,
          opts: [
            'A rebalancing failure',
            'The denominator effect',
            'A vintage year effect',
            'A J-curve effect',
          ],
          a: 1,
          why: 'The private allocation rises because the total portfolio shrank, not because anything was bought. Selling private stakes into that market is exactly what makes it painful.',
          ref: 'Asset Allocation to Alternative Investments',
        },
        {
          text: 'A life insurer’s asset allocation is most directly constrained by:',
          given: null,
          opts: [
            'A perpetual horizon',
            'Regulatory capital requirements and the duration of its policy liabilities',
            'A spending rule set by trustees',
            'A stabilisation mandate',
          ],
          a: 1,
          why: 'Insurers match asset duration to policyholder liabilities under regulatory capital charges that penalise risk taking.',
          ref: 'Portfolio Management for Institutional Investors',
        },
        {
          text: 'A large order in an illiquid stock is best executed with which algorithmic approach, where the manager has low urgency?',
          given: null,
          opts: [
            'An aggressive liquidity-seeking algorithm',
            'A participation or VWAP algorithm spreading the order across the day',
            'A single market order at the open',
            'An implementation shortfall algorithm front-loaded to the first minutes',
          ],
          a: 1,
          why: 'Low urgency in a thin name means market impact dominates; spreading participation over time reduces it at the cost of higher timing risk.',
          ref: 'Trading Costs and Electronic Markets',
        },
        {
          text: 'A sovereign wealth fund established to smooth government revenue from a volatile commodity is best described as:',
          given: null,
          opts: [
            'A savings fund with a long horizon and high risk tolerance',
            'A stabilisation fund with a short horizon and low risk tolerance',
            'A development fund investing domestically',
            'A pension reserve fund',
          ],
          a: 1,
          why: 'Stabilisation funds exist to be drawn on when revenue falls, which means short effective horizons and a conservative allocation.',
          ref: 'Case Study in Portfolio Management: Institutional (SWF)',
        },
      ],
    },
  ],

  'cfa-l3-performance': [
    {
      slug: 'attribution',
      name: 'Attribution & Appraisal',
      blurb: 'Where the return came from, and whether it was worth the risk taken.',
      modules: ['Portfolio Performance Evaluation'],
      cards: [
        {
          kicker: 'DECOMPOSE',
          title: 'Brinson splits excess return into allocation, selection and interaction',
          body: 'Allocation is over- or under-weighting a sector that then outperformed the benchmark overall. Selection is picking better securities inside a sector. Interaction is the cross-term, and is usually assigned to selection when only two effects are reported.',
          formula: 'allocation = Σ(wp − wb)(Rb,i − Rb);  selection = Σ wb,i(Rp,i − Rb,i)',
          exam: 'Overweighting a sector that underperformed the benchmark is a negative allocation effect even if the stocks picked in it beat their peers.',
        },
        {
          kicker: 'APPRAISAL',
          title: 'Which ratio depends on what the portfolio is',
          body: 'Sharpe for a total portfolio, Treynor for a component of a diversified whole, the information ratio against a benchmark, and Sortino where the investor cares about downside deviation rather than total variability.',
          formula: 'Sortino = (Rp − target) / downside deviation',
          exam: 'Sortino is the answer when the stem names a minimum acceptable return or describes asymmetric loss aversion.',
        },
        {
          kicker: 'RETURNS',
          title: 'Time-weighted judges the manager, money-weighted judges the investor',
          body: 'Time-weighted return removes the effect of cash flows the manager does not control, which is why it is the required basis for composite reporting. Money-weighted return includes them, which is what the client actually experienced.',
          formula: null,
          exam: 'When the manager controls the timing of cash flows — a private equity fund drawing capital — money-weighted is the fair measure.',
        },
      ],
      questions: [
        {
          text: 'A manager overweights energy by 5 percentage points. Energy returned 3% against a total benchmark return of 8%. The allocation effect from energy is closest to:',
          given: 'overweight +5pp; sector benchmark return 3%; total benchmark return 8%',
          opts: ['+0.25%', '−0.25%', '+0.15%', '−0.40%'],
          a: 1,
          why: '(wp − wb)(Rb,i − Rb) = 0.05 × (3% − 8%) = −0.25%. Overweighting a laggard costs, whatever the stock picking did.',
          ref: 'Portfolio Performance Evaluation',
        },
        {
          text: 'An investor states a minimum acceptable return of 4% and is indifferent to upside variability. The most appropriate appraisal measure is:',
          given: null,
          opts: ['Sharpe ratio', 'Sortino ratio', 'Treynor ratio', 'Jensen’s alpha'],
          a: 1,
          why: 'Sortino measures excess return over a target per unit of downside deviation, which matches an investor who penalises only shortfall.',
          ref: 'Portfolio Performance Evaluation',
        },
        {
          text: 'A private equity fund controls the timing of its capital calls and distributions. Its performance is most fairly measured by:',
          given: null,
          opts: [
            'Time-weighted return',
            'Money-weighted return (internal rate of return)',
            'The arithmetic mean of annual returns',
            'Modified Dietz on a quarterly basis',
          ],
          a: 1,
          why: 'Where the manager controls cash flow timing, that timing is part of the skill being judged, so the money-weighted return is appropriate.',
          ref: 'Portfolio Performance Evaluation',
        },
        {
          text: 'A portfolio returns 9.5% with active risk of 3.2% against a benchmark returning 7.1%. Its information ratio is closest to:',
          given: 'Rp 9.5%; Rb 7.1%; active risk 3.2%',
          opts: ['0.55', '0.75', '2.40', '2.97'],
          a: 1,
          why: 'IR = (9.5 − 7.1)/3.2 = 2.4/3.2 = 0.75.',
          ref: 'Portfolio Performance Evaluation',
        },
        {
          text: 'The interaction effect in a Brinson attribution arises because:',
          given: null,
          opts: [
            'Sector weights do not sum to one',
            'Selection skill is applied to an over- or under-weighted sector, so the two effects compound',
            'The benchmark is rebalanced quarterly',
            'Currency returns are excluded',
          ],
          a: 1,
          why: 'Interaction is the product of the active weight and the selection return within the sector — the combined effect neither pure effect captures.',
          ref: 'Portfolio Performance Evaluation',
        },
        {
          text: 'A macro attribution analysis, unlike a micro attribution, is principally concerned with:',
          given: null,
          opts: [
            'Individual security selection within a sector',
            'Decisions made by the fund sponsor — policy allocation, manager selection and allocation between managers',
            'Currency hedging at the security level',
            'Trade execution quality',
          ],
          a: 1,
          why: 'Macro attribution evaluates the sponsor’s decisions; micro attribution evaluates an individual manager against their own benchmark.',
          ref: 'Portfolio Performance Evaluation',
        },
      ],
    },
    {
      slug: 'manager-selection-and-gips',
      name: 'Manager Selection & GIPS',
      blurb: 'Due diligence that survives a good track record, and what a compliance claim means.',
      modules: [
        'Investment Manager Selection',
        'Overview of the Global Investment Performance Standards (GIPS)',
      ],
      cards: [
        {
          kicker: 'PROCESS',
          title: 'Two components, and the second is the one that fails',
          body: 'Manager selection is investment due diligence — philosophy, process, people, portfolio — and operational due diligence: custody, valuation, reconciliation, compliance, business viability. Most catastrophic manager failures are operational, not investment.',
          formula: null,
          exam: 'A manager with excellent returns and self-administered valuation is an operational due diligence failure waiting to be written up.',
        },
        {
          kicker: 'ERRORS',
          title: 'Hiring a bad manager and rejecting a good one are not symmetric',
          body: 'A Type I error appoints a manager with no skill; a Type II error rejects one who has it. Type I is visible and costly; Type II is invisible and therefore systematically under-weighted in committee decisions.',
          formula: null,
          exam: 'Tightening selection criteria reduces Type I errors and increases Type II. There is no setting that reduces both.',
        },
        {
          kicker: 'GIPS',
          title: 'Compliance is firm-wide, and every discretionary portfolio is in a composite',
          body: 'A firm cannot claim compliance for one product. Every actual, fee-paying, discretionary portfolio must appear in at least one composite, composites are defined by strategy, and returns must be time-weighted. Verification is recommended, never required.',
          formula: null,
          exam: 'A firm claiming GIPS compliance "for its flagship strategy" is not compliant at all.',
        },
      ],
      questions: [
        {
          text: 'A manager produces strong risk-adjusted returns but values illiquid positions internally with no independent pricing. This most directly indicates a failure in:',
          given: null,
          opts: [
            'Investment due diligence',
            'Operational due diligence',
            'Performance attribution',
            'Benchmark selection',
          ],
          a: 1,
          why: 'Independent valuation is a core operational control. Its absence is an operational due diligence finding regardless of reported performance.',
          ref: 'Investment Manager Selection',
        },
        {
          text: 'A committee raises its minimum track-record requirement from three years to seven. The most likely effect is:',
          given: null,
          opts: [
            'Fewer Type I and fewer Type II errors',
            'Fewer Type I errors and more Type II errors',
            'More Type I errors and fewer Type II errors',
            'No change in either error rate',
          ],
          a: 1,
          why: 'A stricter filter appoints fewer unskilled managers and rejects more skilled ones. The trade-off cannot be avoided, only chosen.',
          ref: 'Investment Manager Selection',
        },
        {
          text: 'A firm states that it "complies with GIPS for its global equity composite". This claim is:',
          given: null,
          opts: [
            'Valid, provided the composite is verified',
            'Invalid — compliance is claimed on a firm-wide basis or not at all',
            'Valid if disclosed alongside the firm’s other composites',
            'Valid only for prospective clients',
          ],
          a: 1,
          why: 'GIPS compliance is firm-wide. Partial claims are prohibited precisely because they allow a firm to present its best strategy under the standard.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'Under GIPS, verification:',
          given: null,
          opts: [
            'Is required before a compliance claim can be made',
            'Is recommended, applies firm-wide, and does not certify any individual composite’s accuracy',
            'Certifies the returns of each composite individually',
            'Must be performed annually by the firm’s own compliance department',
          ],
          a: 1,
          why: 'Verification tests firm-wide policies and construction, is recommended rather than required, and cannot be claimed for a single composite.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'A manager’s five-year record was produced at a previous firm using a team that has since dispersed. In assessing the record, the most appropriate conclusion is that it:',
          given: null,
          opts: [
            'Transfers fully, because the manager is the same person',
            'Has limited predictive value, because the process and people that generated it no longer exist together',
            'Should be extrapolated with a haircut of one third',
            'Is irrelevant to the decision',
          ],
          a: 1,
          why: 'Track records attach to a process and a team as much as to an individual. Portability is the question, and here the answer is weak.',
          ref: 'Investment Manager Selection',
        },
        {
          text: 'Which is a required element of a GIPS composite definition?',
          given: null,
          opts: [
            'Grouping by client type',
            'Grouping by investment mandate, objective or strategy',
            'Grouping by account size only',
            'Grouping by portfolio manager',
          ],
          a: 1,
          why: 'Composites aggregate portfolios managed to a common strategy, so that a prospective client sees the record of the strategy being offered.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
      ],
    },
  ],

  'cfa-l3-derivatives': [
    {
      slug: 'options-strategies',
      name: 'Options Strategies',
      blurb: 'Spreads, collars and straddles — what each one is really a view on.',
      modules: ['Options Strategies'],
      cards: [
        {
          kicker: 'VIEWS',
          title: 'Every structure is a view on direction, volatility, or both',
          body: 'A bull call spread is directional with capped cost. A straddle is a pure volatility view with no direction. A collar sells upside to fund downside protection. Name the view before naming the structure.',
          formula: null,
          exam: 'A stem saying "expects a large move but is unsure of direction" is asking for a straddle or strangle, never a spread.',
        },
        {
          kicker: 'COLLAR',
          title: 'A zero-cost collar fixes a range and gives away the tail',
          body: 'Long the underlying, long a put, short a call struck so the premiums offset. Downside is floored at the put strike and upside is capped at the call strike. It is the standard answer for a concentrated holder who cannot sell.',
          formula:
            'max gain = call strike − S₀ − net premium;  max loss = S₀ − put strike + net premium',
          exam: 'Watch for a tax constraint in the stem: the reason the holding cannot simply be sold is usually an embedded gain.',
        },
        {
          kicker: 'BREAKEVEN',
          title: 'Compute breakevens before picking an answer',
          body: 'A long straddle breaks even at the strike plus and minus the total premium. A bull call spread breaks even at the lower strike plus the net debit. The distractors in these items are almost always the wrong breakeven.',
          formula: 'straddle breakevens = X ± (c + p)',
          exam: 'Maximum loss on a long straddle is the whole premium, and it occurs at exactly the strike.',
        },
      ],
      questions: [
        {
          text: 'An investor buys a call struck at 50 for 4.10 and sells a call struck at 60 for 1.30. The maximum gain and breakeven are closest to:',
          given: 'long 50 call at 4.10; short 60 call at 1.30',
          opts: [
            'Maximum gain 10.00, breakeven 50.00',
            'Maximum gain 7.20, breakeven 52.80',
            'Maximum gain 7.20, breakeven 57.20',
            'Maximum gain 2.80, breakeven 52.80',
          ],
          a: 1,
          why: 'Net debit is 2.80. Maximum gain = (60 − 50) − 2.80 = 7.20, at or above 60. Breakeven = 50 + 2.80 = 52.80.',
          ref: 'Options Strategies',
        },
        {
          text: 'A long straddle on a share at 80 uses a call at 4.60 and a put at 3.90, both struck at 80. The upper breakeven is:',
          given: 'S₀ 80; X 80; c 4.60; p 3.90',
          opts: ['84.60', '88.50', '80.00', '87.10'],
          a: 1,
          why: 'Total premium is 8.50, so the breakevens are 80 ± 8.50, giving 88.50 and 71.50.',
          ref: 'Options Strategies',
        },
        {
          text: 'An executive holds a large, heavily appreciated stake she cannot sell for two years for tax reasons, and wants to limit downside at minimal cost. The most appropriate structure is:',
          given: null,
          opts: [
            'A long straddle',
            'A zero-cost collar',
            'A short call alone',
            'A bear put spread funded by selling the stock',
          ],
          a: 1,
          why: 'A collar floors the downside and funds the put by selling upside, without disposing of the shares and triggering the gain.',
          ref: 'Options Strategies',
        },
        {
          text: 'A covered call writer’s position is best described as:',
          given: null,
          opts: [
            'Long volatility and long the underlying',
            'Short volatility, with upside capped at the strike plus the premium received',
            'Delta neutral',
            'Equivalent to a long put',
          ],
          a: 1,
          why: 'Writing the call sells volatility and caps the upside. The position is synthetically a short put.',
          ref: 'Options Strategies',
        },
        {
          text: 'An investor expects a share to stay within a narrow range until expiry. The structure most consistent with that view is:',
          given: null,
          opts: ['A long strangle', 'A short straddle', 'A bull call spread', 'A protective put'],
          a: 1,
          why: 'Selling both the call and the put earns both premiums if the share does not move, which is precisely a range-bound view. The risk is unbounded, which the stem does not exclude.',
          ref: 'Options Strategies',
        },
        {
          text: 'Maximum loss on a long straddle occurs when the underlying at expiry is:',
          given: null,
          opts: [
            'Far above the strike',
            'Exactly at the strike',
            'Far below the strike',
            'At either breakeven',
          ],
          a: 1,
          why: 'Both options expire worthless only at the strike, so the entire premium is lost there and nowhere else.',
          ref: 'Options Strategies',
        },
      ],
    },
    {
      slug: 'swaps-and-currency',
      name: 'Swaps, Futures & Currency Management',
      blurb: 'Changing exposure without trading the assets, and how far to hedge a currency.',
      modules: ['Swaps, Forwards, and Futures Strategies', 'Currency Management: An Introduction'],
      cards: [
        {
          kicker: 'OVERLAY',
          title: 'Futures change exposure without touching the portfolio',
          body: 'To move duration or equity beta, trade the overlay rather than the holdings: it is faster, far cheaper and leaves the underlying manager’s positions intact. The number of contracts follows from the gap between current and target exposure.',
          formula: 'N = [(D_target − D_current) × V_portfolio] / (D_futures × P_futures)',
          exam: 'Sign matters. A negative N is a short position, and the exam checks whether you noticed.',
        },
        {
          kicker: 'HEDGE RATIO',
          title: 'The hedging decision sits on a spectrum, not a switch',
          body: 'Full hedging minimises currency risk; no hedging maximises it; the answer between them depends on horizon, the correlation between the currency and the asset, hedging cost and the investor’s tolerance for regret.',
          formula: null,
          exam: 'Longer horizons and higher hedging costs push toward less hedging. A short horizon with an imminent liability pushes to fully hedged.',
        },
        {
          kicker: 'COST',
          title: 'A forward hedge costs the interest differential, plus the roll',
          body: 'Hedging a high-yield currency back into a low-yield base currency earns the differential; the reverse pays it. Rolling short-dated forwards repeatedly also pays a bid-offer spread each time, which compounds into a real drag.',
          formula: null,
          exam: 'A "cheap" hedge in one direction is an expensive one in the other. Identify which side of the differential the investor is on.',
        },
      ],
      questions: [
        {
          text: 'A 50 million bond portfolio has a duration of 4.2 and the manager wants 6.5. The cheapest-to-deliver futures contract has a duration of 8.1 and a price of 122,000. The number of contracts required is closest to:',
          given: 'V 50m; D_current 4.2; D_target 6.5; D_futures 8.1; futures price 122,000',
          opts: ['116 long', '116 short', '232 long', '58 long'],
          a: 0,
          why: 'N = (6.5 − 4.2) × 50,000,000 / (8.1 × 122,000) = 115,000,000 / 988,200 ≈ 116. Positive, so the manager buys contracts to add duration.',
          ref: 'Swaps, Forwards, and Futures Strategies',
        },
        {
          text: 'An investor with a twenty-year horizon holds foreign equities whose currency has historically been negatively correlated with the equity return. The most appropriate hedging conclusion is:',
          given: null,
          opts: [
            'Hedge fully, because currency risk is uncompensated',
            'Hedge lightly or not at all, because the currency is dampening portfolio volatility over a long horizon',
            'Hedge exactly half, as a neutral default',
            'Hedge dynamically on a monthly signal',
          ],
          a: 1,
          why: 'A negative correlation means the currency is already offsetting asset moves. Over a long horizon with hedging costs, leaving it unhedged is defensible.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'A manager wants to convert a floating-rate liability into a fixed-rate one. The appropriate position is:',
          given: null,
          opts: [
            'Receive fixed, pay floating',
            'Pay fixed, receive floating',
            'Buy an interest rate cap',
            'Sell a swaption',
          ],
          a: 1,
          why: 'Paying fixed and receiving floating offsets the floating payments on the liability, leaving a net fixed cost.',
          ref: 'Swaps, Forwards, and Futures Strategies',
        },
        {
          text: 'Hedging an exposure to a currency whose interest rate is *below* the investor’s domestic rate, using rolling forward contracts, will most likely:',
          given: null,
          opts: [
            'Earn a positive roll yield for the hedger',
            'Cost a negative roll yield for the hedger',
            'Be costless',
            'Depend only on realised spot moves',
          ],
          a: 0,
          why: 'Selling forward a low-yield currency against a higher-yield domestic currency means selling it at a forward premium, which is a positive carry for the hedger.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'An equitisation overlay that converts a cash balance into equity exposure without buying shares most directly uses:',
          given: null,
          opts: [
            'A long equity index futures position against the cash',
            'A short equity index futures position',
            'A written call on the index',
            'A total return swap paying the equity return',
          ],
          a: 0,
          why: 'Buying index futures against a cash balance replicates the index return on that cash — the standard cash equitisation trade.',
          ref: 'Swaps, Forwards, and Futures Strategies',
        },
        {
          text: 'A minimum-variance hedge ratio for a currency exposure differs from a 100% hedge because it:',
          given: null,
          opts: [
            'Ignores the correlation between the asset return and the currency return',
            'Accounts for that correlation, and can therefore be above or below 100%',
            'Always equals 50%',
            'Applies only to fixed-income portfolios',
          ],
          a: 1,
          why: 'The minimum-variance ratio is the regression slope of the domestic-currency asset return on the currency return, which need not be one.',
          ref: 'Currency Management: An Introduction',
        },
      ],
    },
  ],

  'cfa-l3-ethics': [
    {
      slug: 'asset-manager-code',
      name: 'The Asset Manager Code',
      blurb: 'The six general principles, and the firm-level obligations behind them.',
      modules: ['Asset Manager Code of Professional Conduct'],
      cards: [
        {
          kicker: 'SCOPE',
          title: 'The Code binds firms, where the Standards bind individuals',
          body: 'The Asset Manager Code applies to a firm as a whole and cannot be adopted in part. A firm claiming compliance adopts the entire Code; there is no partial adoption and no modification of the wording.',
          formula: null,
          exam: 'This mirrors GIPS: firm-wide or not at all. A claim scoped to one desk is not a claim.',
        },
        {
          kicker: 'PRINCIPLES',
          title: 'Six general principles of conduct',
          body: 'Act in a professional and ethical manner at all times; act for the benefit of clients; act with independence and objectivity; act with skill, competence and diligence; communicate accurately and in a timely way; uphold the rules governing capital markets.',
          formula: null,
          exam: 'The six principles are followed by six sections of specific provisions — loyalty to clients, investment process, trading, risk management and compliance, performance and valuation, and disclosures.',
        },
        {
          kicker: 'DISCLOSURE',
          title: 'What must be disclosed is broader than what must be asked about',
          body: 'Conflicts, regulatory or disciplinary action, the investment process, fees including any performance fee arrangement, valuation methods for illiquid holdings, and any material change to any of it — disclosed on the firm’s initiative, not on request.',
          formula: null,
          exam: '"The client did not ask" is never a defence in this topic.',
        },
      ],
      questions: [
        {
          text: 'A firm adopts all of the Asset Manager Code except the section on performance and valuation, which it says conflicts with local practice. The firm may:',
          given: null,
          opts: [
            'Claim compliance with the remainder, disclosing the exception',
            'Not claim compliance at all, because the Code is adopted in full or not claimed',
            'Claim compliance if a third party verifies the other sections',
            'Claim compliance for its non-local clients',
          ],
          a: 1,
          why: 'The Code is adopted in its entirety. Partial adoption with disclosure is not a permitted form of the claim.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
        {
          text: 'Under the Code, a firm valuing illiquid holdings must most appropriately:',
          given: null,
          opts: [
            'Use the portfolio manager’s own estimate, disclosed annually',
            'Use an independent third-party valuation where practicable and disclose the method used',
            'Carry them at cost until realised',
            'Exclude them from reported performance',
          ],
          a: 1,
          why: 'The Code requires fair, independent valuation where practicable and disclosure of the methods, precisely because manager-marked illiquids are the classic conflict.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
        {
          text: 'Which is a general principle of conduct under the Asset Manager Code?',
          given: null,
          opts: [
            'Maximise assets under management',
            'Act with independence and objectivity',
            'Achieve benchmark-relative outperformance',
            'Maintain GIPS compliance',
          ],
          a: 1,
          why: 'Independence and objectivity is one of the six general principles. Performance outcomes and GIPS are not principles of the Code.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
        {
          text: 'A firm receives a regulatory censure unrelated to the strategies its clients hold. Under the Code it must:',
          given: null,
          opts: [
            'Disclose it to clients, because regulatory and disciplinary actions are disclosable',
            'Disclose only if a client asks',
            'Disclose only to clients in the affected jurisdiction',
            'Take no action, because the strategies are unaffected',
          ],
          a: 0,
          why: 'Disclosure of regulatory or disciplinary action against the firm is required on the firm’s own initiative, not on request.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
        {
          text: 'The Asset Manager Code requires a firm to maintain a compliance function that:',
          given: null,
          opts: [
            'Reports to the head of the investment team',
            'Is independent, with a designated compliance officer and the authority to act',
            'Is outsourced to the firm’s auditor',
            'Reviews trades annually',
          ],
          a: 1,
          why: 'Independence is the point: a compliance function reporting into the business it supervises cannot supervise it.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
        {
          text: 'A firm’s business continuity plan is addressed by the Code under:',
          given: null,
          opts: [
            'Performance and valuation',
            'Risk management, compliance and support',
            'Loyalty to clients',
            'Disclosures only',
          ],
          a: 1,
          why: 'Business continuity sits in the risk management, compliance and support provisions, alongside the independent compliance function and adequate resourcing.',
          ref: 'Asset Manager Code of Professional Conduct',
        },
      ],
    },
    {
      slug: 'level-iii-application',
      name: 'Level III Application',
      blurb: 'Standards applied to IPS construction, suitability and performance presentation.',
      modules: [
        'Guidance for Standards I–VII (seven separate modules)',
        'Application of the Code and Standards: Level III',
      ],
      cards: [
        {
          kicker: 'SUITABILITY',
          title: 'The IPS is the suitability test, written down in advance',
          body: 'Standard III(C) requires a recommendation to fit the client’s objectives, constraints and risk profile, and requires the IPS to be reviewed at least annually. A trade defensible in isolation is unsuitable if it breaches the written policy.',
          formula: null,
          exam: 'Where a manager has a specific mandate, suitability is judged against the mandate rather than the client’s total wealth.',
        },
        {
          kicker: 'PRESENTATION',
          title: 'Fair, accurate and complete — and that includes terminated accounts',
          body: 'Standard III(D) prohibits presenting performance in a way that misleads. Excluding closed accounts, showing gross returns without labelling them, or presenting a model portfolio as if it were traded all breach it.',
          formula: null,
          exam: 'A composite excluding terminated accounts has survivorship bias built in, which is both a GIPS failure and a III(D) failure.',
        },
        {
          kicker: 'CONFIDENTIALITY',
          title: 'Confidentiality survives the relationship ending',
          body: 'Standard III(E) applies to former clients as it does to current ones, with the exception of illegal activities and where disclosure is required by law or the client permits it.',
          formula: null,
          exam: 'A CFA Institute Professional Conduct Program investigation is one of the situations where disclosure is permitted.',
        },
      ],
      questions: [
        {
          text: 'A manager with a stated small-cap value mandate buys a large-cap growth stock she believes is exceptional. This most likely violates:',
          given: null,
          opts: [
            'Standard V(A) Diligence and Reasonable Basis',
            'Standard III(C) Suitability, because the mandate defines suitability',
            'Standard III(A) Loyalty, Prudence and Care',
            'No standard, because the analysis was sound',
          ],
          a: 1,
          why: 'Where a manager has a specific mandate, the mandate is the suitability test. Conviction in the individual name does not override it.',
          ref: 'Standard III(C) — Suitability',
        },
        {
          text: 'A firm presents a composite that excludes accounts closed during the period. This most likely:',
          given: null,
          opts: [
            'Complies, because closed accounts are no longer managed',
            'Violates Standard III(D), because the presentation is not complete and carries survivorship bias',
            'Violates Standard I(B) Independence',
            'Complies if disclosed in a footnote',
          ],
          a: 1,
          why: 'Removing terminated accounts systematically removes the worst outcomes. That is not a fair, accurate and complete presentation, footnote or not.',
          ref: 'Standard III(D) — Performance Presentation',
        },
        {
          text: 'An IPS drafted four years ago has never been reviewed, though the client retired last year. The manager has most likely violated:',
          given: null,
          opts: [
            'Standard III(C), which requires the IPS to be reviewed and updated regularly',
            'Standard V(C) Record Retention',
            'Standard IV(C) Responsibilities of Supervisors',
            'No standard, if returns have been satisfactory',
          ],
          a: 0,
          why: 'Suitability requires the policy to be reviewed at least annually and whenever circumstances change materially. Retirement is exactly such a change.',
          ref: 'Standard III(C) — Suitability',
        },
        {
          text: 'A former client’s confidential information may be disclosed by a member when:',
          given: null,
          opts: [
            'The relationship has ended',
            'Disclosure is required by law, concerns illegal activities, or the client permits it',
            'A prospective client requests a reference',
            'The information is more than seven years old',
          ],
          a: 1,
          why: 'Standard III(E) continues after the relationship ends, with those three exceptions and no others.',
          ref: 'Standard III(E) — Preservation of Confidentiality',
        },
        {
          text: 'A manager uses a back-tested model portfolio in marketing material, labelled "illustrative performance". Under Standard III(D) this is:',
          given: null,
          opts: [
            'Acceptable, because it is labelled',
            'Acceptable only if it is clearly identified as hypothetical, not represented as actual, and the limitations are disclosed',
            'Prohibited in all circumstances',
            'Acceptable if the model has been run live for one quarter',
          ],
          a: 1,
          why: 'Hypothetical results are not prohibited, but they must be unmistakably identified as such with their limitations stated — a bare "illustrative" label is not enough.',
          ref: 'Standard III(D) — Performance Presentation',
        },
        {
          text: 'A portfolio manager allocates a limited allocation of a hot new issue to accounts on the basis of who complained most about missing the last one. This most likely violates:',
          given: null,
          opts: [
            'Standard III(B) Fair Dealing, because the basis is neither objective nor disclosed',
            'Standard VI(B) Priority of Transactions',
            'Standard I(C) Misrepresentation',
            'Standard V(B) Communication with Clients',
          ],
          a: 0,
          why: 'Allocation must follow an objective, disclosed and consistently applied policy. Responsiveness to complaints is none of those things.',
          ref: 'Standard III(B) — Fair Dealing',
        },
      ],
    },
  ],

  // ---------------------------------------------------------------------------
  // The three Level III pathways. A candidate sits exactly one of these, chosen at
  // registration, and it carries 30–35% of the exam — so each gets the same two
  // segments as a core topic area rather than being treated as an appendix.
  // ---------------------------------------------------------------------------

  'cfa-l3-pathway-portfolio': [
    {
      slug: 'active-equity',
      name: 'Active Equity Strategies',
      blurb:
        'Index-based approaches, factor and fundamental strategies, and constructing the book.',
      modules: [
        'Index-Based Equity Strategies',
        'Active Equity Investing: Strategies',
        'Active Equity Investing: Portfolio Construction',
      ],
      cards: [
        {
          kicker: 'INDEXING',
          title: 'Three ways to track, and each fails differently',
          body: 'Full replication tracks tightest and costs most in small or illiquid markets. Stratified sampling matches risk characteristics with fewer names. Optimisation minimises predicted tracking error and is the most exposed to a wrong risk model.',
          formula: null,
          exam: 'Tracking error rises with turnover, with fees, and with cash drag. Securities lending revenue is the offset that sometimes makes it negative.',
        },
        {
          kicker: 'STYLE',
          title: 'Bottom-up and top-down are different bets on where information is',
          body: 'Bottom-up assumes security-specific information is mispriced; top-down assumes sector, country or factor information is. A portfolio can run both, but the attribution should show which one is paying.',
          formula: null,
          exam: 'Fundamental strategies are judgement-driven and concentrated; quantitative ones are rules-driven, broad, and rely on breadth rather than conviction.',
        },
        {
          kicker: 'BUILD',
          title: 'Three sources of relative return, and a budget for each',
          body: 'Portfolio construction allocates active risk between factor exposures, sector or country tilts, and idiosyncratic stock bets. A well-built book states its intended split; a badly built one discovers it in attribution.',
          formula: 'active risk² ≈ factor risk² + idiosyncratic risk²',
          exam: 'Concentration raises idiosyncratic risk without necessarily raising expected active return — that is the sizing question.',
        },
      ],
      questions: [
        {
          text: 'A manager tracking a 2,000-stock emerging market index with 400 holdings chosen to match country, sector and size exposures is using:',
          given: null,
          opts: [
            'Full replication',
            'Stratified sampling',
            'Optimisation against a risk model',
            'A synthetic swap-based approach',
          ],
          a: 1,
          why: 'Matching characteristic buckets with a subset of names is stratified sampling. Optimisation would minimise a model-predicted tracking error rather than match buckets directly.',
          ref: 'Index-Based Equity Strategies',
        },
        {
          text: 'An index fund reports tracking error below the level implied by its fee. The most likely explanation is:',
          given: null,
          opts: [
            'The index provider rebalances infrequently',
            'Securities lending revenue offsetting part of the fee',
            'A cash drag',
            'A sampling error in the replication',
          ],
          a: 1,
          why: 'Lending revenue accrues to the fund and offsets costs, which can pull realised tracking difference below the fee.',
          ref: 'Index-Based Equity Strategies',
        },
        {
          text: 'A quantitative equity strategy is most likely to derive its expected active return from:',
          given: null,
          opts: [
            'A small number of high-conviction positions',
            'Breadth — many small positions with a modest information coefficient',
            'Sector rotation based on macroeconomic judgement',
            'Concentrated exposure to a single factor',
          ],
          a: 1,
          why: 'Quantitative strategies apply a modest edge across many names, so the fundamental law’s √BR term does the work rather than conviction.',
          ref: 'Active Equity Investing: Strategies',
        },
        {
          text: 'A portfolio has an active risk of 4%, of which 3.2% is factor risk. Its idiosyncratic active risk is closest to:',
          given: 'total active risk 4.0%; factor risk 3.2%',
          opts: ['0.8%', '2.4%', '3.6%', '5.1%'],
          a: 1,
          why: 'Risks add in squares: √(4.0² − 3.2²) = √(16 − 10.24) = √5.76 = 2.4%.',
          ref: 'Active Equity Investing: Portfolio Construction',
        },
        {
          text: 'A long-only manager wants exposure to a value factor. Relative to a long-short implementation, the long-only version most directly suffers from:',
          given: null,
          opts: [
            'A lower information coefficient',
            'A lower transfer coefficient, because negative views cannot be expressed beyond a zero weight',
            'Lower breadth in the underlying signal',
            'Higher benchmark risk by construction',
          ],
          a: 1,
          why: 'The long-only constraint truncates the expression of negative views at a zero holding, which is a transfer coefficient problem.',
          ref: 'Active Equity Investing: Portfolio Construction',
        },
        {
          text: 'A manager states that outperformance came from stock selection, but attribution shows it came almost entirely from an overweight to a single sector. The appropriate conclusion is:',
          given: null,
          opts: [
            'The attribution model is misspecified',
            'The realised return source differs from the stated process, which is a due diligence concern',
            'Stock selection and sector allocation are the same effect',
            'The benchmark is inappropriate',
          ],
          a: 1,
          why: 'A gap between stated process and realised source of return is the standard red flag in manager monitoring, whatever the sign of the return.',
          ref: 'Active Equity Investing: Portfolio Construction',
        },
      ],
    },
    {
      slug: 'yield-curve-and-credit',
      name: 'Yield Curve & Credit Strategy',
      blurb: 'LDI, curve positioning, credit strategy and getting the trade done.',
      modules: [
        'Liability-Driven and Index-Based Strategies',
        'Yield Curve Strategies',
        'Fixed-Income Active Management: Credit Strategies',
        'Trade Strategy and Execution',
      ],
      cards: [
        {
          kicker: 'LDI',
          title: 'Hedge the liability’s sensitivity, not its size',
          body: 'A liability-driven portfolio matches the money duration of assets to that of liabilities. The hedge ratio is a decision, not an identity: hedging less leaves deliberate surplus risk, which some sponsors want and should say so.',
          formula: 'BPV_assets × hedge ratio = BPV_liabilities',
          exam: 'Basis risk survives a perfect duration match whenever the liability discount curve differs from the asset curve.',
        },
        {
          kicker: 'CURVE',
          title: 'Bullet, barbell, ladder — each is a bet on curve shape',
          body: 'A bullet wins on a steepening around its maturity; a barbell wins on a flattening and on volatility, because of its higher convexity; a ladder is the neutral structure with the most predictable reinvestment.',
          formula: null,
          exam: 'Duration-neutral barbell against bullet is the classic convexity trade. It is paid for in yield give-up.',
        },
        {
          kicker: 'CREDIT',
          title: 'Spread duration is the credit risk measure, not duration',
          body: 'Interest rate duration answers what happens if the government curve shifts; spread duration answers what happens if the credit spread moves. A portfolio can be rate-neutral and heavily exposed to spreads at the same time.',
          formula: '%Δprice ≈ −spread duration × Δspread',
          exam: 'Bottom-up credit selection is rewarded in dispersion; top-down beta positioning is rewarded in a spread trend.',
        },
      ],
      questions: [
        {
          text: 'Liabilities have a BPV of 48,000 and assets a BPV of 32,000. To reach a 100% hedge ratio using futures with a BPV of 95 per contract, the manager should:',
          given: 'liability BPV 48,000; asset BPV 32,000; futures BPV 95',
          opts: [
            'Buy 168 contracts',
            'Sell 168 contracts',
            'Buy 337 contracts',
            'Sell 337 contracts',
          ],
          a: 0,
          why: 'The gap is 16,000 of BPV. 16,000 / 95 ≈ 168 contracts, bought to add asset sensitivity toward the liability.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'A manager expects the yield curve to flatten with short rates rising more than long rates, and wants to keep portfolio duration unchanged. The most appropriate position is:',
          given: null,
          opts: [
            'A duration-neutral barbell against the current bullet',
            'A duration-neutral bullet against the current barbell',
            'An outright duration extension',
            'An outright duration reduction',
          ],
          a: 0,
          why: 'A barbell gains relative to a bullet when the curve flattens, and its higher convexity is an additional benefit. Duration neutrality isolates the shape view.',
          ref: 'Yield Curve Strategies',
        },
        {
          text: 'A credit portfolio has an interest rate duration of 0.2 and a spread duration of 4.6. If credit spreads widen 40 basis points with government yields unchanged, the price change is closest to:',
          given: 'rate duration 0.2; spread duration 4.6; Δspread +40bp',
          opts: ['−0.08%', '−1.84%', '−1.92%', '−0.18%'],
          a: 1,
          why: '−4.6 × 0.0040 = −1.84%. The rate duration contributes nothing because government yields did not move.',
          ref: 'Fixed-Income Active Management: Credit Strategies',
        },
        {
          text: 'A pension plan matches asset and liability duration exactly but discounts liabilities on a high-grade corporate curve while holding government bonds. It retains:',
          given: null,
          opts: [
            'No residual risk',
            'Basis risk between the two curves',
            'Only reinvestment risk',
            'Only convexity mismatch risk',
          ],
          a: 1,
          why: 'A duration match across two different curves leaves the spread between them unhedged, which is basis risk and can be large in a crisis.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'Bottom-up credit security selection is most likely to be rewarded when:',
          given: null,
          opts: [
            'Spreads are trending tighter across the whole market',
            'Dispersion among issuers within rating bands is high',
            'Government yields are volatile',
            'Liquidity is uniformly abundant',
          ],
          a: 1,
          why: 'Selection needs differences to exploit. High dispersion means the market is pricing issuers differently, which is where issuer-level work pays.',
          ref: 'Fixed-Income Active Management: Credit Strategies',
        },
        {
          text: 'For a large order in an illiquid corporate bond, the dominant component of implementation shortfall is most likely:',
          given: null,
          opts: ['Commissions', 'Market impact', 'Exchange fees', 'Settlement costs'],
          a: 1,
          why: 'In a dealer market with thin depth, moving size moves the price. Explicit costs are trivial beside it.',
          ref: 'Trade Strategy and Execution',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-markets': [
    {
      slug: 'structures-and-process',
      name: 'Structures & the Investment Process',
      blurb: 'How a fund is put together, and what the GP and the LP each see.',
      modules: [
        'Private Investments and Structures',
        'General Partner and Investor Perspectives and the Investment Process',
      ],
      cards: [
        {
          kicker: 'STRUCTURE',
          title: 'The limited partnership exists to separate control from liability',
          body: 'The GP runs the fund with unlimited liability and a small commitment; LPs commit capital, take limited liability, and have almost no control between closings. The limited partnership agreement is where everything that matters is negotiated.',
          formula: null,
          exam: 'Key-person provisions, no-fault divorce clauses and the investment period length are the LP protections examined most often.',
        },
        {
          kicker: 'WATERFALL',
          title: 'Whole-of-fund defers carry; deal-by-deal accelerates it',
          body: 'A European waterfall returns all contributed capital and the preferred return before any carry is paid. An American waterfall pays carry deal by deal, which brings clawback provisions and escrow into play because early winners can overpay the GP.',
          formula: null,
          exam: 'A catch-up tier follows the preferred return and pays the GP until the agreed profit split is reached.',
        },
        {
          kicker: 'MEASURES',
          title: 'IRR, MOIC, DPI and RVPI each answer a different question',
          body: 'IRR is time-sensitive and manipulable through subscription lines. MOIC ignores time entirely. DPI is cash actually returned, RVPI is what is still held at the manager’s own mark. Read them together or not at all.',
          formula: 'TVPI = DPI + RVPI',
          exam: 'A high IRR with a low DPI means early paper gains and little realised cash. That combination is the point of the question.',
        },
      ],
      questions: [
        {
          text: 'A fund reports a net IRR of 24% and a DPI of 0.3 in year four. The most reasonable interpretation is:',
          given: 'net IRR 24%; DPI 0.3',
          opts: [
            'Strong realised performance',
            'Largely unrealised gains, with little cash returned so far',
            'The fund is in the J-curve trough',
            'The manager has breached the hurdle',
          ],
          a: 1,
          why: 'DPI of 0.3 means only 30% of contributions have come back as cash. The IRR rests on the manager’s own marks and on timing.',
          ref: 'General Partner and Investor Perspectives and the Investment Process',
        },
        {
          text: 'A fund uses a subscription credit facility to delay capital calls. The most likely effect on reported performance is:',
          given: null,
          opts: [
            'A higher reported IRR and an unchanged multiple',
            'A lower reported IRR and a higher multiple',
            'Both IRR and multiple rise',
            'No effect on either',
          ],
          a: 0,
          why: 'Shortening the period capital is outstanding flatters the time-sensitive IRR while leaving the money multiple essentially unchanged, less the facility cost.',
          ref: 'General Partner and Investor Perspectives and the Investment Process',
        },
        {
          text: 'A key-person provision in a limited partnership agreement most directly protects LPs against:',
          given: null,
          opts: [
            'Poor investment performance',
            'The departure of the individuals whose track record the LPs backed',
            'Excessive management fees',
            'Valuation disputes',
          ],
          a: 1,
          why: 'The clause suspends the investment period if named individuals leave, because the LPs committed to those people as much as to the strategy.',
          ref: 'Private Investments and Structures',
        },
        {
          text: 'Under an American, deal-by-deal waterfall, a clawback provision exists because:',
          given: null,
          opts: [
            'The GP may be overpaid carry on early winners that later losses would have offset',
            'Management fees may exceed the cap',
            'The preferred return may be miscalculated',
            'LPs may default on capital calls',
          ],
          a: 0,
          why: 'Carry paid on early successful exits can exceed the GP’s entitlement measured over the whole fund. Clawback recovers the excess.',
          ref: 'Private Investments and Structures',
        },
        {
          text: 'A catch-up provision in a distribution waterfall operates:',
          given: null,
          opts: [
            'Before the preferred return is paid',
            'After the preferred return, paying the GP until the agreed profit split is reached',
            'Only on liquidation',
            'Only where a clawback has been triggered',
          ],
          a: 1,
          why: 'The catch-up tier follows the hurdle and directs distributions to the GP until the overall split — typically 80/20 — is restored.',
          ref: 'Private Investments and Structures',
        },
        {
          text: 'TVPI of 1.8 with DPI of 1.5 implies RVPI of:',
          given: 'TVPI 1.8; DPI 1.5',
          opts: ['0.3', '3.3', '1.2', '0.83'],
          a: 0,
          why: 'TVPI = DPI + RVPI, so RVPI = 1.8 − 1.5 = 0.3. Most of the value has already been distributed.',
          ref: 'General Partner and Investor Perspectives and the Investment Process',
        },
      ],
    },
    {
      slug: 'private-equity-debt-and-real-assets',
      name: 'Private Equity, Debt & Real Assets',
      blurb: 'Buyout arithmetic, direct lending, special situations and the physical assets.',
      modules: [
        'Private Equity',
        'Private Debt',
        'Private Special Situations',
        'Private Real Estate Investments',
        'Infrastructure',
      ],
      cards: [
        {
          kicker: 'BUYOUT',
          title: 'Three levers, and only one of them is skill',
          body: 'Buyout returns come from operational improvement, multiple expansion and deleveraging. The first is the claim every manager makes; the second is the market; the third is arithmetic. Attribution across the three is the due diligence question.',
          formula: 'equity value = EV − net debt;  EV = EBITDA × multiple',
          exam: 'Entry and exit multiples given in a stem are handing you the multiple-expansion term directly.',
        },
        {
          kicker: 'DIRECT LENDING',
          title: 'Private credit is paid for illiquidity and covenants, not for duration',
          body: 'Loans are usually floating-rate and senior, so interest rate duration is short and the return is spread plus fees. The risks are credit selection, covenant erosion and the impossibility of exiting a position quickly.',
          formula: null,
          exam: 'Covenant-lite structures shift risk to the lender by removing the early warning, not by changing the coupon.',
        },
        {
          kicker: 'REAL ASSETS',
          title:
            'Infrastructure returns are regulated or contracted, or they are not infrastructure',
          body: 'The defining feature is a long-dated, often inflation-linked, cash flow underwritten by regulation or a concession. Where that is absent — merchant power, unregulated tolls — the asset behaves like a cyclical business with heavy capital employed.',
          formula: null,
          exam: 'Greenfield carries construction risk; brownfield does not. Regulated returns cap upside as well as flooring downside.',
        },
      ],
      questions: [
        {
          text: 'A buyout is entered at 8.0× EBITDA of 50 with net debt of 240, and exited three years later at 9.0× EBITDA of 62 with net debt of 150. Equity value at exit is closest to:',
          given: 'exit multiple 9.0×; exit EBITDA 62; exit net debt 150',
          opts: ['408', '558', '318', '468'],
          a: 0,
          why: 'EV at exit = 9.0 × 62 = 558. Equity = 558 − 150 = 408.',
          ref: 'Private Equity',
        },
        {
          text: 'Using the same deal, entry equity value was:',
          given: 'entry multiple 8.0×; entry EBITDA 50; entry net debt 240',
          opts: ['160', '400', '240', '110'],
          a: 0,
          why: 'EV at entry = 8.0 × 50 = 400. Equity = 400 − 240 = 160, so the equity multiple is 408/160 = 2.55×.',
          ref: 'Private Equity',
        },
        {
          text: 'A senior direct lending fund holds floating-rate loans. A 150 basis point rise in policy rates will most likely:',
          given: null,
          opts: [
            'Reduce the portfolio’s value sharply through duration',
            'Raise coupon income, while raising borrower default risk',
            'Leave both income and credit risk unchanged',
            'Reduce coupon income',
          ],
          a: 1,
          why: 'Floating coupons reset upward, so income rises and rate duration is minimal. The offsetting concern is that borrowers’ interest cover deteriorates.',
          ref: 'Private Debt',
        },
        {
          text: 'A covenant-lite loan differs from a traditional one principally in that it:',
          given: null,
          opts: [
            'Pays a lower coupon',
            'Removes maintenance covenants, so the lender loses the early warning and the seat at the table',
            'Ranks behind unsecured creditors',
            'Has a shorter maturity',
          ],
          a: 1,
          why: 'Without maintenance tests, deterioration is not surfaced until a payment default, by which point the lender’s options are far narrower.',
          ref: 'Private Debt',
        },
        {
          text: 'An investor seeking long-dated, inflation-linked cash flows with low correlation to equities is best served by:',
          given: null,
          opts: [
            'Merchant power generation',
            'A regulated utility or availability-based concession',
            'A development-stage toll road',
            'A value-add office redevelopment',
          ],
          a: 1,
          why: 'Regulated or availability-based infrastructure has contracted, often indexed, revenue independent of demand — which is the profile described.',
          ref: 'Infrastructure',
        },
        {
          text: 'A distressed-for-control strategy earns its return principally by:',
          given: null,
          opts: [
            'Collecting coupons until maturity',
            'Buying debt at a discount and converting it to equity through the restructuring',
            'Shorting the equity of the distressed issuer',
            'Providing rescue financing at par',
          ],
          a: 1,
          why: 'Buying the fulcrum security cheaply and taking ownership through the reorganisation is the defining distressed-for-control trade.',
          ref: 'Private Special Situations',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-wealth': [
    {
      slug: 'wealth-and-investment-planning',
      name: 'Wealth & Investment Planning',
      blurb: 'Human capital, tax-aware investing, and the conversation before the portfolio.',
      modules: [
        'The Private Wealth Management Industry',
        'Working With the Wealthy',
        'Wealth Planning',
        'Investment Planning',
      ],
      cards: [
        {
          kicker: 'CAPITAL',
          title: 'Human capital is the largest asset on a young client’s balance sheet',
          body: 'Total wealth is financial capital plus the present value of future earnings. Bond-like human capital — a tenured salary — supports a higher equity allocation; equity-like human capital, as in a commission-based or founder income, argues for the opposite.',
          formula: 'total wealth = financial capital + human capital',
          exam: 'A client whose income correlates with their employer’s share price has a concentrated exposure before a single share is bought.',
        },
        {
          kicker: 'TAX',
          title: 'Three tax regimes, three different answers',
          body: 'Accrual taxation compounds after-tax and erodes fastest. Deferred capital gains compound pre-tax and are taxed on realisation. Tax-exempt wrappers compound untouched. Asset location follows directly.',
          formula: 'after-tax future value (deferral) = FV_pretax − t(FV_pretax − basis)',
          exam: 'A low-basis concentrated holding is a tax problem before it is a diversification problem — that is why collars and exchange funds appear.',
        },
        {
          kicker: 'PROCESS',
          title: 'Capacity, tolerance, perception — three different things',
          body: 'Risk capacity is what the balance sheet can survive; risk tolerance is what the client will accept; risk perception is what the client currently believes. Planning addresses all three, and only the first is arithmetic.',
          formula: null,
          exam: 'Goals-based planning assigns each goal its own horizon, required success probability and sub-portfolio.',
        },
      ],
      questions: [
        {
          text: 'A 32-year-old tenured academic with stable, inflation-linked income and modest savings has human capital that is:',
          given: null,
          opts: [
            'Equity-like, arguing for a conservative financial portfolio',
            'Bond-like, supporting a higher equity allocation in the financial portfolio',
            'Irrelevant to allocation before retirement',
            'Equal in risk to the financial portfolio by construction',
          ],
          a: 1,
          why: 'Secure, indexed income behaves like an inflation-linked bond. Total wealth is therefore bond-heavy, which the financial portfolio can offset with equity.',
          ref: 'Investment Planning',
        },
        {
          text: 'A client holds a concentrated low-basis position in her former employer. Selling would realise a large gain. The most appropriate first step is to:',
          given: null,
          opts: [
            'Sell immediately to diversify',
            'Quantify the after-tax cost of each diversification route — outright sale, collar, exchange fund, staged disposal — against the concentration risk',
            'Hold indefinitely to defer tax',
            'Borrow against the position and invest the proceeds',
          ],
          a: 1,
          why: 'The trade-off between concentration risk and the tax cost of removing it is the whole decision, and it cannot be made without pricing both sides.',
          ref: 'Wealth Planning',
        },
        {
          text: 'An investment taxed annually on accrual, relative to one taxed only on realisation at the same rate, will most likely:',
          given: null,
          opts: [
            'Accumulate more after-tax wealth',
            'Accumulate less after-tax wealth, because the tax drag compounds',
            'Accumulate the same amount',
            'Accumulate more only if the holding period is long',
          ],
          a: 1,
          why: 'Annual taxation removes money that would otherwise compound. Deferral leaves the full balance working until realisation.',
          ref: 'Investment Planning',
        },
        {
          text: 'Risk capacity differs from risk tolerance in that capacity is:',
          given: null,
          opts: [
            'A psychological trait measured by questionnaire',
            'An objective function of wealth, liabilities and horizon',
            'The client’s current perception of market conditions',
            'Set by regulation',
          ],
          a: 1,
          why: 'Capacity is what the balance sheet can absorb. Tolerance is willingness, and perception is the client’s present belief, which changes with the market.',
          ref: 'Wealth Planning',
        },
        {
          text: 'A client whose salary and bonus both depend on the profitability of the investment bank she works for should most appropriately:',
          given: null,
          opts: [
            'Overweight financial sector equities to express her expertise',
            'Underweight or hedge financial sector exposure, because her human capital is already concentrated there',
            'Hold the market weight, since human capital is not investable',
            'Hold only cash until she changes employer',
          ],
          a: 1,
          why: 'Her income and the sector fail together. Total-wealth thinking treats that as an existing overweight to be offset.',
          ref: 'Investment Planning',
        },
        {
          text: 'In a goals-based plan, a lifestyle goal with a 95% required success probability and a five-year horizon, alongside a legacy goal with a 60% requirement and a thirty-year horizon, should be funded by:',
          given: null,
          opts: [
            'A single blended portfolio at the weighted average risk level',
            'Two sub-portfolios, the lifestyle goal conservative and short, the legacy goal higher risk and long',
            'The same portfolio, rebalanced annually',
            'Cash for both, to guarantee the lifestyle goal',
          ],
          a: 1,
          why: 'Goals-based planning matches each goal’s horizon and required certainty with its own sub-portfolio rather than averaging them into one.',
          ref: 'Wealth Planning',
        },
      ],
    },
    {
      slug: 'preserving-and-transferring',
      name: 'Preserving & Transferring Wealth',
      blurb: 'Estate planning arithmetic, trusts, and advising across generations.',
      modules: ['Preserving the Wealth', 'Advising the Wealthy', 'Transferring the Wealth'],
      cards: [
        {
          kicker: 'GIFT VS BEQUEST',
          title: 'Lifetime gifting wins when the recipient’s rate is lower and the horizon is long',
          body: 'The relative value of a gift over a bequest depends on the two parties’ tax rates, the expected returns each earns, the horizon, and whether the gift tax is paid by the donor — which itself removes that sum from the taxable estate.',
          formula: 'RV = [(1 + rg)^n (1 − tg)] / [(1 + re)^n (1 − te)]',
          exam: 'A relative value above one means gifting now beats bequeathing later. Work out which rate applies to whom before substituting.',
        },
        {
          kicker: 'TRUSTS',
          title: 'Revocable protects nothing; irrevocable gives up control',
          body: 'A revocable trust keeps assets in the settlor’s estate and offers no creditor protection — its benefit is probate avoidance and continuity. An irrevocable trust removes assets from the estate precisely because the settlor cannot get them back.',
          formula: null,
          exam: 'Where the stem wants creditor protection or estate reduction, the answer is irrevocable. Where it wants flexibility, it is not.',
        },
        {
          kicker: 'CROSS-BORDER',
          title: 'Double taxation is resolved by credit, exemption, or a treaty',
          body: 'Source jurisdictions tax where income arises; residence jurisdictions tax worldwide income. Relief comes from a credit method, an exemption method, or a treaty allocating the right to tax — and the three give materially different answers.',
          formula: 'credit method: tax = max(t_source, t_residence)',
          exam: 'Under the credit method the investor pays the higher of the two rates in total. Under exemption they pay only the source rate.',
        },
      ],
      questions: [
        {
          text: 'Under the credit method for relieving double taxation, an investor resident where the rate is 35% receiving income taxed at source at 20% pays total tax of:',
          given: 'source rate 20%; residence rate 35%; credit method',
          opts: ['20%', '35%', '55%', '15%'],
          a: 1,
          why: 'The credit method allows the source tax against the residence liability, so the investor pays the higher of the two rates in total — 35%.',
          ref: 'Transferring the Wealth',
        },
        {
          text: 'A settlor wants assets removed from her taxable estate and protected from future creditors. The appropriate structure is:',
          given: null,
          opts: [
            'A revocable living trust',
            'An irrevocable trust',
            'A joint account with right of survivorship',
            'A power of attorney',
          ],
          a: 1,
          why: 'Only an irrevocable transfer removes the assets from the estate and from the reach of the settlor’s creditors, at the cost of losing control.',
          ref: 'Preserving the Wealth',
        },
        {
          text: 'Gifting appreciating assets during life, rather than bequeathing them, is most advantageous when:',
          given: null,
          opts: [
            'The recipient faces a higher tax rate and the horizon is short',
            'The recipient faces a lower tax rate and the horizon is long',
            'The donor expects the asset to fall in value',
            'Estate tax rates are zero',
          ],
          a: 1,
          why: 'The relative value expression rewards moving future growth to the lower-taxed party, and the advantage compounds with the horizon.',
          ref: 'Transferring the Wealth',
        },
        {
          text: 'A donor pays the gift tax on a lifetime transfer rather than the recipient. The additional benefit is that:',
          given: null,
          opts: [
            'The gift becomes tax-free',
            'The tax paid is itself removed from the donor’s taxable estate',
            'The recipient’s basis is stepped up',
            'The transfer avoids all future income tax',
          ],
          a: 1,
          why: 'Cash used to pay the gift tax leaves the estate, so the estate is reduced by more than the gift alone — the tax-exclusive advantage.',
          ref: 'Transferring the Wealth',
        },
        {
          text: 'A family with operating businesses, several jurisdictions and three generations of beneficiaries is most appropriately served by:',
          given: null,
          opts: [
            'A single discretionary portfolio',
            'A coordinated structure — governance, succession and investment policy addressed together rather than portfolio-first',
            'Index funds held personally by each beneficiary',
            'An annuity for each beneficiary',
          ],
          a: 1,
          why: 'At this complexity the binding problems are governance, succession and tax across jurisdictions. The portfolio follows from those, not the other way round.',
          ref: 'Advising the Wealthy',
        },
        {
          text: 'Under the exemption method of double taxation relief, an investor resident where the rate is 30%, receiving income taxed at source at 12%, pays total tax of:',
          given: 'source rate 12%; residence rate 30%; exemption method',
          opts: ['30%', '12%', '42%', '18%'],
          a: 1,
          why: 'The exemption method excludes the foreign income from the residence tax base entirely, leaving only the source rate of 12%.',
          ref: 'Transferring the Wealth',
        },
      ],
    },
  ],
};
