import { PremiumSegmentBank } from '../types';

/**
 * CFA Level III — premium segments, tranche II.
 *
 * A third segment for each core area and each pathway. Level III is examined in
 * essays as well as item sets, so these lean further into "recommend and justify"
 * than tranche I did: several items ask which of two defensible answers fits the
 * mandate described, which is the form the constructed-response paper takes.
 */
export const CFA_L3_SEGMENTS_II: PremiumSegmentBank = {
  'cfa-l3-allocation': [
    {
      slug: 'rebalancing-and-implementation',
      name: 'Rebalancing & Implementation Choice',
      blurb: 'Risk parity, factor allocation, and deciding what to do actively at all.',
      modules: ['Overview of Asset Allocation', 'Principles of Asset Allocation'],
      cards: [
        {
          kicker: 'AXES',
          title: 'Allocate by asset class, by risk factor, or by both — and say which',
          body: 'Asset class allocation is intuitive and double-counts exposures, since two classes can load on the same factor. Factor allocation is cleaner analytically and harder to implement and govern. Most institutions allocate by class and monitor by factor.',
          formula: null,
          exam: 'Equities and high yield credit share an equity factor. An allocation that treats them as diversifying is double-counting.',
        },
        {
          kicker: 'PARITY',
          title: 'Risk parity equalises risk contributions, which requires leverage to be sensible',
          body: 'Equalising risk contributions puts most of the capital in low-volatility assets, which produces an expected return below target unless the whole portfolio is levered. The approach is therefore a bet on the cost and availability of that leverage.',
          formula: 'contribution_i = w_i × ∂σp/∂w_i',
          exam: 'Risk parity’s weakness is not the maths; it is the dependence on cheap financing and on volatility estimates being stable.',
        },
        {
          kicker: 'ACTIVE',
          title: 'Decide where active risk is worth paying for, then buy the rest cheaply',
          body: 'The case for active management is strongest where markets are less efficient, dispersion is high and the manager’s edge is documented. Elsewhere the expected value of the fee is negative. That decision belongs in the policy, not in the manager search.',
          formula: null,
          exam: 'A large active allocation to a highly efficient market is the classic thing to criticise in a constructed response.',
        },
      ],
      questions: [
        {
          text: 'An institution allocates 35% to equities and 15% to high yield credit and describes the two as diversifying. The most substantive criticism is that:',
          given: null,
          opts: [
            'High yield has a higher expected return than equities',
            'Both load heavily on a common equity factor, so the allocation double-counts a single exposure',
            'High yield is illiquid',
            'The allocation is too concentrated in fixed income',
          ],
          a: 1,
          why: 'Factor decomposition shows high yield behaving substantially like equity in a drawdown. Treating the two as separate overstates diversification.',
          ref: 'Principles of Asset Allocation',
        },
        {
          text: 'A risk parity portfolio is expected to fall short of a 6% return target without leverage. The most accurate characterisation of the strategy is that it:',
          given: null,
          opts: [
            'Cannot be implemented',
            'Depends on the cost and availability of leverage as much as on the allocation itself',
            'Is equivalent to an equal-weighted portfolio',
            'Removes the need for return forecasts',
          ],
          a: 1,
          why: 'Equalising risk contributions loads capital into low-volatility assets, so the return target is reached by levering the whole portfolio. That makes financing a first-order risk.',
          ref: 'Principles of Asset Allocation',
        },
        {
          text: 'A committee proposes a large active allocation to large-capitalisation domestic equities. The strongest objection is that:',
          given: null,
          opts: [
            'Large-cap equities are too volatile',
            'That market is among the most efficient, so the expected value of active fees there is negative',
            'Domestic equities carry currency risk',
            'The allocation should be to bonds instead',
          ],
          a: 1,
          why: 'Active risk should be spent where dispersion and inefficiency make it likeliest to pay. In a highly efficient market the fee is the most reliable component of the outcome.',
          ref: 'Overview of Asset Allocation',
        },
        {
          text: 'An investor with a strong preference for avoiding losses over a one-year horizon, rather than minimising variance, is best served by an allocation framework built on:',
          given: null,
          opts: [
            'Mean-variance optimisation',
            'Mean-CVaR or another downside-focused objective',
            'Equal weighting',
            'Maximum diversification',
          ],
          a: 1,
          why: 'Variance penalises upside and downside alike. Where the stated objective is shortfall, the objective function should measure shortfall.',
          ref: 'Principles of Asset Allocation',
        },
        {
          text: 'A portfolio’s strategic allocation is reviewed and left unchanged, but the rebalancing corridors are widened substantially. The most likely consequence is:',
          given: null,
          opts: [
            'Lower turnover and greater drift from the strategic allocation between rebalances',
            'Higher turnover and tighter risk control',
            'No change to realised risk',
            'A permanent reduction in expected return',
          ],
          a: 0,
          why: 'Wider corridors trade transaction costs against fidelity to the policy. Less trading means more drift, which is a deliberate choice and should be stated as one.',
          ref: 'Overview of Asset Allocation',
        },
        {
          text: 'Mean-variance optimisation applied to ten asset classes with sample inputs produces a portfolio holding just three of them at large weights. This is best described as:',
          given: null,
          opts: [
            'Evidence that the other seven are unattractive',
            'Error maximisation — the optimiser concentrating in whichever inputs happen to be most favourably estimated',
            'A correctly specified corner solution',
            'A consequence of the risk-free rate assumption',
          ],
          a: 1,
          why: 'Optimisers amplify estimation error into extreme weights. Resampling, shrinkage or constraints are the standard responses.',
          ref: 'Principles of Asset Allocation',
        },
      ],
    },
  ],

  'cfa-l3-construction': [
    {
      slug: 'private-wealth-construction',
      name: 'Building a Private Client Portfolio',
      blurb: 'Taxes, concentration and liquidity, in the order they actually bind.',
      modules: [
        'An Overview of Private Wealth Management',
        'Asset Allocation to Alternative Investments',
      ],
      cards: [
        {
          kicker: 'ORDER',
          title: 'Tax and liquidity bind before the efficient frontier does',
          body: 'For a taxable client the sequence is: establish the goals and the horizon, locate assets across account types, then optimise within what tax and liquidity permit. A pre-tax efficient portfolio that cannot be reached without realising a large gain is not a recommendation.',
          formula: null,
          exam: 'Asset location is usually worth more than an allocation tweak, and it is the answer candidates skip.',
        },
        {
          kicker: 'CONCENTRATION',
          title: 'Four routes out of a concentrated low-basis holding',
          body: 'Staged disposal, a collar or other hedge, an exchange fund, or borrowing against the position. Each trades tax cost against basis risk, control and complexity, and the right answer depends on the client’s constraints rather than on the arithmetic alone.',
          formula: null,
          exam: 'An exchange fund defers tax and gives diversification but locks capital up for years and gives up control.',
        },
        {
          kicker: 'ALTERNATIVES',
          title: 'Size an alternatives allocation against cash needs, not against a target',
          body: 'Commitments are drawn over years and distributions are unpredictable. A private client with lumpy liquidity needs and no institutional cash buffer can carry far less than the allocation model suggests, and the denominator effect will push the weight up exactly when selling is hardest.',
          formula: null,
          exam: 'Over-commitment strategies are for institutions with predictable inflows. Applying one to a family is the error to identify.',
        },
      ],
      questions: [
        {
          text: 'A client holds 60% of her liquid wealth in the shares of her former employer, with a cost basis near zero. The most appropriate first step is to:',
          given: null,
          opts: [
            'Sell the entire position immediately to diversify',
            'Quantify the after-tax cost of each route out — staged sale, collar, exchange fund, borrowing — against the concentration risk',
            'Hold indefinitely to defer the tax',
            'Borrow against the position and invest the proceeds in the same sector',
          ],
          a: 1,
          why: 'The decision is a trade between concentration risk and tax cost, and it cannot be made without pricing both. Each route sits at a different point on that trade.',
          ref: 'An Overview of Private Wealth Management',
        },
        {
          text: 'An exchange fund, as a route out of a concentrated holding, most directly provides:',
          given: null,
          opts: [
            'Immediate liquidity and a step-up in basis',
            'Diversification with tax deferral, at the cost of a multi-year lock-up and loss of control',
            'A guaranteed floor price',
            'Elimination of market risk',
          ],
          a: 1,
          why: 'Contributing the stake to a pooled vehicle defers the gain and diversifies the exposure, but the capital is committed for years and the investor no longer chooses the holdings.',
          ref: 'An Overview of Private Wealth Management',
        },
        {
          text: 'A family office adopts an over-commitment strategy for private equity, committing 130% of the target allocation in expectation of slow drawdowns. For a family with lumpy, unpredictable liquidity needs this is:',
          given: null,
          opts: [
            'Best practice, since it maintains the target allocation',
            'Inappropriate — it relies on predictable inflows that a family, unlike a large institution, does not have',
            'Appropriate only if the commitments are to a single vintage',
            'Neutral, since commitments are not liabilities',
          ],
          a: 1,
          why: 'Over-commitment works where new inflows reliably fund calls. Without them a call arriving in a drawdown forces a sale of exactly the wrong assets.',
          ref: 'Asset Allocation to Alternative Investments',
        },
        {
          text: 'For a taxable private client, asset location means:',
          given: null,
          opts: [
            'Choosing which countries to invest in',
            'Placing heavily taxed assets in sheltered accounts and tax-efficient assets in taxable ones',
            'Selecting the custodian',
            'Deciding between pooled and segregated vehicles',
          ],
          a: 1,
          why: 'Location holds the overall allocation constant and improves the after-tax outcome purely by choosing which wrapper holds what.',
          ref: 'An Overview of Private Wealth Management',
        },
        {
          text: 'A zero-cost collar over a concentrated holding is most likely to be unattractive to a client who:',
          given: null,
          opts: [
            'Wants downside protection at low cash cost',
            'Believes the shares will substantially outperform and wants to keep that upside',
            'Cannot sell for tax reasons',
            'Has a short horizon',
          ],
          a: 1,
          why: 'The collar is funded by selling the upside above the call strike. A client with a strong positive view is giving away exactly what they expect to earn.',
          ref: 'An Overview of Private Wealth Management',
        },
        {
          text: 'Public equity markets fall 25%. A private client’s private equity allocation, held at stale marks, rises from 12% to 15% of the portfolio. The appropriate response is most likely to:',
          given: null,
          opts: [
            'Sell private stakes on the secondary market to restore the weight',
            'Recognise the denominator effect, check that pending capital calls remain fundable, and avoid forced secondary sales',
            'Increase the private allocation further to average in',
            'Suspend the investment policy',
          ],
          a: 1,
          why: 'The weight moved because the denominator shrank. Selling into a distressed secondary market realises a discount to solve a problem that is partly an artefact of measurement.',
          ref: 'Asset Allocation to Alternative Investments',
        },
      ],
    },
  ],

  'cfa-l3-performance': [
    {
      slug: 'gips-composites',
      name: 'GIPS Composites & Reporting',
      blurb: 'Building a composite properly, and what a compliant presentation must contain.',
      modules: [
        'Overview of the Global Investment Performance Standards (GIPS)',
        'Portfolio Performance Evaluation',
      ],
      cards: [
        {
          kicker: 'SCOPE',
          title: 'Firm-wide, every discretionary fee-paying portfolio, in at least one composite',
          body: 'The firm must be defined as it is held out to the market, and every actual, fee-paying, discretionary portfolio must be in at least one composite. Non-discretionary portfolios are excluded; terminated portfolios remain in the composite for the periods they were managed.',
          formula: null,
          exam: 'Excluding terminated portfolios is the survivorship failure that GIPS exists to prevent.',
        },
        {
          kicker: 'CALCULATION',
          title: 'Time-weighted returns, with large flows handled properly',
          body: 'GIPS requires time-weighted returns that adjust for external cash flows, with revaluation on the date of large flows. Money-weighted returns are required only where the firm controls the timing of flows, such as in private capital.',
          formula: null,
          exam: 'Trade-date accounting and accrual accounting for fixed income are both required.',
        },
        {
          kicker: 'PRESENTATION',
          title: 'A compliant presentation is a list, and it is examinable as one',
          body: 'At least five years of performance building to ten, composite and benchmark returns, the number of portfolios, composite assets, firm assets, a measure of internal dispersion, and three-year annualised ex-post standard deviation for composite and benchmark.',
          formula: null,
          exam: 'Dispersion is across portfolios within the composite in one period; the three-year standard deviation is across time.',
        },
      ],
      questions: [
        {
          text: 'A firm removes portfolios from a composite on the date each client terminates the mandate, for all historical periods. This:',
          given: null,
          opts: [
            'Complies, since the firm no longer manages them',
            'Violates GIPS — terminated portfolios must remain in the composite for the periods they were managed',
            'Complies if disclosed',
            'Violates GIPS only if the portfolios underperformed',
          ],
          a: 1,
          why: 'Removing terminated portfolios retrospectively introduces survivorship bias, which is precisely what the standard is designed to prevent.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'Which portfolio may legitimately be excluded from all composites?',
          given: null,
          opts: [
            'A fee-paying discretionary portfolio that underperformed',
            'A non-discretionary portfolio whose client directs the trades',
            'A portfolio terminated mid-year',
            'A newly funded portfolio after it has been invested',
          ],
          a: 1,
          why: 'Only non-discretionary portfolios sit outside the composite structure, because the firm is not exercising the strategy in them.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'Internal dispersion, as required in a GIPS presentation, measures the spread of returns:',
          given: null,
          opts: [
            'Of the composite across time',
            'Across the individual portfolios within the composite in a single period',
            'Between the composite and its benchmark',
            'Of the benchmark across time',
          ],
          a: 1,
          why: 'Dispersion tells a prospect how consistently the strategy was delivered across accounts. The three-year standard deviation is the measure across time.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'A private equity manager reports time-weighted returns for its funds. Under GIPS this is:',
          given: null,
          opts: [
            'Required',
            'Inappropriate — money-weighted returns are required where the firm controls the timing of cash flows',
            'Permitted, provided it is disclosed',
            'Permitted only for funds older than five years',
          ],
          a: 1,
          why: 'Where the manager calls and distributes capital, the timing is part of the performance and the internal rate of return is the required measure.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'A firm newly claiming compliance must present at least:',
          given: null,
          opts: [
            'One year of performance',
            'Five years of performance, or since inception if shorter, building to ten',
            'Ten years immediately',
            'Three years, verified',
          ],
          a: 1,
          why: 'Five years is the minimum, extended each year until ten are shown. Verification is recommended rather than required.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
        {
          text: 'A composite return is computed by averaging the returns of its portfolios equally. Under GIPS this is:',
          given: null,
          opts: [
            'Acceptable in all cases',
            'Incorrect — composite returns must be asset-weighted',
            'Acceptable if disclosed as an equal-weighted composite',
            'Acceptable for composites with fewer than five portfolios',
          ],
          a: 1,
          why: 'Asset weighting makes the composite represent the strategy as actually managed. Equal weighting lets a small account swing the reported figure.',
          ref: 'Overview of the Global Investment Performance Standards (GIPS)',
        },
      ],
    },
  ],

  'cfa-l3-derivatives': [
    {
      slug: 'currency-hedging-programmes',
      name: 'Currency Hedging Programmes',
      blurb: 'Running a hedge over time: ratios, rolls, proxies and when to stop.',
      modules: ['Currency Management: An Introduction', 'Swaps, Forwards, and Futures Strategies'],
      cards: [
        {
          kicker: 'MANDATE',
          title: 'Set the neutral position first, then the discretion around it',
          body: 'A hedging policy states a benchmark hedge ratio and the band within which the manager may deviate. Passive means hold the neutral ratio; discretionary allows tactical deviation within the band; active treats currency as a return source in its own right.',
          formula: null,
          exam: 'Without a stated neutral ratio there is no way to say whether a currency position is a hedge or a bet.',
        },
        {
          kicker: 'ROLL',
          title: 'A rolling forward hedge pays or earns the differential, every time',
          body: 'Each roll crystallises the interest rate differential and a bid-offer spread. Hedging a high-yield currency back into a low-yield base costs carry continuously, which over a long horizon can exceed the currency risk being avoided.',
          formula: null,
          exam: 'Compare the annualised hedging cost against the currency’s volatility before concluding a hedge is worth it.',
        },
        {
          kicker: 'PROXY',
          title: 'A cross hedge trades basis risk for tradability',
          body: 'Where a currency is illiquid or restricted, hedging with a correlated liquid one, or with a basket, is the practical route. The residual is basis risk, and it fails exactly when correlations break — which is when the hedge was most wanted.',
          formula: null,
          exam: 'Minimum-variance hedge ratios are estimated from a regression and are unstable. Say so when recommending one.',
        },
      ],
      questions: [
        {
          text: 'A fund’s policy sets a neutral hedge ratio of 50% with a permitted range of 25% to 75%. The manager holds 70%. This position is best described as:',
          given: null,
          opts: [
            'A breach of policy',
            'A discretionary tactical position within the mandate, expressing a view that the foreign currency will weaken',
            'A fully hedged position',
            'A currency overlay mandate',
          ],
          a: 1,
          why: 'Hedging above neutral is a bet against the foreign currency, taken within the band the policy allows. It is a position, and it should be reported as one.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'An investor hedges exposure to a currency whose interest rate is 4 percentage points above the base currency’s. Rolling forward contracts will:',
          given: 'foreign rate 4pp above base rate',
          opts: [
            'Earn approximately 4% a year in carry',
            'Cost approximately 4% a year in carry',
            'Be carry-neutral',
            'Depend only on realised spot moves',
          ],
          a: 1,
          why: 'Selling forward a high-yield currency means selling at a forward discount, which is realised as a cost at each roll regardless of what spot does.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'A manager cannot trade forwards in a restricted currency and hedges using a correlated liquid currency instead. The principal residual exposure is:',
          given: null,
          opts: [
            'Counterparty risk',
            'Basis risk, which is largest exactly when correlations break',
            'Settlement risk',
            'Interest rate risk',
          ],
          a: 1,
          why: 'A proxy hedge works while the relationship holds. Crises are when the relationship breaks and when the hedge was most needed.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'An equity portfolio manager wants to reduce equity beta from 1.05 to 0.70 on a 80 million portfolio using index futures with a beta of 1.00 and a contract value of 125,000. The required position is closest to:',
          given: 'V 80m; β current 1.05; β target 0.70; β futures 1.00; contract value 125,000',
          opts: [
            '224 contracts short',
            '224 contracts long',
            '560 contracts short',
            '448 contracts short',
          ],
          a: 0,
          why: 'N = (0.70 − 1.05) × 80,000,000 / (1.00 × 125,000) = −28,000,000/125,000 = −224, so 224 contracts sold.',
          ref: 'Swaps, Forwards, and Futures Strategies',
        },
        {
          text: 'A minimum-variance hedge ratio estimated from three years of monthly data is 1.18. The most appropriate caution to attach to a recommendation using it is that:',
          given: null,
          opts: [
            'Ratios above 1.0 are not permitted',
            'The estimate is a regression coefficient and is unstable out of sample, so the ratio should be monitored and re-estimated',
            'The ratio should be rounded to 1.0',
            'Monthly data cannot be used',
          ],
          a: 1,
          why: 'The ratio is fitted to a past relationship. Presenting it without its estimation error overstates how precisely the hedge can be set.',
          ref: 'Currency Management: An Introduction',
        },
        {
          text: 'A long-horizon investor holds foreign equities whose currency has a low correlation with the equity return and a hedging cost of 3% a year. The most defensible recommendation is to:',
          given: 'long horizon; low currency-equity correlation; hedging cost 3% a year',
          opts: [
            'Hedge fully, because currency risk is uncompensated',
            'Hedge little or not at all, because the persistent cost is likely to exceed the volatility reduction over that horizon',
            'Hedge exactly half as a neutral default',
            'Hedge dynamically on a momentum signal',
          ],
          a: 1,
          why: 'A 3% annual certain cost against an uncertain volatility reduction, over decades, is a poor trade. "Uncompensated risk" is an argument for hedging only when hedging is cheap.',
          ref: 'Currency Management: An Introduction',
        },
      ],
    },
  ],

  'cfa-l3-ethics': [
    {
      slug: 'standards-in-portfolio-context',
      name: 'Standards in a Portfolio Context',
      blurb: 'Soft dollars, trade allocation, proxy voting and the duties owed to a fund.',
      modules: [
        'Code of Ethics and Standards of Professional Conduct',
        'Guidance for Standards I–VII (seven separate modules)',
      ],
      cards: [
        {
          kicker: 'TO WHOM',
          title: 'For a pooled fund the client is the fund, not the individual holder',
          body: 'A manager of a commingled vehicle owes loyalty to the fund and to its stated objectives, not to any one investor’s preferences. A large holder asking for a deviation is asking the manager to breach a duty owed to everyone else in the pool.',
          formula: null,
          exam: 'This is the standard Level III trap: the biggest investor asks, and the answer is still no.',
        },
        {
          kicker: 'PROXY',
          title: 'Voting is part of managing the asset, and cost is a legitimate consideration',
          body: 'Proxy voting is part of the duty of care, but voting every proxy regardless of cost is not required. A documented policy that weighs the cost of analysis against the value at stake is what Standard III(A) expects.',
          formula: null,
          exam: 'A blanket policy of always following management, or never voting, is the answer to reject.',
        },
        {
          kicker: 'SOFT DOLLARS',
          title: 'Client brokerage is a client asset',
          body: 'Research bought with client commissions must benefit the clients whose brokerage paid for it. Directed brokerage arranged by the client itself is permitted but the manager must disclose where it compromises best execution.',
          formula: null,
          exam: 'Buying the firm’s own overheads — rent, salaries, marketing — with soft dollars is never acceptable.',
        },
      ],
      questions: [
        {
          text: 'The largest investor in a commingled equity fund asks the manager to avoid a particular sector on ethical grounds. The manager should most appropriately:',
          given: null,
          opts: [
            'Comply, given the size of the holding',
            'Decline, because the duty is owed to the fund and its stated mandate rather than to one holder',
            'Comply and disclose to other holders',
            'Comply for the portion of the fund the investor owns',
          ],
          a: 1,
          why: 'In a pooled vehicle the client is the fund. Accommodating one holder’s preference changes the strategy every other holder bought.',
          ref: 'Standard III(A) — Loyalty, Prudence and Care',
        },
        {
          text: 'A manager uses client commissions to pay for a market data terminal used firm-wide, including by the marketing team. This is:',
          given: null,
          opts: [
            'Acceptable, since research tools benefit clients indirectly',
            'A violation — client brokerage may not fund the firm’s own overheads',
            'Acceptable if disclosed annually',
            'Acceptable if allocated pro rata',
          ],
          a: 1,
          why: 'Soft dollars must buy research that benefits the paying clients. Mixed-use items require the non-research portion to be paid for by the firm.',
          ref: 'Standard III(A) — Loyalty, Prudence and Care',
        },
        {
          text: 'A manager adopts a policy of not voting proxies on small holdings where the cost of analysis exceeds the value at stake. This is:',
          given: null,
          opts: [
            'A violation, because every proxy must be voted',
            'Acceptable, provided the policy is documented and disclosed and reflects a genuine cost-benefit judgement',
            'Acceptable only for index funds',
            'A violation of Standard V(A)',
          ],
          a: 1,
          why: 'Proxy voting is part of the duty of care, not an absolute obligation regardless of cost. What is required is a considered, disclosed policy.',
          ref: 'Standard III(A) — Loyalty, Prudence and Care',
        },
        {
          text: 'A client directs the manager to place all trades with a specified broker whose execution is demonstrably worse. The manager should:',
          given: null,
          opts: [
            'Refuse the instruction outright',
            'Follow the instruction but inform the client that it may compromise best execution and document that disclosure',
            'Follow it silently, since the client chose it',
            'Split orders between brokers without telling the client',
          ],
          a: 1,
          why: 'Client-directed brokerage is permitted. What is required is that the client understands the cost of their own instruction.',
          ref: 'Standard III(A) — Loyalty, Prudence and Care',
        },
        {
          text: 'A firm receives an allocation of a heavily oversubscribed new issue. Its allocation policy is documented, objective and consistently applied, and results in some clients receiving nothing. This is:',
          given: null,
          opts: [
            'A violation of Standard III(B) Fair Dealing',
            'Acceptable — fair dealing requires fairness, not identical treatment',
            'Acceptable only if every client receives something',
            'A violation unless the policy is approved by clients annually',
          ],
          a: 1,
          why: 'Pro-rata or other objective allocation may produce zero fills at small account sizes. Fairness is in the rule and its consistent application.',
          ref: 'Standard III(B) — Fair Dealing',
        },
        {
          text: 'A portfolio manager is offered a seat on the board of a company held in client portfolios. Under the Standards she must, at minimum:',
          given: null,
          opts: [
            'Decline the seat',
            'Disclose the arrangement to her employer and to clients, and consider whether it creates a conflict she cannot manage',
            'Accept and resign from managing that holding',
            'Accept, provided she receives no fee',
          ],
          a: 1,
          why: 'Standard VI(A) requires disclosure of anything that could impair independence, to employer and clients. Whether it is manageable is the next question, not the first.',
          ref: 'Standard VI(A) — Disclosure of Conflicts',
        },
      ],
    },
  ],

  'cfa-l3-pathway-portfolio': [
    {
      slug: 'execution-and-case-study',
      name: 'Execution & the Endowment Case',
      blurb:
        'Choosing an execution strategy, measuring what it cost, and a case that ties it together.',
      modules: [
        'Trade Strategy and Execution',
        'Case Study in Portfolio Management: Institutional (Endowment)',
      ],
      cards: [
        {
          kicker: 'URGENCY',
          title: 'The trade’s motivation sets the strategy',
          body: 'Information-driven trades are urgent and should pay spread and impact to get done before the information is public. Liquidity-driven and rebalancing trades are patient and should minimise impact. Matching the algorithm to the motivation is the whole decision.',
          formula: null,
          exam: 'An implementation shortfall algorithm front-loads for urgency; VWAP and participation algorithms spread for patience.',
        },
        {
          kicker: 'MEASURE',
          title: 'Implementation shortfall counts the decision, not the ticket',
          body: 'Delay cost from the decision to the order reaching the market, execution cost against the arrival price, explicit fees, and the opportunity cost of the unfilled remainder. The last term is the one candidates omit and is often the largest.',
          formula: 'IS = delay + realised execution + fees + missed trade opportunity',
          exam: 'A high fill rate at a poor price and a low fill rate at a good price can produce the same shortfall. That is the point of the measure.',
        },
        {
          kicker: 'ENDOWMENT',
          title: 'A spending rule is a liability with a smoothing mechanism attached',
          body: 'Smoothing rules average the spending base over several years, which stabilises the institution’s budget and delays the portfolio’s response to a drawdown. The cost is that a sustained fall in value is felt for years after it happens.',
          formula:
            'spending = smoothing × prior spending grown by inflation + (1 − smoothing) × rate × asset value',
          exam: 'Higher smoothing means more budget stability and slower adjustment. State the trade rather than the preference.',
        },
      ],
      questions: [
        {
          text: 'A manager must sell a large position because a stock has been removed from the portfolio’s eligible universe, with no information advantage and no deadline. The most appropriate execution approach is:',
          given: null,
          opts: [
            'An aggressive liquidity-seeking algorithm',
            'A patient participation strategy spread over several sessions to minimise market impact',
            'A single market order at the open',
            'A block trade at any available discount',
          ],
          a: 1,
          why: 'With no information to protect and no deadline, impact dominates the cost. Patience is the cheaper side of the trade-off.',
          ref: 'Trade Strategy and Execution',
        },
        {
          text: 'A decision to buy 200,000 shares is taken at 30.00. 140,000 fill at an average of 30.18 with fees of 0.03 per share; the remainder is unfilled and the price ends at 30.90. The missed trade opportunity cost is:',
          given: 'decision price 30.00; 60,000 unfilled; final price 30.90',
          opts: ['25,200', '54,000', '60,000', '4,200'],
          a: 1,
          why: '60,000 shares × (30.90 − 30.00) = 54,000. Omitting the unfilled portion understates the shortfall by more than the executed cost.',
          ref: 'Trade Strategy and Execution',
        },
        {
          text: 'An endowment uses a three-year smoothed spending rule. Following a 30% market fall, the effect on spending relative to a rule based on current market value is that spending:',
          given: null,
          opts: [
            'Falls immediately by the same proportion',
            'Falls more gradually, stabilising the budget but sustaining the drawdown on the portfolio for longer',
            'Is unaffected in all years',
            'Rises to maintain the institution’s programmes',
          ],
          a: 1,
          why: 'Smoothing spreads the adjustment. The institution gets budget stability; the portfolio keeps paying out at a rate its reduced value no longer supports.',
          ref: 'Case Study in Portfolio Management: Institutional (Endowment)',
        },
        {
          text: 'An endowment with a 5% spending rule, 2% expected inflation and 0.4% costs requires a long-run nominal return of at least:',
          given: 'spending 5%; inflation 2%; costs 0.4%',
          opts: ['5.0%', '7.0%', '7.4%', '7.5%'],
          a: 2,
          why: 'Approximately 5% + 2% + 0.4% = 7.4% to preserve real value. The multiplicative form gives a figure slightly higher.',
          ref: 'Case Study in Portfolio Management: Institutional (Endowment)',
        },
        {
          text: 'A trader reports an average execution price better than the day’s VWAP but the portfolio manager reports a large implementation shortfall. The most likely reconciliation is that:',
          given: null,
          opts: [
            'One of the two figures is wrong',
            'The price moved substantially between the decision and the order reaching the market, which VWAP does not capture',
            'Fees were excluded from VWAP',
            'The order was filled in full',
          ],
          a: 1,
          why: 'VWAP benchmarks execution against the day. Implementation shortfall benchmarks against the decision price, so delay cost appears in one and not the other.',
          ref: 'Trade Strategy and Execution',
        },
        {
          text: 'An endowment’s investment committee proposes raising the private markets allocation from 20% to 35% while maintaining the current spending rule. The most substantive concern is:',
          given: null,
          opts: [
            'Private markets have lower expected returns',
            'Liquidity — spending and capital calls both have to be met from a shrinking liquid sleeve, particularly in a drawdown',
            'Private markets cannot be benchmarked',
            'The committee lacks authority',
          ],
          a: 1,
          why: 'Spending is a continuous claim and capital calls are unpredictable. Raising the illiquid share without changing the spending rule concentrates both on a smaller liquid base.',
          ref: 'Case Study in Portfolio Management: Institutional (Endowment)',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-markets': [
    {
      slug: 'valuation-and-exits',
      name: 'Valuation & Exits',
      blurb:
        'Valuing a private company, and the routes by which a fund actually realises a return.',
      modules: [
        'Private Equity',
        'Private Special Situations',
        'General Partner and Investor Perspectives and the Investment Process',
      ],
      cards: [
        {
          kicker: 'METHODS',
          title:
            'Comparables, transactions, discounted cash flow — and the first is the market’s opinion',
          body: 'Trading comparables give a public-market view that needs a discount for illiquidity and an adjustment for control. Precedent transactions already embed a control premium. A discounted cash flow stands alone and is only as good as the operating plan behind it.',
          formula: null,
          exam: 'Do not apply a control premium to a precedent transaction multiple. It is already in there.',
        },
        {
          kicker: 'EXIT',
          title: 'Trade sale, secondary buyout, IPO, dividend recapitalisation',
          body: 'A trade sale to a strategic buyer usually pays the highest price because synergies are available to the buyer. A secondary sale to another sponsor is faster and cleaner. An IPO gives a partial exit at market prices with a lock-up. A recapitalisation returns cash without selling anything.',
          formula: null,
          exam: 'A dividend recapitalisation is not an exit. It returns capital and leaves the risk in place, with more leverage on it.',
        },
        {
          kicker: 'BRIDGE',
          title: 'Bridge the entry equity to the exit equity in three terms',
          body: 'Value creation splits into EBITDA growth, multiple expansion and debt paydown. Attribution across the three is the due diligence question, because only the first is a claim about the manager rather than about the market or about arithmetic.',
          formula: 'equity = EBITDA × multiple − net debt',
          exam: 'A track record built on multiple expansion in a falling-rate decade is a statement about the decade.',
        },
      ],
      questions: [
        {
          text: 'An analyst values a private target using precedent transaction multiples and then adds a 25% control premium. This is:',
          given: null,
          opts: [
            'Correct practice',
            'Double-counting — precedent transactions already reflect control',
            'Correct only for majority stakes',
            'Correct if a marketability discount is also applied',
          ],
          a: 1,
          why: 'Transaction multiples are paid by acquirers taking control, so the premium is embedded. Adding it again inflates the valuation.',
          ref: 'Private Equity',
        },
        {
          text: 'A sponsor sells a portfolio company to another private equity firm. This exit route is best described as:',
          given: null,
          opts: [
            'A trade sale',
            'A secondary buyout',
            'An initial public offering',
            'A dividend recapitalisation',
          ],
          a: 1,
          why: 'A sale to another financial sponsor is a secondary buyout. A trade sale is to a strategic buyer, who can usually pay more because of synergies.',
          ref: 'Private Equity',
        },
        {
          text: 'A company is bought at 9.0× EBITDA of 40 with net debt of 250, and sold at 9.0× EBITDA of 58 with net debt of 170. The equity value at exit is:',
          given: 'exit multiple 9.0×; exit EBITDA 58; exit net debt 170',
          opts: ['352', '522', '292', '412'],
          a: 0,
          why: 'Enterprise value at exit is 9.0 × 58 = 522. Equity is 522 − 170 = 352.',
          ref: 'Private Equity',
        },
        {
          text: 'For that deal, the value created came from:',
          given:
            'entry 9.0× on EBITDA 40 with net debt 250; exit 9.0× on EBITDA 58 with net debt 170',
          opts: [
            'Multiple expansion alone',
            'EBITDA growth and debt paydown, with no multiple expansion',
            'Debt paydown alone',
            'Multiple expansion and EBITDA growth',
          ],
          a: 1,
          why: 'The multiple is unchanged at 9.0×, so nothing came from repricing. EBITDA rose from 40 to 58 and net debt fell from 250 to 170.',
          ref: 'Private Equity',
        },
        {
          text: 'A dividend recapitalisation is best described as:',
          given: null,
          opts: [
            'An exit that realises the sponsor’s position',
            'A return of capital funded by new borrowing, which leaves the equity risk in place at higher leverage',
            'A sale of a minority stake to a co-investor',
            'A restructuring of the fund’s management fee',
          ],
          a: 1,
          why: 'Cash is returned without selling the asset. The sponsor’s exposure remains and the company carries more debt against it.',
          ref: 'Private Equity',
        },
        {
          text: 'An investor reviewing a buyout manager finds that 70% of historical value creation came from multiple expansion during a decade of falling interest rates. The appropriate conclusion is that:',
          given: null,
          opts: [
            'The manager has demonstrated strong operational skill',
            'Much of the record reflects the market environment rather than repeatable manager skill',
            'The record is fraudulent',
            'Multiple expansion is the most reliable source of return',
          ],
          a: 1,
          why: 'Repricing is a claim about the market, not about the manager. The part worth paying for is what came from operating improvement.',
          ref: 'General Partner and Investor Perspectives and the Investment Process',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-wealth': [
    {
      slug: 'behaviour-and-advice',
      name: 'Behaviour & the Advisory Relationship',
      blurb: 'Client types, family governance, and advice that survives a bad year.',
      modules: [
        'The Private Wealth Management Industry',
        'Working With the Wealthy',
        'Advising the Wealthy',
      ],
      cards: [
        {
          kicker: 'SOURCE',
          title: 'How the wealth was made shapes how it is held',
          body: 'An entrepreneur who built and sold a business is typically comfortable with concentration and control and uncomfortable delegating. Inherited wealth is often more risk averse and more focused on preservation and transfer. The source is a better predictor than a questionnaire.',
          formula: null,
          exam: 'Self-made clients frequently resist diversification precisely because concentration is what worked for them.',
        },
        {
          kicker: 'ADAPT OR CORRECT',
          title: 'Cognitive errors are moderated; emotional biases are accommodated',
          body: 'Anchoring, framing and availability respond to education, better data and structured process. Loss aversion, regret aversion and status quo usually do not, and a portfolio the client abandons in a drawdown is worse than a slightly suboptimal one they hold.',
          formula: null,
          exam: 'Wealth relative to the goal decides how far to accommodate: a client with ample assets can afford a suboptimal portfolio they will actually keep.',
        },
        {
          kicker: 'GOVERNANCE',
          title: 'For a family, governance is the deliverable',
          body: 'A family constitution, a defined decision process, an education programme for the next generation, and clarity on who speaks for the family. Without these, the portfolio is renegotiated at every family event and no investment policy survives.',
          formula: null,
          exam: 'At real complexity, the binding problems are governance and succession. The portfolio follows.',
        },
      ],
      questions: [
        {
          text: 'A client who built and sold a manufacturing business insists on holding 40% of her wealth in a single private company she is advising. The most effective initial response is to:',
          given: null,
          opts: [
            'Refuse the mandate',
            'Quantify the concentration risk against her stated goals and agree a floor of diversified assets that secures the essential ones',
            'Diversify the portfolio without discussing it',
            'Agree, since the client understands the business',
          ],
          a: 1,
          why: 'Framing the decision around which goals are at risk converts an argument about preference into one about consequences, and secures the essential goals whatever she decides about the rest.',
          ref: 'Working With the Wealthy',
        },
        {
          text: 'A client with assets far exceeding her lifetime needs exhibits strong loss aversion. The most appropriate advisory response is to:',
          given: null,
          opts: [
            'Educate the bias away and implement the mean-variance optimal portfolio',
            'Accommodate it with a more conservative allocation, since she can afford the cost and would otherwise abandon the plan in a drawdown',
            'Ignore it, since her capacity is high',
            'Move the entire portfolio to cash',
          ],
          a: 1,
          why: 'Emotional biases are accommodated rather than corrected, and ample wealth is exactly the condition under which the cost of accommodating is affordable.',
          ref: 'Advising the Wealthy',
        },
        {
          text: 'An analyst notices a client repeatedly refusing to sell losers while readily selling winners. This is best described as:',
          given: null,
          opts: [
            'Confirmation bias',
            'The disposition effect, arising from loss aversion',
            'Anchoring',
            'Overconfidence',
          ],
          a: 1,
          why: 'Realising gains and deferring losses is the disposition effect. It is emotional in origin, which is why information alone rarely changes it.',
          ref: 'Working With the Wealthy',
        },
        {
          text: 'A third-generation family with operating businesses in four countries has no agreed decision process and revisits its investment policy at every family gathering. The adviser’s priority should be:',
          given: null,
          opts: [
            'Optimising the portfolio allocation',
            'Establishing family governance — a constitution, a decision process, and clarity on who speaks for the family',
            'Reducing investment fees',
            'Consolidating custody',
          ],
          a: 1,
          why: 'No investment policy survives being renegotiated continuously. Governance is what makes any subsequent portfolio decision durable.',
          ref: 'Advising the Wealthy',
        },
        {
          text: 'A client anchors on the price at which he bought a holding five years ago and refuses to sell below it. This bias is:',
          given: null,
          opts: [
            'Emotional, and should be accommodated',
            'Cognitive, and responds to education and a structured process that reframes the decision around current prospects',
            'Evidence of superior information',
            'Unrelated to portfolio outcomes',
          ],
          a: 1,
          why: 'Anchoring is a cognitive error. Showing that the purchase price has no bearing on future returns is the correction, and it often works.',
          ref: 'Working With the Wealthy',
        },
        {
          text: 'The private wealth management industry differs from institutional asset management most fundamentally in that private clients:',
          given: null,
          opts: [
            'Have larger portfolios',
            'Are taxed, have finite and uncertain horizons, and bring goals that are personal rather than contractual',
            'Are more sophisticated',
            'Require higher returns',
          ],
          a: 1,
          why: 'Taxation, mortality and goals that cannot be written as a liability schedule are what make the private problem structurally different.',
          ref: 'The Private Wealth Management Industry',
        },
      ],
    },
  ],
};
