import { PremiumSegmentBank } from '../types';

/**
 * FRM Part II — premium segments.
 *
 * Part II is application rather than tools, so these items put the candidate in
 * the position of having to choose a method and justify it, which is how the
 * paper is actually written.
 */
export const FRM_P2_SEGMENTS: PremiumSegmentBank = {
  'frm-p2-market': [
    {
      slug: 'var-backtesting-and-evt',
      name: 'VaR Estimation, Backtesting & EVT',
      blurb: 'Choosing an estimator, proving it works, and modelling the part beyond the data.',
      modules: [
        'VaR estimation approaches and their limitations; backtesting VaR',
        'Expected Shortfall and other coherent measures; parametric and non-parametric estimation',
        'Extreme value theory and tail risk',
      ],
      cards: [
        {
          kicker: 'BACKTEST',
          title: 'Count the exceptions, then test whether the count is plausible',
          body: 'A 99% daily VaR should be exceeded about 2.5 times in 250 days. Kupiec’s unconditional coverage test asks whether the observed count is consistent with that. Christoffersen adds independence — exceptions clustering together is its own failure.',
          formula: 'expected exceptions = (1 − confidence) × observations',
          exam: 'Passing coverage while failing independence means the model is right on average and wrong exactly when it matters.',
        },
        {
          kicker: 'ESTIMATORS',
          title: 'Three families, three failure modes',
          body: 'Parametric is fast and wrong in the tails. Historical simulation inherits the empirical distribution but cannot see an unprecedented event and weights a five-year-old day equally with yesterday. Monte Carlo is flexible and only as good as its assumptions.',
          formula: null,
          exam: 'Age-weighted historical simulation is the standard fix for the equal-weighting problem.',
        },
        {
          kicker: 'EVT',
          title: 'Model the tail separately, because the middle is not informative about it',
          body: 'Peaks-over-threshold fits a generalised Pareto distribution to exceedances above a threshold. The shape parameter ξ governs tail heaviness: ξ > 0 is a fat tail, and the choice of threshold trades bias against variance.',
          formula: null,
          exam: 'EVT extrapolates beyond the sample, which is exactly what historical simulation cannot do.',
        },
      ],
      questions: [
        {
          text: 'A 99% one-day VaR model produces 11 exceptions in 250 trading days. The most appropriate conclusion is that the model:',
          given: '250 observations; 99% confidence; 11 exceptions',
          opts: [
            'Is well calibrated, since exceptions are expected',
            'Materially understates risk — about 2.5 exceptions were expected',
            'Overstates risk',
            'Cannot be assessed without the loss magnitudes',
          ],
          a: 1,
          why: 'Expected exceptions are 0.01 × 250 = 2.5. Eleven is far outside a plausible range and fails an unconditional coverage test.',
          ref: 'VaR estimation approaches and their limitations; backtesting VaR',
        },
        {
          text: 'A VaR model passes Kupiec’s test but its exceptions occur on six consecutive days. This most directly indicates a failure of:',
          given: null,
          opts: [
            'Unconditional coverage',
            'Independence of exceptions, which Christoffersen’s test examines',
            'Subadditivity',
            'The square root of time rule',
          ],
          a: 1,
          why: 'Clustered exceptions mean the model does not adapt to changing volatility, even though the long-run count is right.',
          ref: 'VaR estimation approaches and their limitations; backtesting VaR',
        },
        {
          text: 'Age-weighted historical simulation addresses which weakness of standard historical simulation?',
          given: null,
          opts: [
            'Its inability to handle non-linear instruments',
            'Its equal weighting of distant and recent observations',
            'Its assumption of normality',
            'Its reliance on a covariance matrix',
          ],
          a: 1,
          why: 'Standard historical simulation gives a day five years ago the same weight as yesterday. Age weighting decays older observations.',
          ref: 'Expected Shortfall and other coherent measures; parametric and non-parametric estimation',
        },
        {
          text: 'In a peaks-over-threshold EVT model, a fitted shape parameter ξ of 0.35 indicates:',
          given: 'ξ = 0.35',
          opts: [
            'A thin tail, thinner than the normal distribution',
            'A fat tail, with the moments above 1/ξ undefined',
            'An exponential tail',
            'A bounded tail',
          ],
          a: 1,
          why: 'Positive ξ is the heavy-tailed Fréchet case. Moments of order 1/ξ and above do not exist, so with ξ = 0.35 the third moment onward is undefined.',
          ref: 'Extreme value theory and tail risk',
        },
        {
          text: 'Lowering the threshold in a peaks-over-threshold model most directly:',
          given: null,
          opts: [
            'Reduces both bias and variance of the tail estimate',
            'Reduces variance by using more exceedances, at the cost of bias from including non-tail observations',
            'Reduces bias at the cost of variance',
            'Has no effect on the fitted shape parameter',
          ],
          a: 1,
          why: 'More exceedances means a more stable fit, but observations from the body of the distribution contaminate the tail estimate. That trade-off is the whole threshold choice.',
          ref: 'Extreme value theory and tail risk',
        },
        {
          text: 'A risk manager must choose between VaR and expected shortfall for setting a trading limit on a book holding deep out-of-the-money options. Expected shortfall is preferable principally because it:',
          given: null,
          opts: [
            'Is easier to backtest',
            'Captures the magnitude of losses beyond the threshold, which is where an option book’s risk lives',
            'Requires fewer observations',
            'Is always smaller and therefore more conservative',
          ],
          a: 1,
          why: 'Selling far out-of-the-money options produces a loss distribution that is unremarkable up to the VaR point and severe beyond it. VaR is blind to precisely that.',
          ref: 'Expected Shortfall and other coherent measures; parametric and non-parametric estimation',
        },
      ],
    },
    {
      slug: 'volatility-copulas-and-frtb',
      name: 'Volatility Models, Copulas & FRTB',
      blurb: 'Smiles, dependence structures, and what the trading book rules changed.',
      modules: [
        'Volatility modelling: GARCH, EWMA, implied volatility surfaces',
        'Correlation and copulas',
        'Volatility smiles; exotic and mortgage-backed products',
        'Fundamental Review of the Trading Book (FRTB)',
      ],
      cards: [
        {
          kicker: 'SMILE',
          title: 'The smile is the market pricing what the model cannot',
          body: 'A skew in equity index options reflects demand for downside protection and the fat left tail Black–Scholes assumes away. A symmetric smile, common in currencies, reflects fat tails in both directions.',
          formula: null,
          exam: 'Equity index: a downward-sloping skew. Currency: a roughly symmetric smile. The shape tells you the asset class.',
        },
        {
          kicker: 'COPULAS',
          title: 'A copula separates the margins from the dependence',
          body: 'Each variable keeps its own marginal distribution; the copula supplies the joint structure. A Gaussian copula has zero tail dependence, which is precisely why it failed on structured credit; a t copula has positive tail dependence.',
          formula: null,
          exam: 'Zero tail dependence means extremes are asymptotically independent — the assumption that made senior CDO tranches look safe.',
        },
        {
          kicker: 'FRTB',
          title: 'Expected shortfall, liquidity horizons, and a hard boundary',
          body: 'FRTB replaced VaR with expected shortfall at 97.5%, calibrated to a stress period and scaled by risk-factor liquidity horizons; it tightened the trading book–banking book boundary and requires desk-level model approval with P&L attribution.',
          formula: null,
          exam: 'The boundary matters because arbitrage between books is what the old regime rewarded.',
        },
      ],
      questions: [
        {
          text: 'Equity index options typically display implied volatility that falls as the strike rises. This skew is most consistent with:',
          given: null,
          opts: [
            'A market expectation of symmetric moves',
            'Demand for downside protection and a fat left tail in the return distribution',
            'A violation of put–call parity',
            'Arbitrage between the cash and futures markets',
          ],
          a: 1,
          why: 'Crash risk and persistent hedging demand bid up low-strike puts, which the Black–Scholes framework can only express as a higher implied volatility.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
        {
          text: 'A Gaussian copula applied to a portfolio of correlated credits will most likely:',
          given: null,
          opts: [
            'Overstate the probability of many simultaneous defaults',
            'Understate it, because the Gaussian copula has zero tail dependence',
            'Reproduce the empirical joint distribution exactly',
            'Be equivalent to a t copula with low degrees of freedom',
          ],
          a: 1,
          why: 'Zero asymptotic tail dependence means extreme events are treated as nearly independent — which is what made senior structured credit tranches appear remote from loss.',
          ref: 'Correlation and copulas',
        },
        {
          text: 'Under FRTB, the internal models approach measures risk using:',
          given: null,
          opts: [
            'VaR at 99% over ten days',
            'Expected shortfall at 97.5%, calibrated to a period of stress and scaled by liquidity horizons',
            'Expected shortfall at 99% with no liquidity adjustment',
            'Stressed VaR at 95%',
          ],
          a: 1,
          why: 'FRTB moved to stressed expected shortfall at 97.5% with risk-factor liquidity horizons replacing a single ten-day assumption.',
          ref: 'Fundamental Review of the Trading Book (FRTB)',
        },
        {
          text: 'FRTB tightened the boundary between the trading book and the banking book principally to:',
          given: null,
          opts: [
            'Simplify reporting',
            'Prevent capital arbitrage through reclassification of positions between books',
            'Reduce the number of risk factors',
            'Align with IFRS 9',
          ],
          a: 1,
          why: 'Under the previous regime a position could be moved to whichever book carried the lower charge. A strict boundary with restrictions on reclassification removes that.',
          ref: 'Fundamental Review of the Trading Book (FRTB)',
        },
        {
          text: 'A t copula is often preferred to a Gaussian copula for modelling joint defaults because it:',
          given: null,
          opts: [
            'Has thinner tails',
            'Exhibits tail dependence, so extreme events co-occur more often',
            'Requires fewer parameters',
            'Guarantees positive definiteness',
          ],
          a: 1,
          why: 'The t copula’s positive tail dependence reproduces the observed tendency of defaults to cluster in a stress, which the Gaussian copula cannot.',
          ref: 'Correlation and copulas',
        },
        {
          text: 'Under FRTB, desk-level model approval requires ongoing P&L attribution testing, whose purpose is to establish that:',
          given: null,
          opts: [
            'The desk is profitable',
            'The risk model’s explanation of daily P&L matches the actual P&L closely enough for the model to be trusted',
            'The desk’s VaR exceptions are below the threshold',
            'The desk uses the standardised approach as a floor',
          ],
          a: 1,
          why: 'If the model cannot explain the desk’s own daily P&L, it cannot be relied on to capitalise the desk, and approval is withdrawn.',
          ref: 'Fundamental Review of the Trading Book (FRTB)',
        },
      ],
    },
  ],

  'frm-p2-credit': [
    {
      slug: 'default-models',
      name: 'Default Models & Credit VaR',
      blurb: 'Structural against reduced-form, default correlation, and portfolio credit loss.',
      modules: [
        'Structural and reduced-form default models; Merton model',
        'Portfolio credit risk, default correlation and credit VaR',
        'Credit analysis and the credit process; ratings and rating transitions',
      ],
      cards: [
        {
          kicker: 'MERTON',
          title: 'Equity is a call on the firm’s assets',
          body: 'Default occurs when asset value falls below the face value of debt at maturity. Equity is therefore a call struck at that face value, risky debt is a risk-free bond less a put, and the credit spread follows from the option value.',
          formula: 'E = V·N(d₁) − D·e^(−rT)·N(d₂);  PD = N(−d₂)',
          exam: 'Distance to default is how many standard deviations of asset value sit between now and the default point.',
        },
        {
          kicker: 'REDUCED FORM',
          title: 'Default as an unpredictable arrival',
          body: 'A hazard-rate model treats default as a jump with an intensity fitted to market spreads or historical data. It needs no unobservable asset value and produces a term structure of default probabilities directly — at the cost of any economic story.',
          formula: 'P(survival to T) = e^(−λT)',
          exam: 'Spread ≈ λ × LGD is the standard approximation. Given a spread and a recovery, you can back out the implied hazard rate.',
        },
        {
          kicker: 'CORRELATION',
          title: 'Portfolio credit risk is almost entirely a correlation question',
          body: 'Expected loss adds linearly and ignores correlation. The tail does not: default correlation drives the shape of the loss distribution and therefore the credit VaR. A one-factor copula makes that correlation a single parameter.',
          formula: null,
          exam: 'Raising default correlation leaves expected loss unchanged and fattens the tail. Both halves of that sentence are examined.',
        },
      ],
      questions: [
        {
          text: 'Under the Merton model, the value of a firm’s risky debt is equivalent to:',
          given: null,
          opts: [
            'A risk-free bond plus a long put on the firm’s assets',
            'A risk-free bond minus a put on the firm’s assets, written to the equity holders',
            'A call on the firm’s assets struck at the debt face value',
            'A risk-free bond plus a call',
          ],
          a: 1,
          why: 'Debtholders are effectively short a put: if assets fall below the face value, they receive the assets instead of par.',
          ref: 'Structural and reduced-form default models; Merton model',
        },
        {
          text: 'A bond trades at a credit spread of 300 basis points with an expected recovery rate of 40%. The implied annual hazard rate is closest to:',
          given: 'spread 300bp; recovery 40%',
          opts: ['3.0%', '5.0%', '7.5%', '1.8%'],
          a: 1,
          why: 'spread ≈ λ × LGD, so λ ≈ 0.03/0.60 = 5.0%.',
          ref: 'Structural and reduced-form default models; Merton model',
        },
        {
          text: 'Under a reduced-form model with a constant hazard rate of 4%, the probability of surviving three years is closest to:',
          given: 'λ 4%; T 3',
          opts: ['88.0%', '88.7%', '12.0%', '96.0%'],
          a: 1,
          why: 'P(survival) = e^(−0.04 × 3) = e^(−0.12) = 0.8869, or 88.7%.',
          ref: 'Structural and reduced-form default models; Merton model',
        },
        {
          text: 'Increasing the assumed default correlation in a portfolio of identical credits will most likely:',
          given: null,
          opts: [
            'Increase expected loss and increase credit VaR',
            'Leave expected loss unchanged and increase credit VaR',
            'Decrease expected loss and increase credit VaR',
            'Leave both unchanged',
          ],
          a: 1,
          why: 'Expected loss is the sum of individual expected losses whatever the correlation. Correlation changes the dispersion, fattening the tail that credit VaR measures.',
          ref: 'Portfolio credit risk, default correlation and credit VaR',
        },
        {
          text: 'Distance to default in the Merton framework is best described as:',
          given: null,
          opts: [
            'The difference between asset value and debt, in currency',
            'The number of standard deviations of asset value between the current value and the default point',
            'The time remaining until the debt matures',
            'The credit spread divided by loss given default',
          ],
          a: 1,
          why: 'Standardising the gap by asset volatility is what makes firms of different sizes comparable, and is what maps to a default probability.',
          ref: 'Structural and reduced-form default models; Merton model',
        },
        {
          text: 'A structural model’s principal practical weakness relative to a reduced-form model is that it:',
          given: null,
          opts: [
            'Cannot produce a term structure of default probabilities',
            'Requires asset value and asset volatility, neither of which is directly observable',
            'Cannot be calibrated to equity prices',
            'Assumes default is unpredictable',
          ],
          a: 1,
          why: 'The inputs must be inferred from equity prices and balance sheet data. Reduced-form models sidestep this by fitting an intensity to observable spreads.',
          ref: 'Structural and reduced-form default models; Merton model',
        },
      ],
    },
    {
      slug: 'counterparty-and-structured-credit',
      name: 'Counterparty Risk & Structured Credit',
      blurb: 'CVA and wrong-way risk, netting and collateral, tranching and correlation.',
      modules: [
        'Counterparty risk, CVA/DVA/FVA and wrong-way risk',
        'Netting, collateral and margining',
        'Credit derivatives and credit default swaps',
        'Securitisation, structured credit and CDOs',
      ],
      cards: [
        {
          kicker: 'CVA',
          title: 'CVA prices the counterparty’s possible failure into the trade',
          body: 'Credit valuation adjustment is the expected loss from counterparty default over the life of the exposure — expected positive exposure, default probability and loss given default combined. DVA is the mirror image and is why a firm’s own deterioration can produce a gain.',
          formula: 'CVA ≈ Σ EPE(t) × PD(t) × LGD × discount',
          exam: 'DVA booking a profit when your own credit worsens is a genuine feature of the accounting, and the exam asks about it.',
        },
        {
          kicker: 'WRONG WAY',
          title: 'Exposure and counterparty quality moving together',
          body: 'Wrong-way risk is when exposure rises exactly as the counterparty’s creditworthiness falls — buying protection on a sovereign from a bank in that sovereign, or an oil swap with a producer. Specific wrong-way risk is a legal or structural link; general is a macro one.',
          formula: null,
          exam: 'A stem where the collateral is the counterparty’s own shares is describing specific wrong-way risk.',
        },
        {
          kicker: 'TRANCHES',
          title: 'Tranching redistributes correlation risk, it does not remove risk',
          body: 'Equity tranches lose first and benefit from low default correlation; senior tranches are exposed to the simultaneous-default scenario, so higher correlation hurts them. The total pool loss is unchanged by how it is sliced.',
          formula: null,
          exam: 'Long the equity tranche is long correlation; long the senior tranche is short correlation. That pair is examined directly.',
        },
      ],
      questions: [
        {
          text: 'A bank buys credit protection on a sovereign from a large bank domiciled in that same country. This is best described as:',
          given: null,
          opts: ['Right-way risk', 'Specific wrong-way risk', 'Basis risk only', 'Settlement risk'],
          a: 1,
          why: 'The protection is worth most precisely when the seller is least able to pay, and the link is structural rather than merely macroeconomic.',
          ref: 'Counterparty risk, CVA/DVA/FVA and wrong-way risk',
        },
        {
          text: 'A firm’s own credit spread widens sharply. Under standard derivative accounting this most likely produces:',
          given: null,
          opts: [
            'A CVA loss',
            'A DVA gain, because its own liabilities are worth less',
            'No valuation effect',
            'An FVA gain',
          ],
          a: 1,
          why: 'Debit valuation adjustment reflects the firm’s own default probability on its derivative liabilities, so a deteriorating own credit produces an accounting gain.',
          ref: 'Counterparty risk, CVA/DVA/FVA and wrong-way risk',
        },
        {
          text: 'Close-out netting reduces counterparty exposure by:',
          given: null,
          opts: [
            'Requiring collateral against each trade individually',
            'Allowing positive and negative mark-to-market positions with the same counterparty to be offset into a single claim on default',
            'Transferring the trades to a central counterparty',
            'Reducing the notional of each trade',
          ],
          a: 1,
          why: 'Without enforceable netting a defaulting counterparty’s administrator can enforce the in-the-money trades and disclaim the others. Netting collapses them to one net figure.',
          ref: 'Netting, collateral and margining',
        },
        {
          text: 'An investor long the equity tranche of a synthetic CDO is best described as:',
          given: null,
          opts: [
            'Long default correlation',
            'Short default correlation',
            'Neutral to default correlation',
            'Long only the individual default probabilities',
          ],
          a: 0,
          why: 'Higher correlation raises the probability that no defaults occur at all, which is the equity tranche’s best outcome. Senior tranches are the other side of that trade.',
          ref: 'Securitisation, structured credit and CDOs',
        },
        {
          text: 'A five-year CDS on a reference entity trades at 240 basis points while the reference entity’s five-year bond trades at an asset swap spread of 180 basis points. The CDS basis is:',
          given: 'CDS 240bp; asset swap spread 180bp',
          opts: ['+60 basis points', '−60 basis points', '+420 basis points', '0'],
          a: 0,
          why: 'CDS basis is the CDS spread less the cash spread: 240 − 180 = +60 bp, a positive basis.',
          ref: 'Credit derivatives and credit default swaps',
        },
        {
          text: 'Initial margin, unlike variation margin, is designed to cover:',
          given: null,
          opts: [
            'The current mark-to-market exposure',
            'Potential future exposure over the close-out period following a default',
            'Accrued interest on the collateral',
            'The counterparty’s funding costs',
          ],
          a: 1,
          why: 'Variation margin settles today’s exposure; initial margin covers the move that could occur between the last exchange and the close-out of the portfolio.',
          ref: 'Netting, collateral and margining',
        },
      ],
    },
  ],

  'frm-p2-operational': [
    {
      slug: 'measuring-operational-risk',
      name: 'Measuring Operational Risk',
      blurb: 'RCSA, loss data, model risk, and the Basel capital approach.',
      modules: [
        'Operational risk taxonomy, RCSA and loss data collection',
        'Modelling operational risk loss distributions; capital approaches',
        'Model risk management and validation',
        'Basel operational risk framework; regulation and supervision',
      ],
      cards: [
        {
          kicker: 'INPUTS',
          title: 'Four data elements, and they disagree on purpose',
          body: 'Internal loss data, external loss data, scenario analysis and business environment and internal control factors. Internal data is relevant but thin in the tail; external data fills the tail but needs scaling; scenarios cover what has not happened yet.',
          formula: null,
          exam: 'Scenario analysis is the only element that can price a risk with no loss history at all.',
        },
        {
          kicker: 'BASEL',
          title: 'The standardised approach replaced the modelled one',
          body: 'Basel III replaced the advanced measurement approach with a standardised approach built from a business indicator component scaled by an internal loss multiplier. Firms no longer set their own operational capital from their own models.',
          formula: 'operational capital = BIC × ILM',
          exam: 'The reason for the change was that AMA outputs were not comparable between banks. That comparability argument is the examinable point.',
        },
        {
          kicker: 'MODEL RISK',
          title: 'Three sources, and validation must address all three',
          body: 'A model can be conceptually wrong, implemented wrong, or used wrongly. Effective validation covers conceptual soundness, ongoing monitoring including benchmarking, and outcomes analysis — and is performed independently of the model’s developers.',
          formula: null,
          exam: 'Using a correct model outside the range it was calibrated for is a use failure, not a design failure.',
        },
      ],
      questions: [
        {
          text: 'A bank faces a risk with no internal loss history — a novel cyber-extortion scenario. The most appropriate data element is:',
          given: null,
          opts: [
            'Internal loss data',
            'Scenario analysis',
            'Business environment and internal control factors alone',
            'The business indicator component',
          ],
          a: 1,
          why: 'Scenario analysis exists precisely to price risks that have not yet produced a loss at the firm.',
          ref: 'Operational risk taxonomy, RCSA and loss data collection',
        },
        {
          text: 'Under the Basel III standardised approach, operational risk capital is driven by:',
          given: null,
          opts: [
            'The bank’s own advanced measurement model',
            'A business indicator component scaled by an internal loss multiplier',
            'Gross income alone',
            'Risk-weighted assets for credit risk',
          ],
          a: 1,
          why: 'The advanced measurement approach was withdrawn because outputs were not comparable across banks. The standardised approach uses a prescribed size measure adjusted for loss history.',
          ref: 'Basel operational risk framework; regulation and supervision',
        },
        {
          text: 'A pricing model calibrated for interest rates between 1% and 6% is applied to a negative-rate environment. This is best described as:',
          given: null,
          opts: [
            'A conceptual soundness failure',
            'A model use failure — correct model, applied outside its calibrated range',
            'An implementation error',
            'A data quality failure',
          ],
          a: 1,
          why: 'The model may be sound and correctly coded. Applying it outside the domain it was validated for is a use failure, and validation should have set that boundary explicitly.',
          ref: 'Model risk management and validation',
        },
        {
          text: 'Effective model validation must be:',
          given: null,
          opts: [
            'Performed by the model developers, who understand it best',
            'Independent of the development function, and cover conceptual soundness, ongoing monitoring and outcomes analysis',
            'Limited to code review',
            'Performed once, at implementation',
          ],
          a: 1,
          why: 'Independence is the control. Validation that reports to the developers reproduces their assumptions rather than challenging them.',
          ref: 'Model risk management and validation',
        },
        {
          text: 'External operational loss data must be scaled before use in a bank’s own model principally because:',
          given: null,
          opts: [
            'It is reported in different currencies',
            'The reporting firms differ in size, business mix and control environment',
            'It is collected annually rather than daily',
            'It excludes near-misses',
          ],
          a: 1,
          why: 'A loss of a given size means something different at a firm ten times larger with a different business mix. Scaling adjusts for that before the data enters the tail estimate.',
          ref: 'Modelling operational risk loss distributions; capital approaches',
        },
        {
          text: 'A risk and control self-assessment differs from loss data collection in that RCSA is:',
          given: null,
          opts: [
            'Backward looking and quantitative',
            'Forward looking and judgement-based, assessing inherent and residual risk against controls',
            'A regulatory filing',
            'Performed only by internal audit',
          ],
          a: 1,
          why: 'RCSA asks the business what could go wrong and how well controls mitigate it. Loss data records what already did.',
          ref: 'Operational risk taxonomy, RCSA and loss data collection',
        },
      ],
    },
    {
      slug: 'resilience-cyber-and-crime',
      name: 'Resilience, Cyber & Financial Crime',
      blurb: 'Third parties, continuity, sanctions and laundering — the risks with no P&L line.',
      modules: [
        'Cyber risk and information security; third-party and outsourcing risk',
        'Business continuity and operational resilience',
        'Financial crime: money laundering, sanctions and fraud',
        'Risk governance, risk appetite and the three lines of defence',
        'Stress testing and enterprise risk management',
      ],
      cards: [
        {
          kicker: 'RESILIENCE',
          title: 'Resilience is about important business services, not systems',
          body: 'Supervisors ask firms to identify services whose disruption would harm customers or market integrity, set impact tolerances for each, map the people, processes and third parties behind them, and test against severe but plausible scenarios.',
          formula: null,
          exam: 'An impact tolerance is a maximum tolerable disruption stated in time or volume, set per service. It is not a recovery time objective for a server.',
        },
        {
          kicker: 'THIRD PARTY',
          title: 'Outsourcing the activity never outsources the accountability',
          body: 'A firm remains responsible for an outsourced function. Concentration risk is the harder problem: many firms depending on the same cloud provider or the same market data vendor creates a systemic single point of failure no individual firm can diversify away.',
          formula: null,
          exam: 'A fourth-party dependency — your vendor’s vendor — is the one firms most often fail to map.',
        },
        {
          kicker: 'CRIME',
          title: 'Three stages, and detection is easiest at the first',
          body: 'Placement puts criminal proceeds into the system, layering obscures the trail through complex transfers, integration returns apparently legitimate funds. Controls concentrate on placement because layering across jurisdictions is far harder to unpick.',
          formula: null,
          exam: 'Sanctions is strict liability in most regimes: intent is no defence, which is why screening is preventive rather than detective.',
        },
      ],
      questions: [
        {
          text: 'Under an operational resilience framework, an impact tolerance is best described as:',
          given: null,
          opts: [
            'The recovery time objective for a critical server',
            'The maximum tolerable disruption to an important business service, expressed in time or volume',
            'The firm’s overall risk appetite statement',
            'The capital held against operational risk',
          ],
          a: 1,
          why: 'Impact tolerances are set per important business service and measured from the customer’s or market’s perspective, not from the technology’s.',
          ref: 'Business continuity and operational resilience',
        },
        {
          text: 'A bank outsources its payment processing to a specialist provider. Responsibility for the resilience of that service:',
          given: null,
          opts: [
            'Transfers to the provider under the contract',
            'Remains with the bank, which must oversee the provider and plan for its failure',
            'Transfers to the regulator',
            'Is shared equally by contract',
          ],
          a: 1,
          why: 'Accountability cannot be outsourced. The contract allocates cost and remedy; it does not move the regulatory obligation.',
          ref: 'Cyber risk and information security; third-party and outsourcing risk',
        },
        {
          text: 'Several large banks rely on the same cloud provider for core services. The resulting risk is best described as:',
          given: null,
          opts: [
            'Idiosyncratic operational risk at each bank',
            'Concentration risk with systemic implications that no single firm can diversify away',
            'Market risk',
            'Model risk',
          ],
          a: 1,
          why: 'A common dependency turns an individual firm’s outage into a market-wide one. Diversification at the firm level does not address a shared single point of failure.',
          ref: 'Cyber risk and information security; third-party and outsourcing risk',
        },
        {
          text: 'Complex transfers between accounts in multiple jurisdictions, designed to obscure the origin of funds, describe which stage of money laundering?',
          given: null,
          opts: ['Placement', 'Layering', 'Integration', 'Structuring'],
          a: 1,
          why: 'Layering is the stage that breaks the audit trail. Placement is entry into the system; integration is the apparently legitimate re-emergence.',
          ref: 'Financial crime: money laundering, sanctions and fraud',
        },
        {
          text: 'A firm inadvertently processes a payment for a sanctioned party despite having no intent to breach. In most sanctions regimes the firm:',
          given: null,
          opts: [
            'Has no liability, because intent is required',
            'May still be liable, because sanctions breaches are generally strict liability',
            'Is liable only if the amount exceeds a threshold',
            'Is liable only if the payment completes',
          ],
          a: 1,
          why: 'Strict liability is why screening controls are preventive. "We did not know" is not a defence, which changes how the control must be designed.',
          ref: 'Financial crime: money laundering, sanctions and fraud',
        },
        {
          text: 'A firm-wide stress test differs from a scenario analysis performed by a single desk principally in that it:',
          given: null,
          opts: [
            'Uses more severe shocks',
            'Applies a consistent scenario across risk types and businesses, capturing interactions the desks cannot see',
            'Is required annually',
            'Excludes operational risk',
          ],
          a: 1,
          why: 'The value of a firm-wide test is coherence: the same macro path applied everywhere reveals concentrations and second-order effects that desk-level work misses.',
          ref: 'Stress testing and enterprise risk management',
        },
      ],
    },
  ],

  'frm-p2-liquidity': [
    {
      slug: 'funding-and-market-liquidity',
      name: 'Funding & Market Liquidity',
      blurb: 'Two different risks with one name, liquidity-adjusted VaR, and the spiral.',
      modules: [
        'Liquidity risk: funding vs market liquidity',
        'Liquidity-adjusted VaR and transaction cost measurement',
        'Cash flow modelling and liquidity stress testing',
        'Intraday, collateral and contingent liquidity management',
      ],
      cards: [
        {
          kicker: 'TWO RISKS',
          title: 'Funding liquidity is about you; market liquidity is about the asset',
          body: 'Funding liquidity risk is the inability to meet obligations as they fall due. Market liquidity risk is the inability to sell an asset near its fair value. They interact viciously: a funding shortfall forces sales, sales move prices, losses trigger margin calls.',
          formula: null,
          exam: 'That interaction is the liquidity spiral, and every liquidity-driven failure in the curriculum is an instance of it.',
        },
        {
          kicker: 'LVAR',
          title: 'Add the cost of getting out to the cost of being wrong',
          body: 'Liquidity-adjusted VaR adds an exit cost to the VaR figure — commonly half the bid-offer spread times position value, widened by a multiple of the spread’s own volatility in a stress.',
          formula: 'LVaR = VaR + 0.5 × spread × position value',
          exam: 'The endogenous version also stretches the liquidation horizon for a position large relative to daily volume.',
        },
        {
          kicker: 'INTRADAY',
          title: 'A bank can be solvent, funded for the day, and still fail at noon',
          body: 'Intraday liquidity is a separate discipline: payment systems settle in real time, and a queued outflow with no incoming funds is a default even if the end-of-day position is comfortable. Collateral must be in the right place, in the right form, at the right hour.',
          formula: null,
          exam: 'Contingent liquidity — committed facilities and a contingency funding plan — is the answer to a stress that has already started.',
        },
      ],
      questions: [
        {
          text: 'A fund holds assets that are fundamentally sound but must sell into a thin market to meet redemptions, realising prices well below fair value. This is most directly:',
          given: null,
          opts: [
            'Credit risk',
            'Market liquidity risk crystallised by funding liquidity pressure',
            'Operational risk',
            'Model risk',
          ],
          a: 1,
          why: 'Redemptions create the funding need; the thin market turns that need into a realised loss. The two together are the liquidity spiral.',
          ref: 'Liquidity risk: funding vs market liquidity',
        },
        {
          text: 'A position worth 40 million has a one-day 99% VaR of 1.2 million and trades at a bid-offer spread of 0.60%. Liquidity-adjusted VaR using the half-spread is closest to:',
          given: 'position 40m; VaR 1.2m; spread 0.60%',
          opts: ['1.32 million', '1.44 million', '1.20 million', '1.56 million'],
          a: 0,
          why: 'Exit cost = 0.5 × 0.006 × 40m = 120,000. LVaR = 1.2m + 0.12m = 1.32 million.',
          ref: 'Liquidity-adjusted VaR and transaction cost measurement',
        },
        {
          text: 'A bank meets its end-of-day liquidity requirements comfortably but fails to settle a large payment at 11am. This is a failure of:',
          given: null,
          opts: [
            'Structural liquidity',
            'Intraday liquidity management',
            'Capital adequacy',
            'Net stable funding',
          ],
          a: 1,
          why: 'Real-time settlement means obligations fall due through the day. An end-of-day surplus does not settle an 11am payment.',
          ref: 'Intraday, collateral and contingent liquidity management',
        },
        {
          text: 'Endogenous liquidity risk, as distinct from exogenous, arises when:',
          given: null,
          opts: [
            'The market-wide bid-offer spread widens for everyone',
            'The position is large relative to normal traded volume, so liquidating it moves the price',
            'The central bank withdraws a facility',
            'The exchange halts trading',
          ],
          a: 1,
          why: 'Exogenous liquidity is a property of the market. Endogenous liquidity is a property of your position size within it.',
          ref: 'Liquidity-adjusted VaR and transaction cost measurement',
        },
        {
          text: 'A contingency funding plan is most useful when it:',
          given: null,
          opts: [
            'Lists the firm’s committed facilities',
            'Specifies triggers, named decision-makers, and the sequence of actions, tested before a stress',
            'Sets the liquidity coverage ratio target',
            'Is filed with the regulator annually',
          ],
          a: 1,
          why: 'A plan is only worth anything if the decisions are pre-made and rehearsed. Assembling the committee during the run is what fails.',
          ref: 'Intraday, collateral and contingent liquidity management',
        },
        {
          text: 'In a liquidity stress test, the most appropriate treatment of undrawn committed credit lines the bank has *granted* is to:',
          given: null,
          opts: [
            'Exclude them, since they are undrawn',
            'Assume a substantial drawdown rate, because borrowers draw exactly when the bank is stressed',
            'Treat them as a source of liquidity',
            'Net them against the bank’s own facilities',
          ],
          a: 1,
          why: 'Committed lines are contingent outflows that correlate with the stress. Treating them as dormant is how a plan understates the outflow.',
          ref: 'Cash flow modelling and liquidity stress testing',
        },
      ],
    },
    {
      slug: 'balance-sheet-irrbb-and-basel',
      name: 'Balance Sheet, IRRBB & Basel Liquidity',
      blurb: 'Transfer pricing, repo, banking-book rate risk, and the two ratios.',
      modules: [
        'Deposit and wholesale funding structures; transfer pricing',
        'Balance sheet management; repo markets',
        'Interest rate risk in the banking book (IRRBB)',
        'LCR, NSFR and the Basel liquidity framework',
        'Contingency funding plans',
      ],
      cards: [
        {
          kicker: 'RATIOS',
          title: 'LCR is thirty days; NSFR is one year',
          body: 'The liquidity coverage ratio holds high-quality liquid assets against thirty days of stressed net outflows. The net stable funding ratio requires available stable funding to cover required stable funding over a year. Both have a 100% minimum.',
          formula: 'LCR = HQLA / net stressed outflows (30d);  NSFR = ASF / RSF',
          exam: 'A bank can pass LCR and fail NSFR: plenty of liquid assets, funded far too short.',
        },
        {
          kicker: 'FTP',
          title: 'Funds transfer pricing is what stops liquidity being free',
          body: 'Charging business units for the liquidity and term of the funding they consume, and crediting them for stable funding they raise, is what makes the cost visible where the decision is made. Without it, long illiquid lending looks costless to the lender.',
          formula: null,
          exam: 'A mispriced or absent FTP regime is the standard explanation for a balance sheet that has drifted long and illiquid.',
        },
        {
          kicker: 'IRRBB',
          title: 'Two measures, and they can disagree',
          body: 'Economic value of equity measures the present-value effect of a rate shock on the whole banking book. Net interest income measures the earnings effect over one to three years. A position good for one can be bad for the other, and supervisors ask for both.',
          formula: null,
          exam: 'Behavioural assumptions — deposit stickiness, prepayment — drive both, and are where the modelling risk lives.',
        },
      ],
      questions: [
        {
          text: 'A bank holds 84 billion of high-quality liquid assets against stressed net outflows of 70 billion over thirty days. Its liquidity coverage ratio is:',
          given: 'HQLA 84bn; net stressed outflows 70bn',
          opts: ['83%', '120%', '100%', '154%'],
          a: 1,
          why: 'LCR = 84/70 = 120%, comfortably above the 100% minimum.',
          ref: 'LCR, NSFR and the Basel liquidity framework',
        },
        {
          text: 'A bank passes the LCR comfortably but reports an NSFR of 92%. This most likely indicates:',
          given: null,
          opts: [
            'Insufficient high-quality liquid assets',
            'Adequate short-term liquidity but a funding profile that is too short relative to asset maturity',
            'Excess capital',
            'A breach of the leverage ratio',
          ],
          a: 1,
          why: 'The two ratios measure different horizons. Ample HQLA with too little stable funding is exactly the thirty-day pass and one-year fail.',
          ref: 'LCR, NSFR and the Basel liquidity framework',
        },
        {
          text: 'A bank with no funds transfer pricing regime is most likely to accumulate:',
          given: null,
          opts: [
            'Excess short-dated liquid assets',
            'Long-dated illiquid lending funded short, because the funding cost is invisible to the lending unit',
            'Excess regulatory capital',
            'Too much stable retail funding',
          ],
          a: 1,
          why: 'If liquidity and term are free at the point of decision, the business writes the loans whose true funding cost nobody is charged for.',
          ref: 'Deposit and wholesale funding structures; transfer pricing',
        },
        {
          text: 'Under IRRBB, economic value of equity and net interest income can give opposite signals because:',
          given: null,
          opts: [
            'One is a regulatory measure and the other is not',
            'EVE is a present-value measure over the whole book while NII is an earnings measure over a short horizon',
            'EVE ignores the banking book',
            'NII excludes deposits',
          ],
          a: 1,
          why: 'A repricing profile that protects short-horizon earnings can leave long-dated value exposed, and the reverse. Supervisors require both for that reason.',
          ref: 'Interest rate risk in the banking book (IRRBB)',
        },
        {
          text: 'In a repo transaction, the haircut protects the cash lender against:',
          given: null,
          opts: [
            'The borrower’s operational risk',
            'A fall in collateral value between the borrower’s default and the sale of the collateral',
            'Interest rate risk on the cash leg',
            'Settlement failure at initiation',
          ],
          a: 1,
          why: 'The haircut is the cushion covering price moves over the close-out period, which is why it widens for volatile or illiquid collateral.',
          ref: 'Balance sheet management; repo markets',
        },
        {
          text: 'The behavioural assumption with the largest effect on a bank’s measured IRRBB is usually:',
          given: null,
          opts: [
            'The day count convention on term loans',
            'The assumed effective maturity of non-maturity deposits',
            'The credit spread on wholesale funding',
            'The frequency of internal reporting',
          ],
          a: 1,
          why: 'Non-maturity deposits are contractually overnight and behaviourally long. The assumed profile drives both EVE and NII, and it is the assumption that broke in 2023.',
          ref: 'Interest rate risk in the banking book (IRRBB)',
        },
      ],
    },
  ],

  'frm-p2-investment': [
    {
      slug: 'factors-and-risk-budgeting',
      name: 'Factor Theory & Risk Budgeting',
      blurb: 'What is actually being paid for, and how to allocate risk rather than capital.',
      modules: [
        'Factor theory and portfolio construction',
        'Risk budgeting and risk monitoring for investment portfolios',
        'Portfolio performance measurement and attribution',
        'Risk-adjusted performance measures',
        'Portfolio VaR and risk decomposition',
      ],
      cards: [
        {
          kicker: 'FACTORS',
          title: 'Assets are bundles of factor exposures',
          body: 'Factor theory holds that the premium is paid for bearing a factor, not for holding an asset. Two assets with the same exposures should earn the same premium, which is why factor-based allocation can dominate asset-class allocation.',
          formula: null,
          exam: 'A bad-times argument underlies every credible factor: it pays because it hurts when investors can least bear it.',
        },
        {
          kicker: 'BUDGETING',
          title: 'Allocating capital and allocating risk are different decisions',
          body: 'A 60/40 portfolio by capital is roughly 90/10 by risk contribution, because equities are far more volatile. Risk budgeting allocates marginal contributions to risk rather than money, which is what risk parity formalises.',
          formula: 'MCR_i = ∂σp/∂w_i;  contribution_i = w_i × MCR_i',
          exam: 'Component contributions sum to total portfolio risk. That identity is what makes the decomposition usable.',
        },
        {
          kicker: 'DECOMPOSE',
          title: 'Marginal, incremental and component VaR answer different questions',
          body: 'Marginal VaR is the effect of a small change in a position. Incremental VaR is the effect of adding or removing the position entirely. Component VaR is the share of total VaR attributable to it, and the components sum to the whole.',
          formula: null,
          exam: 'Incremental is the right measure for a yes-or-no decision on a trade; marginal for sizing one already being held.',
        },
      ],
      questions: [
        {
          text: 'A portfolio holds 60% equities at 18% volatility and 40% bonds at 5% volatility, with a correlation of 0.1. Its risk contribution profile is best described as:',
          given: 'w_eq 60% σ 18%; w_bd 40% σ 5%; ρ 0.1',
          opts: [
            'Balanced, since capital is close to evenly split',
            'Dominated by equities, which contribute the large majority of portfolio risk',
            'Dominated by bonds',
            'Indeterminate without expected returns',
          ],
          a: 1,
          why: 'Equity volatility is over three times bond volatility and the weight is larger, so the equity contribution to portfolio variance overwhelms the bond contribution. Capital weights badly misdescribe risk.',
          ref: 'Risk budgeting and risk monitoring for investment portfolios',
        },
        {
          text: 'A manager is deciding whether to add a new position to an existing portfolio. The most appropriate measure is:',
          given: null,
          opts: ['Marginal VaR', 'Incremental VaR', 'Component VaR', 'Undiversified VaR'],
          a: 1,
          why: 'Incremental VaR measures the change in total VaR from adding the whole position, which is exactly the decision being taken.',
          ref: 'Portfolio VaR and risk decomposition',
        },
        {
          text: 'Component VaRs for a portfolio have the property that they:',
          given: null,
          opts: [
            'Each equal the standalone VaR of the position',
            'Sum to the total portfolio VaR',
            'Are always positive',
            'Are independent of correlation',
          ],
          a: 1,
          why: 'The decomposition is additive by construction, which is what lets a risk budget be allocated across positions. A hedging position can have a negative component.',
          ref: 'Portfolio VaR and risk decomposition',
        },
        {
          text: 'A risk parity portfolio allocates so that:',
          given: null,
          opts: [
            'Capital is split equally across asset classes',
            'Each asset class contributes equally to total portfolio risk',
            'Expected returns are equalised',
            'Each asset class has the same Sharpe ratio',
          ],
          a: 1,
          why: 'Risk parity equalises risk contributions, which typically means far less capital in equities and leverage applied to the lower-volatility sleeves.',
          ref: 'Risk budgeting and risk monitoring for investment portfolios',
        },
        {
          text: 'A credible risk factor commanding a premium should, according to factor theory, have returns that are:',
          given: null,
          opts: [
            'Uncorrelated with everything',
            'Poor in bad times, when investors least want losses',
            'Positively skewed',
            'Uncorrelated with the business cycle',
          ],
          a: 1,
          why: 'A premium compensates for bearing pain when it is least tolerable. A factor that paid off in bad times would command a negative premium.',
          ref: 'Factor theory and portfolio construction',
        },
        {
          text: 'A fund reports a Sharpe ratio of 1.4 over three years and monthly returns with skewness of −2.1 and excess kurtosis of 9. The Sharpe ratio most likely:',
          given: 'Sharpe 1.4; skewness −2.1; excess kurtosis 9',
          opts: [
            'Fairly represents the risk taken',
            'Understates the risk, because it uses standard deviation and ignores the fat left tail',
            'Overstates the risk',
            'Is invalid for monthly data',
          ],
          a: 1,
          why: 'Standard deviation treats a severe left tail as ordinary variability. Strategies that sell tail risk routinely show high Sharpe ratios until the tail arrives.',
          ref: 'Risk-adjusted performance measures',
        },
      ],
    },
    {
      slug: 'hedge-funds-and-illiquid-assets',
      name: 'Hedge Funds & Illiquid Assets',
      blurb: 'Strategy exposures, the biases in the index, and valuing what does not trade.',
      modules: [
        'Hedge fund strategies, structures and risks',
        'Illiquid assets and valuation of private holdings',
      ],
      cards: [
        {
          kicker: 'INDEX BIAS',
          title: 'Three biases, all pushing the same way',
          body: 'Hedge fund indices suffer survivorship — failed funds leave; backfill — a fund joins with its good history attached; and selection — reporting is voluntary. All three inflate reported returns, typically by several percentage points a year.',
          formula: null,
          exam: 'Backfill bias is the one candidates forget. It is why an index return can exceed the average investor experience substantially.',
        },
        {
          kicker: 'EXPOSURES',
          title: 'Most hedge fund returns are factor exposures wearing a fee',
          body: 'Regressing returns on equity, credit, volatility and trend factors usually explains a large share. What remains is the alpha being paid for, and it is generally much smaller than the headline return suggests.',
          formula: null,
          exam: 'Serial correlation in reported returns is evidence of stale pricing, not of low risk.',
        },
        {
          kicker: 'ILLIQUID',
          title: 'Reported volatility of illiquid assets is an artefact',
          body: 'Marks are stale and smoothed, so measured volatility and correlation are understated and Sharpe ratios overstated. Unsmoothing — modelling the reported series as a moving average of true returns — recovers something closer to reality.',
          formula: null,
          exam: 'High first-order autocorrelation in a monthly return series is the diagnostic for smoothing.',
        },
      ],
      questions: [
        {
          text: 'A hedge fund index includes a fund’s performance history from before it began reporting. The resulting bias is:',
          given: null,
          opts: ['Survivorship bias', 'Backfill bias', 'Selection bias', 'Liquidity bias'],
          a: 1,
          why: 'Backfill bias arises because funds join an index after a good run and bring that run with them. Survivorship is about the funds that leave.',
          ref: 'Hedge fund strategies, structures and risks',
        },
        {
          text: 'A fund’s monthly returns show first-order autocorrelation of 0.42. The most likely explanation is:',
          given: 'monthly return autocorrelation 0.42',
          opts: [
            'Genuine return predictability the manager is exploiting',
            'Stale or smoothed pricing of illiquid positions',
            'High leverage',
            'A change in the benchmark',
          ],
          a: 1,
          why: 'Liquid markets do not produce autocorrelation of that size. Marks that lag reality do, and they depress measured volatility at the same time.',
          ref: 'Illiquid assets and valuation of private holdings',
        },
        {
          text: 'Unsmoothing a reported private asset return series will most likely:',
          given: null,
          opts: [
            'Raise measured volatility and correlation with public markets',
            'Lower measured volatility',
            'Leave the Sharpe ratio unchanged',
            'Remove the effect of leverage',
          ],
          a: 0,
          why: 'Unsmoothing recovers the underlying variation that averaging suppressed, which raises both volatility and correlation, and lowers the Sharpe ratio.',
          ref: 'Illiquid assets and valuation of private holdings',
        },
        {
          text: 'A gate provision in a hedge fund’s terms most directly protects:',
          given: null,
          opts: [
            'The manager’s fee income',
            'Remaining investors, by preventing forced liquidation of illiquid holdings to meet large redemptions',
            'The prime broker',
            'The fund’s auditor',
          ],
          a: 1,
          why: 'Without a gate, meeting large redemptions forces sales of the most liquid assets first, leaving remaining investors with the illiquid residue.',
          ref: 'Hedge fund strategies, structures and risks',
        },
        {
          text: 'A managed futures strategy’s return profile most closely resembles:',
          given: null,
          opts: [
            'A short straddle',
            'A long straddle — small losses in ranging markets, large gains in sustained trends',
            'A fixed-income portfolio',
            'A covered call',
          ],
          a: 1,
          why: 'Trend following loses a little repeatedly in choppy markets and earns substantially in persistent moves, which is a long-volatility, long-straddle-like payoff.',
          ref: 'Hedge fund strategies, structures and risks',
        },
        {
          text: 'A regression of a hedge fund’s returns on equity, credit and volatility factors gives an R² of 0.78. The most reasonable conclusion is that:',
          given: 'R² 0.78 against standard factors',
          opts: [
            'The fund has substantial idiosyncratic alpha',
            'Most of the return is explained by factor exposures obtainable more cheaply elsewhere',
            'The fund is market neutral',
            'The factor model is misspecified',
          ],
          a: 1,
          why: 'If four-fifths of the variation is factor exposure, the fee is being charged largely for beta. What is left is the part worth paying an alpha fee for.',
          ref: 'Hedge fund strategies, structures and risks',
        },
      ],
    },
  ],

  'frm-p2-current': [
    {
      slug: 'ai-and-digital-assets',
      name: 'AI, Machine Learning & Digital Assets',
      blurb: 'Model risk with no coefficients to read, and what a stablecoin actually is.',
      modules: [
        'Artificial intelligence and machine learning in finance',
        'Digital assets and stablecoins',
        'A rotating set of readings, replaced substantially each year',
      ],
      cards: [
        {
          kicker: 'EXPLAINABILITY',
          title: 'A model nobody can explain cannot be validated in the usual way',
          body: 'Machine learning models resist the coefficient-by-coefficient challenge that validation relies on. Governance shifts toward data lineage, outcome monitoring, challenger models and documented limits on where the model may be used.',
          formula: null,
          exam: 'Regulatory exposure is greatest in credit decisions, where explainability may be a legal requirement rather than a preference.',
        },
        {
          kicker: 'STABLECOINS',
          title: 'A peg is a promise, and promises have issuers',
          body: 'Fiat-backed coins depend on reserve quality and redemption at par — a money market fund with a blockchain. Algorithmic coins depend on market incentives and have failed repeatedly. The risk is credit and liquidity, not cryptography.',
          formula: null,
          exam: 'Reserve composition and redemption terms are the two things to ask about. Everything else follows from them.',
        },
        {
          kicker: 'CONCENTRATION',
          title: 'Common models are a new correlation channel',
          body: 'If many firms use similar models trained on similar data, they react to the same signals simultaneously. That homogeneity is a systemic concern in the same family as common third-party dependencies.',
          formula: null,
          exam: 'Herding by model is the mechanism to name when asked how AI adoption could amplify a shock.',
        },
      ],
      questions: [
        {
          text: 'A bank replaces a logistic regression credit scorecard with a gradient-boosted model. The principal new model risk management challenge is:',
          given: null,
          opts: [
            'Higher computational cost',
            'Reduced explainability, which complicates validation and may conflict with a legal duty to explain a credit decision',
            'A smaller training data requirement',
            'The absence of out-of-sample testing methods',
          ],
          a: 1,
          why: 'The predictive gain comes with opacity. In credit, explanation may be a legal obligation, which makes explainability a compliance constraint rather than a preference.',
          ref: 'Artificial intelligence and machine learning in finance',
        },
        {
          text: 'The principal risk in a fiat-backed stablecoin is best described as:',
          given: null,
          opts: [
            'Cryptographic weakness in the blockchain',
            'Credit and liquidity risk on the reserve assets, and the terms on which redemption is honoured',
            'Mining concentration',
            'Smart contract bugs',
          ],
          a: 1,
          why: 'The peg rests on an issuer holding adequate, liquid reserves and redeeming at par. That is a balance sheet question, not a cryptography one.',
          ref: 'Digital assets and stablecoins',
        },
        {
          text: 'Widespread adoption of similar machine learning models across trading firms most plausibly increases systemic risk by:',
          given: null,
          opts: [
            'Reducing market liquidity permanently',
            'Producing correlated reactions to the same signals, amplifying moves',
            'Increasing operational risk at each firm independently',
            'Raising transaction costs',
          ],
          a: 1,
          why: 'Homogeneous models trained on common data act alike at the same moment, which is herding by construction.',
          ref: 'Artificial intelligence and machine learning in finance',
        },
        {
          text: 'An algorithmic stablecoin maintains its peg through:',
          given: null,
          opts: [
            'Full reserves of short-dated government securities',
            'Market incentives and a mint-and-burn mechanism, with no external asset backing',
            'A central bank guarantee',
            'Over-collateralisation with fiat deposits',
          ],
          a: 1,
          why: 'The mechanism relies on arbitrageurs acting on incentives that hold only while confidence holds — which is why these designs have failed abruptly.',
          ref: 'Digital assets and stablecoins',
        },
        {
          text: 'Data lineage documentation matters more for machine learning models than for traditional ones principally because:',
          given: null,
          opts: [
            'Regulators require it only for AI',
            'The model’s behaviour is determined by the training data in ways that cannot be read off its parameters',
            'Training data is always larger',
            'The models are retrained less often',
          ],
          a: 1,
          why: 'With no interpretable coefficients, the data is the specification. Understanding what the model does requires understanding what it was shown.',
          ref: 'Artificial intelligence and machine learning in finance',
        },
        {
          text: 'The "current issues" section of the FRM curriculum differs from the others in that it:',
          given: null,
          opts: [
            'Carries the largest weight',
            'Is substantially replaced each year, so material more than a cycle old is unreliable',
            'Contains no quantitative content',
            'Is optional',
          ],
          a: 1,
          why: 'The readings rotate substantially each cycle. Preparing from an old reading list is the specific failure mode for this section.',
          ref: 'A rotating set of readings, replaced substantially each year',
        },
      ],
    },
    {
      slug: 'climate-and-banking-stress',
      name: 'Climate Risk & Banking Stress',
      blurb: 'Physical and transition risk, and what 2023 taught about deposits.',
      modules: [
        'Climate and transition risk',
        'Post-2023 banking-stress lessons',
        'Cyber and operational resilience',
      ],
      cards: [
        {
          kicker: 'CLIMATE',
          title: 'Physical and transition risk pull in opposite directions',
          body: 'Physical risk is damage from acute events and chronic shifts. Transition risk is the loss from policy, technology and preference changes as the economy decarbonises. A slow transition raises physical risk; a fast one raises transition risk.',
          formula: null,
          exam: 'Climate scenarios are long-horizon and deterministic rather than probabilistic, which is why they sit outside conventional stress testing.',
        },
        {
          kicker: '2023',
          title: 'Uninsured deposits ran faster than any model assumed',
          body: 'Concentrated, uninsured, digitally mobile deposits left at a speed no historical calibration contemplated, while held-to-maturity securities carried unrealised losses that only crystallised on sale. Interest rate risk in the banking book became a liquidity event.',
          formula: null,
          exam: 'The link between unrealised AFS/HTM losses and deposit flight is the mechanism to name.',
        },
        {
          kicker: 'GREENWASHING',
          title: 'A disclosure risk that is also a conduct risk',
          body: 'Overstating environmental credentials creates regulatory, litigation and reputational exposure. It is assessed like any other conduct risk — through product governance, evidence for claims, and independent challenge.',
          formula: null,
          exam: 'Treat greenwashing as misrepresentation with a climate label, not as a separate risk type.',
        },
      ],
      questions: [
        {
          text: 'A carbon tax introduced faster than expected damages the value of a bank’s loans to heavy industry. This is best classified as:',
          given: null,
          opts: ['Physical risk', 'Transition risk', 'Operational risk', 'Liquidity risk'],
          a: 1,
          why: 'Losses arising from policy, technology or preference shifts in the move to a low-carbon economy are transition risk. Physical risk is damage from the climate itself.',
          ref: 'Climate and transition risk',
        },
        {
          text: 'A bank holds a large held-to-maturity securities portfolio with substantial unrealised losses and a concentrated base of uninsured deposits. The principal risk is that:',
          given: null,
          opts: [
            'Credit losses on the securities crystallise',
            'Deposit flight forces sales that realise the unrealised losses, turning rate risk into a solvency event',
            'The securities fail to mature',
            'Operational risk in settlement rises',
          ],
          a: 1,
          why: 'Held-to-maturity accounting hides the loss only while the assets are held. A run forces the sale, and the loss appears at the worst moment.',
          ref: 'Post-2023 banking-stress lessons',
        },
        {
          text: 'Climate scenario analysis differs from conventional regulatory stress testing principally in its:',
          given: null,
          opts: [
            'Use of probabilistic loss distributions',
            'Very long horizon and reliance on deterministic pathways rather than probabilities',
            'Focus on a single quarter',
            'Exclusion of the banking book',
          ],
          a: 1,
          why: 'Climate pathways run for decades and are specified as scenarios without attached probabilities, which is why they cannot be folded into a capital calculation directly.',
          ref: 'Climate and transition risk',
        },
        {
          text: 'The 2023 episode challenged which modelling assumption most directly?',
          given: null,
          opts: [
            'Recovery rates on senior unsecured debt',
            'The behavioural stability and assumed effective maturity of non-maturity deposits',
            'Equity market correlation in a stress',
            'Operational loss severity distributions',
          ],
          a: 1,
          why: 'Deposits assumed sticky proved to be neither sticky nor slow, once they were uninsured, concentrated and movable by phone.',
          ref: 'Post-2023 banking-stress lessons',
        },
        {
          text: 'A fund markets a strategy as environmentally sustainable without evidence for the claim. This exposure is most appropriately managed as:',
          given: null,
          opts: [
            'A new and separate risk type requiring its own capital charge',
            'A conduct and misrepresentation risk, addressed through product governance and evidence for claims',
            'A market risk',
            'A credit risk on the underlying holdings',
          ],
          a: 1,
          why: 'Greenwashing is misrepresentation with a climate label. The controls are the existing conduct controls applied to the claim.',
          ref: 'Climate and transition risk',
        },
        {
          text: 'A cyber attack disables a bank’s payment processing for two days. Under an operational resilience framework the key question is whether:',
          given: null,
          opts: [
            'The attack vector was novel',
            'The disruption exceeded the impact tolerance set for that important business service',
            'The bank’s capital ratio fell',
            'The attacker was sanctioned',
          ],
          a: 1,
          why: 'Resilience is assessed against pre-set impact tolerances for named services. Whether the cause was novel does not change whether the tolerance was breached.',
          ref: 'Cyber and operational resilience',
        },
      ],
    },
  ],
};
