import { PremiumSegmentBank } from '../types';

/**
 * FRM Part II — premium segments, tranche II.
 *
 * A third segment per topic area. Part II's readings are dense enough that
 * revisiting one from a different angle is not repetition: the credit section's
 * Basel capital and stress testing reading had no coverage at all, and the market
 * section's term structure models had none either.
 */
export const FRM_P2_SEGMENTS_II: PremiumSegmentBank = {
  'frm-p2-market': [
    {
      slug: 'term-structure-and-hedging',
      name: 'Term Structure Models & Rate Hedging',
      blurb: 'Modelling the short rate, and hedging a book against moves that are not parallel.',
      modules: ['Fixed-income and term-structure models; interest rate risk hedging'],
      cards: [
        {
          kicker: 'MODELS',
          title: 'Drift, mean reversion, and whether volatility depends on the level',
          body: 'Model 1 has drift and constant volatility. Adding mean reversion pulls the rate toward a long-run level at a speed set by the reversion parameter. Level-dependent volatility — as in CIR — keeps rates positive and makes volatility fall as rates approach zero.',
          formula: 'dr = k(θ − r)dt + σ dW',
          exam: 'Higher mean reversion flattens the volatility term structure, because distant rates are pulled back toward θ.',
        },
        {
          kicker: 'KEY RATES',
          title: 'Key rate durations decompose what effective duration averages away',
          body: 'Effective duration assumes a parallel shift. A portfolio hedged to zero effective duration can still lose heavily on a steepening. Key rate durations measure sensitivity to a shift at each maturity point and sum to the effective duration.',
          formula: 'Σ key rate durations = effective duration',
          exam: 'A barbell and a bullet can share an effective duration and have opposite key rate profiles. That is the whole point.',
        },
        {
          kicker: 'HEDGE',
          title: 'Hedge the factors, not the maturities',
          body: 'Principal component analysis of curve moves gives level, slope and curvature, with level explaining most of the variance. A hedge constructed against those three factors is more robust than one built maturity by maturity, and needs fewer instruments.',
          formula: null,
          exam: 'Level typically explains 80–90% of curve variance. Slope and curvature account for most of the rest.',
        },
      ],
      questions: [
        {
          text: 'In a short rate model dr = k(θ − r)dt + σ dW, increasing the mean reversion parameter k will most likely:',
          given: null,
          opts: [
            'Raise the volatility of long-dated rates',
            'Lower the volatility of long-dated rates relative to short-dated ones',
            'Leave the volatility term structure unchanged',
            'Make negative rates impossible',
          ],
          a: 1,
          why: 'Stronger reversion pulls the rate back toward θ, so distant rates vary less. The volatility term structure slopes down more steeply.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
        {
          text: 'A portfolio has zero effective duration but key rate durations of +3.1 at two years and −3.1 at ten years. It will lose money if the curve:',
          given: 'KRD +3.1 at 2y; −3.1 at 10y; effective duration 0',
          opts: [
            'Shifts up in parallel',
            'Steepens, with ten-year yields rising relative to two-year yields',
            'Flattens',
            'Does not move',
          ],
          a: 2,
          why: 'The position is long the two-year point and short the ten-year point, so it gains on steepening and loses on flattening. A parallel shift nets to nothing.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
        {
          text: 'Principal component analysis of yield curve changes typically finds that the first component:',
          given: null,
          opts: [
            'Represents curvature and explains about 5% of variance',
            'Represents a level shift and explains the large majority of variance',
            'Represents slope and explains about half the variance',
            'Cannot be interpreted economically',
          ],
          a: 1,
          why: 'The first principal component is a near-parallel level move and typically explains 80–90% of the variance, which is why duration hedging works as well as it does.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
        {
          text: 'A model with constant volatility permits negative interest rates. Relative to a model with level-dependent volatility, this is:',
          given: null,
          opts: [
            'Always a defect',
            'A defect or a feature depending on the market — several sovereign curves have traded below zero',
            'Impossible to calibrate',
            'Equivalent to assuming mean reversion',
          ],
          a: 1,
          why: 'Negative rates were long treated as a modelling flaw and then occurred. Which model is appropriate depends on the market being modelled.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
        {
          text: 'A trader hedges a bond position by matching effective duration with a single futures contract. The residual exposure is greatest to:',
          given: null,
          opts: [
            'A small parallel shift',
            'A non-parallel move in the curve',
            'A change in the risk-free rate',
            'Credit spread compression',
          ],
          a: 1,
          why: 'A single-instrument duration hedge is calibrated to a parallel shift. Twists and butterflies are exactly what it cannot offset.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
        {
          text: 'A portfolio has key rate durations of 1.2, 2.4 and 1.9 at the two-, five- and ten-year points, and no other exposures. Its effective duration is:',
          given: 'KRDs 1.2, 2.4, 1.9',
          opts: ['1.83', '2.40', '5.50', '4.30'],
          a: 2,
          why: 'Key rate durations sum to the effective duration: 1.2 + 2.4 + 1.9 = 5.50.',
          ref: 'Fixed-income and term-structure models; interest rate risk hedging',
        },
      ],
    },
  ],

  'frm-p2-credit': [
    {
      slug: 'basel-credit-capital',
      name: 'Basel Credit Capital & Stress Testing',
      blurb: 'Standardised against internal ratings, and what a credit stress test is for.',
      modules: ['Basel credit risk capital frameworks; stress testing credit portfolios'],
      cards: [
        {
          kicker: 'APPROACHES',
          title: 'Standardised uses prescribed weights; IRB uses the bank’s own estimates',
          body: 'Under the standardised approach risk weights come from external ratings and prescribed tables. Under foundation IRB the bank estimates probability of default and the supervisor sets loss given default and exposure at default; under advanced IRB the bank estimates all three.',
          formula: null,
          exam: 'Basel III added an output floor: IRB capital cannot fall below a set percentage of the standardised result.',
        },
        {
          kicker: 'FORMULA',
          title: 'The IRB formula capitalises unexpected loss, not expected loss',
          body: 'Capital is computed from a conditional default probability at a 99.9% systemic stress, less the expected loss that is already provisioned. A correlation parameter prescribed by asset class drives how much the conditional probability exceeds the unconditional one.',
          formula: 'K = [LGD × N(stressed PD) − PD × LGD] × maturity adjustment',
          exam: 'Expected loss is deducted because it belongs in provisions. Double-counting it is the conceptual error.',
        },
        {
          kicker: 'STRESS',
          title: 'A credit stress test is a scenario, not a percentile',
          body: 'Take a coherent macro path — unemployment, growth, house prices, rates — and translate it through models into defaults, migrations, provisions and capital. The output is a capital trajectory under that path, with no probability attached, which is what makes it usable for planning.',
          formula: null,
          exam: 'Migration matters as much as default: downgrades raise risk weights and consume capital before anything defaults.',
        },
      ],
      questions: [
        {
          text: 'Under the foundation internal ratings-based approach, which parameter does the bank estimate itself?',
          given: null,
          opts: [
            'Loss given default',
            'Probability of default',
            'Exposure at default',
            'All three',
          ],
          a: 1,
          why: 'Foundation IRB lets the bank estimate PD only; the supervisor prescribes LGD and EAD. Advanced IRB permits all three.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
        {
          text: 'The Basel III output floor requires that capital computed under internal models:',
          given: null,
          opts: [
            'Exceed the bank’s economic capital',
            'Not fall below a prescribed percentage of the standardised approach result',
            'Equal the leverage ratio requirement',
            'Be recalculated quarterly',
          ],
          a: 1,
          why: 'The floor limits how far modelled capital can diverge from a comparable prescribed calculation, which was the criticism of the pre-crisis IRB regime.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
        {
          text: 'The IRB capital formula subtracts expected loss because:',
          given: null,
          opts: [
            'Expected loss is not a real cost',
            'Expected loss is covered by provisions and pricing, so capital is held against the unexpected part',
            'Expected loss is captured in the leverage ratio',
            'Supervisors require it to be ignored',
          ],
          a: 1,
          why: 'Provisions absorb expected loss. Capital exists for the dispersion around it, and counting expected loss twice would overstate the requirement.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
        {
          text: 'In a supervisory credit stress test, a scenario of rising unemployment consumes capital before any defaults occur because:',
          given: null,
          opts: [
            'Provisions are released',
            'Rating migrations raise risk weights and forward-looking provisions rise',
            'The leverage ratio changes',
            'Risk-weighted assets are held constant',
          ],
          a: 1,
          why: 'Downgrades increase risk weights and expected credit loss provisioning is forward-looking, so capital is consumed on the way into the stress rather than at the point of default.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
        {
          text: 'An exposure of 80 million has PD of 1%, LGD of 45% and the bank holds provisions equal to expected loss. Expected loss and therefore the provision is:',
          given: 'EAD 80m; PD 1%; LGD 45%',
          opts: ['360,000', '800,000', '3,600,000', '180,000'],
          a: 0,
          why: 'EL = 0.01 × 0.45 × 80,000,000 = 360,000.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
        {
          text: 'The asset correlation parameter in the IRB formula matters because it determines:',
          given: null,
          opts: [
            'The recovery rate',
            'How far the stressed conditional default probability exceeds the unconditional one, and therefore the capital charge',
            'The maturity adjustment alone',
            'The size of the output floor',
          ],
          a: 1,
          why: 'Higher assumed correlation means defaults cluster more in a systemic stress, which raises the conditional probability at the 99.9% point and the capital held against it.',
          ref: 'Basel credit risk capital frameworks; stress testing credit portfolios',
        },
      ],
    },
  ],

  'frm-p2-operational': [
    {
      slug: 'scenarios-rcsa-and-reporting',
      name: 'Scenarios, RCSA & Reporting',
      blurb: 'Running the assessment, building a scenario, and telling the board something useful.',
      modules: [
        'Operational risk taxonomy, RCSA and loss data collection',
        'Risk governance, risk appetite and the three lines of defence',
        'Stress testing and enterprise risk management',
      ],
      cards: [
        {
          kicker: 'RCSA',
          title: 'Inherent, control, residual — and only residual is compared to appetite',
          body: 'Inherent risk is the exposure before controls. Control effectiveness is assessed and evidenced. Residual risk is what remains, and it is residual risk that is measured against the stated appetite. An assessment that stops at inherent risk tells nobody what to do.',
          formula: null,
          exam: 'A control assessed as effective without evidence of testing is an assertion, not an assessment.',
        },
        {
          kicker: 'SCENARIOS',
          title: 'A scenario needs a mechanism, not just a number',
          body: 'Useful operational scenarios describe how the loss happens — which control fails, in what order, with what second-order effects — and only then size it. A number with no narrative cannot be challenged, cannot be mitigated and will not be believed.',
          formula: null,
          exam: 'Scenario analysis is the only data element that can price a risk with no loss history, which is why it dominates for cyber.',
        },
        {
          kicker: 'REPORTING',
          title: 'Key risk indicators are leading; loss data is lagging',
          body: 'A good KRI moves before the loss does — staff turnover in a control function, ageing of unreconciled items, the backlog of unpatched systems. A report full of lagging indicators describes a past the board cannot act on.',
          formula: null,
          exam: 'Thresholds and escalation paths are what turn an indicator into a control rather than a chart.',
        },
      ],
      questions: [
        {
          text: 'In a risk and control self-assessment, the risk measured against the firm’s stated appetite is:',
          given: null,
          opts: ['Inherent risk', 'Residual risk', 'Control risk', 'Expected loss'],
          a: 1,
          why: 'Appetite is about what the firm is prepared to carry after its controls operate. Inherent risk describes the exposure before them and is a sizing input, not a decision point.',
          ref: 'Operational risk taxonomy, RCSA and loss data collection',
        },
        {
          text: 'A business unit rates a control as "effective" with no record of testing in the past two years. The assessment should most appropriately be treated as:',
          given: null,
          opts: [
            'Acceptable, since the unit owns the risk',
            'Unsupported — control effectiveness requires evidence, and second-line challenge exists for this',
            'A second-line failure only',
            'Evidence that the risk is immaterial',
          ],
          a: 1,
          why: 'Self-assessment without evidence is an assertion. The second line’s role is to challenge exactly this, which is why it must be independent of the business.',
          ref: 'Risk governance, risk appetite and the three lines of defence',
        },
        {
          text: 'Which is the strongest key risk indicator for the risk of a settlement failure?',
          given: null,
          opts: [
            'The value of settlement losses in the past year',
            'The ageing profile of unreconciled breaks, with an escalation threshold',
            'The number of trades settled',
            'The size of the operational risk capital charge',
          ],
          a: 1,
          why: 'Ageing breaks precede the loss and can be acted on. Past losses and volumes are lagging or contextual, and the capital charge is an output.',
          ref: 'Risk governance, risk appetite and the three lines of defence',
        },
        {
          text: 'An operational risk scenario is documented as "a cyber incident causing a 250 million loss", with no further detail. The principal deficiency is that it:',
          given: null,
          opts: [
            'Understates the loss',
            'Describes no mechanism, so it cannot be challenged, mitigated or validated',
            'Uses the wrong distribution',
            'Should have been expressed as a percentage of revenue',
          ],
          a: 1,
          why: 'Without a causal chain there is nothing to argue with and no control to strengthen. The number is unfalsifiable and therefore useless for management.',
          ref: 'Operational risk taxonomy, RCSA and loss data collection',
        },
        {
          text: 'Under the three lines of defence, the risk management function’s role in an RCSA is to:',
          given: null,
          opts: [
            'Complete the assessment on the business’s behalf',
            'Set the framework and provide independent challenge to the business’s own assessment',
            'Audit the assessment annually',
            'Approve the residual risk rating as the risk owner',
          ],
          a: 1,
          why: 'The business owns the risk and the assessment; the second line owns the framework and the challenge; the third line provides assurance over both.',
          ref: 'Risk governance, risk appetite and the three lines of defence',
        },
        {
          text: 'A firm-wide stress test integrates credit, market and operational scenarios on a single macro path. Its advantage over separate exercises is that it:',
          given: null,
          opts: [
            'Requires less data',
            'Reveals interactions and concentrations that each risk type, assessed alone, reports as tolerable',
            'Produces a lower capital requirement',
            'Replaces the need for risk appetite',
          ],
          a: 1,
          why: 'Coherence is the point. The same downturn that raises credit losses also widens spreads and strains operations, and only a joint scenario shows the combined effect.',
          ref: 'Stress testing and enterprise risk management',
        },
      ],
    },
  ],

  'frm-p2-liquidity': [
    {
      slug: 'liquidity-stress-and-planning',
      name: 'Liquidity Stress Testing & Planning',
      blurb:
        'Building the cash flow ladder, choosing the assumptions, and the plan for when it happens.',
      modules: [
        'Cash flow modelling and liquidity stress testing',
        'Contingency funding plans',
        'Deposit and wholesale funding structures; transfer pricing',
      ],
      cards: [
        {
          kicker: 'LADDER',
          title: 'A cash flow ladder is contractual maturity plus behaviour',
          body: 'Contractual dates are the starting point and almost never the answer: deposits stay longer than overnight, revolvers get drawn, and assets that could be sold may not be saleable. The behavioural overlay is where the judgement and the error both live.',
          formula:
            'cumulative net cash flow by bucket = inflows − outflows + counterbalancing capacity',
          exam: 'Counterbalancing capacity is the unencumbered liquid assets that can be monetised, after haircut, in each bucket.',
        },
        {
          kicker: 'ASSUMPTIONS',
          title: 'The scenario is a set of run-off rates, and they are the whole answer',
          body: 'Retail insured deposits run slowly; uninsured corporate deposits run fast; wholesale funding does not roll at all. Committed lines granted to customers draw down precisely when the bank is stressed, because the customers are stressed too.',
          formula: null,
          exam: 'Undrawn committed lines the bank has granted are contingent *outflows*. Treating them as dormant understates the stress.',
        },
        {
          kicker: 'PLAN',
          title: 'A contingency funding plan is a set of pre-made decisions',
          body: 'Triggers that escalate automatically, named decision-makers, a sequenced list of actions from cheapest to most damaging, and pre-tested operational capability to execute each. Assembling a committee during a run is the failure mode the plan exists to prevent.',
          formula: null,
          exam: 'The plan must be tested. An untested plan is a document, and documents do not raise funding.',
        },
      ],
      questions: [
        {
          text: 'In a liquidity stress test, undrawn committed credit lines the bank has granted to corporate customers should be treated as:',
          given: null,
          opts: [
            'Ignored, since they are undrawn',
            'Contingent outflows with a substantial assumed drawdown, because customers draw when they are stressed',
            'Inflows, since they generate fee income',
            'Counterbalancing capacity',
          ],
          a: 1,
          why: 'Drawdowns correlate with the stress being modelled. Treating the lines as dormant removes one of the largest outflows from the scenario.',
          ref: 'Cash flow modelling and liquidity stress testing',
        },
        {
          text: 'Which funding source should be assigned the fastest run-off rate in a severe stress scenario?',
          given: null,
          opts: [
            'Insured retail deposits',
            'Uninsured corporate deposits held by a small number of counterparties',
            'Five-year senior unsecured debt',
            'Equity',
          ],
          a: 1,
          why: 'Concentrated, uninsured and digitally mobile deposits have proved to be the fastest-moving liability a bank has, as 2023 demonstrated.',
          ref: 'Deposit and wholesale funding structures; transfer pricing',
        },
        {
          text: 'Counterbalancing capacity in a liquidity ladder means:',
          given: null,
          opts: [
            'Total assets on the balance sheet',
            'Unencumbered liquid assets that can be monetised in the bucket, net of haircuts',
            'The bank’s regulatory capital',
            'Committed lines the bank has received but not drawn, at full face value',
          ],
          a: 1,
          why: 'Only assets that are both unencumbered and realisable in the relevant timeframe count, and they count after the haircut the market would apply under stress.',
          ref: 'Cash flow modelling and liquidity stress testing',
        },
        {
          text: 'A contingency funding plan lists available actions but names no triggers and no decision-makers. Its principal weakness is that:',
          given: null,
          opts: [
            'It omits the regulatory ratios',
            'The decisions still have to be made under stress, which is what the plan was supposed to prevent',
            'It is too long',
            'It does not quantify the cost of each action',
          ],
          a: 1,
          why: 'The value of the plan is in decisions pre-made and rehearsed. A menu with no trigger and no owner defers the hard part to the worst moment.',
          ref: 'Contingency funding plans',
        },
        {
          text: 'A funds transfer pricing regime that charges all business units the same rate regardless of the tenor of the assets they originate will most likely:',
          given: null,
          opts: [
            'Encourage short-dated lending',
            'Subsidise long-dated illiquid lending at the expense of short-dated business',
            'Have no behavioural effect',
            'Raise the net stable funding ratio',
          ],
          a: 1,
          why: 'A flat rate under-charges the long end and over-charges the short end, so the balance sheet drifts long and illiquid without anyone deciding that it should.',
          ref: 'Deposit and wholesale funding structures; transfer pricing',
        },
        {
          text: 'A bank’s cumulative net cash position is positive in every bucket out to one month but negative at three months. The appropriate conclusion is that:',
          given: null,
          opts: [
            'The bank has no liquidity issue, since the first month is covered',
            'A survival horizon exists but ends before three months, which must be addressed through funding tenor or asset liquidity',
            'The LCR must be below 100%',
            'The stress scenario is too severe to be useful',
          ],
          a: 1,
          why: 'The ladder identifies where the gap opens. Covering one month says nothing about the quarter, and the remedy is a change to funding profile or liquid asset holdings.',
          ref: 'Cash flow modelling and liquidity stress testing',
        },
      ],
    },
  ],

  'frm-p2-investment': [
    {
      slug: 'performance-and-attribution',
      name: 'Performance Measurement & Attribution',
      blurb: 'Decomposing a return, and judging whether the risk taken was worth it.',
      modules: [
        'Portfolio performance measurement and attribution',
        'Risk-adjusted performance measures',
      ],
      cards: [
        {
          kicker: 'DECOMPOSE',
          title: 'Allocation, selection, interaction — and currency, if there is any',
          body: 'Allocation is the effect of sector weights; selection is the effect of security choice within sectors; interaction is the cross-term. For an international portfolio, currency is a fourth effect and should be reported separately from the local return.',
          formula: 'allocation = Σ(wp − wb)(Rb,i − Rb)',
          exam: 'An overweight to a sector that beat the total benchmark is a positive allocation effect, whatever the stocks inside it did.',
        },
        {
          kicker: 'RATIOS',
          title: 'Pick the denominator that matches the question',
          body: 'Sharpe divides by total risk and suits a whole portfolio. Treynor divides by beta and suits a component. The information ratio divides active return by tracking error and compares managers against a benchmark. Sortino divides by downside deviation where only shortfall matters.',
          formula: 'IR = (Rp − Rb)/tracking error',
          exam: 'The information ratio is unaffected by levering the active position, which is what makes it the comparison measure.',
        },
        {
          kicker: 'LIMITS',
          title: 'Every ratio using standard deviation is blind to the shape of the tail',
          body: 'A strategy that sells options has a high Sharpe ratio until the tail arrives, because standard deviation treats a catastrophic left tail as ordinary variability. Skewness, kurtosis and maximum drawdown belong beside the ratio, not in a footnote.',
          formula: null,
          exam: 'A high Sharpe ratio with strong negative skew and high kurtosis is the signature of a short-volatility strategy.',
        },
      ],
      questions: [
        {
          text: 'A manager underweights a sector by 4 percentage points. The sector returned 12% against a total benchmark return of 7%. The allocation effect is:',
          given: 'underweight −4pp; sector benchmark return 12%; total benchmark 7%',
          opts: ['−0.20%', '+0.20%', '−0.48%', '+0.48%'],
          a: 0,
          why: '(wp − wb)(Rb,i − Rb) = (−0.04)(0.12 − 0.07) = −0.0020, or −0.20%. Underweighting an outperforming sector costs.',
          ref: 'Portfolio performance measurement and attribution',
        },
        {
          text: 'A portfolio returned 10.8% with a standard deviation of 12% and a beta of 0.85. The risk-free rate is 3%. Its Treynor ratio is closest to:',
          given: 'Rp 10.8%; σ 12%; β 0.85; Rf 3%',
          opts: ['0.065', '0.092', '0.127', '0.650'],
          a: 1,
          why: '(10.8% − 3%)/0.85 = 7.8/0.85 = 9.18, expressed as 0.092 in decimal terms.',
          ref: 'Risk-adjusted performance measures',
        },
        {
          text: 'A fund reports a Sharpe ratio of 2.1 over four years, monthly skewness of −3.0 and a maximum drawdown of 42% in a single month. The most reasonable conclusion is that:',
          given: 'Sharpe 2.1; skewness −3.0; max drawdown 42%',
          opts: [
            'The fund has exceptional risk-adjusted returns',
            'The Sharpe ratio is understating the risk, because standard deviation cannot see a tail of that shape',
            'The drawdown must be a data error',
            'Skewness is irrelevant to the Sharpe ratio',
          ],
          a: 1,
          why: 'Standard deviation treats a 42% single-month loss as one more observation. The high ratio and the severe left tail are the same strategy described two ways.',
          ref: 'Risk-adjusted performance measures',
        },
        {
          text: 'Two managers have information ratios of 0.55 and 0.80 with tracking errors of 6% and 2% respectively. For an investor who can scale the active position freely, the better manager is:',
          given: 'IR 0.55 with TE 6%; IR 0.80 with TE 2%',
          opts: [
            'The first, because it takes more active risk',
            'The second, because the information ratio is the scale-free measure of skill',
            'They are equivalent',
            'Indeterminate without the benchmark return',
          ],
          a: 1,
          why: 'Scaling the active position scales return and risk together, leaving the ratio unchanged. The higher ratio offers the better opportunity set at any chosen risk level.',
          ref: 'Risk-adjusted performance measures',
        },
        {
          text: 'In attributing the return of an international equity portfolio, currency effects should most appropriately be:',
          given: null,
          opts: [
            'Combined with security selection',
            'Reported as a separate effect alongside the local-currency allocation and selection effects',
            'Excluded, since they are not the manager’s decision',
            'Netted against the benchmark return',
          ],
          a: 1,
          why: 'Currency is a distinct decision, often taken by a different party under a hedging policy. Merging it into selection makes both effects uninterpretable.',
          ref: 'Portfolio performance measurement and attribution',
        },
        {
          text: 'A portfolio’s total attribution shows allocation +0.9%, selection −0.3% and interaction +0.1%. Its active return was:',
          given: 'allocation +0.9%; selection −0.3%; interaction +0.1%',
          opts: ['+0.50%', '+0.70%', '+1.30%', '−0.30%'],
          a: 1,
          why: '0.9 − 0.3 + 0.1 = +0.70%. The effects sum to the active return, which is the identity that makes the decomposition usable.',
          ref: 'Portfolio performance measurement and attribution',
        },
      ],
    },
  ],

  'frm-p2-current': [
    {
      slug: 'cyber-resilience-in-practice',
      name: 'Cyber Resilience in Practice',
      blurb: 'Attack paths, third parties, recovery, and what supervisors now expect.',
      modules: [
        'Cyber and operational resilience',
        'A rotating set of readings, replaced substantially each year',
      ],
      cards: [
        {
          kicker: 'PATHS',
          title: 'Most incidents arrive through credentials or through a supplier',
          body: 'Phishing and credential theft, unpatched externally facing systems, and compromise of a third party with privileged access account for the large majority. Sophisticated novel exploits make the headlines; ordinary hygiene failures make the losses.',
          formula: null,
          exam: 'Privileged access management and multi-factor authentication are the controls that address the dominant paths.',
        },
        {
          kicker: 'RECOVERY',
          title: 'Backups only count if they are immutable, isolated and tested',
          body: 'Ransomware targets backups first. A backup on the same network with the same credentials is not a backup. Recovery capability is proven by restoring, on a schedule, under timed conditions — not by the existence of a backup policy.',
          formula: null,
          exam: 'Recovery time and recovery point objectives are commitments about the *service*, and must be consistent with its impact tolerance.',
        },
        {
          kicker: 'EXPECTATION',
          title: 'Supervisors have moved from prevention to assumed compromise',
          body: 'The current framing is that a severe incident will occur, and the question is whether important business services stay inside their impact tolerances through it. That shifts investment from perimeter defence toward detection, segmentation, recovery and substitutability.',
          formula: null,
          exam: 'Mapping the people, processes and third parties behind each important business service is the precondition for all of it.',
        },
      ],
      questions: [
        {
          text: 'A bank maintains nightly backups on network-attached storage using the same domain credentials as its production systems. Against a ransomware incident this is:',
          given: null,
          opts: [
            'Adequate, since backups exist',
            'Inadequate — the backups are reachable with the same compromised credentials and will be encrypted too',
            'Adequate if backups are taken twice daily',
            'Adequate provided the data is encrypted at rest',
          ],
          a: 1,
          why: 'Ransomware operators target backups first. Isolation and immutability are what make a backup a recovery capability rather than another copy to lose.',
          ref: 'Cyber and operational resilience',
        },
        {
          text: 'Under an operational resilience framework, the question asked after a two-day outage of a payment service is whether:',
          given: null,
          opts: [
            'The attack vector was previously known',
            'The disruption breached the impact tolerance set for that important business service',
            'The firm’s capital ratio fell',
            'The attacker has been identified',
          ],
          a: 1,
          why: 'Resilience is assessed against pre-set tolerances for named services. Novelty of the cause does not change whether the tolerance held.',
          ref: 'Cyber and operational resilience',
        },
        {
          text: 'Which control most directly addresses the most common cyber intrusion paths into a financial institution?',
          given: null,
          opts: [
            'An annual penetration test',
            'Multi-factor authentication combined with privileged access management and timely patching',
            'Cyber insurance',
            'A longer password policy',
          ],
          a: 1,
          why: 'Credential compromise and unpatched external systems dominate the incident data. These three controls attack exactly those paths.',
          ref: 'Cyber and operational resilience',
        },
        {
          text: 'A firm’s most critical trading platform is supplied by a vendor who in turn depends on a single cloud region. The firm has assessed the vendor but not the vendor’s dependencies. The gap is:',
          given: null,
          opts: [
            'Immaterial, since the contract is with the vendor',
            'Fourth-party concentration risk, which the firm has not mapped and cannot mitigate unknowingly',
            'A capital adequacy issue',
            'A market risk',
          ],
          a: 1,
          why: 'Accountability for the service does not stop at the first supplier. An unmapped dependency two steps out is a single point of failure nobody has priced.',
          ref: 'Cyber and operational resilience',
        },
        {
          text: 'Supervisory expectations have shifted from preventing incidents toward assuming compromise. The most direct consequence for investment is:',
          given: null,
          opts: [
            'Less spending on security overall',
            'More on detection, segmentation, tested recovery and substitutability, relative to perimeter defence',
            'More on cyber insurance alone',
            'A shift of accountability to third parties',
          ],
          a: 1,
          why: 'If a severe incident is assumed, the measurable objective becomes how quickly and how far service is restored, which is what those four capabilities determine.',
          ref: 'Cyber and operational resilience',
        },
        {
          text: 'Cyber insurance is best understood as:',
          given: null,
          opts: [
            'A substitute for control investment',
            'A transfer of part of the financial consequence, which does not transfer the operational or regulatory consequence',
            'A regulatory requirement',
            'Full protection against business interruption',
          ],
          a: 1,
          why: 'Insurance pays some of the cost. It does not restore the service, satisfy the supervisor or repair the customer relationship, and policies exclude a great deal.',
          ref: 'Cyber and operational resilience',
        },
      ],
    },
  ],
};
