import { PremiumSegmentBank } from '../types';

/**
 * FRM Part I — premium segments.
 *
 * Part I is examined as 100 multiple-choice questions in four hours, so speed
 * matters as much as depth. These items are written to be answerable in about two
 * minutes each, with the arithmetic kept to what a candidate would actually do
 * under that clock.
 */
export const FRM_P1_SEGMENTS: PremiumSegmentBank = {
  'frm-p1-foundations': [
    {
      slug: 'governance-and-erm',
      name: 'Risk Governance & ERM',
      blurb: 'Appetite, the three lines, data aggregation, and the GARP Code.',
      modules: [
        'Risk governance: board and audit responsibilities, risk appetite, ERM',
        'Risk data aggregation and risk reporting',
        'GARP Code of Conduct',
      ],
      cards: [
        {
          kicker: 'LINES',
          title: 'Three lines of defence, and what each one actually owns',
          body: 'The business owns and takes the risk. Risk management and compliance set the framework and challenge the business. Internal audit provides independent assurance over both — which is why it reports to the board, not to the executive.',
          formula: null,
          exam: 'An audit function reporting to the CEO is a governance failure however competent it is.',
        },
        {
          kicker: 'APPETITE',
          title: 'Appetite is a board statement; limits are its implementation',
          body: 'The risk appetite statement says how much risk the firm will accept in pursuit of its strategy. Limits, triggers and escalation thresholds translate that into numbers a desk can be measured against. A statement with no limits beneath it is decoration.',
          formula: null,
          exam: 'Capacity is what the firm could survive; appetite is what it chooses to take. They are not the same number.',
        },
        {
          kicker: 'DATA',
          title: 'Aggregation failures are why crises are discovered late',
          body: 'BCBS 239 exists because firms could not answer "what is our total exposure to this counterparty" inside a day. The principles cover governance, accuracy, completeness, timeliness and adaptability — the last mattering most in a stress.',
          formula: null,
          exam: 'Adaptability is the ability to produce a report nobody planned for. That is the one a crisis actually demands.',
        },
      ],
      questions: [
        {
          text: 'Under the three lines of defence model, independent assurance over the effectiveness of the risk framework is provided by:',
          given: null,
          opts: [
            'The business units taking the risk',
            'Internal audit, reporting to the board',
            'The risk management function',
            'The external auditor only',
          ],
          a: 1,
          why: 'The third line is internal audit, and its independence comes from reporting to the board rather than to the management it reviews.',
          ref: 'Risk governance: board and audit responsibilities, risk appetite, ERM',
        },
        {
          text: 'A firm’s risk appetite statement differs from its risk capacity in that appetite is:',
          given: null,
          opts: [
            'The maximum loss the firm could absorb before failing',
            'The amount of risk the firm chooses to take in pursuit of its strategy',
            'Set by the regulator',
            'Measured only in economic capital terms',
          ],
          a: 1,
          why: 'Capacity is the survivable maximum; appetite is the chosen level within it. Confusing the two is how firms run at capacity by accident.',
          ref: 'Risk governance: board and audit responsibilities, risk appetite, ERM',
        },
        {
          text: 'A bank cannot produce a consolidated exposure to a failing counterparty within a week because positions sit in incompatible systems. This is most directly a failure of:',
          given: null,
          opts: [
            'Market risk measurement',
            'Risk data aggregation capability',
            'Credit rating methodology',
            'Model validation',
          ],
          a: 1,
          why: 'This is the BCBS 239 problem: the exposure exists and is known locally, but cannot be assembled in time to act on.',
          ref: 'Risk data aggregation and risk reporting',
        },
        {
          text: 'Enterprise risk management is best distinguished from siloed risk management by its treatment of:',
          given: null,
          opts: [
            'Regulatory capital only',
            'Interactions and concentrations across risk types and business units',
            'Operational risk exclusively',
            'The pricing of individual trades',
          ],
          a: 1,
          why: 'ERM exists to see the aggregate — correlated exposures and concentrations that each silo reports as acceptable on its own.',
          ref: 'Risk governance: board and audit responsibilities, risk appetite, ERM',
        },
        {
          text: 'Under the GARP Code of Conduct, a risk professional who discovers that a colleague is deliberately misstating a valuation should:',
          given: null,
          opts: [
            'Take no action unless asked',
            'Escalate through appropriate channels and not participate in the conduct',
            'Correct the valuation quietly without reporting it',
            'Resign immediately',
          ],
          a: 1,
          why: 'The Code requires integrity and prohibits knowing participation in misrepresentation. Escalation and dissociation are the required responses.',
          ref: 'GARP Code of Conduct',
        },
        {
          text: 'A board sets a risk appetite statement but no supporting limits or escalation triggers. The most likely consequence is that:',
          given: null,
          opts: [
            'Risk taking is effectively unconstrained at desk level',
            'Regulatory capital requirements rise automatically',
            'The firm’s economic capital falls',
            'Internal audit becomes the first line of defence',
          ],
          a: 0,
          why: 'Appetite only binds through limits that someone is measured against. Without them the statement changes no decision on any desk.',
          ref: 'Risk governance: board and audit responsibilities, risk appetite, ERM',
        },
      ],
    },
    {
      slug: 'capm-performance-and-disasters',
      name: 'CAPM, Performance & Disasters',
      blurb: 'Risk-adjusted measures, multifactor models, and what actually went wrong each time.',
      modules: [
        'CAPM and risk-adjusted performance measurement',
        'Multifactor models',
        'Financial disasters and case studies; lessons of the global financial crisis',
      ],
      cards: [
        {
          kicker: 'MEASURES',
          title: 'Four ratios, and the one the exam wants depends on the denominator',
          body: 'Sharpe divides by total risk, Treynor by beta, the information ratio by tracking error, and Jensen’s alpha is a difference rather than a ratio. M² restates Sharpe in return units by levering to benchmark volatility.',
          formula: 'M² = Rf + (Rp − Rf)(σm/σp)',
          exam: 'Read whether the portfolio is the investor’s whole holding. That single fact picks between Sharpe and Treynor.',
        },
        {
          kicker: 'FACTORS',
          title: 'Arbitrage pricing does not tell you what the factors are',
          body: 'APT requires only that returns are driven by a linear factor structure and that no arbitrage exists. It is more general than the CAPM and correspondingly less falsifiable — the factors are an empirical choice, not a result.',
          formula: 'E(Ri) = Rf + Σ βij λj',
          exam: 'λ is the factor risk premium, β the exposure. Mixing them up inverts the arithmetic.',
        },
        {
          kicker: 'DISASTERS',
          title: 'The same three failures, over and over',
          body: 'Leverage against illiquid positions, a funding structure shorter than the assets, and a control environment that could not see or would not challenge the position. Barings, LTCM, Amaranth, Lehman and Northern Rock are permutations of these.',
          formula: null,
          exam: 'Barings is rogue trading plus combined front and back office. LTCM is leverage plus liquidity plus correlation convergence.',
        },
      ],
      questions: [
        {
          text: 'A portfolio returns 11% with volatility of 16% and beta of 1.1. The risk-free rate is 3% and the market returned 9% with volatility of 13%. The portfolio’s M² is closest to:',
          given: 'Rp 11%; σp 16%; Rf 3%; Rm 9%; σm 13%',
          opts: ['9.5%', '8.2%', '11.0%', '6.5%'],
          a: 0,
          why: 'M² = Rf + (Rp − Rf)(σm/σp) = 3% + 8% × (13/16) = 3% + 6.5% = 9.5%. Levered to the market’s volatility the portfolio returns half a point more than the market’s 9%.',
          ref: 'CAPM and risk-adjusted performance measurement',
        },
        {
          text: 'Which measure is most appropriate for ranking a fund that will be one of many holdings in a well-diversified portfolio?',
          given: null,
          opts: ['Sharpe ratio', 'Treynor ratio', 'Standard deviation', 'Maximum drawdown'],
          a: 1,
          why: 'As a component, only the systematic risk it contributes is relevant, and Treynor divides excess return by beta.',
          ref: 'CAPM and risk-adjusted performance measurement',
        },
        {
          text: 'Under the arbitrage pricing theory, the expected return on a security is determined by:',
          given: null,
          opts: [
            'A single market factor only',
            'Its exposures to a set of systematic factors multiplied by each factor’s risk premium',
            'Its total volatility',
            'Its idiosyncratic risk premium',
          ],
          a: 1,
          why: 'APT prices systematic factor exposures. It does not specify what the factors are, which is both its generality and its weakness.',
          ref: 'Multifactor models',
        },
        {
          text: 'A security has exposures of 0.9 to a growth factor with a premium of 4% and 0.4 to an inflation factor with a premium of 2%. With a risk-free rate of 3%, its expected return is closest to:',
          given: 'Rf 3%; β₁ 0.9, λ₁ 4%; β₂ 0.4, λ₂ 2%',
          opts: ['7.4%', '9.0%', '6.6%', '5.8%'],
          a: 0,
          why: '3% + 0.9(4%) + 0.4(2%) = 3% + 3.6% + 0.8% = 7.4%.',
          ref: 'Multifactor models',
        },
        {
          text: 'The collapse of Barings Bank is most directly attributed to:',
          given: null,
          opts: [
            'A sovereign default',
            'A single trader controlling both the trading and settlement functions, with no independent reconciliation',
            'A failure of the value-at-risk model',
            'A liquidity run by depositors',
          ],
          a: 1,
          why: 'Combining front and back office removed the control that would have surfaced the losses. It is the canonical segregation-of-duties failure.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
        {
          text: 'The common lesson from LTCM and from the 2007–09 crisis, as regards diversification, is that:',
          given: null,
          opts: [
            'Correlations are stable through time',
            'Correlations rise sharply in a stress, so diversification fails when it is most needed',
            'Leverage reduces risk if positions are hedged',
            'Liquidity risk is fully captured by VaR',
          ],
          a: 1,
          why: 'Both episodes turned on positions that were diversified in normal conditions and became a single trade under stress, with leverage forcing liquidation into that.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
      ],
    },
  ],

  'frm-p1-quant': [
    {
      slug: 'regression-and-time-series',
      name: 'Regression & Time Series',
      blurb: 'Diagnostics that matter, and telling a trend from a unit root.',
      modules: [
        'Linear regression; multiple regression and regression diagnostics',
        'Stationary and non-stationary time series',
      ],
      cards: [
        {
          kicker: 'DIAGNOSTICS',
          title: 'What each violation breaks, and what it leaves intact',
          body: 'Heteroskedasticity and autocorrelation leave coefficients unbiased and wreck the standard errors. Omitted variables bias the coefficients themselves. Multicollinearity inflates standard errors without biasing anything.',
          formula: null,
          exam: 'White or Newey–West standard errors fix inference. Nothing fixes an omitted variable except including it.',
        },
        {
          kicker: 'STATIONARITY',
          title: 'Trend-stationary and difference-stationary need different treatments',
          body: 'A series with a deterministic trend is made stationary by removing the trend. A series with a unit root is made stationary by differencing. Applying the wrong remedy leaves the series non-stationary or over-differences it.',
          formula: 'ADF tests H₀: a unit root is present',
          exam: 'Failing to reject the ADF null means non-stationary. The null is the unit root, not stationarity — the sign of the conclusion flips if you forget.',
        },
        {
          kicker: 'MODELS',
          title: 'AR, MA and ARMA, read off the correlograms',
          body: 'An AR(p) shows a decaying autocorrelation function and a partial autocorrelation function cutting off after p. An MA(q) shows the reverse: an ACF cutting off after q and a decaying PACF.',
          formula: null,
          exam: 'Cut-off in the PACF means AR; cut-off in the ACF means MA. That mnemonic answers most identification questions.',
        },
      ],
      questions: [
        {
          text: 'A regression’s residuals show variance increasing with the fitted value. Coefficient estimates are:',
          given: null,
          opts: [
            'Biased, and standard errors are unaffected',
            'Unbiased, but standard errors are inconsistent, so t-statistics are unreliable',
            'Biased, and standard errors are inconsistent',
            'Unbiased, and inference is unaffected',
          ],
          a: 1,
          why: 'Heteroskedasticity does not bias the coefficients; it invalidates the usual standard errors. White standard errors restore valid inference.',
          ref: 'Linear regression; multiple regression and regression diagnostics',
        },
        {
          text: 'An augmented Dickey–Fuller test on a price series returns a test statistic above the critical value, failing to reject the null. The series is:',
          given: null,
          opts: [
            'Stationary',
            'Non-stationary, consistent with a unit root',
            'Trend-stationary',
            'White noise',
          ],
          a: 1,
          why: 'The ADF null is that a unit root is present. Failing to reject means the evidence is consistent with non-stationarity.',
          ref: 'Stationary and non-stationary time series',
        },
        {
          text: 'A series has an autocorrelation function that cuts off sharply after lag 2 and a slowly decaying partial autocorrelation function. It is best modelled as:',
          given: null,
          opts: ['AR(2)', 'MA(2)', 'ARMA(2,2)', 'A random walk'],
          a: 1,
          why: 'A cut-off in the ACF identifies a moving average process; the order is the lag at which it cuts off.',
          ref: 'Stationary and non-stationary time series',
        },
        {
          text: 'Omitting a variable that is correlated with an included regressor and with the dependent variable most directly causes:',
          given: null,
          opts: [
            'Heteroskedastic residuals',
            'Biased and inconsistent coefficient estimates',
            'Multicollinearity',
            'Serial correlation only',
          ],
          a: 1,
          why: 'The omitted effect loads onto the correlated included variable, biasing its coefficient. Robust standard errors do not help.',
          ref: 'Linear regression; multiple regression and regression diagnostics',
        },
        {
          text: 'Newey–West standard errors are most appropriate when residuals exhibit:',
          given: null,
          opts: [
            'Multicollinearity',
            'Both heteroskedasticity and autocorrelation',
            'Non-normality only',
            'Perfect collinearity',
          ],
          a: 1,
          why: 'Newey–West is the heteroskedasticity- and autocorrelation-consistent estimator, which is why it is the default for overlapping-return regressions.',
          ref: 'Linear regression; multiple regression and regression diagnostics',
        },
        {
          text: 'Differencing a series that is trend-stationary rather than difference-stationary will most likely:',
          given: null,
          opts: [
            'Correctly induce stationarity',
            'Over-difference the series, introducing a moving average structure into the errors',
            'Leave the series unchanged',
            'Remove heteroskedasticity',
          ],
          a: 1,
          why: 'Over-differencing manufactures negative autocorrelation in the errors and complicates the model rather than simplifying it.',
          ref: 'Stationary and non-stationary time series',
        },
      ],
    },
    {
      slug: 'volatility-and-simulation',
      name: 'Volatility, Correlation & Simulation',
      blurb: 'EWMA and GARCH, correlation estimation, and when to bootstrap.',
      modules: [
        'Measuring volatility and correlation',
        'Simulation methods and bootstrapping',
        'Machine learning and prediction',
      ],
      cards: [
        {
          kicker: 'EWMA',
          title: 'One parameter, no mean reversion',
          body: 'EWMA weights recent squared returns more heavily with decay λ and never reverts to a long-run level. RiskMetrics used λ = 0.94 for daily data. It is GARCH(1,1) with the long-run term set to zero.',
          formula: 'σ²t = λσ²t−1 + (1 − λ)r²t−1',
          exam: 'A lower λ means faster reaction and a noisier estimate. Higher λ is smoother and slower.',
        },
        {
          kicker: 'GARCH',
          title: 'Persistence is α + β, and it must be below one',
          body: 'GARCH(1,1) adds a long-run variance the process reverts to. Persistence α + β near one means shocks decay slowly; at or above one the unconditional variance does not exist and the model is misspecified.',
          formula: 'σ²t = ω + αr²t−1 + βσ²t−1;  long-run σ² = ω/(1 − α − β)',
          exam: 'Compute the long-run variance, then take its square root. Reporting variance as volatility is the standard slip.',
        },
        {
          kicker: 'RESAMPLING',
          title: 'Bootstrap when you do not trust the distribution',
          body: 'Monte Carlo draws from an assumed distribution; the bootstrap resamples the observed data and so inherits its fat tails and skew without naming them. The cost is that it can only produce events resembling those already seen.',
          formula: null,
          exam: 'A block bootstrap preserves serial dependence. A plain bootstrap destroys it, which matters for any volatility series.',
        },
      ],
      questions: [
        {
          text: 'Under EWMA with λ = 0.94, yesterday’s volatility estimate was 1.20% and yesterday’s return was −2.50%. Today’s volatility estimate is closest to:',
          given: 'λ 0.94; σt−1 1.20%; rt−1 −2.50%',
          opts: ['1.32%', '1.44%', '1.20%', '1.63%'],
          a: 0,
          why: 'σ² = 0.94(0.0120²) + 0.06(0.0250²) = 0.94(0.000144) + 0.06(0.000625) = 0.0001354 + 0.0000375 = 0.0001729; √ = 1.315%.',
          ref: 'Measuring volatility and correlation',
        },
        {
          text: 'A GARCH(1,1) model has ω = 0.000002, α = 0.06 and β = 0.92. The long-run daily volatility is closest to:',
          given: 'ω 0.000002; α 0.06; β 0.92',
          opts: ['0.71%', '1.00%', '1.41%', '0.50%'],
          a: 1,
          why: 'Long-run variance = ω/(1 − α − β) = 0.000002/0.02 = 0.0001. Volatility is its square root: √0.0001 = 0.01, or 1.00% a day. Reporting the variance as the volatility is the usual slip.',
          ref: 'Measuring volatility and correlation',
        },
        {
          text: 'A GARCH(1,1) estimation returns α + β = 1.02. The most appropriate conclusion is that:',
          given: null,
          opts: [
            'Volatility is strongly mean reverting',
            'The model is misspecified, since the unconditional variance is not defined',
            'The long-run variance is negative but usable',
            'The model reduces to EWMA',
          ],
          a: 1,
          why: 'Persistence at or above one means variance does not revert and the unconditional variance does not exist. The estimate is not usable as fitted.',
          ref: 'Measuring volatility and correlation',
        },
        {
          text: 'A risk manager wants to estimate a 99% VaR for a portfolio whose returns are visibly fat-tailed, without assuming a distribution. The most appropriate method is:',
          given: null,
          opts: [
            'Parametric VaR with a normal assumption',
            'A historical or bootstrap approach that resamples observed returns',
            'Delta-normal VaR',
            'A Monte Carlo simulation from a normal distribution',
          ],
          a: 1,
          why: 'Resampling observed data inherits the empirical tail shape. Every other option imposes the distribution the manager is trying to avoid assuming.',
          ref: 'Simulation methods and bootstrapping',
        },
        {
          text: 'A block bootstrap is preferred to a simple bootstrap when the data:',
          given: null,
          opts: [
            'Are independently and identically distributed',
            'Exhibit serial dependence, such as volatility clustering',
            'Are normally distributed',
            'Contain no outliers',
          ],
          a: 1,
          why: 'Resampling contiguous blocks preserves the dependence structure that an observation-by-observation resample would destroy.',
          ref: 'Simulation methods and bootstrapping',
        },
        {
          text: 'In a machine learning credit model, k-fold cross-validation is used principally to:',
          given: null,
          opts: [
            'Increase the size of the training set',
            'Obtain an out-of-sample performance estimate and control overfitting',
            'Remove multicollinearity among features',
            'Guarantee a linear decision boundary',
          ],
          a: 1,
          why: 'Rotating the held-out fold gives repeated out-of-sample estimates, which is how overfitting is detected and hyperparameters are chosen.',
          ref: 'Machine learning and prediction',
        },
      ],
    },
  ],

  'frm-p1-markets': [
    {
      slug: 'futures-and-hedging',
      name: 'Futures, Forwards & Hedging',
      blurb: 'Margin mechanics, the minimum-variance hedge ratio, and basis risk.',
      modules: [
        'Exchange-traded and OTC market structure, central counterparties',
        'Forwards and futures: mechanics, margin, hedge ratios, basis risk',
        'Commodity forwards and futures',
      ],
      cards: [
        {
          kicker: 'HEDGE RATIO',
          title: 'The optimal ratio is a regression slope',
          body: 'The minimum-variance hedge ratio is the correlation between spot and futures changes times the ratio of their standard deviations. A ratio of one is only correct when the hedge is perfect, which it almost never is.',
          formula: 'h* = ρ(σS/σF);  contracts = h* × QA / QF',
          exam: 'Round the contract count to a whole number and say which way you rounded — the exam’s options often differ by one contract.',
        },
        {
          kicker: 'BASIS',
          title: 'Basis risk is what is left after the hedge',
          body: 'Basis is spot minus futures. A hedge converts price risk into basis risk, and the basis moves when the hedged asset differs from the deliverable, when the dates differ, or when carry changes. It converges to zero at delivery.',
          formula: 'basis = S − F',
          exam: 'A strengthening basis helps a short hedger and hurts a long hedger. Fix the direction before answering.',
        },
        {
          kicker: 'MARGIN',
          title: 'Variation margin is a daily cash flow, not a bookkeeping entry',
          body: 'Futures settle daily against the initial margin, and a fall below maintenance margin triggers a call back to the initial level, not to the maintenance level. That difference is the whole question in most margin items.',
          formula: null,
          exam: 'A central counterparty novates the trade, replacing bilateral counterparty risk with exposure to the CCP and its default waterfall.',
        },
      ],
      questions: [
        {
          text: 'Spot price changes have a standard deviation of 0.68, futures price changes 0.81, and their correlation is 0.85. The minimum-variance hedge ratio is closest to:',
          given: 'σS 0.68; σF 0.81; ρ 0.85',
          opts: ['0.71', '0.85', '1.01', '1.19'],
          a: 0,
          why: 'h* = 0.85 × (0.68/0.81) = 0.85 × 0.8395 = 0.714.',
          ref: 'Forwards and futures: mechanics, margin, hedge ratios, basis risk',
        },
        {
          text: 'Using that hedge ratio, hedging an exposure of 120,000 units with contracts of 5,000 units requires:',
          given: 'h* 0.714; QA 120,000; QF 5,000',
          opts: ['17 contracts', '24 contracts', '12 contracts', '34 contracts'],
          a: 0,
          why: '0.714 × 120,000 / 5,000 = 17.1, so 17 contracts.',
          ref: 'Forwards and futures: mechanics, margin, hedge ratios, basis risk',
        },
        {
          text: 'A short hedger benefits when the basis:',
          given: null,
          opts: ['Weakens', 'Strengthens', 'Converges to zero', 'Becomes negative'],
          a: 1,
          why: 'The short hedger is long the asset and short futures, so a rise in spot relative to futures — a strengthening basis — improves the combined position.',
          ref: 'Forwards and futures: mechanics, margin, hedge ratios, basis risk',
        },
        {
          text: 'Initial margin is 6,000 per contract and maintenance margin is 4,500. A trader holding one contract sees the balance fall to 4,100. The variation margin call is:',
          given: 'initial 6,000; maintenance 4,500; balance 4,100',
          opts: ['400', '1,500', '1,900', '0'],
          a: 2,
          why: 'A breach of maintenance restores the account to the *initial* level: 6,000 − 4,100 = 1,900. Topping up to maintenance only would be 400, the standard distractor.',
          ref: 'Forwards and futures: mechanics, margin, hedge ratios, basis risk',
        },
        {
          text: 'A central counterparty reduces bilateral counterparty risk principally by:',
          given: null,
          opts: [
            'Guaranteeing that no member defaults',
            'Novating each trade so that the CCP becomes buyer to every seller and seller to every buyer',
            'Requiring physical delivery',
            'Publishing all trades to the market',
          ],
          a: 1,
          why: 'Novation replaces a web of bilateral exposures with exposure to the CCP, backed by margin and a default waterfall. It concentrates risk rather than removing it.',
          ref: 'Exchange-traded and OTC market structure, central counterparties',
        },
        {
          text: 'A commodity with high storage costs and negligible convenience yield will most likely show a futures curve in:',
          given: null,
          opts: ['Backwardation', 'Contango', 'A flat shape', 'Inversion at the front only'],
          a: 1,
          why: 'Cost of carry above any benefit of holding the physical puts futures above spot, which is contango.',
          ref: 'Commodity forwards and futures',
        },
      ],
    },
    {
      slug: 'institutions-swaps-and-rates',
      name: 'Institutions, Swaps & Rates',
      blurb: 'Where each institution’s risk actually sits, and valuing a swap off the curve.',
      modules: [
        'Financial institutions and their risks: banks, insurers, pension funds, mutual and hedge funds',
        'Economic vs regulatory capital; insurance company ratios',
        'Swaps: cash flows and valuation',
        'Interest rates and interest-rate products',
      ],
      cards: [
        {
          kicker: 'CAPITAL',
          title:
            'Economic capital is the firm’s own answer; regulatory capital is the supervisor’s',
          body: 'Economic capital is the amount needed to absorb losses to a chosen confidence level over a chosen horizon. Regulatory capital is a prescribed minimum. Where economic exceeds regulatory the constraint is internal, and vice versa.',
          formula: 'economic capital ≈ unexpected loss at the chosen confidence level',
          exam: 'Expected loss is provisioned and priced in. Capital exists for the unexpected part.',
        },
        {
          kicker: 'INSURERS',
          title: 'Two ratios, and the combined one is the underwriting verdict',
          body: 'Loss ratio is claims over premiums; expense ratio is expenses over premiums; the combined ratio is their sum. Above 100% the underwriting business loses money and only investment income can rescue the year.',
          formula: 'combined ratio = loss ratio + expense ratio',
          exam: 'A combined ratio of 103% with strong investment returns is still an underwriting loss. The exam asks about the underwriting.',
        },
        {
          kicker: 'SWAPS',
          title: 'Value the legs, take the difference',
          body: 'Immediately after a reset the floating leg is worth par. The fixed leg is a bond priced off the current curve. The swap’s value to the fixed payer is the floating leg less the fixed leg, on the notional.',
          formula: 'V (to payer of fixed) = B_floating − B_fixed',
          exam: 'Rates up means the fixed leg is worth less, so the fixed payer gains. Establish the direction before touching the numbers.',
        },
      ],
      questions: [
        {
          text: 'An insurer reports a loss ratio of 71% and an expense ratio of 34%. Its underwriting result is:',
          given: 'loss ratio 71%; expense ratio 34%',
          opts: [
            'A profit, with a combined ratio of 105%',
            'A loss, with a combined ratio of 105%',
            'Break-even',
            'Indeterminate without investment income',
          ],
          a: 1,
          why: 'The combined ratio is 105%, so claims and expenses exceed premiums. Investment income may rescue the year, but the underwriting lost money.',
          ref: 'Economic vs regulatory capital; insurance company ratios',
        },
        {
          text: 'A bank’s economic capital exceeds its regulatory capital requirement. This most directly implies that:',
          given: null,
          opts: [
            'The regulator has miscalculated the requirement',
            'The bank’s own risk assessment is the binding constraint on its balance sheet',
            'The bank is undercapitalised',
            'Expected losses exceed unexpected losses',
          ],
          a: 1,
          why: 'Whichever measure is larger binds. Here the internal assessment sets the capital the bank must hold above the supervisory floor.',
          ref: 'Economic vs regulatory capital; insurance company ratios',
        },
        {
          text: 'A defined benefit pension plan’s principal financial risk is best described as:',
          given: null,
          opts: [
            'Equity market risk in isolation',
            'The mismatch between asset and liability sensitivity to interest rates and longevity',
            'Operational risk in benefit administration',
            'Liquidity risk from member withdrawals',
          ],
          a: 1,
          why: 'The plan exists to meet a long-dated, rate-sensitive, longevity-sensitive liability. Surplus volatility comes from the mismatch, not from the assets alone.',
          ref: 'Financial institutions and their risks: banks, insurers, pension funds, mutual and hedge funds',
        },
        {
          text: 'Immediately after a reset date, the floating leg of a plain vanilla interest rate swap is worth:',
          given: null,
          opts: [
            'Zero',
            'Par, on the notional',
            'The present value of all expected future floating payments discounted at the fixed rate',
            'The notional times the fixed rate',
          ],
          a: 1,
          why: 'A floating rate note reprices to par at each reset, which is what makes swap valuation a matter of pricing the fixed leg alone.',
          ref: 'Swaps: cash flows and valuation',
        },
        {
          text: 'A firm pays fixed and receives floating on a swap. Market rates fall sharply. The value of the swap to the firm:',
          given: null,
          opts: ['Rises', 'Falls', 'Is unchanged', 'Depends on the day count convention'],
          a: 1,
          why: 'The fixed leg it pays becomes more valuable as rates fall, so the position loses. Paying fixed is economically being short a bond.',
          ref: 'Swaps: cash flows and valuation',
        },
        {
          text: 'An open-ended mutual fund faces a risk that a closed-ended fund does not, namely:',
          given: null,
          opts: [
            'Market risk on its holdings',
            'Redemption risk forcing asset sales at unfavourable prices',
            'Credit risk on its counterparties',
            'Operational risk in valuation',
          ],
          a: 1,
          why: 'Daily redemption at NAV means investor outflows force sales. A closed-ended fund’s investors sell to each other in the market instead.',
          ref: 'Financial institutions and their risks: banks, insurers, pension funds, mutual and hedge funds',
        },
      ],
    },
  ],

  'frm-p1-valuation': [
    {
      slug: 'var-and-stress',
      name: 'VaR, Expected Shortfall & Stress Testing',
      blurb: 'Coherence, scaling, and what a stress test is for that VaR is not.',
      modules: [
        'Value-at-Risk and Expected Shortfall; coherent risk measures',
        'Stress testing and scenario analysis',
        'Economic and regulatory capital',
      ],
      cards: [
        {
          kicker: 'COHERENCE',
          title: 'VaR fails exactly one of the four axioms',
          body: 'A coherent measure is monotonic, translation invariant, positively homogeneous and subadditive. VaR satisfies the first three and can violate subadditivity — the risk of a combined portfolio can exceed the sum of the parts. Expected shortfall does not.',
          formula: 'ES = E[loss | loss > VaR]',
          exam: 'Subadditivity is the axiom that matters for risk aggregation, because without it diversification can appear to increase risk.',
        },
        {
          kicker: 'SCALING',
          title: 'The square root of time, and the assumption hiding inside it',
          body: 'Scaling a one-day VaR to ten days by √10 assumes returns are independent and identically distributed with a zero mean. Autocorrelation or volatility clustering breaks it, usually understating the longer-horizon figure.',
          formula: 'VaR_T = VaR_1 × √T',
          exam: 'Confidence levels scale through the z-multiple, not through √T. Changing both at once is two separate steps.',
        },
        {
          kicker: 'STRESS',
          title: 'Stress testing asks a different question from VaR',
          body: 'VaR answers "how bad is a bad day at a given probability". A stress test answers "what happens in this specific scenario", with no probability attached — which is why it catches the correlated, tail, and liquidity events VaR is calibrated away from.',
          formula: null,
          exam: 'Reverse stress testing starts from the failure and works back to what would cause it. That is the one supervisors ask for.',
        },
      ],
      questions: [
        {
          text: 'A portfolio has a one-day 99% VaR of 2.4 million. Assuming returns are i.i.d. with zero mean, the ten-day 99% VaR is closest to:',
          given: 'one-day 99% VaR 2.4m; T = 10',
          opts: ['7.6 million', '24.0 million', '3.4 million', '12.0 million'],
          a: 0,
          why: '2.4 × √10 = 2.4 × 3.162 = 7.59 million.',
          ref: 'Value-at-Risk and Expected Shortfall; coherent risk measures',
        },
        {
          text: 'Which property of a coherent risk measure can value-at-risk fail?',
          given: null,
          opts: ['Monotonicity', 'Subadditivity', 'Translation invariance', 'Positive homogeneity'],
          a: 1,
          why: 'VaR can report a combined portfolio as riskier than the sum of its parts, particularly with discrete or heavily skewed loss distributions. Expected shortfall is subadditive.',
          ref: 'Value-at-Risk and Expected Shortfall; coherent risk measures',
        },
        {
          text: 'A portfolio of 80 million has an expected annual return of 6% and volatility of 20%. The 95% annual VaR, using z = 1.645, is closest to:',
          given: 'value 80m; μ 6%; σ 20%; z 1.645',
          opts: ['21.5 million', '26.3 million', '16.0 million', '31.1 million'],
          a: 0,
          why: 'VaR = −(0.06 − 1.645 × 0.20) × 80m = −(0.06 − 0.329) × 80m = 0.269 × 80m = 21.5 million.',
          ref: 'Value-at-Risk and Expected Shortfall; coherent risk measures',
        },
        {
          text: 'Expected shortfall at the 97.5% level, compared with VaR at the same level, will:',
          given: null,
          opts: [
            'Always be smaller',
            'Always be at least as large, because it averages the losses beyond the threshold',
            'Be equal for normally distributed returns',
            'Be undefined for fat-tailed distributions',
          ],
          a: 1,
          why: 'ES is the mean of the tail beyond the VaR point, so it cannot be smaller and is strictly larger whenever the tail has any mass.',
          ref: 'Value-at-Risk and Expected Shortfall; coherent risk measures',
        },
        {
          text: 'Reverse stress testing differs from conventional stress testing in that it:',
          given: null,
          opts: [
            'Uses historical scenarios only',
            'Starts from a defined failure outcome and identifies the scenarios that would produce it',
            'Assigns probabilities to each scenario',
            'Applies only to market risk',
          ],
          a: 1,
          why: 'Working backwards from failure surfaces the combinations a forward-looking scenario set would never have been asked about.',
          ref: 'Stress testing and scenario analysis',
        },
        {
          text: 'Scaling a one-day VaR to a longer horizon by the square root of time most likely understates risk when returns exhibit:',
          given: null,
          opts: [
            'Zero autocorrelation',
            'Positive autocorrelation or volatility clustering',
            'Negative skewness only',
            'A constant mean',
          ],
          a: 1,
          why: 'The scaling assumes independence. Positive dependence means shocks accumulate rather than cancel, so the true multi-day risk exceeds the scaled figure.',
          ref: 'Value-at-Risk and Expected Shortfall; coherent risk measures',
        },
      ],
    },
    {
      slug: 'credit-and-operational-models',
      name: 'Credit & Operational Risk Models',
      blurb: 'Expected and unexpected loss, transition matrices, and operational capital.',
      modules: [
        'Credit risk: expected loss, unexpected loss, credit VaR',
        'Country and sovereign risk; external ratings and rating transition matrices',
        'Operational risk: loss distributions, capital approaches, Monte Carlo estimation',
      ],
      cards: [
        {
          kicker: 'LOSS',
          title: 'Expected loss is priced; unexpected loss is capitalised',
          body: 'Expected loss is PD × LGD × EAD and belongs in the spread and the provision. Unexpected loss is the dispersion around it, and that is what economic capital covers. Credit VaR is unexpected loss at a chosen confidence level.',
          formula: 'EL = PD × LGD × EAD;  credit VaR = credit loss at confidence − EL',
          exam: 'Deducting expected loss from the credit VaR figure is the step candidates skip.',
        },
        {
          kicker: 'TRANSITIONS',
          title: 'A transition matrix is where downgrade risk comes from',
          body: 'Rows are current ratings, columns are ratings one year later, and each row sums to one. Most credit loss in a diversified portfolio arrives as migration and spread widening rather than default.',
          formula: null,
          exam: 'Multi-year probabilities come from multiplying the matrix by itself, which assumes a Markov process — an assumption that does not survive contact with rating momentum.',
        },
        {
          kicker: 'OPERATIONAL',
          title: 'Frequency and severity, convolved',
          body: 'The loss distribution approach models how often events happen and how bad each one is, then combines them by Monte Carlo into an aggregate annual loss distribution. Capital is a high quantile of that, less the expected loss.',
          formula: null,
          exam: 'Operational loss severity is heavily fat-tailed: a handful of events dominates the capital number, which is why external loss data matters.',
        },
      ],
      questions: [
        {
          text: 'A loan has exposure at default of 20 million, probability of default of 2% and loss given default of 55%. Expected loss is:',
          given: 'EAD 20m; PD 2%; LGD 55%',
          opts: ['220,000', '400,000', '1,100,000', '110,000'],
          a: 0,
          why: 'EL = 0.02 × 0.55 × 20,000,000 = 220,000.',
          ref: 'Credit risk: expected loss, unexpected loss, credit VaR',
        },
        {
          text: 'A credit portfolio’s 99.9% worst-case loss is 48 million and its expected loss is 9 million. Credit VaR at that confidence level is:',
          given: 'worst-case loss 48m; expected loss 9m',
          opts: ['48 million', '39 million', '57 million', '9 million'],
          a: 1,
          why: 'Credit VaR measures the unexpected part: 48 − 9 = 39 million. Expected loss is already provisioned.',
          ref: 'Credit risk: expected loss, unexpected loss, credit VaR',
        },
        {
          text: 'Squaring a one-year rating transition matrix to obtain two-year probabilities assumes that:',
          given: null,
          opts: [
            'Recovery rates are constant',
            'Rating migration is a Markov process, so next year’s transition depends only on the current rating',
            'Default is impossible in year one',
            'Ratings are assigned by a single agency',
          ],
          a: 1,
          why: 'Matrix multiplication embeds the Markov assumption. Rating momentum — recently downgraded issuers being more likely to be downgraded again — violates it.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
        {
          text: 'In the loss distribution approach to operational risk, aggregate annual loss is obtained by:',
          given: null,
          opts: [
            'Multiplying average frequency by average severity',
            'Convolving a frequency distribution with a severity distribution, usually by Monte Carlo',
            'Taking the largest historical loss',
            'Applying a fixed percentage of gross income',
          ],
          a: 1,
          why: 'Frequency and severity are modelled separately and combined by simulation, because the aggregate distribution has no closed form for realistic severity assumptions.',
          ref: 'Operational risk: loss distributions, capital approaches, Monte Carlo estimation',
        },
        {
          text: 'A bank supplements its internal operational loss data with an external consortium database principally because:',
          given: null,
          opts: [
            'Regulators require a minimum data volume',
            'Its own history contains too few extreme events to estimate the tail that drives capital',
            'External data is cheaper to collect',
            'Internal data is not auditable',
          ],
          a: 1,
          why: 'Operational severity is fat-tailed and capital is set by the tail. One bank’s history rarely contains enough extreme events to estimate it.',
          ref: 'Operational risk: loss distributions, capital approaches, Monte Carlo estimation',
        },
        {
          text: 'Sovereign risk in local currency differs from sovereign risk in foreign currency principally because:',
          given: null,
          opts: [
            'Local currency debt cannot default',
            'A government can create the local currency it owes, so default there is a policy choice rather than an inability to pay',
            'Foreign currency debt is always subordinated',
            'Local currency debt carries no inflation risk',
          ],
          a: 1,
          why: 'Local currency obligations can be met by issuance, at the cost of inflation and currency depreciation. Foreign currency obligations require reserves the state may not have.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
      ],
    },
  ],
};
