import { PremiumSegmentBank } from '../types';

/**
 * Tranche III — a fourth segment, allocated by exam weight rather than evenly.
 *
 * Tranches I and II gave every one of the 38 areas three segments. Spreading a
 * fourth evenly would put as much new material into Level II Economics, which is
 * 5–10% of one exam and two readings long, as into the Level III pathways, which
 * are 30–35% of a paper a candidate actually sits. So this tranche goes only to
 * areas whose published weight midpoint is 11% or above, heaviest first.
 *
 * That is a product decision and it is the honest one: candidates' time follows
 * the weights, and so should the content they are paying for.
 */
export const TRANCHE_III_SEGMENTS: PremiumSegmentBank = {
  'cfa-l3-pathway-portfolio': [
    {
      slug: 'index-strategies-and-ldi',
      name: 'Index Strategies & LDI',
      blurb: 'Replicating an index cheaply, and building a portfolio against a liability.',
      modules: ['Index-Based Equity Strategies', 'Liability-Driven and Index-Based Strategies'],
      cards: [
        {
          kicker: 'REPLICATE',
          title: 'Full replication, sampling, or a derivative — cost decides',
          body: 'Full replication tracks tightest in liquid large-cap indices. Stratified sampling and optimisation cut cost in broad or illiquid ones at the price of tracking error. A total return swap or futures gives exposure with no holdings at all, and introduces counterparty and roll considerations instead.',
          formula: null,
          exam: 'A synthetic index position has no securities to lend, which removes an income source the physical fund has.',
        },
        {
          kicker: 'LDI',
          title: 'Hedge the liability’s sensitivities, then decide how much risk to keep',
          body: 'Match the basis point value, and where the liability is inflation-linked match that exposure too. The hedge ratio is a deliberate decision: below 100% leaves surplus risk the sponsor is choosing to run, and it should be stated as a choice rather than emerge from a shortage of long bonds.',
          formula: 'BPV_assets × hedge ratio = BPV_liabilities',
          exam: 'Leverage through repo or swaps is how a plan hedges long duration without holding the whole balance sheet in bonds.',
        },
        {
          kicker: 'RESIDUALS',
          title: 'A perfect duration match still leaves three things',
          body: 'Basis risk between the liability discount curve and the asset curve; convexity mismatch on a large move; and longevity, which no financial instrument in the portfolio addresses at all.',
          formula: null,
          exam: 'Longevity risk is transferred through a buy-in, a buy-out or a longevity swap, not through the bond portfolio.',
        },
      ],
      questions: [
        {
          text: 'A pension plan hedges liability duration using interest rate swaps funded through repo rather than by holding long government bonds outright. The principal motivation is:',
          given: null,
          opts: [
            'Lower counterparty risk',
            'Capital efficiency — achieving the duration exposure without committing the whole portfolio to bonds',
            'Higher expected return on the hedge itself',
            'Avoiding the need for collateral',
          ],
          a: 1,
          why: 'Derivative-based hedging frees capital for return-seeking assets while still matching the liability sensitivity. The cost is collateral management and roll risk.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'Liabilities have a BPV of 62,000 and the asset portfolio a BPV of 24,000. To reach a 75% hedge ratio using swaps with a BPV of 110 per million notional, the required notional is closest to:',
          given:
            'liability BPV 62,000; asset BPV 24,000; target hedge ratio 75%; swap BPV 110 per million',
          opts: ['155 million', '205 million', '345 million', '564 million'],
          a: 1,
          why: 'Target asset BPV = 0.75 × 62,000 = 46,500. The gap to close is 46,500 − 24,000 = 22,500, so the notional is 22,500/110 = 205 million. Hedging to 100% rather than 75% would need 345 million, which is the next distractor.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'A plan achieves an exact duration match but discounts liabilities on a corporate curve while holding government bonds. It retains:',
          given: null,
          opts: [
            'No residual risk',
            'Basis risk between the two curves, which can be large precisely in a crisis',
            'Only longevity risk',
            'Only convexity risk',
          ],
          a: 1,
          why: 'A duration match across different curves leaves the spread between them unhedged. In a stress the spread widens and the match fails when it is most needed.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'Which risk in a defined benefit plan cannot be hedged by any instrument in the bond portfolio?',
          given: null,
          opts: ['Interest rate risk', 'Inflation risk', 'Longevity risk', 'Credit spread risk'],
          a: 2,
          why: 'Longevity is transferred through a buy-in, buy-out or longevity swap. No bond position addresses members living longer than assumed.',
          ref: 'Liability-Driven and Index-Based Strategies',
        },
        {
          text: 'Relative to a physically replicated index fund, a synthetic index position using a total return swap:',
          given: null,
          opts: [
            'Earns securities lending revenue',
            'Forgoes lending revenue and introduces counterparty exposure to the swap provider',
            'Has zero tracking error by construction',
            'Requires no collateral',
          ],
          a: 1,
          why: 'There are no securities to lend, and performance depends on a counterparty honouring the swap. The trade-off is often a tighter and more predictable tracking difference.',
          ref: 'Index-Based Equity Strategies',
        },
        {
          text: 'A manager tracking a broad small-cap index with 2,400 constituents would most appropriately use:',
          given: null,
          opts: [
            'Full replication, for the tightest tracking',
            'Stratified sampling or optimisation, because full replication would be prohibitively costly in illiquid names',
            'A single futures contract on a large-cap index',
            'An equal-weighted portfolio of the largest 50 names',
          ],
          a: 1,
          why: 'Transaction costs in the long tail of an illiquid index exceed the tracking error saved. Sampling is the standard answer for breadth plus illiquidity.',
          ref: 'Index-Based Equity Strategies',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-markets': [
    {
      slug: 'private-debt-and-special-situations',
      name: 'Private Debt & Special Situations',
      blurb: 'Lending privately, and what happens when the borrower stops paying.',
      modules: ['Private Debt', 'Private Special Situations', 'Private Investments and Structures'],
      cards: [
        {
          kicker: 'SPECTRUM',
          title: 'Senior, unitranche, mezzanine, and the return comes from different places',
          body: 'Senior direct lending earns spread and fees with covenants and security. Unitranche blends senior and junior into one instrument at a blended rate. Mezzanine sits below the senior debt and earns part of its return in equity-linked form.',
          formula: null,
          exam: 'Loans are usually floating-rate, so private credit returns are spread plus base rate, with little interest rate duration.',
        },
        {
          kicker: 'FULCRUM',
          title: 'In a restructuring the fulcrum security becomes the equity',
          body: 'The fulcrum is the most senior claim not paid in full — the one that converts to ownership in a reorganisation. Identifying it correctly is the whole distressed-for-control trade, and it depends on the enterprise value the process ultimately accepts.',
          formula: null,
          exam: 'Above the fulcrum you are repaid; below it you are wiped out. Which class that is depends on the valuation the court or the parties adopt.',
        },
        {
          kicker: 'RECOVERY',
          title: 'Documentation determines recovery more than the label does',
          body: 'Security over what assets, in which jurisdiction, with what guarantees from which entities, and whether value can be moved out from under the lenders. Structural subordination — lending to a holding company whose operating subsidiaries owe others first — is the trap.',
          formula: null,
          exam: 'A "senior" loan to a holding company can rank behind unsecured trade creditors of the operating company.',
        },
      ],
      questions: [
        {
          text: 'A lender holds a "senior" loan to a holding company whose operating subsidiaries have their own unsecured trade creditors and no upstream guarantees. The lender is:',
          given: null,
          opts: [
            'Senior to all creditors of the group',
            'Structurally subordinated to the operating companies’ creditors, despite the label',
            'Protected by the seniority of the instrument',
            'Equal in ranking to the trade creditors',
          ],
          a: 1,
          why: 'Claims are satisfied at the entity that owes them. Without guarantees or security from the operating entities, the holding company lender is paid only from residual value after their creditors.',
          ref: 'Private Debt',
        },
        {
          text: 'A company has 300 of senior secured debt, 150 of senior unsecured notes and 100 of subordinated notes. The restructuring values the enterprise at 380. The fulcrum security is:',
          given: 'enterprise value 380; senior secured 300; senior unsecured 150; subordinated 100',
          opts: [
            'The senior secured debt',
            'The senior unsecured notes',
            'The subordinated notes',
            'The existing equity',
          ],
          a: 1,
          why: 'Secured debt of 300 is covered in full, leaving 80 for the 150 of senior unsecured. That class is the most senior not paid in full, so it converts to the new equity.',
          ref: 'Private Special Situations',
        },
        {
          text: 'A unitranche loan differs from a senior-plus-mezzanine structure principally in that it:',
          given: null,
          opts: [
            'Pays a lower blended rate',
            'Combines both layers in a single instrument at a blended rate, simplifying the borrower’s documentation',
            'Ranks behind trade creditors',
            'Carries no covenants',
          ],
          a: 1,
          why: 'One instrument, one lender group, one rate. Any internal ranking between lenders is handled in an agreement among them rather than in the borrower’s capital structure.',
          ref: 'Private Debt',
        },
        {
          text: 'A direct lending fund holds floating-rate senior loans. Base rates rise 200 basis points and stay there. The most likely combined effect is:',
          given: null,
          opts: [
            'Portfolio value falls sharply through duration',
            'Coupon income rises while borrower interest coverage deteriorates, raising default risk',
            'No effect on either income or credit quality',
            'Coupon income falls',
          ],
          a: 1,
          why: 'Floating coupons reset upward, so income rises and duration is minimal. The same rise squeezes the borrowers, which is the offsetting concern.',
          ref: 'Private Debt',
        },
        {
          text: 'A rescue financing provided to a company in distress, ranking ahead of existing debt with the consent of the court, is best described as:',
          given: null,
          opts: [
            'Mezzanine finance',
            'Priming or debtor-in-possession financing',
            'A dividend recapitalisation',
            'A unitranche loan',
          ],
          a: 1,
          why: 'Financing that ranks ahead of existing claims, with court sanction, is what allows a company to keep operating through a reorganisation.',
          ref: 'Private Special Situations',
        },
        {
          text: 'The principal risk of relying on an enterprise value estimate when buying the fulcrum security is that:',
          given: null,
          opts: [
            'The coupon may be suspended',
            'A lower accepted valuation moves the fulcrum up the structure, wiping out the class purchased',
            'Recovery rates are fixed by statute',
            'The process cannot be completed',
          ],
          a: 1,
          why: 'The fulcrum is defined by the valuation the process adopts. A lower value means a more senior class absorbs the equity and everything below it is impaired.',
          ref: 'Private Special Situations',
        },
      ],
    },
  ],

  'cfa-l3-pathway-private-wealth': [
    {
      slug: 'tax-aware-investing',
      name: 'Tax-Aware Investing',
      blurb: 'Harvesting, location, turnover and the arithmetic of deferral.',
      modules: ['Investment Planning', 'Preserving the Wealth'],
      cards: [
        {
          kicker: 'DEFERRAL',
          title: 'Deferral is worth the return on the tax not yet paid',
          body: 'An unrealised gain is an interest-free loan from the tax authority, and its value compounds with the horizon and the return. That is why low-turnover strategies and in-kind transfers matter more for a taxable investor than a few basis points of fee.',
          formula: 'after-tax FV = FV_pretax − t(FV_pretax − basis)',
          exam: 'The benefit rises with horizon and with return. Over a short horizon it is small and not worth distorting the portfolio for.',
        },
        {
          kicker: 'HARVESTING',
          title: 'Realising a loss converts it into a deferred asset',
          body: 'Selling a loss position and reinvesting in a similar, not identical, exposure banks the loss against gains while keeping the market position. Wash sale rules define how similar is too similar, and the benefit is deferral rather than elimination, since basis falls.',
          formula: null,
          exam: 'Harvesting lowers basis, so it defers tax rather than avoiding it — unless a step-up occurs at death.',
        },
        {
          kicker: 'TURNOVER',
          title: 'A manager’s pre-tax alpha has to clear the tax its turnover creates',
          body: 'A strategy turning over 120% a year realising short-term gains needs materially more pre-tax alpha than a low-turnover one to deliver the same after-tax result. Comparing managers on pre-tax returns, for a taxable client, compares the wrong number.',
          formula: null,
          exam: 'Tax-managed and tax-aware mandates are worth a fee premium exactly to the extent they reduce realised short-term gains.',
        },
      ],
      questions: [
        {
          text: 'An investor holds a position worth 500,000 with a basis of 200,000, facing a 25% rate on realised gains. The tax deferred by not selling is:',
          given: 'value 500,000; basis 200,000; tax rate 25%',
          opts: ['50,000', '75,000', '125,000', '300,000'],
          a: 1,
          why: 'The unrealised gain is 300,000 and the tax on it would be 75,000 — an interest-free loan for as long as the position is held.',
          ref: 'Investment Planning',
        },
        {
          text: 'Tax loss harvesting produces a benefit that is best described as:',
          given: null,
          opts: [
            'A permanent elimination of tax',
            'A deferral, because realising the loss also reduces the basis of the replacement holding',
            'An increase in pre-tax return',
            'A reduction in portfolio risk',
          ],
          a: 1,
          why: 'The loss offsets a gain now and lowers basis, so more gain is realised later. It is a timing benefit, worth the return on the tax deferred.',
          ref: 'Investment Planning',
        },
        {
          text: 'Two managers deliver identical 8% pre-tax returns. One turns the portfolio over 15% a year, the other 130% with mostly short-term gains. For a taxable investor:',
          given: null,
          opts: [
            'The two are equivalent',
            'The low-turnover manager will usually deliver a materially higher after-tax return',
            'The high-turnover manager is preferable, because gains are realised and compounded',
            'The comparison depends only on the fee',
          ],
          a: 1,
          why: 'Realising gains annually, at the higher short-term rate, removes money that would otherwise compound. Pre-tax equivalence is not after-tax equivalence.',
          ref: 'Investment Planning',
        },
        {
          text: 'An investor holds both a high-yield bond fund and a broad equity index fund, and has a tax-sheltered account and a taxable account of equal size. The most tax-efficient location is:',
          given: null,
          opts: [
            'Bonds in the taxable account, equities in the sheltered account',
            'Bonds in the sheltered account, equities in the taxable account',
            'Half of each in both accounts',
            'It makes no difference',
          ],
          a: 1,
          why: 'The bond fund throws off income taxed annually at the higher rate; the index fund defers most of its return as unrealised gain. Shelter the heavily taxed asset.',
          ref: 'Investment Planning',
        },
        {
          text: 'A jurisdiction grants a step-up in basis at death. The planning implication for a low-basis holding is that:',
          given: null,
          opts: [
            'It should be sold and repurchased annually',
            'Holding it until death eliminates the deferred gain entirely, which favours gifting other assets instead',
            'It should be gifted during life in preference to all other assets',
            'The step-up applies only to real estate',
          ],
          a: 1,
          why: 'A step-up removes the accrued gain. The low-basis asset is therefore the one to hold, and high-basis assets are the better candidates for lifetime gifting.',
          ref: 'Preserving the Wealth',
        },
        {
          text: 'An investor sells a fund at a loss and immediately buys an economically near-identical fund tracking the same index. In most jurisdictions this is:',
          given: null,
          opts: [
            'Fully effective for harvesting the loss',
            'At risk of being disallowed under wash sale or substantially-identical rules',
            'Effective only if the two funds have different managers',
            'Effective only for losses above a threshold',
          ],
          a: 1,
          why: 'Rules on substantially identical securities exist exactly to prevent a loss being realised while the economic position is unchanged. A related but genuinely different exposure is the usual route.',
          ref: 'Investment Planning',
        },
      ],
    },
  ],

  'frm-p1-markets': [
    {
      slug: 'rates-products-and-mbs',
      name: 'Rates Products & Mortgages',
      blurb: 'Rate conventions, the products built on them, and the prepayment option.',
      modules: [
        'Interest rates and interest-rate products',
        'Corporate bonds; mortgages and mortgage-backed securities',
        'Exchange-traded and OTC market structure, central counterparties',
      ],
      cards: [
        {
          kicker: 'CONVENTIONS',
          title: 'Day counts and compounding are not details when you are comparing',
          body: 'Money market instruments quote on actual/360 or a discount basis; bonds on 30/360 or actual/actual. Two instruments quoted differently cannot be compared until both are converted to the same basis, and the difference is large enough to change a decision.',
          formula: 'bond equivalent yield = discount yield × 365/360 adjusted for price',
          exam: 'A discount-basis quote understates the true yield because the discount is taken on face rather than on the price paid.',
        },
        {
          kicker: 'MORTGAGES',
          title: 'A mortgage is an amortising loan with a free option attached',
          body: 'The borrower may prepay at any time without penalty in most markets, which is a call on the loan struck at par. The lender is short that option and is not separately paid for it beyond the spread in the rate.',
          formula: null,
          exam: 'Prepayment speed is quoted as CPR annually or SMM monthly, and the PSA benchmark expresses it as a percentage of a standard ramp.',
        },
        {
          kicker: 'CLEARING',
          title: 'A central counterparty concentrates risk in exchange for netting it',
          body: 'Novation replaces bilateral exposures with exposure to the CCP, multilateral netting cuts gross exposure sharply, and a default waterfall — margin, default fund, then mutualised loss — absorbs a failure. The CCP itself becomes systemically critical.',
          formula: null,
          exam: 'Initial margin covers potential future exposure over the close-out period; variation margin settles today’s move.',
        },
      ],
      questions: [
        {
          text: 'A Treasury bill is quoted at a discount yield of 4.80% with 90 days to maturity on a 360-day basis. Relative to its bond equivalent yield, the discount yield is:',
          given: 'discount yield 4.80%; 90 days; actual/360',
          opts: [
            'Higher, because it uses a 360-day year',
            'Lower, because the discount is computed on face value rather than on the price paid',
            'Identical',
            'Indeterminate without the coupon',
          ],
          a: 1,
          why: 'The discount basis divides by face rather than by the smaller purchase price, and uses 360 days rather than 365. Both adjustments raise the bond equivalent yield above the quoted figure.',
          ref: 'Interest rates and interest-rate products',
        },
        {
          text: 'A pool has a single monthly mortality rate of 0.5%. The corresponding constant prepayment rate is closest to:',
          given: 'SMM 0.5%',
          opts: ['5.8%', '6.0%', '0.5%', '12.0%'],
          a: 0,
          why: 'CPR = 1 − (1 − SMM)^12 = 1 − 0.995^12 = 1 − 0.9416 = 5.84%. Multiplying by twelve gives 6.0%, the distractor.',
          ref: 'Corporate bonds; mortgages and mortgage-backed securities',
        },
        {
          text: 'The prepayment option in a standard residential mortgage is best described as:',
          given: null,
          opts: [
            'A put held by the lender',
            'A call on the loan held by the borrower, struck at par',
            'An obligation on the borrower to refinance',
            'A feature with no option value',
          ],
          a: 1,
          why: 'The borrower may repay at par whenever it suits, which is exactly a call struck at par. The lender is short it, which is the source of the negative convexity.',
          ref: 'Corporate bonds; mortgages and mortgage-backed securities',
        },
        {
          text: 'In a central counterparty’s default waterfall, losses beyond the defaulter’s own margin are absorbed next by:',
          given: null,
          opts: [
            'Surviving members’ variation margin',
            'The defaulter’s contribution to the default fund, then the CCP’s own capital, then the mutualised default fund',
            'The central bank',
            'The exchange’s shareholders only',
          ],
          a: 1,
          why: 'The standard sequence is the defaulter’s margin, the defaulter’s default fund contribution, a tranche of CCP capital, and then the surviving members’ mutualised contributions.',
          ref: 'Exchange-traded and OTC market structure, central counterparties',
        },
        {
          text: 'Multilateral netting through a central counterparty most directly reduces:',
          given: null,
          opts: [
            'Market risk on the underlying positions',
            'Gross counterparty exposure, by offsetting positions across all members',
            'The need for initial margin',
            'The volatility of the cleared instruments',
          ],
          a: 1,
          why: 'Netting collapses a web of offsetting bilateral claims into a single net position per member. The market risk on the underlying is untouched.',
          ref: 'Exchange-traded and OTC market structure, central counterparties',
        },
        {
          text: 'A 30-year mortgage pool experiences a sharp fall in mortgage rates. The investor most directly faces:',
          given: null,
          opts: [
            'Extension risk and a longer average life',
            'Contraction risk, with principal returned early to be reinvested at lower rates',
            'An increase in credit risk',
            'A rise in the pool’s duration',
          ],
          a: 1,
          why: 'Refinancing accelerates, shortening average life and returning capital precisely when reinvestment yields are worst. That asymmetry is the negative convexity.',
          ref: 'Corporate bonds; mortgages and mortgage-backed securities',
        },
      ],
    },
  ],

  'frm-p1-valuation': [
    {
      slug: 'country-risk-and-capital',
      name: 'Country Risk, Ratings & Capital',
      blurb: 'Sovereign analysis, what a rating does and does not say, and sizing capital.',
      modules: [
        'Country and sovereign risk; external ratings and rating transition matrices',
        'Economic and regulatory capital',
      ],
      cards: [
        {
          kicker: 'SOVEREIGN',
          title: 'Ability and willingness are separate questions',
          body: 'Ability is measured through debt to GDP, the maturity profile, reserves against short-term external debt and the currency of issuance. Willingness is political, and a government able to pay may still choose not to — which is why local-currency and foreign-currency ratings differ.',
          formula: null,
          exam: 'A government can print the local currency it owes. Foreign currency obligations require reserves it may not have.',
        },
        {
          kicker: 'RATINGS',
          title: 'A rating is an ordinal opinion about default, not a probability and not a price',
          body: 'Ratings are through-the-cycle and change slowly, which makes them stable and lagging. They say nothing about expected loss magnitude in most scales, nothing about liquidity, and nothing about whether the spread on offer is adequate.',
          formula: null,
          exam: 'Rating agencies are paid by issuers, which is the conflict the exam expects you to name.',
        },
        {
          kicker: 'CAPITAL',
          title: 'Economic capital is chosen; regulatory capital is imposed',
          body: 'Economic capital follows from a confidence level and a horizon the firm selects, usually aligned to a target rating. Regulatory capital is a prescribed floor. Whichever is higher binds, and a firm running well above both is either conservative or under-earning.',
          formula: 'economic capital = loss at chosen confidence − expected loss',
          exam: 'Targeting a AA rating implies a confidence level around 99.97%, because that is roughly the historical one-year default rate for AA.',
        },
      ],
      questions: [
        {
          text: 'A sovereign’s local-currency rating is two notches above its foreign-currency rating. The most likely reason is that:',
          given: null,
          opts: [
            'Local currency debt is issued under foreign law',
            'The government can create the currency it owes domestically, but foreign currency obligations require reserves',
            'Local currency debt has shorter maturities',
            'Foreign currency debt is always secured',
          ],
          a: 1,
          why: 'Default on local currency debt is a policy choice with inflationary consequences; default on foreign currency debt can be an inability to pay. Ratings reflect that difference.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
        {
          text: 'A firm targets a confidence level of 99.97% over one year for its economic capital. This is most consistent with:',
          given: null,
          opts: [
            'A regulatory minimum',
            'A desire to maintain a AA-equivalent credit rating',
            'A one-in-ten-year event',
            'A stress testing requirement',
          ],
          a: 1,
          why: 'The confidence level is chosen to match the historical one-year default rate of the target rating. Around three basis points corresponds to AA.',
          ref: 'Economic and regulatory capital',
        },
        {
          text: 'A one-year transition matrix shows a BBB issuer with a 4% probability of moving to BB and a 0.3% probability of default. For a diversified BBB portfolio, the larger source of loss over the year is most likely:',
          given: 'P(BBB→BB) 4%; P(BBB→default) 0.3%',
          opts: [
            'Default losses',
            'Migration and the associated spread widening',
            'Neither — the two are equal',
            'Interest rate movements',
          ],
          a: 1,
          why: 'Downgrades are an order of magnitude more frequent than defaults, and each one repricing a position produces mark-to-market loss well before any default occurs.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
        {
          text: 'The principal structural criticism of the credit rating agency model is that:',
          given: null,
          opts: [
            'Ratings change too frequently',
            'Issuers pay for their own ratings, which creates a conflict of interest',
            'Ratings are expressed on an ordinal scale',
            'Agencies publish transition matrices',
          ],
          a: 1,
          why: 'The issuer-pays model gives the agency a commercial interest in the rating being acceptable to the party being rated. It is the conflict that structured credit exposed.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
        {
          text: 'A portfolio has expected loss of 18 million and a loss at the 99.9% confidence level of 145 million. Economic capital is:',
          given: 'expected loss 18m; 99.9% loss 145m',
          opts: ['127 million', '145 million', '163 million', '18 million'],
          a: 0,
          why: '145 − 18 = 127 million. Expected loss is provisioned and priced; capital covers the unexpected part.',
          ref: 'Economic and regulatory capital',
        },
        {
          text: 'A country with reserves of 40 billion and short-term external debt of 72 billion is most exposed to:',
          given: 'reserves 40bn; short-term external debt 72bn',
          opts: [
            'Domestic inflation only',
            'A sudden stop, since reserves cannot cover maturing external obligations if they are not rolled',
            'A currency appreciation',
            'A fall in the local-currency rating only',
          ],
          a: 1,
          why: 'A reserves-to-short-term-external-debt ratio below one means a refusal to roll over cannot be met from reserves. It is the standard sudden-stop indicator.',
          ref: 'Country and sovereign risk; external ratings and rating transition matrices',
        },
      ],
    },
  ],

  'frm-p1-foundations': [
    {
      slug: 'crisis-case-studies',
      name: 'Crisis Case Studies',
      blurb: 'The 2007–09 mechanics in detail, and what each earlier failure taught first.',
      modules: [
        'Financial disasters and case studies; lessons of the global financial crisis',
        'Risk governance: board and audit responsibilities, risk appetite, ERM',
      ],
      cards: [
        {
          kicker: 'CHAIN',
          title: 'The crisis ran through funding, not through credit alone',
          body: 'Subprime losses were large but not, on their own, system-ending. What ended the system was short-term funding against long-dated illiquid assets: repo haircuts rose, asset-backed commercial paper stopped rolling, and institutions that were solvent on paper could not fund themselves.',
          formula: null,
          exam: 'Maturity transformation outside the deposit insurance perimeter is the phrase to have ready.',
        },
        {
          kicker: 'RATINGS',
          title: 'The correlation assumption did the damage, not the default rates',
          body: 'Senior tranches were rated on models assuming low, stable default correlation across geographically diverse mortgage pools. When house prices fell nationally, correlation went to one, and tranches sized against a diversification that did not exist were impaired together.',
          formula: null,
          exam: 'The Gaussian copula’s zero tail dependence is the specific technical failure to name.',
        },
        {
          kicker: 'EARLIER',
          title: 'Each earlier failure taught one thing',
          body: 'Barings: segregation of duties. Metallgesellschaft: a hedge that is right in the long run can fail on margin calls in the short run. LTCM: leverage plus convergence trades plus correlation going to one. Amaranth: concentration in an illiquid spread position.',
          formula: null,
          exam: 'Metallgesellschaft is the funding-liquidity-kills-a-sound-hedge case, and it is examined as such.',
        },
      ],
      questions: [
        {
          text: 'Metallgesellschaft’s losses on its oil hedging programme arose principally because:',
          given: null,
          opts: [
            'The hedge was directionally wrong',
            'Short-dated futures generated margin calls the firm could not fund, while the offsetting long-dated supply contracts produced no cash',
            'The counterparties defaulted',
            'Oil prices rose sharply',
          ],
          a: 1,
          why: 'The economic hedge was defensible; the cash flow timing was not. Variation margin was due immediately while the gain on the physical contracts accrued over years.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
        {
          text: 'The rapid impairment of highly rated senior mortgage tranches in 2007–08 is best attributed to:',
          given: null,
          opts: [
            'Fraudulent origination alone',
            'Model assumptions of low default correlation across pools, which failed when house prices fell nationally',
            'A rise in interest rates',
            'A shortage of servicers',
          ],
          a: 1,
          why: 'Tranche sizing depended on losses being idiosyncratic. A national price decline made them common, and the subordination sized against diversification proved inadequate.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
        {
          text: 'An institution funding long-dated illiquid assets with overnight repo is most vulnerable to:',
          given: null,
          opts: [
            'A rise in the credit quality of its assets',
            'A rise in repo haircuts, which forces asset sales regardless of the assets’ ultimate value',
            'A fall in interest rates',
            'A widening of its own credit spread only',
          ],
          a: 1,
          why: 'Higher haircuts require more collateral for the same cash. Selling into a falling market to raise it is the mechanism that turned a valuation problem into a solvency one.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
        {
          text: 'Long-Term Capital Management’s failure combined leverage with:',
          given: null,
          opts: [
            'An outright directional bet on equities',
            'Convergence trades across markets whose spreads widened together when correlations rose',
            'Fraudulent reporting',
            'An operational settlement failure',
          ],
          a: 1,
          why: 'Individually small, diversified relative-value positions became a single trade in the stress, and the leverage that made them worthwhile made the unwind forced.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
        {
          text: 'Which governance change most directly addresses the lesson of Barings?',
          given: null,
          opts: [
            'A higher capital requirement',
            'Separation of trading from settlement, with independent reconciliation',
            'A lower risk appetite statement',
            'More frequent external audit',
          ],
          a: 1,
          why: 'One individual controlling both the trade and its confirmation removed the control that would have surfaced the losses. Segregation of duties is the specific remedy.',
          ref: 'Risk governance: board and audit responsibilities, risk appetite, ERM',
        },
        {
          text: 'Post-crisis reform introduced liquidity requirements alongside capital requirements because:',
          given: null,
          opts: [
            'Capital requirements had been set too low',
            'Institutions failed while still reporting adequate capital, having lost the ability to fund themselves',
            'Liquidity is easier to measure',
            'Capital ratios are pro-cyclical',
          ],
          a: 1,
          why: 'Solvency and liquidity are different constraints. The crisis demonstrated that a bank can be adequately capitalised and fail in days for want of funding.',
          ref: 'Financial disasters and case studies; lessons of the global financial crisis',
        },
      ],
    },
  ],

  'frm-p1-quant': [
    {
      slug: 'machine-learning-in-risk',
      name: 'Machine Learning in Risk',
      blurb: 'Where it helps, where it does not, and the validation problem it creates.',
      modules: ['Machine learning and prediction', 'Simulation methods and bootstrapping'],
      cards: [
        {
          kicker: 'FIT',
          title: 'Supervised, unsupervised, reinforcement — and risk uses mostly the first two',
          body: 'Supervised learning predicts a labelled target: default, fraud, a rating. Unsupervised learning finds structure with no target: peer clustering, anomaly detection, dimension reduction. Reinforcement learning appears in execution, rarely in risk measurement.',
          formula: null,
          exam: 'Anomaly detection for fraud or rogue trading is the unsupervised application the exam names.',
        },
        {
          kicker: 'LIMITS',
          title: 'More flexible models need more data and more discipline, not less',
          body: 'A model with thousands of parameters fitted to a decade of monthly observations will fit noise perfectly. Financial data is short, non-stationary and low signal-to-noise, which is the opposite of the setting these methods were developed for.',
          formula: null,
          exam: 'Non-stationarity is the reason a model validated on 2010–2019 data may be useless in 2020.',
        },
        {
          kicker: 'VALIDATE',
          title: 'Walk-forward testing with point-in-time data, or the result is fiction',
          body: 'Randomly shuffling a time series into training and test sets leaks the future into the past. Validation must respect time order, and the features must be as they were known on the decision date rather than as later restated.',
          formula: null,
          exam: 'Look-ahead bias from restated fundamentals and survivorship bias from current constituents are the two that inflate every naive backtest.',
        },
      ],
      questions: [
        {
          text: 'A risk team splits ten years of daily data randomly into 70% training and 30% test sets to validate a default model. The principal flaw is:',
          given: null,
          opts: [
            'The test set is too small',
            'Random splitting of a time series leaks future information into the training set',
            'Daily data is too frequent',
            'Ten years is insufficient',
          ],
          a: 1,
          why: 'Observations from after the test period end up in training. Validation on a time series must be walk-forward so the model only ever sees the past.',
          ref: 'Machine learning and prediction',
        },
        {
          text: 'Clustering banks by balance sheet characteristics with no predefined labels is an example of:',
          given: null,
          opts: [
            'Supervised learning',
            'Unsupervised learning',
            'Reinforcement learning',
            'Bootstrapping',
          ],
          a: 1,
          why: 'There is no target variable. The method looks for structure in the features themselves, which is the defining property of unsupervised learning.',
          ref: 'Machine learning and prediction',
        },
        {
          text: 'A gradient-boosted model with 4,000 parameters is fitted to 180 monthly observations. The most likely outcome is:',
          given: 'parameters 4,000; observations 180',
          opts: [
            'A well-specified model with high explanatory power',
            'Severe overfitting — the model will reproduce the sample almost exactly and generalise poorly',
            'An underfitted model',
            'A model with high bias and low variance',
          ],
          a: 1,
          why: 'Parameters vastly exceeding observations means the model can memorise the sample. In-sample fit will be near perfect and out-of-sample performance poor.',
          ref: 'Machine learning and prediction',
        },
        {
          text: 'Using restated financial statement data as features in a backtest introduces:',
          given: null,
          opts: ['Survivorship bias', 'Look-ahead bias', 'Selection bias', 'Anchoring'],
          a: 1,
          why: 'Restated figures were not available on the original decision date. The model is given information it could not have had.',
          ref: 'Machine learning and prediction',
        },
        {
          text: 'A bootstrap is used to estimate the confidence interval around a portfolio’s Sharpe ratio. Its principal advantage over a parametric approach is that it:',
          given: null,
          opts: [
            'Requires fewer observations',
            'Makes no assumption about the return distribution, inheriting the sample’s own skew and fat tails',
            'Eliminates estimation error',
            'Produces a narrower interval',
          ],
          a: 1,
          why: 'Resampling the observed returns carries their empirical shape into the estimate. A parametric interval imposes a distribution that financial returns rarely have.',
          ref: 'Simulation methods and bootstrapping',
        },
        {
          text: 'A model validated on 2010–2019 data performs poorly from 2020 onward. The most likely cause is:',
          given: null,
          opts: [
            'Insufficient training data',
            'Non-stationarity — the data-generating process changed',
            'An error in the loss function',
            'Too few features',
          ],
          a: 1,
          why: 'A decade of low rates and low volatility is one regime. A model fitted to it encodes that regime, and no amount of additional data from it helps in another.',
          ref: 'Machine learning and prediction',
        },
      ],
    },
  ],

  'frm-p2-market': [
    {
      slug: 'volatility-surfaces-and-exotics',
      name: 'Volatility Surfaces & Exotics',
      blurb: 'Reading the surface, and the products whose risk lives in its shape.',
      modules: [
        'Volatility modelling: GARCH, EWMA, implied volatility surfaces',
        'Volatility smiles; exotic and mortgage-backed products',
      ],
      cards: [
        {
          kicker: 'SURFACE',
          title: 'Two axes, and each says something different',
          body: 'Across strikes the surface shows the market’s view of tail shape — a skew in equities, a smile in currencies. Across maturities it shows the term structure of expected volatility, usually upward sloping in calm markets and inverted in a stress.',
          formula: null,
          exam: 'An inverted volatility term structure — short-dated implied above long-dated — is a stress signature.',
        },
        {
          kicker: 'EXOTICS',
          title: 'Barriers and digitals have discontinuous risk',
          body: 'A digital option pays a fixed amount if a condition holds, so its delta spikes near the strike at expiry. A barrier option knocks in or out at a level, so the entire position can vanish on a touch. Both are far harder to hedge than the vanilla equivalent.',
          formula: null,
          exam: 'Hedging a digital near expiry can require a position larger than the payout, which is why they are traded as call spreads.',
        },
        {
          kicker: 'MBS',
          title: 'Option-adjusted spread on an MBS is a model output, not a market quote',
          body: 'The OAS depends on the prepayment model and the interest rate volatility assumption fed into it. Two desks quoting different OAS for the same bond are usually disagreeing about prepayment speeds, not about value.',
          formula: null,
          exam: 'Higher assumed volatility raises the prepayment option’s value and lowers the computed OAS.',
        },
      ],
      questions: [
        {
          text: 'Short-dated implied volatility rises above long-dated implied volatility. This inversion is most consistent with:',
          given: null,
          opts: [
            'A calm market expecting stability',
            'A market stress, with immediate uncertainty expected to subside',
            'A change in the risk-free rate',
            'An increase in dividend expectations',
          ],
          a: 1,
          why: 'An inverted term structure prices acute near-term uncertainty that the market expects to pass. It is one of the more reliable stress indicators.',
          ref: 'Volatility modelling: GARCH, EWMA, implied volatility surfaces',
        },
        {
          text: 'A trader is short a digital call expiring tomorrow with the underlying trading close to the strike. The principal difficulty is:',
          given: null,
          opts: [
            'Vega, which is at its maximum',
            'A delta that changes discontinuously near the strike, requiring a hedge potentially larger than the payout',
            'Theta, which works in the trader’s favour',
            'Rho, because rates dominate at short maturities',
          ],
          a: 1,
          why: 'The payoff is a step function, so the hedge ratio explodes as expiry approaches at the money. Desks manage this by replicating with a tight call spread.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
        {
          text: 'An up-and-out call knocks out if the underlying touches a barrier above the strike. Relative to a vanilla call with the same strike, it is:',
          given: null,
          opts: [
            'More expensive, because of the additional feature',
            'Cheaper, because the payoff is extinguished in exactly the scenarios where the vanilla pays most',
            'Identically priced',
            'Cheaper only if volatility is low',
          ],
          a: 1,
          why: 'The knock-out removes the best outcomes for the holder, so the option must cost less. That is what makes barriers attractive to buyers and awkward to hedge.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
        {
          text: 'Two dealers quote option-adjusted spreads of 48 and 71 basis points on the same mortgage-backed security. The most likely explanation is:',
          given: null,
          opts: [
            'One dealer has mispriced the bond',
            'They are using different prepayment models and volatility assumptions',
            'The bond has two different coupons',
            'One quote includes accrued interest',
          ],
          a: 1,
          why: 'OAS is a model output. The disagreement is about how fast borrowers will prepay and how volatile rates will be, not about the observed price.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
        {
          text: 'Raising the assumed interest rate volatility when computing the OAS of a pass-through MBS will:',
          given: null,
          opts: [
            'Raise the computed OAS',
            'Lower it, because the borrower’s prepayment option becomes more valuable',
            'Leave it unchanged',
            'Make it negative by construction',
          ],
          a: 1,
          why: 'The investor is short the prepayment option. A more valuable option absorbs more of the bond’s spread, leaving less as option-adjusted compensation.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
        {
          text: 'An equity index option surface shows implied volatility falling as the strike rises. A trader who believes the skew is too steep would most directly:',
          given: null,
          opts: [
            'Buy low-strike puts and sell high-strike calls',
            'Sell low-strike puts and buy higher-strike options, flattening the exposure to the skew',
            'Buy a straddle',
            'Sell a calendar spread',
          ],
          a: 1,
          why: 'Believing the skew is too steep means low strikes are expensive relative to high ones. Selling the expensive wing and buying the cheaper one expresses that directly.',
          ref: 'Volatility smiles; exotic and mortgage-backed products',
        },
      ],
    },
  ],

  'frm-p2-credit': [
    {
      slug: 'securitisation-and-clos',
      name: 'Securitisation & CLOs',
      blurb: 'Waterfalls, coverage tests, and what a CLO tranche is actually exposed to.',
      modules: [
        'Securitisation, structured credit and CDOs',
        'Credit derivatives and credit default swaps',
      ],
      cards: [
        {
          kicker: 'WATERFALL',
          title: 'Interest and principal have separate waterfalls',
          body: 'Interest received pays fees, then senior coupons, then junior coupons, then the equity residual. Principal repays tranches in order of seniority. Coverage tests can divert interest to repay senior principal early, which is where the equity holder loses first.',
          formula: null,
          exam: 'A failed overcollateralisation test redirects cash from the equity tranche to amortise senior notes. Name that mechanism.',
        },
        {
          kicker: 'TESTS',
          title: 'Overcollateralisation and interest coverage are the structural brakes',
          body: 'The OC test compares collateral par to tranche par; the IC test compares interest received to interest due. Failing either diverts cash upward. They are what make a CLO self-correcting and what make the junior tranches’ cash flows so path-dependent.',
          formula: 'OC ratio = collateral par / (tranche par + senior par)',
          exam: 'Defaults and downgrades below a threshold are haircut in the OC calculation, so a wave of downgrades can trip the test before any default.',
        },
        {
          kicker: 'CLO vs CDO',
          title: 'A CLO is actively managed leveraged loans; the pre-crisis CDO was not',
          body: 'CLOs hold senior secured leveraged loans, are actively traded by a manager within documented constraints, and have a reinvestment period. The structured credit that failed in 2008 held static pools of mortgage exposures, often re-securitised.',
          formula: null,
          exam: 'Manager skill and the reinvestment period are genuine differences, not marketing. So is holding senior secured rather than subordinated collateral.',
        },
      ],
      questions: [
        {
          text: 'A CLO fails its senior overcollateralisation test. The immediate consequence is that:',
          given: null,
          opts: [
            'The manager is replaced',
            'Interest that would have gone to the equity tranche is diverted to amortise the senior notes',
            'The deal is liquidated',
            'The senior coupon is deferred',
          ],
          a: 1,
          why: 'The test is a structural brake. Cash is redirected up the waterfall until the ratio is restored, and the equity residual is the first to stop receiving.',
          ref: 'Securitisation, structured credit and CDOs',
        },
        {
          text: 'A wave of downgrades to CCC, with no defaults, can trip a CLO’s overcollateralisation test because:',
          given: null,
          opts: [
            'Downgraded assets are sold automatically',
            'Holdings above a CCC bucket limit are carried at market value or haircut par in the test calculation',
            'The interest coverage test is recalculated monthly',
            'Rating agencies require it',
          ],
          a: 1,
          why: 'Excess CCC holdings are haircut in the numerator, so the ratio falls without a single missed payment. That is why downgrade waves hit CLO equity before defaults do.',
          ref: 'Securitisation, structured credit and CDOs',
        },
        {
          text: 'The equity tranche of a CLO is best described as:',
          given: null,
          opts: [
            'A senior claim on the collateral pool',
            'A levered residual claim, long default correlation and highly path-dependent through the coverage tests',
            'A fixed-rate bond',
            'Equivalent to a credit default swap on the pool',
          ],
          a: 1,
          why: 'It receives what is left after everything else, benefits when defaults cluster in no year at all, and its cash flows can be switched off by a test failure.',
          ref: 'Securitisation, structured credit and CDOs',
        },
        {
          text: 'A CLO differs most substantively from a pre-crisis mortgage CDO in that the CLO:',
          given: null,
          opts: [
            'Has no tranching',
            'Holds actively managed senior secured leveraged loans rather than a static pool of subordinated mortgage exposures',
            'Carries no credit risk',
            'Is not rated',
          ],
          a: 1,
          why: 'Collateral seniority, active management within constraints, and a reinvestment period are real structural differences, whatever the similarity of the tranching.',
          ref: 'Securitisation, structured credit and CDOs',
        },
        {
          text: 'An investor buys protection on an index tranche covering the 3–7% loss band. Pool losses reach 5%. The investor’s protection has:',
          given: 'tranche attachment 3%, detachment 7%; pool loss 5%',
          opts: [
            'Not yet been triggered',
            'Been triggered, with half the tranche notional written down',
            'Been fully exhausted',
            'Been triggered only if defaults exceed 7%',
          ],
          a: 1,
          why: 'Losses above the 3% attachment eat into the tranche. At 5% of pool loss, 2 of the 4 percentage points of tranche width are consumed — half the tranche.',
          ref: 'Credit derivatives and credit default swaps',
        },
        {
          text: 'A protection seller on a senior index tranche is economically:',
          given: null,
          opts: [
            'Long default correlation',
            'Short default correlation, because clustered defaults are what reach a senior attachment point',
            'Neutral to correlation',
            'Long the individual default probabilities only',
          ],
          a: 1,
          why: 'Senior tranches are only impaired when defaults arrive together. Higher correlation raises that probability, which hurts the seller of protection on them.',
          ref: 'Credit derivatives and credit default swaps',
        },
      ],
    },
  ],

  'frm-p2-operational': [
    {
      slug: 'model-risk-and-supervision',
      name: 'Model Risk & Supervision',
      blurb: 'Validating a model properly, and what supervisors expect the framework to look like.',
      modules: [
        'Model risk management and validation',
        'Basel operational risk framework; regulation and supervision',
      ],
      cards: [
        {
          kicker: 'DEFINE',
          title: 'A model is any quantitative method producing an output used in a decision',
          body: 'That includes spreadsheets, vendor packages and machine learning pipelines, not just the pricing library. Firms that scope model risk narrowly discover their largest exposures in exactly the tools nobody registered as models.',
          formula: null,
          exam: 'An unregistered spreadsheet driving a capital calculation is the classic finding.',
        },
        {
          kicker: 'VALIDATE',
          title: 'Three pillars, and outcomes analysis is the one with teeth',
          body: 'Conceptual soundness reviews the theory and the design choices. Ongoing monitoring checks that the model still applies as conditions change. Outcomes analysis compares predictions with what happened — backtesting and benchmarking against a challenger model.',
          formula: null,
          exam: 'Validation must be independent of development and must have the authority to restrict a model’s use.',
        },
        {
          kicker: 'SUPERVISION',
          title: 'Three pillars again, and the second is where judgement enters',
          body: 'Pillar 1 sets minimum capital by formula. Pillar 2 is the supervisory review of the firm’s own capital adequacy assessment, where risks not captured in Pillar 1 are addressed. Pillar 3 is disclosure, which lets the market apply its own discipline.',
          formula: null,
          exam: 'Interest rate risk in the banking book and concentration risk are Pillar 2 items, not Pillar 1.',
        },
      ],
      questions: [
        {
          text: 'A bank scopes model risk to cover only its front-office pricing library. The most likely consequence is that:',
          given: null,
          opts: [
            'Validation resources are used efficiently',
            'Spreadsheets and vendor tools driving capital and provisioning sit outside the framework entirely',
            'Regulatory capital falls',
            'Backtesting becomes unnecessary',
          ],
          a: 1,
          why: 'A model is any quantitative method feeding a decision. A narrow scope leaves the tools that actually drive reported numbers unvalidated.',
          ref: 'Model risk management and validation',
        },
        {
          text: 'Which validation activity most directly tests whether a model’s predictions match reality?',
          given: null,
          opts: [
            'Conceptual soundness review',
            'Outcomes analysis, including backtesting and benchmarking against a challenger model',
            'Code review',
            'Documentation review',
          ],
          a: 1,
          why: 'Conceptual review examines the design and documentation review the record. Only outcomes analysis compares what the model said with what happened.',
          ref: 'Model risk management and validation',
        },
        {
          text: 'Interest rate risk in the banking book is addressed under which Basel pillar?',
          given: null,
          opts: ['Pillar 1', 'Pillar 2', 'Pillar 3', 'It is not addressed'],
          a: 1,
          why: 'IRRBB is a Pillar 2 risk, assessed through the supervisory review process rather than by a prescribed Pillar 1 capital formula.',
          ref: 'Basel operational risk framework; regulation and supervision',
        },
        {
          text: 'A validation function reports to the head of the quantitative team that builds the models. This arrangement:',
          given: null,
          opts: [
            'Is efficient, since the reviewers understand the models best',
            'Compromises independence — validation must be able to challenge and restrict use without reporting to the developers',
            'Satisfies supervisory expectations if documented',
            'Is acceptable for low-materiality models only',
          ],
          a: 1,
          why: 'A function reporting to the people it reviews cannot restrict their work. Independence is the control, not the expertise.',
          ref: 'Model risk management and validation',
        },
        {
          text: 'Pillar 3 of the Basel framework is concerned with:',
          given: null,
          opts: [
            'Minimum capital requirements',
            'Public disclosure, so that market participants can assess a bank’s risk profile',
            'Supervisory review',
            'Liquidity coverage',
          ],
          a: 1,
          why: 'Pillar 3 is market discipline through disclosure. Pillar 1 is the formula and Pillar 2 the supervisory review.',
          ref: 'Basel operational risk framework; regulation and supervision',
        },
        {
          text: 'A model performs well on its validation sample but its inputs have drifted far outside the range seen during development. The appropriate response is to:',
          given: null,
          opts: [
            'Continue using it, since validation passed',
            'Restrict its use, revalidate against the current input range, and document the limitation until then',
            'Replace it with expert judgement permanently',
            'Increase the confidence level of its output',
          ],
          a: 1,
          why: 'A model is validated for a domain. Operating outside that domain is a use failure, and the framework must be able to restrict use rather than merely note the concern.',
          ref: 'Model risk management and validation',
        },
      ],
    },
  ],
};
